gatling: fix undefined reference to 'crypt'
ff30c899d8b made libcrypt support optional (and off-by-default) in
glibc, which requires all packages still using it to depend on
libxcrypt.

See also https://github.com/NixOS/nixpkgs/pull/181764