nottetris2: drop
crashes on startup:

[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
Error: No available video device
stack traceback:
        [C]: ?
        [C]: in function 'require'
        [string "boot.lua"]:1: in function <[string "boot.lua"]:1>
        [C]: in function 'xpcall'