lua.pkgs.luarocks: fix usage in cross-compilation
copy of comment https://github.com/luarocks/luarocks/pull/1433/commits/8d878e4981d71c08090f509c390dcb4c879971f6#r954257465

with this patch the build of luasystem fails

LD=ld
```
ld  -shared -o system/core.so src/core.o src/compat.o src/time.o -L/nix/store/...-glibc-2.35-163/lib -Wl,-rpath,/nix/store/...-glibc-2.35-163/lib -lrt
/nix/store/vhf2cr6immz4qdxd83y025fnxim8mmfg-binutils-2.38/bin/ld: unrecognized option '-Wl,-rpath,/nix/store/...-glibc-2.35-163/lib'
/nix/store/vhf2cr6immz4qdxd83y025fnxim8mmfg-binutils-2.38/bin/ld: use the --help option for usage information

Error: Build error: Failed compiling module system/core.so
```

LD=gcc
```
gcc  -shared -o system/core.so src/core.o src/compat.o src/time.o -L/nix/store/...-glibc-2.35-163/lib -Wl,-rpath,/nix/store/...-glibc-2.35-163/lib -lrt
```

`-Wl,rpath... -lrt` are added by https://github.com/luarocks/luarocks/blob/ecb63347bf7d44c68210befc9d03c013350c7831/src/luarocks/build/builtin.lua#L249-L250