bird-lg: disable frontend checks on darwin
Disable the checks of bird-lg-frontend on darwin as this tries to
create a localhost proxy which is forbidden by the nix build
mechanism.

The produced error on aarch64-darwin is:
```
--- FAIL: TestWhoisConnectionError (0.00s)
    whois_test.go:94: Whois AS6939 without server produced output, got dial tcp 127.0.0.1:0: connect: can't assign requested address
```