paperless-ngx: fix frontend build
paperless-ngx's frontend tries to build canvas node pacakge and fails
due to missing headers:

```
npm ERR! In file included from ../src/CanvasPattern.cc:6:
npm ERR! ../src/Image.h:18:10: fatal error: 'gif_lib.h' file not found
npm ERR! #include <gif_lib.h>
npm ERR!          ^~~~~~~~~~~
```

On darwin, canvas requires CoreText headers:

```
npm ERR! 1 warning generated.
npm ERR! ../src/register_font.cc:9:10: fatal error: 'CoreText/CoreText.h' file not found
npm ERR! #include <CoreText/CoreText.h>
npm ERR!          ^~~~~~~~~~~~~~~~~~~~~
```