Revert "libcamera: 0.0.1 -> 0.0.3"
This reverts commit 389e2645548d0242289e53db526bf8d27e049f9f.

The libcamera upgrade is incompatible with the pipewire 0.3.60.

```
g++ -Ispa/plugins/libcamera/libspa-libcamera.so.p -Ispa/plugins/libcamera -I../spa/plugins/libcamera -Ispa/include -I../spa/include -I/nix/store/p48bnpv5d4kb8giv8gng3cpd3cdlkj88-systemd-minimal-251.10-dev/include -I/nix/store/mca50785p1aa780c4c46h47f8c6356qx-libcamera-0.0.3/include/libcamera -I/nix/store/hvg7m930kyhrdksg5z5p9jijhmay7isq-libdrm-2.4.113-dev/include -I/nix/store/hvg7m930kyhrdksg5z5p9jijhmay7isq-libdrm-2.4.113-dev/include/libdrm -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -Wpedantic -std=c++17 -fvisibility=hidden -fno-strict-aliasing -Werror=suggest-attribute=format -Wsign-compare -Wpointer-arith -Wformat -Wformat-security -Wimplicit-fallthrough -Wmissing-braces -Wtype-limits -Wvariadic-macros -Wmaybe-uninitialized -Wno-missing-field-initializers -Wno-unused-parameter -Wno-pedantic -Wdeprecated-declarations -Wunused-result -fPIC -pthread -MD -MQ spa/plugins/libcamera/libspa-libcamera.so.p/libcamera-source.cpp.o -MF spa/plugins/libcamera/libspa-libcamera.so.p/libcamera-source.cpp.o.d -o spa/plugins/libcamera/libspa-libcamera.so.p/libcamera-source.cpp.o -c ../spa/plugins/libcamera/libcamera-source.cpp
In file included from ../spa/plugins/libcamera/libcamera-source.cpp:205:
../spa/plugins/libcamera/libcamera-utils.cpp: In function 'void spa_libcamera_get_config({anonymous}::impl*)':
../spa/plugins/libcamera/libcamera-utils.cpp:77:18: error: 'VideoRecording' was not declared in this scope; did you mean 'libcamera::StreamRole::VideoRecording'?
   77 |  roles.push_back(VideoRecording);
      |                  ^~~~~~~~~~~~~~
      |                  libcamera::StreamRole::VideoRecording
In file included from /nix/store/mca50785p1aa780c4c46h47f8c6356qx-libcamera-0.0.3/include/libcamera/libcamera/camera.h:22,
                 from ../spa/plugins/libcamera/libcamera-source.cpp:55:
/nix/store/mca50785p1aa780c4c46h47f8c6356qx-libcamera-0.0.3/include/libcamera/libcamera/stream.h:68:2: note: 'libcamera::StreamRole::VideoRecording' declared here
   68 |  VideoRecording,
      |  ^~~~~~~~~~~~~~
[234/780] Compiling C++ object spa/plugins/aec/libspa-aec-webrtc.so.p/aec-webrtc.cpp.o
ninja: build stopped: subcommand failed.
```