home-assistant: pin plugwise at 0.20.1
With 0.21.0 the home-assistant test is missing a Mock object:

```
AttributeError: Mock object has no attribute 'set_max_boiler_temperature'
```