floorp-bin: fix usage as `programs.firefox.package`
Fixes #442254 [0].

Apparently, there is a big difference whether we `wrapFirefox` the
package inside top-level/all-packages.nix or by-name/.

With the latter, using something like

  programs.firefox = {
    enable = true;
    package = pkgs.floorp-bin;
  };

breaks with

  error: function 'anonymous lambda' called with unexpected arguments 'cfg', 'nativeMessagingHosts' and 'extraPrefsFiles'
  at <nixpkgs>/pkgs/by-name/fl/floorp-bin/package.nix:1:1:
      1| {
       | ^
      2|   wrapFirefox,

[0] https://github.com/NixOS/nixpkgs/issues/442254

Signed-off-by: Christoph Heiss <christoph@c8h4.io>