hylafaxplus: fix by downgrading libtiff to 4.5.1
libtiff 4.6.0 (updated with
0a74a54ac2600656cd0b640d5ea1c8efb5c35d68)
drops many tiff-processing utility executables, like
tiff2ps and fax2ps, that are needed by hylafaxplus.
As a result, the build fails with

> FATAL ERROR: /nix/store/5i80biwsgjb4yhp4z81nsk3kp5rivd8f-libtiff-4.6.0-bin/bin/tiff2ps does not exist or is not an executable program!

see https://hydra.nixos.org/build/239580858 .

The commit at hand fixes the package by using libtiff_4_5
which got introduced in the previous commit.

Note on long-term prospect for this situation:
According to hylafaxplus developer Lee Howard,
it might take months before one of these options
(or a combination thereof) might be implemented:

* a new package "tifftools" with the utility executables emerges
* The hylafaxplus package incorporates the source
  of these executables and builds them by itself
* hylafaxplus is rewritten so as to not use these programs
* libtiff reincorporates the programs, maybe after fixing them

Cf. https://sourceforge.net/p/hylafax/mailman/message/38259441/

Another reference: a discussion on the libtiff mailing list:
https://www.asmail.be/msg0054915176.html