Dictd dbs dont unpack (#13)
* squashfsTools: add NixOS cdrom boot as passthru test

This is the same test which blocks nixos-unstable-small. It recently
caused a long blockage, due to a regression in squashfsTools itself
corrupting the iso image, see #132286.

* python3Packages.pyfma: fix build

* python3Packages.dipy: 1.3.0 -> 1.4.1

* python3Packages.emoji: 1.4.1 -> .1.4.2

* python3Packages.datasets: 1.8.0 -> 1.11.0

* gdu: 5.3.0 -> 5.5.0

https://github.com/dundee/gdu/releases/tag/v5.4.0
https://github.com/dundee/gdu/releases/tag/v5.5.0

* bazarr: fix build

* sane: Add support for the unfree Fujitsu ScanSnap drivers

This adds the scanner files already linked from the
`etc/sane.d/epjitsu.conf` file, which are extracted from the Windows
drivers and mirrored on GitHub.

Being a Japanese hardware vendor, Fujitsu’s software release &
licensing methods are horrifying, but their scanners are some of the
best, so we should definitly have discoverable support for them, which
this patch hopefully adds.

Inspiration was taken from the following sources:
https://www.josharcher.uk/code/install-scansnap-s1300-drivers-linux/
https://ubuntuforums.org/archive/index.php/t-1461915.html
https://github.com/stevleibelt/scansnap-firmware

* grpc: fix cross

I couldn't find any alternative to setting _gRPC_PROTOBUF_PROTOC_EXECUTABLE.
protobuf.cmake uses find_program when cross-compiling, which finds the
host platform's protoc instead of the build platform's.  I even tried
giving protobuf multiple outputs and not including the one with the
binary in buildInputs, but it didn't help.

* nixos/syncthing: fix curl not retrying on network errors

* coursera-dl: fix tests

* broot: add dywedir to maintainers

* broot: 1.6.0 -> 1.6.2

* lib.systems.doubles: re-sort

These were alphabetically sorted until m68k and s390 were added.

* lib.systems: add m68k-netbsd support

m68k was recently added for Linux and none, but NetBSD also supports
m68k.  Nothing will build yet, but I want to make sure we at least
encode the existence of NetBSD support for every applicable
architecture we support for other operating systems.

* renderdoc: 1.14 -> 1.15

* xboxdrv: update url

* tt-rss-plugin-auth-ldap: fix compat with latest tt-rss

* chromium: Drop two gn overrides that are not required anymore

The chromium and chromiumBeta builds still succeed.

* nixos/captive-browser: fix startup

It seems as since Chromium 92, `chromium` crashes on startup if
`XDG_CONFIG_HOME` points to a read-only (store-)path.

* pkgs/top-level/release.nix: build pkgsLLVM.stdenv as part of trunk

Having pkgsLLVM.stdenv built with nixpkgs:trunk will make building
anything in pkgsLLVM decidedly less painful since it will eliminate
the need to build LLVM and clang locally, which shouldn't be as bad
on hydra.

Darwin is disabled for now since it doesn't evaluate correctly there
(infinite recursion problem with the SDK).

* 1password: 1.9.1 -> 1.11.2 (#131497)

* 1password: 1.9.1 -> 1.11.2

Also, we are using the new `apple_universal` package 1password added
to support amd64 and the new M1 architecture. If this is a problem, we
can revert to 1.11.0 for now, which is the last version that uses the
old `darwin_amd64` package.

Co-authored-by: Mario Rodas <marsam@users.noreply.github.com>

* chia: unbreak

* soapui: 5.5.0 -> 5.6.0 (#131307)

Co-authored-by: Benjamin Asbach <asbachb@users.noreply.github.com>

* vimPlugins.onedark-nvim: Add lush-nvim dependency (#131987)

* vimPlugins.onedark-nvim: Add lush-nvim dependency

* Update pkgs/misc/vim-plugins/overrides.nix

Co-authored-by: Sandro <sandro.jaeckel@gmail.com>

* nixos/virtualbox-image: cast baseImageFreeSpace into str

This fixes an evaluation error that's blocking the nixos-unstable
channel (#132328).

* python3Packages.types-requests: 2.25.0 -> 2.25.1

* nixos/nix-daemon: fix registry flake type

Before this commit, the `flake` option was typed with `types.unspecified`.

This type get's merged via [`mergeDefaultOption`](https://github.com/NixOS/nixpkgs/blob/ebb592a04c5282f316d60cd4aba066f6e5d74b65/lib/options.nix#L119-L128), which has a line
```nix
else if all isFunction list then x: mergeDefaultOption loc (map (f: f x) list)
```

`lib.isFunction` detects an attrs in the shape of `{__functor = ...}` as
a function and hence this line substitutes such attrs with a function
(f: f x).

If now, a flake input has a `__functor` as it's output, this will
coerce the once attrs to a function. This breaks a lot of things later
in the stack, for example a later `lib.filterAttrs seive <LAMBDA>` will
fail for obious reasons.

According to @infinisil, `types.unspecified` is due to deprecation. In
the meantime this PR provides a specific fix for the specific problem
discovered.

* tools/networking: replace name with pname&version

* doc: rust: improve documentation on cargoLock.lockFile

* captive-browser: 2019-04-16 -> 2021-08-01

Changes: https://github.com/FiloSottile/captive-browser/compare/08450562e58bf9564ee98ad64ef7b2800e53338f...9c707dc32afc6e4146e19b43a3406329c64b6f3c

* phosh: 0.12.0 -> 0.12.1

* phoc: 0.7.1 -> 0.8.0

* psysh: deprecate phases

* psalm: deprecate phases

* phpstan: deprecate phases

* phpmd: deprecate phases

* php-cs-fixer: deprecate phases

* phpcs: deprecate phases

* phpcbf: deprecate phases

* php/box: deprecate phases

* lilypond-fonts: deprecate phases

* linux_xanmod: 5.13.6 -> 5.13.7

* rdma-core: 35.0 -> 36.0

* estudio: deprecate phases

* nixos/display-managers: update set-session for new "SessionType" property

GDM 40.1 switched from storing X11 sessions in the "XSession" property
on AccountService to "Session" with a "x11" "SessionType".

For compatibility reasons, we should set both, since AccountService
doesn't seem to provide the compatibility for us.

* mfcl2700dncupswrapper: deprecate phases

* mfcl2700dnlpr: deprecate phases

* mfcl2720dwcupswrapper: deprecate phases

* mfcl2720dwlpr: deprecate phases

* mfcl8690cdwcupswrapper: deprecate phases

* mfcl8690cdwlpr: deprecate phases

* splix: deprecate phases

* seahorse: add glib-networking for sync

* bacon: 1.1.6 -> 1.1.8

* bupstash: 0.9.1 -> 0.10.0

* checkstyle: 8.44 -> 8.45

* chezmoi: 2.1.2 -> 2.1.3

* velero: 1.6.0 -> 1.6.2

* jetbrains-jdk: 11.0.10-b1427 -> 11_0_11-b1504.13

The homepage has been updated.

* disfetch: 2.2 -> 2.7

* gobgpd: 2.29.0 -> 2.30.0

* headscale: 0.3.4 -> 0.3.6

* iosevka-bin: 8.0.2 -> 9.0.1

* tfk8s: 0.1.5 -> 0.1.6

* knot-dns: 3.0.8 -> 3.1.0

NEWS + migration guide:
https://gitlab.nic.cz/knot/knot-dns/-/tags/v3.1.0
https://www.knot-dns.cz/docs/3.1/html/migration.html#upgrade-3-0-x-to-3-1-x

* protoc-gen-grpc-web: init at 1.2.1

* chromium: Drop our closure_compiler patch for Java

Hopefully the Java dependency can be dropped soon:
https://bugs.chromium.org/p/chromium/issues/detail?id=1192875#c5

* mgba: cleanup

* tahoe-lafs: cleanup

* ecl: cleanup

* ghostunnel: format

* zchunk: format

* notmuch: cleanup

* interval: format

* jitsi-meet-electron: format

* QuickChick: format

* dune-release: remove -f from rm -rf

* renderdoc: format, cleanup

* keynav: format

* openafs: cleanup

* grpc: format

* maintainers: add ilyakooo0

* rust-analyzer: 2021-07-12 -> 2021-08-02

* chia-plotter: init at unstable-2021-07-12

* pivx: cleanup, format

* grpc: format

* knot-dns: cleanup

* cosign: 1.0.0 -> 1.0.1

* toxvpn: format, cleanup

* ssmtp: cleanup, format

* azureus: drop

* ntfy-webpush: init at 0.1.3 (#132404)

* wezterm: install desktop file

* plex: 1.23.5.4862-0f739d462 -> 1.23.6.4881-e2e58f321

* terraform-ls: 0.19.1 -> 0.20.0

* matcha-gtk-theme: 2021-07-20 -> 2021-08-02

* shfmt: 3.3.0 -> 3.3.1

https://github.com/mvdan/sh/releases/tag/v3.3.1

* dasel: 1.15.0 -> 1.16.1

https://github.com/TomWright/dasel/blob/master/CHANGELOG.md#v1160---2021-08-01

* telegram-cli: init 20200106

Co-authored-by: @sikmir @SuperSandro2000

* rabbitmq-server: 3.8.9 -> 3.9.1

* knot-dns: disable tests broken on aarch64-darwin

Upstream is aware but they don't have a fix yet.
I'm not aware of NixPkgs being used for another platform
affected by this (e.g. ppc64le).

* kratos: 0.6.0-alpha.2 -> 0.7.1-alpha.1 (#132399)

* virtualbox: 6.1.22 -> 6.1.26 (#132223)

Co-authored-by: Sandro <sandro.jaeckel@gmail.com>

* nixos/redis: Use toString for interpolating slaveOf.port

* perlPackages.PerlMagick: 7.0.10 -> 7.0.11-1

* enableRedistributableFirmware: add rtw89-firmware

* nixos/tests/gitlab: disable gitlab-pages tests

* rabbitmq-server: Apply nixpkgs-review hints

* knot-dns: only depend on libmnl on Linux

I didn't realize that it's only relevant for Linux,
and it unnecessarily disabled builds for *-darwin.

* python3Packages.cbor2: 5.4.0 -> 5.4.1

* perlPackages.ImageMagick: rename from perlPackages.PerlMagick

* element-{web,desktop}: 1.7.33 -> 1.7.34

* verifpal: 0.13.7 -> 0.26.0 (#132429)

* nvidia_x11: fix suspend script paths since 470.57.02 (#131838)

nvidia 470.57.02 changed the path of `nvidia-sleep.sh` and systemd
scripts, making `builder.sh` miss them and suspend-to-ram on systems
where `hardware.nvidia.powerManagement.enable = true` is set fail.

* vimPlugins: update

* vimPlugins.gruvbox-material: init at 2021-07-29

* vimPlugins.vim-clap: Update cargo sha256

* icewm: 2.3.4 -> 2.6.0

* linux: only configure IDE to "no" pre-5.14

When trying to build a 5.14 (rc-*), this fails to build otherwise:

> error: unused option: IDE

* djv: init at 2.0.8-unstable-2021-07-31

* mysql_jdbc: modernize, 5.1.46 -> 5.1.49

* libsigrok_0_3: fix

Apparently we have an old-version override and it doesn't make the
bindings at all, so only run the installCheck when we know it should
succeed.

* skopeo: 1.3.1 -> 1.4.0

https://github.com/containers/skopeo/releases/tag/v1.4.0

* remove maintainer vozz

* maintainers: add twitchyliquid64

* sirula: init at unstable-2021-07-11

This commit packages sirula, a simple app launcher for wayland.

* unixcw: use libsForQt5, enable qt wrapper (#131816)

* python3Packages.pyintesishome: 1.7.7 -> 1.8.0

* vscode-extensions.hashicorp.terraform: 2.13.2 -> 2.14.0

* v2ray: 4.41.0 -> 4.41.1

* jellyfin-media-player: 1.6.0 -> 1.6.1

* jellyfin-media-player: added kranzes (myself) as a maintainer

* python3Packages.pikepdf: 2.12.2 -> 2.16.1

* exploitdb: 2021-07-30 -> 2021-08-03

* roon-bridge: support aarch64-linux

* nixos/roon-bridge: register module in module-list

* chromium: 92.0.4515.107 -> 92.0.4515.131

https://chromereleases.googleblog.com/2021/08/the-stable-channel-has-been-updated-to.html

This update includes 10 security fixes.

CVEs:
CVE-2021-30590 CVE-2021-30591 CVE-2021-30592 CVE-2021-30593
CVE-2021-30594 CVE-2021-30596 CVE-2021-30597

* buildah: 1.21.1 -> 1.22.0

Signed-off-by: Sascha Grunert <sgrunert@redhat.com>

* dict-dbs: add dontUnpack = true

Fixes the "variable $src or $srcs should point to the source" error.

Co-authored-by: Jamie McClymont <jamie@kwiius.com>
Co-authored-by: Fabian Affolter <mail@fabian-affolter.ch>
Co-authored-by: Fabian Affolter <fabian@affolter-engineering.ch>
Co-authored-by: Robert Hensing <roberth@users.noreply.github.com>
Co-authored-by: zowoq <59103226+zowoq@users.noreply.github.com>
Co-authored-by: Jörg Thalheim <Mic92@users.noreply.github.com>
Co-authored-by: Andrei Pampu <pampu.s.andrei@gmail.com>
Co-authored-by: Profpatsch <mail@profpatsch.de>
Co-authored-by: Ryan Mulligan <ryan@ryantm.com>
Co-authored-by: Alyssa Ross <hi@alyssa.is>
Co-authored-by: Naïm Favier <n@monade.li>
Co-authored-by: Lassulus <github@lassul.us>
Co-authored-by: Alexandre Esteves <alexandre.fmp.esteves@gmail.com>
Co-authored-by: Vladimír Čunát <v@cunat.cz>
Co-authored-by: Vladyslav M <dywedir@gra.red>
Co-authored-by: Jan Solanti <jhs@psonet.com>
Co-authored-by: davidak <davidak@users.noreply.github.com>
Co-authored-by: Jörg Thalheim <joerg@thalheim.io>
Co-authored-by: Michael Weiss <dev.primeos@gmail.com>
Co-authored-by: Maximilian Bosch <maximilian@mbosch.me>
Co-authored-by: sternenseemann <0rpkxez4ksa01gb3typccl0i@systemli.org>
Co-authored-by: David Reaver <johndreaver@gmail.com>
Co-authored-by: Mario Rodas <marsam@users.noreply.github.com>
Co-authored-by: Louis Bettens <louis@bettens.info>
Co-authored-by: Benjamin Asbach <asbachb.github@impl.it>
Co-authored-by: Benjamin Asbach <asbachb@users.noreply.github.com>
Co-authored-by: Vinícius Müller <vinigm.nho@gmail.com>
Co-authored-by: Sandro <sandro.jaeckel@gmail.com>
Co-authored-by: Luke Granger-Brown <git@lukegb.com>
Co-authored-by: ajs124 <ajs124@users.noreply.github.com>
Co-authored-by: David Arnold <dgx.arnold@gmail.com>
Co-authored-by: Aaron Andersen <aaron@fosslib.net>
Co-authored-by: Felix Buehler <account@buehler.rocks>
Co-authored-by: figsoda <figsoda@pm.me>
Co-authored-by: Zhaofeng Li <hello@zhaofeng.li>
Co-authored-by: Bernardo Meurer <bernardo@meurer.org>
Co-authored-by: Markus Kowalewski <markus.kowalewski@gmail.com>
Co-authored-by: Anderson Torres <torres.anderson.85@protonmail.com>
Co-authored-by: Sebastian Sellmeier <mail@sebastian-sellmeier.de>
Co-authored-by: R. RyanTM <ryantm-bot@ryantm.com>
Co-authored-by: Tristan Gosselin-Hane <starcraft66@gmail.com>
Co-authored-by: klDen <kl@kenzymele.com>
Co-authored-by: Ben Siraphob <bensiraphob@gmail.com>
Co-authored-by: superherointj <5861043+superherointj@users.noreply.github.com>
Co-authored-by: 06kellyjac <dev@j-k.io>
Co-authored-by: iko <ilyakooo0@gmail.com>
Co-authored-by: Mukund Lakshman <yaymukund@gmail.com>
Co-authored-by: Niklas <44636701+MayNiklas@users.noreply.github.com>
Co-authored-by: Mustafa Çalışkan <musfay@protonmail.com>
Co-authored-by: Florian Klink <flokli@flokli.de>
Co-authored-by: Manuel Bärenz <programming@manuelbaerenz.de>
Co-authored-by: Vladyslav Burzakovskyy <vladislav.burzakovskij@satoshilabs.com>
Co-authored-by: Markus Partheymueller <markus.partheymueller@cyberus-technology.de>
Co-authored-by: Victor Nawothnig <dminuoso+git@icloud.com>
Co-authored-by: Artturin <Artturin@artturin.com>
Co-authored-by: Robin Gloster <mail@glob.in>
Co-authored-by: Domen Kožar <domen@dev.si>
Co-authored-by: Yureka <yuka@yuka.dev>
Co-authored-by: Sumner Evans <me@sumnerevans.com>
Co-authored-by: Malte-Christian <3236302+malte-christian@users.noreply.github.com>
Co-authored-by: André Vitor de Lima Matos <andre.vmatos@gmail.com>
Co-authored-by: Linus Heckemann <git@sphalerite.org>
Co-authored-by: Julian Stecklina <js@alien8.de>
Co-authored-by: Pascal Bach <pascal.bach@nextrem.ch>
Co-authored-by: Harrison Houghton <hora.rhino@gmail.com>
Co-authored-by: Robert Scott <code@humanleg.org.uk>
Co-authored-by: Stig <stig@stig.io>
Co-authored-by: ollieh <3164917+ollieh@users.noreply.github.com>
Co-authored-by: adisbladis <adisbladis@gmail.com>
Co-authored-by: Tom <twitchyliquid64@ciphersink.net>
Co-authored-by: Rob Brewer <rwb123@gmail.com>
Co-authored-by: Ryan Horiguchi <ryan.horiguchi@gmail.com>
Co-authored-by: Vanilla <neko@hydev.org>
Co-authored-by: Ilan Joselevich <personal@ilanjoselevich.com>
Co-authored-by: Lein Matsumaru <applePrincess@applePrincess.io>
Co-authored-by: Sascha Grunert <sgrunert@redhat.com>
Co-authored-by: Andrey Golovizin <ag@sologoc.com>