lame: prevent build failure from using outdated symbol list
Before this change, trying to build LAME on Darwin would throw an error:

Undefined symbols for architecture x86_64:
  "_lame_init_old", referenced from:
     -exported_symbol[s_list] command line option
ld: symbol(s) not found for architecture x86_64
clang-4.0: error: linker command failed with exit code 1 (use -v to see invocation)

(cherry picked from commit e82dc084d4d1c663c024fcc3c629d850c9cb5c3e)