evcc: 0.309.1 -> 0.311.1
https://github.com/evcc-io/evcc/releases/tag/0.311.1

Also remove tag "test" which otherwise breaks the build of the ship-go
dependency:

> vendor/github.com/enbility/ship-go/ship/handshake.go:63:72: undefined: getHelloInitTimeout

The 'test' tag prevented the production timeouts from being included,
and the test definitions are only available in test.
https://github.com/enbility/ship-go/blob/dev/README.md#fast-test-execution-with-test-build-tags

Generally, the 'test' tag is not something you need to manually add, and
indeed no other go package in nixpkgs has such a flag enabled.

(cherry picked from commit c6ff2a8cc7986fe4c37c440f090d36ca1f207712)