python310Packages.ocrmypdf: fix build on Darwin
With enabled sandbox we get
    PermissionError: [Errno 1] Operation not permitted
when calling os.nice().

(cherry picked from commit 65450988a59dc253a93148e6d9cd739a0e9e2083)