nixos/miniflux: don't require DATABASE_URL if not createDatabaseLocally
For example, if providing through EnvironmentFile due to secrets then we
need to allow the env to build without this config.

Fixes this error:

    error: The option `services.miniflux.config.DATABASE_URL' was accessed but has no value defined. Try setting the option.

(cherry picked from commit fd3a8eddcb44829c3e5aded7d768e0f7b27fb2f6)