delly: remove `postPatch` modification
* In Sept 2024 (https://github.com/NixOS/nixpkgs/commit/a9275e71f84c148a47ddabe5bcb5950d2d8ba1da),
  a postPatch modification to Makefile was added to downgrade from c++17
  to c++14. I don't understand the initial reasoning behind the change,
  but as of today this causes compilation error on `aarch64-darwin`:

  ```
  src/modvcf.h:147:29: error: no template named 'void_t' in namespace 'std'; did you mean 'boost::void_t'?
    147 |   struct _HasMinCpgDepth<T, std::void_t<decltype(std::declval<T>().minCpgDepth)>> : std::true_type {};
        |                             ^~~~~~~~~~~
        |                             boost::void_t
  ```

  Compiling/building project with c++17 resolves the problem.

Resolves: #556820