swfdec: drop
Broken due to broken gstreamer 0.10 and does not seem to build with --disable-gstreamer in configureFlags:

	libtool: link: gcc -Wall -Wextra -Wno-missing-field-initializers -Wno-unused-parameter -Wold-style-definition -Wdeclaration-after-statement -Wmissing-declarations -Wmissing-prototypes -Wredundant-decls -Wmissing-noreturn -Wshadow -Wpointer-arith -Wcast-align -Wwrite-strings -Winline -Wformat-nonliteral -Wformat-security -Wswitch-enum -Wswitch-default -Winit-self -Wmissing-include-dirs -Wundef -Waddress -Waggregate-return -Wmissing-format-attribute -Wno-multichar -Wnested-externs -std=gnu99 -I/nix/store/q24nzpj4lvzvvj2vkgywrsy1xyrskx1y-cairo-1.16.0-dev/include/cairo -I/nix/store/iid4kx5h4xw1c8zfl9hbls3w7wl1nc3k-freetype-2.10.2-dev/include/freetype2 -I/nix/store/iid4kx5h4xw1c8zfl9hbls3w7wl1nc3k-freetype-2.10.2-dev/include -I/nix/store/6gspczr6c1ci62ih04nb41dwh3053s1z-fontconfig-2.13.92-dev/include -I/nix/store/iid4kx5h4xw1c8zfl9hbls3w7wl1nc3k-freetype-2.10.2-dev/include/freetype2 -I/nix/store/j81d3idny3bq1z465kbs48in466vws1i-glib-2.64.4-dev/include -I/nix/store/j81d3idny3bq1z465kbs48in466vws1i-glib-2.64.4-dev/include/glib-2.0 -I/nix/store/mazsps24z01540n3g01m8yf52wm6avkd-glib-2.64.4/lib/glib-2.0/include -I/nix/store/gcl6pcr3dgaqwflvnnzcgzarpzb5pp5w-pango-1.45.3-dev/include/pango-1.0 -I/nix/store/xqm5l9n4xwl8z530iqn8806hvs1dgrpq-harfbuzz-2.6.7-dev/include/harfbuzz -I/nix/store/glf8vfw53iz0xlwmfkw6005kn74pm23i-gtk+-2.24.32-dev/include/gtk-2.0 -I/nix/store/g9pfp91b5syf8qpp5hv8pqwyaca1k0v8-gtk+-2.24.32/lib/gtk-2.0/include -I/nix/store/jvqgd252mkv6b0ky7k2ld1sgdi3fnql0-gdk-pixbuf-2.40.0-dev/include/gdk-pixbuf-2.0 -I/nix/store/yjd5mh1xrx06glzn8limgv6hh6alw88s-atk-2.36.0-dev/include/atk-1.0 -I/nix/store/sayziyky8aqf58130d642cvc3hkdwz5x-libsoup-2.70.0-dev/include/libsoup-2.4 -I.. -pthread -I/nix/store/j81d3idny3bq1z465kbs48in466vws1i-glib-2.64.4-dev/include -I/nix/store/j81d3idny3bq1z465kbs48in466vws1i-glib-2.64.4-dev/include/glib-2.0 -I/nix/store/mazsps24z01540n3g01m8yf52wm6avkd-glib-2.64.4/lib/glib-2.0/include -I/nix/store/q24nzpj4lvzvvj2vkgywrsy1xyrskx1y-cairo-1.16.0-dev/include/cairo -I/nix/store/iid4kx5h4xw1c8zfl9hbls3w7wl1nc3k-freetype-2.10.2-dev/include/freetype2 -I/nix/store/iid4kx5h4xw1c8zfl9hbls3w7wl1nc3k-freetype-2.10.2-dev/include -I/nix/store/ck8acp8qaqmdh9kkxy0amcn51n2wsw39-zlib-1.2.11-dev/include -I/nix/store/im2q3xxm6swqqzmks0vylvyca0zq7jyr-libpng-apng-1.6.37-dev/include/libpng16 -I/nix/store/q24nzpj4lvzvvj2vkgywrsy1xyrskx1y-cairo-1.16.0-dev/include/cairo -I/nix/store/iid4kx5h4xw1c8zfl9hbls3w7wl1nc3k-freetype-2.10.2-dev/include/freetype2 -I/nix/store/iid4kx5h4xw1c8zfl9hbls3w7wl1nc3k-freetype-2.10.2-dev/include -I/nix/store/ck8acp8qaqmdh9kkxy0amcn51n2wsw39-zlib-1.2.11-dev/include -I/nix/store/im2q3xxm6swqqzmks0vylvyca0zq7jyr-libpng-apng-1.6.37-dev/include/libpng16 -g -O2 -pthread -o .libs/swfdec-test swfdec_test-swfdec_test.o swfdec_test-swfdec_test_buffer.o swfdec_test-swfdec_test_function.o swfdec_test-swfdec_test_global.o swfdec_test-swfdec_test_image.o swfdec_test-swfdec_test_plugin.o swfdec_test-swfdec_test_socket.o swfdec_test-swfdec_test_swfdec_socket.o swfdec_test-swfdec_test_test.o swfdec_test-swfdec_test_utils.o  ../swfdec/.libs/libswfdec-0.8.so -L/nix/store/39yl51648a6d2rbz5ffzvw62y4f42d48-cairo-1.16.0/lib -L/nix/store/lxbxwg609cw3zby7ba78h0992hp9rcfy-zlib-1.2.11/lib -L/nix/store/zjrnaa0c9hiqkc21ny5p5k3ijk731prv-libpng-apng-1.6.37/lib -L/nix/store/mazsps24z01540n3g01m8yf52wm6avkd-glib-2.64.4/lib -L/nix/store/xwpjpc5ypbqpn9p0ir2dv6sp87aj772m-pango-1.45.3/lib -L/nix/store/zlpl17p3aq9a0x1nkxkp4bb1q949kl22-harfbuzz-2.6.7/lib -L/nix/store/zay41pvqbqgc4fhn376afvcx9s9hm6k2-liboil-0.3.17/lib /nix/store/zay41pvqbqgc4fhn376afvcx9s9hm6k2-liboil-0.3.17/lib/liboil-0.3.so -lrt -lgthread-2.0 -lm -L/nix/store/n9n570xdj4gnza8yp1vkgqlidadcwkbj-fontconfig-2.13.92-lib/lib -L/nix/store/6nlkl2jqywpyxwk7c8il8kr5d3fkplpz-freetype-2.10.2/lib -L/nix/store/g9pfp91b5syf8qpp5hv8pqwyaca1k0v8-gtk+-2.24.32/lib -L/nix/store/awfrddgfpv76s64fcsrjk64lnmkwgll5-gdk-pixbuf-2.40.0/lib -L/nix/store/17m4xwywi3v2smafq98mzla3jippnqp9-atk-2.36.0/lib -L/nix/store/h5q0dj39gqp58h6mvsmb5bvbyd3vdghn-libsoup-2.70.0/lib /nix/store/g9pfp91b5syf8qpp5hv8pqwyaca1k0v8-gtk+-2.24.32/lib/libgtk-x11-2.0.so /nix/store/g9pfp91b5syf8qpp5hv8pqwyaca1k0v8-gtk+-2.24.32/lib/libgdk-x11-2.0.so -lpangocairo-1.0 -latk-1.0 -lgdk_pixbuf-2.0 -lpangoft2-1.0 -lpango-1.0 /nix/store/zlpl17p3aq9a0x1nkxkp4bb1q949kl22-harfbuzz-2.6.7/lib/libharfbuzz.so /nix/store/n9n570xdj4gnza8yp1vkgqlidadcwkbj-fontconfig-2.13.92-lib/lib/libfontconfig.so /nix/store/6nlkl2jqywpyxwk7c8il8kr5d3fkplpz-freetype-2.10.2/lib/libfreetype.so -L/nix/store/jgfa1mslsw5ag1mgr5bggi1f30nn5zam-bzip2-1.0.6.0.1/lib /nix/store/jgfa1mslsw5ag1mgr5bggi1f30nn5zam-bzip2-1.0.6.0.1/lib/libbz2.so -lsoup-2.4 -lgio-2.0 -lgobject-2.0 -lglib-2.0 /nix/store/39yl51648a6d2rbz5ffzvw62y4f42d48-cairo-1.16.0/lib/libcairo.so /nix/store/zjrnaa0c9hiqkc21ny5p5k3ijk731prv-libpng-apng-1.6.37/lib/libpng16.so -lz -pthread -Wl,-rpath -Wl,/nix/store/kxyr9r1xacpkkxy2jdl6hn172j922nla-swfdec-0.8.4/lib -Wl,-rpath -Wl,/nix/store/zay41pvqbqgc4fhn376afvcx9s9hm6k2-liboil-0.3.17/lib -Wl,-rpath -Wl,/nix/store/g9pfp91b5syf8qpp5hv8pqwyaca1k0v8-gtk+-2.24.32/lib -Wl,-rpath -Wl,/nix/store/zlpl17p3aq9a0x1nkxkp4bb1q949kl22-harfbuzz-2.6.7/lib -Wl,-rpath -Wl,/nix/store/n9n570xdj4gnza8yp1vkgqlidadcwkbj-fontconfig-2.13.92-lib/lib -Wl,-rpath -Wl,/nix/store/6nlkl2jqywpyxwk7c8il8kr5d3fkplpz-freetype-2.10.2/lib -Wl,-rpath -Wl,/nix/store/jgfa1mslsw5ag1mgr5bggi1f30nn5zam-bzip2-1.0.6.0.1/lib -Wl,-rpath -Wl,/nix/store/39yl51648a6d2rbz5ffzvw62y4f42d48-cairo-1.16.0/lib -Wl,-rpath -Wl,/nix/store/zjrnaa0c9hiqkc21ny5p5k3ijk731prv-libpng-apng-1.6.37/lib
	/nix/store/1ar9gcmvikdk1wij0cw4fnwvl5i07ag1-binutils-2.31.1/bin/ld: swfdec_test-swfdec_test_test.o: undefined reference to symbol 'g_module_build_path'
	/nix/store/1ar9gcmvikdk1wij0cw4fnwvl5i07ag1-binutils-2.31.1/bin/ld: /nix/store/mazsps24z01540n3g01m8yf52wm6avkd-glib-2.64.4/lib/libgmodule-2.0.so.0: error adding symbols: DSO missing from command line