python3Packages.laspy: Add fast lazrs backend
Requires laspy >= 2.6.0 due to this fix:
https://github.com/laspy/laspy/commit/036c37e9e16e912c296147d20ecd6c638d7bac78

Older versions error:

    laspy.errors.LaspyException: Could not initialize a laz backend: LasZipAppender.__new__() missing 1 required positional argument: 'point_count'