openttd: fix build against icu-76
Without the change `openttd` build fails in `master` as
https://hydra.nixos.org/build/290760688:

    [100%] Linking CXX executable openttd
    ld: CMakeFiles/openttd_lib.dir/src/survey.cpp.o: undefined reference to symbol 'u_versionToString_76'
    ld: /nix/store/...-icu4c-76.1/lib/libicuuc.so.76: error adding symbols: DSO missing from command line
    collect2: error: ld returned 1 exit status