graphene-hardened-malloc: constrain platforms to x64 linux
Build error on i686:

> util.h:39:18: error: '__int128' is not supported on this target
  typedef unsigned __int128 u128;

(cherry picked from commit a08851c925cf2eef92b4f6ccf9581751633f0f40)