pylint: fix 1.9
It depends on pyenchant, which is disabled on python2. This results
in:
```
nix-env -iA unstable.python27Packages.pylint
replacing old 'python2.7-pylint-1.9.5'
installing 'python2.7-pylint-1.9.5'
error: pyenchant-3.1.1 not supported for interpreter python2.7
```

Remove it, à la
https://github.com/NixOS/nixpkgs/commit/eb0d5fc3f076ad8fbac43158e77277066bbe28b9
and now it builds again.