rocmPackages.meta.release-packagePlatforms: skip missing attrs
Fixes:
error: evaluation aborted with the following error message: 'cannot find attribute 'pkgsRocm.beets-unstable''