task-master-ai: add missing dependency
when running the following command

```sh
task-master init
```

it fails with the following error

```txt
Error: spawn node ENOENT
```