bpftools: use binutils-2.38 for linux before 5.19
Without the change bpftools build fails on binutils-2.39 due to API change:

    jit_disasm.c:105:17: error: too few arguments to function 'init_disassemble_info'
      105 |                 init_disassemble_info(&info, stdout,
          |                 ^~~~~~~~~~~~~~~~~~~~~