unity-test: fix unstable patch hashes
Without the change the attempt to refetch patches fails with hash mismatch:

````
$ nix build --no-link -f. unity-test.patches --rebuild
error: hash mismatch in fixed-output derivation '/nix/store/h81wmb8js5h1g2is5bzisf6b9d36arxc-771.patch.drv':
         specified: sha256-r8ldVb7WrzVwTC2CtGul9Jk4Rzt+6ejk+paYAfFlR5M=
            got:    sha256-viNwaqZ+hjIY4qnlLN55/TMzqmoNAgc1Eq5Yv17tr7c=
```

It happens because repository now adds one extra digit to abbreviated
hash:

```diff
    diff -U0 before after
    @@ -2 +2 @@
    -index 6585129c..9489aef4 100644
    +index 6585129c9..9489aef48 100644
```

Let's use `?full_index=1` to use full hash in diff output.