ipmicfg: fix broken pkg: 1.34.0 -> 1.34.2
Summary
===

ipmicfg looks to be broken due to a broken supermicro download link. I
found a minor version upgrade link that works and upgraded this nix pkg
with it.

Detailed reproduction / literate change
===

Adding `ipmicfg` to my `configuration.nix`

```

  environment.systemPackages = with pkgs; [
    ipmicfg
  ];
```

breaks the `nixos-rebuild switch`:

```
~ λ sudo nixos-rebuild switch
trying https://www.supermicro.com/wftp/utility/IPMICFG/IPMICFG_1.34.0_build.220906.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   201  100   201    0     0    897      0 --:--:-- --:--:-- --:--:--   901
100   150  100   150    0     0    254      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  163k    0  163k    0     0   234k      0 --:--:-- --:--:-- --:--:--  234k
unpacking source archive /build/IPMICFG_1.34.0_build.220906.zip
[/build/IPMICFG_1.34.0_build.220906.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /build/IPMICFG_1.34.0_build.220906.zip or
        /build/IPMICFG_1.34.0_build.220906.zip.zip, and cannot find /build/IPMICFG_1.34.0_build.220906.zip.ZIP, period.
do not know how to unpack source archive /build/IPMICFG_1.34.0_build.220906.zip
error: builder for '/nix/store/0l6h8gbvynn0fpl1gfnj0hhv6hj5nc8h-source.drv' failed with exit code 1
error: 1 dependencies of derivation '/nix/store/0gv1k3zpgj2dkdfxzfv5dl0wlb0flk7p-ipmicfg-1.34.0.drv' failed to build
error: 1 dependencies of derivation '/nix/store/s9h4j6yfmyjp312vy55ya5qdh7z630cy-system-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/5fw4wznnvwr7gjglv5pxx8m15nma0k27-nixos-system-nixos-23.05.1784.d8bb6c681cf.drv' failed to build
```

curling that URL shows it has been moved:

```

~ λ  curl https://www.supermicro.com/wftp/utility/IPMICFG/IPMICFG_1.34.0_build.220906.zip
<head><title>Document Moved</title></head>
<body><h1>Object Moved</h1>This document may be found <a HREF="https://www.supermicro.com/wdl/utility/IPMICFG/IPMICFG_1.34.0_build.220906.zip">here</a></body>
```

following the 301 goes to the homepage:

```

~ λ curl https://www.supermicro.com/wdl/utility/IPMICFG/IPMICFG_1.34.0_build.220906.zip
<head><title>Document Moved</title></head>
<body><h1>Object Moved</h1>This document may be found <a HREF="https://www.supermicro.com/">here</a></body>
```

In other words, it looks like this link is broken now.

On the bright side, I found an upgrade:

```
curl https://www.supermicro.com/wdl/utility/IPMICFG/
www.supermicro.com - /wdl/utility/IPMICFG/
[To Parent Directory]

 3/24/2023  9:34 AM         1000 CheckSum.txt
 3/24/2023  9:34 AM          512 IPMICFG_1.34.2_build.230224.sig
 3/24/2023  9:34 AM      2381414 IPMICFG_1.34.2_build.230224.zip
 3/24/2023  9:34 AM          512 IPMICFG_1.34.2_build.230224_ESXi.sig
 3/24/2023  9:34 AM      1643195 IPMICFG_1.34.2_build.230224_ESXi.zip
 3/24/2023  9:34 AM       839705 IPMICFG_UserGuide.pdf
 3/24/2023  9:34 AM        <dir> Previous Releases
```

wgetting the `IPMICFG_1.34.2_build.230224.zip` file works as expected.

```
/tmp λ wget https://www.supermicro.com/wdl/utility/IPMICFG/IPMICFG_1.34.2_build.230224.zip
--2023-07-09 18:04:53--  https://www.supermicro.com/wdl/utility/IPMICFG/IPMICFG_1.34.2_build.230224.zip
Resolving www.supermicro.com (www.supermicro.com)... 23.44.174.154, 23.44.174.120
Connecting to www.supermicro.com (www.supermicro.com)|23.44.174.154|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2381414 (2.3M) [application/x-zip-compressed]
Saving to: ‘IPMICFG_1.34.2_build.230224.zip’

IPMICFG_1.34.2_buil 100%[===================>]   2.27M  --.-KB/s    in 0.08s

2023-07-09 18:04:53 (27.5 MB/s) - ‘IPMICFG_1.34.2_build.230224.zip’ saved [2381414/2381414]
```

cross-referencing the provided `CheckSum.txt` file:

```
/tmp λ curl https://www.supermicro.com/wdl/utility/IPMICFG/CheckSum.txt
IPMICFG_1.34.2_build.230224.sig
  CRC32 CheckSum : D32AD874
  MD5 CheckSum : 7D74C33E34584CE01895486B71D042DF
  SHA-256 CheckSum : BF783BFE0DD0FE54A995873BCF8118CFC2C0E15C8A15D691BB721ED170B5AE8F
IPMICFG_1.34.2_build.230224.zip
  CRC32 CheckSum : DD3EA812
  MD5 CheckSum : 0F1C7B0528A3C6CE93488B9964AEDBED
  SHA-256 CheckSum : FADD6CDDE37427313620CD894B041A6CF298E76277093B5EE5BF6D4A20780AA3
IPMICFG_1.34.2_build.230224_ESXi.sig
  CRC32 CheckSum : CDDAC198
  MD5 CheckSum : 7AB98B5150418B815D2B740C5661565B
  SHA-256 CheckSum : A0CD49060A8EA77A5B0E0B1BF63D60B2512354A2F15EB32E884B14602A9A6B81
IPMICFG_1.34.2_build.230224_ESXi.zip
  CRC32 CheckSum : 0D3DA053
  MD5 CheckSum : 262D3D6B4A27D8ED93D5941DD217EEC6
  SHA-256 CheckSum : A896E52811B7333D55BF72E2133ABF8F07951752899172C4C5131F4919CDB7FA
IPMICFG_UserGuide.pdf
  CRC32 CheckSum : 7A6FF7C1
  MD5 CheckSum : 00C09CC09036830000AC1348C9024832
  SHA-256 CheckSum : 6CB4986DA00627030A73154A436CCE06309ED3DC55D26097AF2ED0DBB97259A5
```

```
/tmp λ sha256sum IPMICFG_1.34.2_build.230224.zip
fadd6cdde37427313620cd894b041a6cf298e76277093b5ee5bf6d4a20780aa3  IPMICFG_1.34.2_build.230224.zip
```

We find that it is the same as the downloaded build zip.

To get the nix sha256:

```
/tmp λ nix-prefetch-url --unpack https://www.supermicro.com/wdl/utility/IPMICFG/IPMICFG_1.34.2_build.230224.zip
path is '/nix/store/4l050cmkki5l926d4zqn269532f193mh-IPMICFG_1.34.2_build.230224.zip'
1s924y6f0lvmd2m0na1nh0vyqf8qpp34wc6ndi8fwga4ynj66l63
```