prelink: unstable-2019-06-24 -> 20151030-unstable-2024-07-02
Without the change build fails on `gcc-14` as
https://hydra.nixos.org/build/294837353:

    execstack.c: In function 'execstack_make_rdwr':
    execstack.c:138:17: error: passing argument 1 of 'asprintf' from incompatible pointer type []
      138 |       asprintf (&prelink_path, "%s/%s", dirname, PRELINK_PROG EXEEXT);
          |                 ^~~~~~~~~~~~~
          |                 |
          |                 const char **

(cherry picked from commit 22d5893faec01fce7b9abbe9f9ba415f924c21b0)