cinnamon.cinnamon-common: unbreak cinnamon-settings-users
ValueError: Namespace Gtk not available

(cherry picked from commit 1e8e84a59fdbdcb6a053066eb04d5596feb266ac)