gclient2nix: fix for electron_44
Fixes error:

```
ValueError: invalid "and" operand 'checkout_s390' (inside 'checkout_linux and checkout_s390 and non_git_source')
```

(cherry picked from commit fbc9efcbf2a286131bcf0ae42a69b5d0f34d9b0c)