gclient2nix: update, fix for electron_43
Fixes error:

```
KeyError: "host_cpu was used as a variable, but was not declared in the vars dict (file 'DEPS', line 114)"
```

https://chromium.googlesource.com/webpagereplay.git/+/b2b856131e36c99e9de9c419fe8ca02f857082ba/DEPS#114
(cherry picked from commit c6eb78bad219df56465dff8ade35dd2c4829df17)