aewan: fix build against ncurses-6.3
`ncuses-6.3` added printf-style function attributes and now makes
it easier to catch cases when user input is used in palce of format
string when built with CFLAGS=-Werror=format-security:

    aewan.c: In function 'paint_screen':
    aewan.c:147:7: error: format not a string literal and no format arguments [-Werror=format-security]
      147 |       printw(msg);
          |       ^~~~~~

Let's pull a patch pending upstream inclusion.