ttf2pt1: fix build with gcc14
- add patch fixing build with c99 from fedora:
https://src.fedoraproject.org/rpms/ttf2pt1/c/070de5269475785d27ae7996513bee12cb9a0f53
Fixes build error:
```
t1asm.c: In function 'main':
t1asm.c:501:15: error: implicit declaration of function 'getopt';
did you mean 'getsubopt'? []
  501 |   while ((c = getopt(argc, argv, "bl:")) != -1)
      |               ^~~~~~
      |               getsubopt
```

- add patch fixing build with gcc14 from fedora
https://src.fedoraproject.org/rpms/ttf2pt1/c/1ebb612acb7088095c6bd7242209f0ce848895fb
Patch does not apply as is with `fetchpatch` because of incorrect
listed files: `diff -u ft.c{.orig,}`.
Fixes `-Wincompatible-pointer-types` errors:
`error: intialization of ... from incompatible pointer type ...`
for `outl_moveto`, `outl_lineto`, `outl_conicto` and `outl_cubicto`
in `ft.c`