doc/builders/images/dockertools: improve shadowSetup example
The example snippet will fail with this error as it is not self contained and
assumes `shadowSetup` was given:

    $ nix-build docker-image.nix
    error: undefined variable 'shadowSetup' at docker-image.nix:20:7

Instead use the full reference to `shadowSetup` in the example so it will work
as stated.

(cherry picked from commit ac66ff97ed1f86d2ac98e1f49cfff427fe1e526d)