remove missing attribute 'lens-family-th_0_4_1_0'
$ nix-env -f '<nixpkgs>' -qaPA pkgs.haskell.packages.ghc7103 -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/master.tar.gz
error: attribute ‘lens-family-th_0_4_1_0’ missing, at /nix/store/l7kr5m1h1rp16fh7d1m47caj2yj6xz4m-master.tar.gz/pkgs/development/haskell-modules/configuration-ghc-7.10.x.nix:161:20