Use propagatedBuildInputs for Python dependencies
When I ran rpl, I got the error

```
ModuleNotFoundError: No module named 'chardet'
```

but making this change to use propagatedBuildInputs fixed it, as
described at
https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/python.section.md#handling-dependencies-handling-dependencies