haskellPackages.3d-graphics-example: fix the eval
Without the change the eval fails as:

    $ nix build --no-link -f. haskellPackages.3d-graphics-example
    error:
       … while evaluating the attribute 'value'
         at pkgs/development/haskell-modul
         2162|         name = old;
         2163|         value =
             |         ^
         2164|           lib.warnOnInstantiate "haskell.packages.*.${old} has b

       … in the right operand of the update (//) operator
         at lib/derivations.nix:253:12:
          252|     in
          253|     drv // mapAttrs (_: lib.warn msg) drvToWrap;
             |            ^
          254| }

       (stack trace truncated; use '--show-trace' to show the full, detailed tr

       error: attribute '_3d-graphics-example' missing
       at pkgs/development/haskell-modules/configuration-nix.nix:2165:13:
         2164|           lib.warnOnInstantiate "haskell.packages.*.${old} has been renamed to haskell.packages.*.${new}"
         2165|             self.${new};
             |             ^
         2166|       }
       Did you mean one of 3d-graphics-example or _3d-graphics-examples?

(cherry picked from commit a677747fff3c929db7366b2950717884a6752032)