echidna: fix broken build
The overridden `hevm` package declared in `echnidna`s package
is missing its `tuple` dependency, leading to failing builds:

```
Configuring hevm-0.51.3...
CallStack (from HasCallStack):
  withMetadata, called at libraries/Cabal/Cabal/src/Distribution/Simple/Utils.hs:370:14 in Cabal-3.8.1.0:Distribution.Simple.Utils
Error: Setup: Encountered missing or private dependencies:
tuple >=0.3.0.2 && <0.4
```