linuxPackages.perf: use binutils-2.38 for linux before 5.19
Without the change perf build fails on binutils-2.39 due to API change:

util/annotate.c: In function 'symbol__disassemble_bpf':
util/annotate.c:1765:9: error: too few arguments to function 'init_disassemble_info'
 1765 |         init_disassemble_info(&info, s,
      |         ^~~~~~~~~~~~~~~~~~~~~