python3Packages.openllm-core: fix `optional-dependencies` evaluation
Without the change eval fails as:

    $ nix build --no-link -f. python3Packages.openllm-core.optional-dependencies
    error:
           79|   passthru.optional-dependencies =
             |   ^
           80|   let

       error: attribute 'accelerate' missing

From what I see `accelerate` was always missing in `transflrmers` package.
While at it fixed `full` evaluation by disambiguating between input
argument and `passthru` attribute.