lirc: adapt to linux-headers-5.18
Without the change update to linux-header-5.18 causes build failure as:

    lircd.cpp: In function 'int setup_hardware()':
    lircd.cpp:492:49: error: 'LIRC_CAN_SET_REC_FILTER' was not declared in this scope; did you mean 'LIRC_CAN_SET_REC_CARRIER'?
      492 |                     || (curr_driver->features & LIRC_CAN_SET_REC_FILTER)) {
          |                                                 ^~~~~~~~~~~~~~~~~~~~~~~
          |                                                 LIRC_CAN_SET_REC_CARRIER