vsmartcard-vpcd: add missing wrapPythonPrograms
Fixes this issue:

  $ vicc
  Traceback (most recent call last):
    File "/run/current-system/sw/bin/vicc", line 116, in <module>
      from virtualsmartcard.VirtualSmartcard import VirtualICC
  ModuleNotFoundError: No module named 'virtualsmartcard'