unixODBCDrivers.mariadb: fix build with gcc15
- add patch from merged upstream PR that adds missing `#include <cstdint>`
https://www.github.com/mariadb-corporation/mariadb-connector-odbc/pull/63
https://github.com/mariadb-corporation/mariadb-connector-odbc/commit/a3ced654db2ef93de0a818f2d66171f6084e5f2d

Fixes build failure with gcc15:
```
/build/source/driver/class/ColumnDefinition.h:55:10: error: 'uint8_t'
does not name a type
   55 |   static uint8_t maxCharlen[];
      |          ^~~~~~~
/build/source/driver/class/ColumnDefinition.h:30:1: note: 'uint8_t' is
defined in header '<cstdint>'; this is probably fixable by adding
'#include <cstdint>'
   29 | #include "SQLString.h"
  +++ |+#include <cstdint>
   30 |
/build/source/driver/interface/CmdInformation.h:35:15: error: 'int64_t'
was not declared in this scope
   35 |   std::vector<int64_t> batchRes;
      |               ^~~~~~~
/build/source/driver/interface/CmdInformation.h:26:1: note: 'int64_t' is
defined in header '<cstdint>'; this is probably fixable by adding
'#include <cstdint>'
   25 | #include <memory>
  +++ |+#include <cstdint>
   26 |
```