stdenv: assert whether `name` or (`pname` and `version`) are given
Without the assertion, when a `pname` was missing, the whole trace was

    error: attribute 'pname' missing, at /home/freddy/Code/libraries/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:84:54

which is pretty useless if you happened to have changed a lot of
expressions.