saleae-logic: 1.1.15 -> 1.2.9
Changelog:
http://support.saleae.com/hc/en-us/articles/210245593-Saleae-Logic-Beta-Software-Changelog

(Yes, the changelog title contains the word 'beta', but as of version
1.2.9 the beta branding is removed from the software as the beta branch
was merged to master.)

This software update is required for newer logic analysers (e.g. Logic
Pro 8). (The original Logic is still supported, although it's difficult
to find info about it on their website.)

v1.2.9 grew new dependencies: libxcb, zlib, pciutils, xkeyboardconfig.

The LD_PRELOAD library hack, used to divert writes from
$out/Settings/settings.xml to $HOME/.saleae-logic-settings.xml, has been
updated. The new software writes more paths
($out/{Settings,Errors,Databases,Calibration}) and uses a few extra
library calls to access those paths
(open,openat,stat,access,unlink,...). So instead of single file
redirect, the library now redirects accesses to all those directories,
mirrored in $HOME/.saleae-logic/. (Existing
$HOME/.saleae-logic-settings.xml files will be automatically migrated to
$HOME/.saleae-logic/Settings/settings.xml.)

(cherry picked from commit 314b1fbf0c923af4a300c7b92c41ad9e3fc7ae96)

[release-16.03 backport note: s/stdenv.cc.cc.lib/stdenv.cc.cc/ to fix
error: attribute ‘lib’ missing, at .../saleae-logic/default.nix:19:65]