stabber: disable blanket -Werror
Without the change `stabber` fails to build on `staging-next` as:

    src/server/stanza.c: In function 'stanza_to_string':
    /nix/store/dlkvzm8kb7s8bhni6f23i1p2qcv8w4dq-glib-2.78.3-dev/include/glib-2.0/glib/gstring.h:74:5: error: ignoring return value of 'g_string_free_and_steal' declared with attribute 'warn_unused_result' [-Werror=unused-result]

It happens due to blanket `-Werror` option. Disable it.