ipfs-cluster: fix build
Compile ipfs-cluster with Go 1.24 instead of Go 1.25 because:
- Their CI uses Go 1.24, see https://github.com/ipfs-cluster/ipfs-cluster/blob/v1.1.4/.github/workflows/tests.yml#L10
- ipfs-cluster fails to compile with Go 1.25:
  ```
  Building subPackage .
  Building subPackage ./adder
  Building subPackage ./adder/adderutils
  Building subPackage ./adder/ipfsadd
  Building subPackage ./adder/sharding
  Building subPackage ./adder/single
  Building subPackage ./allocator/balanced
  Building subPackage ./api
  Building subPackage ./api/common
  Building subPackage ./api/common/test
  Building subPackage ./api/ipfsproxy
  Building subPackage ./api/pb
  Building subPackage ./api/pinsvcapi
  Building subPackage ./api/pinsvcapi/pinsvc
  Building subPackage ./api/rest
  Building subPackage ./api/rest/client
  Building subPackage ./cmd/ipfs-cluster-ctl
  Building subPackage ./cmd/ipfs-cluster-follow
  # github.com/cockroachdb/swiss
  vendor/github.com/cockroachdb/swiss/map.go:286:7: undefined: hashFn
  vendor/github.com/cockroachdb/swiss/map.go:337:14: undefined: getRuntimeHasher
  vendor/github.com/cockroachdb/swiss/map.go:338:22: undefined: fastrand64
  vendor/github.com/cockroachdb/swiss/map.go:600:23: undefined: fastrand64
  vendor/github.com/cockroachdb/swiss/map.go:649:19: undefined: fastrand64
  vendor/github.com/cockroachdb/swiss/map.go:670:20: undefined: fastrand64
  vendor/github.com/cockroachdb/swiss/options.go:30:14: undefined: hashFn
  ```