lib/gvariant: Fix error message for unsupported primitives
Without this, passing an integer to a setting will fail with a confusing error:

    error: cannot coerce an integer to a string

(cherry picked from commit d248f5786017607f828603866ed4cfae03614700)