python311Packages.sip: add poppler-qt5 to passthru.tests
It breaks on sip 6.8.0 with

    NameError: name 'SocstringSignature' is not defined. Did you mean: 'DocstringSignature'?