noweb: 2.13 -> unstable-2026-04-19
Noweb doesn't publish updates as version tags since 2023 [^1] although
the codebase is still actively maintained [^2]. The README states:

> NOTE ABOUT VERSION

> Noweb predates Semantic Versioning (semver.org) by more than 20 years.
Aside from bug fixes, all versions 2.x should be compatible.  A change
in x means either that something significant changed or that a
significant number of years elapsed since the previous release.
Minor versions get a suffix a, b, etc.

> Version 2.13 is meant to be the last numbered version; future versions
should be referred to by git commit hash.

[^1]: https://github.com/nrnrnr/noweb/releases
[^2]: https://github.com/nrnrnr/noweb/commits/master/

With the newest version of GCC, building the old 2.13 version fails due
to some failing incomparable pointer checks (-Wincompatible-pointer-types; see below).
This change updates the package to the most recent commit on `master`
(committed April 19th, 2026), for which the build completes
successfully.

Build failure log from Hydra:

```
[...]
ipp.c:92:17: error: initialization of 'char * (*)(void)' from incompatible pointer type 'char * (*)(char *)' [-Wincompatible-pointer-types]
   92 |    { "else",    elsedir },
      |                 ^~~~~~~
ipp.c:92:17: note: (near initialization for 'pplist[4].func')
ipp.c:71:17: note: 'elsedir' declared here
   71 | static  char *  elsedir (char *s);
      |                 ^~~~~~~
ipp.c:93:17: error: initialization of 'char * (*)(void)' from incompatible pointer type 'char * (*)(char *)' [-Wincompatible-pointer-types]
   93 |    { "endif",   endif   },
      |                 ^~~~~
ipp.c:93:17: note: (near initialization for 'pplist[5].func')
ipp.c:72:17: note: 'endif' declared here
   72 | static  char *  endif   (char *s);
      |                 ^~~~~
ipp.c:94:17: error: initialization of 'char * (*)(void)' from incompatible pointer type 'char * (*)(char *)' [-Wincompatible-pointer-types]
   94 |    { "include", include },
      |                 ^~~~~~~
ipp.c:94:17: note: (near initialization for 'pplist[6].func')
ipp.c:74:17: note: 'include' declared here
   74 | static  char *  include (char *s);
      |                 ^~~~~~~
ipp.c:95:17: error: initialization of 'char * (*)(void)' from incompatible pointer type 'char * (*)(char *)' [-Wincompatible-pointer-types]
   95 |    { "line",    setline },
      |                 ^~~~~~~
ipp.c:95:17: note: (near initialization for 'pplist[7].func')
ipp.c:75:17: note: 'setline' declared here
   75 | static  char *  setline (char *s);
      |                 ^~~~~~~
ipp.c:96:17: error: initialization of 'char * (*)(void)' from incompatible pointer type 'char * (*)(char *)' [-Wincompatible-pointer-types]
   96 |    { "error",   errdir  },
[...]
```