pythonPackages.pyrealsense2: fix breakage
Fixes compilation error: `'cerr' is not a member of 'std'` in `wrappers/python/pyrs_device.cpp`.
This error appeared likely because either some upstream header removing the import, or because the compiler has gotten stricter.