haskell.packages.ghcjs.exceptions: fix eval
Without the change the eval fails as:

    $ nix build --no-link -f. haskell.packages.ghcjs.exceptions
    error:
           … in the left operand of the update (//) operator
             at pkgs/development/haskell-modules/lib/compose.nix:40:7:
               39|     mkDerivation = drv: (args.mkDerivation drv).override f;
               40|   })) // {
                 |       ^
               41|     overrideScope = scope: overrideCabal f (drv.overrideScope scope);

           error: attribute 'exceptions_0_10_7' missing
           at pkgs/development/haskell-modules/configuration-ghcjs.nix:30:26:
               29|   stm = doJailbreak self.stm_2_5_3_1;
               30|   exceptions = dontCheck self.exceptions_0_10_7;
                 |                          ^
               31|
           Did you mean exceptions_0_10_8?

(cherry picked from commit b1f5c64b80ab3f28b29fdc54d50bceca0ff784df)