lxc.tests: update `incus.container` reference
Without the change the test build attempt fails the evaluation as:

    $ nix build --no-link -f. lxc.tests

       error: attribute 'container' missing

       at pkgs/os-specific/linux/lxc/default.nix:65:19:

           64|   passthru = {
           65|     tests.incus = nixosTests.incus.container;
             |                   ^

This started happening after `container` test was split in two in
c607e70f7053 "nixosTests.incus: add test with old and new init".