libratbag: fix `ratbagctl` typelib error
`ImportError: cannot import name Gio, introspection typelib not found`

(cherry picked from commit e8f703ab9bfa90dd0e16b246463f103579c00aab)