python311.pkgs.mox3: disable
Uses APIs removed in Python 3.11, for example this exception in
aprslib's tests:

	E           AttributeError: module 'inspect' has no attribute 'getargspec'

	/nix/store/x6ps6s9k2i1dcnb9jf1kbfgghgf6k53f-python3.11-mox3-1.1.0/lib/python3.11/site-packages/mox3/mox.py:909: AttributeError

Unmaintained upstream.