eztrace: use binutils-2.38 until upstream is ported
Without the change eztrace build fails on binutils-2.39 due to API change:

    ../pptrace/arch/x86_64/hijack.c: In function 'check_instructions':
    ../pptrace/arch/x86_64/hijack.c:62:3: error: too few arguments to function 'init_disassemble_info'
       62 |   init_disassemble_info ( &i, NULL, dummy_print );
          |   ^~~~~~~~~~~~~~~~~~~~~