xorg.libXpresent: add xorg.libXfixes to propagated build inputs
Without it the `mpv` build fails as:

    ...-libXpresent-1.0.1/include/X11/extensions/Xpresent.h:31:10: fatal error: X11/extensions/Xfixes.h: No such file or directory
       31 | #include <X11/extensions/Xfixes.h>
          |          ^~~~~~~~~~~~~~~~~~~~~~~~~

(cherry picked from commit b68ce27a3f702eb359c532208f3bc2ceabd527e0)