pythonPackages.dbus-python: 1.2.12 -> 1.2.16
This upgrades dbus-python to the 1.2.16 release. Reason for this version
upgrade is a the failing hamster application (see. programs.hamster).
With a 1.2.12 dbus-python version hamster can not start and fails with:

    Traceback (most recent call last):
      File "/nix/store/5ax21lyiprc9v5l3pl7dbfr2hqbrh970-hamster-3.0.2/bin/.hamster-wrapped", line 41, in <module>
        from hamster import client, reports
      File "/nix/store/5ax21lyiprc9v5l3pl7dbfr2hqbrh970-hamster-3.0.2/lib/python3.8/site-packages/hamster/client.py", line 46, in <module>
        assert not (
    AssertionError: python3.8 changed str(<dbus integers>).
       That broke hamster (https://github.com/projecthamster/hamster/issues/477).
       Please upgrade to dbus-python >= 1.2.14.