xxh: remove from pythonPackages set
error: xxh should use `buildPythonPackage` or `toPythonModule` if it is to be part of the Python pa
ckages set."}

(cherry picked from commit 4af6e0bc5f524b7dc80f2bbf8bc9ce4489744885)