trimmomatic: fix build by switching to JDK 21
For some reason, the invocation of jre_minimal in conjunction with
JDK 11 leads to failures; `jlink` complains about a version mismatch
with the target JRE version:

```
Running phase: patchPhase
Running phase: updateAutotoolsGnuConfigScriptsPhase
Running phase: configurePhase
no configure script, doing nothing
Running phase: buildPhase
Error: jlink version 21.0 does not match target java.base version 11.0
```

I didn't invest much time into figuring out how this happens, because
simply switching to JDK 21 seems to do at least fix the failing build.