haskellPackages.Agda: Fix build for ghc 8.10.2 → 8.10.3 upgrade
Commit 1998b95adc6b5a9aef336e45955a01575bd898f1 “haskellPackages:
update default compiler from ghc 8.10.2 to version 8.10.3” broke Agda
because Agda.cabal incorrectly declares a transformers dependency only
for ghc < 8.10.3:

    if impl(ghc >= 8.6.4) && impl(ghc < 8.10.3)
      build-depends: transformers == 0.5.6.2

    if impl(ghc >= 8.4) && impl(ghc < 8.6.4)
      build-depends: transformers == 0.5.5.0

    if impl(ghc < 8.4)
      build-depends: transformers == 0.5.2.0

leading to this error:

    src/full/Agda/Utils/Maybe.hs:13:1: error:
    Could not load module ‘Control.Monad.Trans.Maybe’
    It is a member of the hidden package ‘transformers-0.5.6.2’.
    Perhaps you need to add ‘transformers’ to the build-depends in your .cabal file.
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
       |
    13 | import Control.Monad.Trans.Maybe
       | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Signed-off-by: Anders Kaseorg <andersk@mit.edu>