tijolo: mark as broken
While updating crystal for 1.14 this project breaks with

    In src/code_language.cr:46:18

     46 | mime = Gio.content_type_guess(file.to_s, contents[0, contents_size])
                     ^-----------------
    Error: wrong number of arguments for 'Gio.content_type_guess' (given 2, expected 4)

    Overloads are:
     - Gio.content_type_guess(filename : ::String, data : Pointer(UInt8), data_size : UInt64, result_uncertain : Pointer(Bool))