mprime: fix fatal error with -march=znver1
Compiling for recent architectures causes rounding issues:

FATAL ERROR: Rounding was 0.4977243728, expected less than 0.4