qarte: use pyqt5_with_qtmultimedia
Otherwise, qarte fails at run-time with:

>     from PyQt5.QtMultimedia import QMediaPlayer
> ModuleNotFoundError: No module named 'PyQt5.QtMultimedia'

(cherry picked from commit ef15478313dccf73684d46816d20752ba5b18cf4)