fpm2: 0.79 -> 0.90
Among other things switched from gtk2 to gtk3 and fixed build failure
against upstream gcc-10:

    ld: sha256.o:src/fpm.h:187: multiple definition of
      `ini'; main.o:src/fpm.h:187: first defined here

changelog: https://als.regnet.cz/fpm2/changelog