evolution-data-server: Fix darwin build
Probably caused by the clang 16 bump.

/tmp/nix-build-evolution-data-server-3.50.3.drv-0/evolution-data-server-3.50.3/src/addressbook/libebook-contacts/e-phone-number-private.cpp:186:7: error: no member named 'auto_ptr' in namespace 'std'
        std::auto_ptr<EPhoneNumber> parsed_number(new EPhoneNumber);
        ~~~~~^