ocamlformat: Build on OCaml 4.14
OCamlformat fails to build since the bump to OCaml 5.2 in
https://github.com/NixOS/nixpkgs/pull/346071

       error: ocamlformat 0.26.1 is not available for OCaml 5.2.1

This changes which version of the compiler is used to build OCamlformat.
4.14 is used to increase sharing when several versions of the tool are
used at the same time. This will not change OCamlformat's behaviors.