mpvScripts.buildLua: fix buildLua's runtime-dependencies argument
Fix buildLua's runtime-dependencies argument to prevent the following
nasty error, introduced in commit b3c149a393bd ("mpvScripts.twitch-chat:
refactor using buildLua's `runtime-dependencies`"):

    error: expected a list but found a set: { [...] }

Fixes: 104e1b0b1bfe ("mpvScripts.buildLua: add a `runtime-dependencies` option")