nix-required-mounts: Fix eval test
Without this I'm getting an error:

error: The option `fileSystems."/".fsType' was accessed but has no value defined. Try setting the option.