rust-bindgen: some features of bindgen require a recent version of llvm
Features likes 'asm goto' are only available if compiled with llvm >= 11.

This is required for rust-in-linux development for example. I believe
binding to llvmPackages_latest is an acceptable tradeoff.

```
  RUSTC L rust/build_error.o
error: unknown argument: '-fmacro-prefix-map=./='
error: unknown argument: '-fno-stack-clash-protection'
error: unknown warning option '-Wno-frame-address'; did you mean '-Wno-address'? [-Wunknown-warning-option]
error: unknown warning option '-Wno-pointer-to-enum-cast' [-Wunknown-warning-option]
./arch/x86/include/asm/bitops.h:138:9: error: 'asm goto' constructs are not supported yet
./arch/x86/include/asm/bitops.h:162:9: error: 'asm goto' constructs are not supported yet
./arch/x86/include/asm/bitops.h:201:9: error: 'asm goto' constructs are not supported yet
./include/linux/list.h:282:9: warning: duplicate 'const' declaration specifier [-Wduplicate-decl-specifier]
./include/linux/list.h:318:27: warning: duplicate 'const' declaration specifier [-Wduplicate-decl-specifier]
./include/linux/list.h:821:10: warning: duplicate 'const' declaration specifier [-Wduplicate-decl-specifier]
./include/linux/list.h:830:10: warning: duplicate 'const' declaration specifier [-Wduplicate-decl-specifier]
./arch/x86/include/asm/atomic.h:83:9: error: 'asm goto' constructs are not supported yet
./arch/x86/include/asm/atomic.h:123:9: error: 'asm goto' constructs are not supported yet
./arch/x86/include/asm/atomic.h:137:9: error: 'asm goto' constructs are not supported yet
./arch/x86/include/asm/atomic.h:152:9: error: 'asm goto' constructs are not supported yet
./arch/x86/include/asm/atomic64_64.h:76:9: error: 'asm goto' constructs are not supported yet
./arch/x86/include/asm/atomic64_64.h:118:9: error: 'asm goto' constructs are not supported yet
./arch/x86/include/asm/atomic64_64.h:132:9: error: 'asm goto' constructs are not supported yet
./arch/x86/include/asm/atomic64_64.h:147:9: error: 'asm goto' constructs are not supported yet
./include/linux/jump_label.h:278:2: error: expected '(' after 'asm'
./include/linux/jump_label.h:284:2: error: expected '(' after 'asm'
./include/linux/jump_label.h:306:2: error: expected '(' after 'asm'
./include/linux/jump_label.h:309:3: error: expected '(' after 'asm'
./include/linux/jump_label.h:317:2: error: expected '(' after 'asm'
./include/linux/jump_label.h:320:3: error: expected '(' after 'asm'
./include/linux/llist.h:189:9: warning: duplicate 'const' declaration specifier [-Wduplicate-decl-specifier]
fatal error: too many errors emitted, stopping now [-ferror-limit=]
error: unknown argument: '-fmacro-prefix-map=./=', err: true
error: unknown argument: '-fno-stack-clash-protection', err: true
error: unknown warning option '-Wno-frame-address'; did you mean '-Wno-address'? [-Wunknown-warning-option], err: true
error: unknown warning option '-Wno-pointer-to-enum-cast' [-Wunknown-warning-option], err: true
./arch/x86/include/asm/bitops.h:138:9: error: 'asm goto' constructs are not supported yet, err: true
./arch/x86/include/asm/bitops.h:162:9: error: 'asm goto' constructs are not supported yet, err: true
./arch/x86/include/asm/bitops.h:201:9: error: 'asm goto' constructs are not supported yet, err: true
./include/linux/list.h:282:9: warning: duplicate 'const' declaration specifier [-Wduplicate-decl-specifier], err: false
./include/linux/list.h:318:27: warning: duplicate 'const' declaration specifier [-Wduplicate-decl-specifier], err: false
./include/linux/list.h:821:10: warning: duplicate 'const' declaration specifier [-Wduplicate-decl-specifier], err: false
./include/linux/list.h:830:10: warning: duplicate 'const' declaration specifier [-Wduplicate-decl-specifier], err: false
./arch/x86/include/asm/atomic.h:83:9: error: 'asm goto' constructs are not supported yet, err: true
./arch/x86/include/asm/atomic.h:123:9: error: 'asm goto' constructs are not supported yet, err: true
./arch/x86/include/asm/atomic.h:137:9: error: 'asm goto' constructs are not supported yet, err: true
./arch/x86/include/asm/atomic.h:152:9: error: 'asm goto' constructs are not supported yet, err: true
./arch/x86/include/asm/atomic64_64.h:76:9: error: 'asm goto' constructs are not supported yet, err: true
./arch/x86/include/asm/atomic64_64.h:118:9: error: 'asm goto' constructs are not supported yet, err: true
./arch/x86/include/asm/atomic64_64.h:132:9: error: 'asm goto' constructs are not supported yet, err: true
./arch/x86/include/asm/atomic64_64.h:147:9: error: 'asm goto' constructs are not supported yet, err: true
./include/linux/jump_label.h:278:2: error: expected '(' after 'asm', err: true
./include/linux/jump_label.h:284:2: error: expected '(' after 'asm', err: true
./include/linux/jump_label.h:306:2: error: expected '(' after 'asm', err: true
./include/linux/jump_label.h:309:3: error: expected '(' after 'asm', err: true
./include/linux/jump_label.h:317:2: error: expected '(' after 'asm', err: true
./include/linux/jump_label.h:320:3: error: expected '(' after 'asm', err: true
./include/linux/llist.h:189:9: warning: duplicate 'const' declaration specifier [-Wduplicate-decl-specifier], err: false
fatal error: too many errors emitted, stopping now [-ferror-limit=], err: true
thread 'main' panicked at 'Unable to generate bindings: ()', src/main.rs:54:36
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
make[1]: *** [rust/Makefile:141: rust/bindings_generated.rs] Error 1
make[1]: *** Deleting file 'rust/bindings_generated.rs'
```

Signed-off-by: Arthur Gautier <baloo@superbaloo.net>