pygit2: add six, required dependency for pygit2 0.24.x
latest build of pygit2 from wheel failing, it requires six

```
creating build/bdist.linux-x86_64/wheel/pygit2-0.24.0.dist-info/WHEEL
installing
/tmp/nix-build-python2.7-pygit2-0.24.0.drv-0/pygit2-0.24.0/dist /tmp/nix-build-python2.7-pygit2-0.24.0.drv-0/pygit2-0.24.0
Ignoring indexes: https://pypi.python.org/simple
Processing ./pygit2-0.24.0-cp27-cp27mu-linux_x86_64.whl
Collecting six (from pygit2==0.24.0)
  Could not find a version that satisfies the requirement six (from pygit2==0.24.0) (from versions: )
  No matching distribution found for six (from pygit2==0.24.0)
  builder for ‘/nix/store/84kvvycmhjg6fqpnxhh6k2xh6h5zbykz-python2.7-pygit2-0.24.0.drv’ failed with exit code 1
  cannot build derivation ‘/nix/store/mdpmiy430cbvqmxj0lc9vvq575d6d639-python2.7-powerline-2.1.4.drv’: 1 dependencies couldn't be built
  cannot build derivation ‘/nix/store/5nxmmixwf0wfml3hqqf8si1dk7j16c5r-all.drv’: 1 dependencies couldn't be built
  error: build of ‘/nix/store/5nxmmixwf0wfml3hqqf8si1dk7j16c5r-all.drv’ failed

```