mawk: fix `passthru.tests`, relax hardening options
`nix-build -A mawk.passthru.tests` was previously failing:
> error: builder for '/nix/store/gc20k2mizdw3aacda6nqwyvi7kqzn1dh-mawk-1.3.4-20240819-test-version.drv' failed with exit code 1;
>        last 2 log lines:
>        > mawk -W version returned a non-zero exit code.
>        > *** buffer overflow detected ***: terminated

the `mawk` binary was unusable; would crash on *any* invocation.

context: <https://github.com/NixOS/nixpkgs/pull/533402#issuecomment-4960077454>
(cherry picked from commit aa630e7f14c8e98a819e9f38f0ca6f6c4a19eb93)