nixos/stash: Fix default auth config + add tests
The default configuration has both username and passwordFile being
defined to null. However if you try and use this you run into the
following error:

```
error: cannot coerce null to a string: null
```

from the `password=$(< ${cfg.passwordFile})` line.

If I try to write an empty file using pkgs.writeFile then I run into the
error here:
https://github.com/NixOS/nixpkgs/blob/f560ccec6b1116b22e6ed15f4c510997d99d5852/nixos/modules/services/web-apps/stash.nix#L472

I have also added a test by trying to copy what caddy.nix is doing via
this comment:
https://discourse.nixos.org/t/test-configuration-change-with-vm-test/69511/2

I also updated an example for one of the options as it uses lowercase
attributes not uppercase.

I assume the tests work as I do not get an error when running nix-build,
but if I revert my change to the ExecStartPre section the coerce error
gets raised.