bazel_4: fix CLang 16 Werror-s on darwin
Fixing `bazel_4` after #234710

Error example
https://hydra.nixos.org/build/241174862/nixlog/1
```
Execution platform: //:default_host_platform
third_party/zlib/gzwrite.c:89:20: error: call to undeclared function 'write'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
            writ = write(state->fd, strm->next_in, put);
                   ^
```

Similar to #269481 and #269297

(cherry picked from commit 746e394638e28f254a8c2afa9ab66acd2893268a)