pies: 1.3 -> 1.8
- update to latest release, fixes `implicit-function-declaration` errors
with gcc14:
```
pp.c: In function 'pp_add_option':
pp.c:29:7: error: implicit declaration of function 'exit' []
   29 |       exit (EX_CONFIG);
      |       ^~~~
```