keybase: add cf-private on darwin
    Undefined symbols for architecture x86_64:
      "_OBJC_CLASS_$_NSData", referenced from:
          objc-class-ref in _x002.o
      "_OBJC_CLASS_$_NSDictionary", referenced from:
          objc-class-ref in _x002.o
      "_OBJC_CLASS_$_NSURL", referenced from:
          objc-class-ref in _x002.o
    ld: symbol(s) not found for architecture x86_64

(cherry picked from commit be9fc0d669641c7e3747c37b8419beb93fa5bc0e)