hamster: fix install
* Tell the build system where it can install Python files, with the
  PYTHONDIR environment variable. Without this it tries to install to
  the existing python3 store path, which fails:

    waflib.Errors.WafError: Could not create the directory /nix/store/HASH-python3-VERSION/lib/pythonX.Y/site-packages/hamster

* Add setuptools as runtime dependency to prevent this fatal runtime
  error since Python 3.12:

    ModuleNotFoundError: No module named 'distutils'