bazel_7: fix darwin compilation with CLang 16 & recent nixpkgs/master
Workaround for #166205 similar to
https://github.com/NixOS/nixpkgs/commit/51451ac4069e18b5813b38d57cb68cd72b7ec51e

And warning fix similar to `bazel_6` fix for
```
external/upb~0.0.0-20220923-a547704/upb/mini_table.c:634:14: error: defining a type within '__builtin_offsetof' is a Clang extension [-Werror,-Wgnu-offsetof-extensions]
  UPB_ASSERT(UPB_ALIGN_OF(upb_StringView) ==
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

(cherry picked from commit 306e8eaf537440f3d28f32720b27f6288627125b)