Remove icon in package.nix
The "icon_free.png" that this derivative tries to pull for the shortcut icon keeps changing, causing different SHA values.

```
error: hash mismatch in fixed-output derivation '/nix/store/XXX-icon_free.png.drv':
         specified: sha256-widkv2VGh+eOauUK/6Sz/e2auCNFAsc8n9z0fdrSnW0=
            got:    sha256-oK++vjT4W+XsutWfR0hJeTxqoy4cdEqHBKEdZX2ylUI=
```

```
error: hash mismatch in fixed-output derivation '/nix/store/0pk9h8vvqxr4lcv6whnsgncdfdq6bjsp-icon_free.png.drv':
         specified: sha256-widkv2VGh+eOauUK/6Sz/e2auCNFAsc8n9z0fdrSnW0=
            got:    sha256-2PTGTOqYPyufIoosf3jmbJRrlpDJj+O1f593ZtN3spc=
```

I removed the fetching of the icon temporarily, but perhaps a better source can be used. Might be related to caching?