bpftools: add enableDebugger, set to false on Power64
`bpftools` is needed by `systemd`, but `bpf_dbg` is not.  Currently `bpf_dbg`
fails to build with the error message below.  Nothing else in the NixOS ISO
needs `bpf_dbg`, so until I can track down the root cause it's easier to simply
disable that build target.

```
error: builder for '/nix/store/daq740s0f31akfv12p828fv3ri01mv4p-bpftools-5.19.8.drv' failed with exit code 2;
       last 10 log lines:
       > gcc -Wall -O2 -D__EXPORTED_HEADERS__ -I/build/linux-5.19.8/tools/include/uapi -I/build/linux-5.19.8/tools/include -DDISASM_FOUR_ARGS_SIGNATURE -o bpf_asm bpf_asm.o bpf_exp.yacc.o bpf_exp.lex.o
       > gcc -Wall -O2 -D__EXPORTED_HEADERS__ -I/build/linux-5.19.8/tools/include/uapi -I/build/linux-5.19.8/tools/include -DDISASM_FOUR_ARGS_SIGNATURE -c -o bpf_dbg.o /build/linux-5.19.8/tools/bpf/bpf_dbg.c
       > In file included from /nix/store/kmpmsx894r939p7wbr6d3g3lfzm41i56-glibc-2.35-163-dev/include/asm/sigcontext.h:14,
       >                  from /nix/store/kmpmsx894r939p7wbr6d3g3lfzm41i56-glibc-2.35-163-dev/include/bits/sigcontext.h:30,
       >                  from /nix/store/kmpmsx894r939p7wbr6d3g3lfzm41i56-glibc-2.35-163-dev/include/signal.h:301,
       >                  from /build/linux-5.19.8/tools/bpf/bpf_dbg.c:51:
       > /nix/store/kmpmsx894r939p7wbr6d3g3lfzm41i56-glibc-2.35-163-dev/include/asm/elf.h:160:9: error: unknown type name '__vector128'
       >   160 | typedef __vector128 elf_vrreg_t;
       >       |         ^~~~~~~~~~~
       > make: *** [Makefile:67: bpf_dbg.o] Error 1
       For full logs, run 'nix log /nix/store/daq740s0f31akfv12p828fv3ri01mv4p-bpftools-5.19.8.drv'.
```