litecoin: add missing framework and mark broken on darwin
    In file included from qt/bitcoin.cpp:9:
    ./qt/bitcoingui.h:14:10: fatal error: 'QLabel' file not found
    #include <QLabel>
             ^~~~~~~~
    1 error generated.

/cc ZHF #45961