icewm: fix trailing -I compilation errors
Fixes

cc1plus: error: to generate dependencies you must specify either '-M' or
'-MM'

errors which occur while compiling due to trailing -I for libintl,
which appears to be found now but without requiring any include/link
flags.