dirmngr: remove
dirmngr was merged into gnupg long ago. nixpkgs does not use it as a
dependency anywhere. On top of that it fails to build on upstream
gcc-10 as:

    ld: validate.o:/build/dirmngr-1.1.1/src/dirmngr.h:123:
      multiple definition of `opt'; dirmngr.o:/build/dirmngr-1.1.1/src/dirmngr.h:123: first defined here

Let's remove the package.