nixops_unstable: fix `tests` eval with `allowAliases = false;`
Without the change `tests` eval fails as:

    $ nix build --no-link -f. nixops_unstable.tests --arg config '{ allowAliases = false; }'
    error:
       error: attribute 'nixosTest' missing
           22|   testLegacyNetwork = { nixopsPkg, ... }: pkgs.nixosTest ({
             |                                           ^
           23|     name = "nixops-legacy-network";
       Did you mean nixosTests?

The alias is defined as:

    pkgs/top-level/aliases.nix:  nixosTest = testers.nixosTest; # Added 2022-05-05