home-assistant-custom-components.xiaomi_miot: 0.7.21 -> 0.7.23
Diff: https://github.com/al-one/hass-xiaomi-miot/compare/v0.7.21...v0.7.23

Changelog: https://github.com/al-one/hass-xiaomi-miot/releases/tag/v0.7.23

Fix with home-assistant v2024.11:

```
  File "/var/lib/hass/custom_components/xiaomi_miot/__init__.py", line 30, in <module>
    from homeassistant.config import DATA_CUSTOMIZE
ImportError: cannot import name 'DATA_CUSTOMIZE' from 'homeassistant.config' (/nix/store/m1bqz8krvqssm8zq8i456ds5287dfvd9-homeassistant-2024.11.1/lib/python3.12/site-packages/homeassistant/config.py)
```

(cherry picked from commit 03e9fb3803d749d291af8f64fd0c67977ef05446)