. (#4)
* maintainers: remove jD91mZM2

Thank you for every single commit to NixOS and nixpkgs.
https://github.com/NixOS/nixpkgs/commits?author=jD91mZM2

https://www.redox-os.org/news/open-source-mental-health/

* pythonPackages: set mainProgram to pname by default

Calling `nix run poetry` or another python package usually fails
because of the "pythonX" prefix in name.
Adjust mainProgram to ignore that prefix.

* python3Packages.pytenable: 1.2.8 -> 1.3.0

* python3Packages.minidump: 0.0.17 -> 0.0.18

* firefox-beta-bin: 85.0b6 -> 90.0b6

* firefox-devedition-bin: 85.0b6 -> 90.0b6

* python3Packages.configargparse: 1.4 -> 1.4.1

* goofys: init at unstable-2021-03-26

* sauerbraten: set mainProgram to sauerbraten_client

so that nix run nixpkgs#sauerbraten starts the game

* python3Packages.discordpy: 1.7.2 -> 1.7.3

* pass-import: 3.1 -> 3.2

* efont-unicode: init at 0.4.2

* prometheus-node-exporter: fix version info (#126580)

Closes #126359

* mg: 6.8.1 -> 6.9 (#126694)

Co-authored-by: Sandro <sandro.jaeckel@gmail.com>

* interception-tools-plugins.caps2esc: 0.1.3 -> 0.3.2

* interception-tools-plugins.dual-function-keys: 1.1.0 -> 1.4.0

* Update pkgs/applications/misc/variety/default.nix

Co-authored-by: Sandro <sandro.jaeckel@gmail.com>

* ocamlPackages.magic-mime: 1.0.0 -> 1.1.3

* hyprspace: init at 0.1.2

* pdns-recursor: 2.5.1 -> 2.5.2

* python3Packages.pyialarm: 1.8.1 -> 1.9.0

* weechat: 3.1 -> 3.2

https://github.com/weechat/weechat/releases/tag/v3.2

* python3Packages.awesomeversion: 21.5.0 -> 21.6.0

* pdns-recursor: fix ambiguous license

* python3Packages.fastjsonschema: 2.14.5 -> 2.15.1

* ocamlPackages.parmap: 1.2 -> 1.2.3

* armips: init at 0.11.0

* python3Packages.skytemple-files: fix non-working patch

* radsecproxy: 1.8.2 -> 1.9.0

Fixes CVE-2021-32642.
https://github.com/radsecproxy/radsecproxy/releases/tag/1.9.0

* iosevka: 5.0.2 -> 7.0.4, iosevka-bin: 5.0.5 -> 7.0.4  (#126664)

* iosevka: 5.0.2 -> 7.0.4

* iosevka-bin: 5.0.5 -> 7.0.4

* tanka: 0.15.1 -> 0.16.0

* super-slicer: 2.2.54.2 -> 2.3.56.5

We are finally up a version!

* terraform-ls: drop test that fail on aarch64 for aarch64 builds

* gbsplay: 2016-12-17 -> 0.0.94

Add the "nas" output plugin. Remove configure flags since those should
get detected automatically. Install bash completions. Format through
nixpkgs-fmt.

* ocamlPackages.fileutils: 0.5.3 -> 0.6.3

* ncurses: fix build on NetBSD

Only tested cross-compiling, but is probably necessary for native too.

Fixes errors like this:

linking ../lib/libncursesw.so
x86_64-unknown-netbsd-gcc  --param max-inline-insns-single=1200 -Wl,-shared -Wl,-Bshareable -o ../lib/libncursesw.so ../obj_s/hardscroll.o ../obj_s/hashmap.o ../obj_s/lib_addch.o ../obj_s/lib_addstr.o ../obj_s/lib_beep.o ../obj_s/lib_bkgd.o ../obj_s/lib_box.o ../obj_s/lib_chgat.o ../obj_s/lib_clear.o ../obj_s/lib_clearok.o ../obj_s/lib_clrbot.o ../obj_s/lib_clreol.o ../obj_s/lib_color.o ../obj_s/lib_colorset.o ../obj_s/lib_delch.o ../obj_s/lib_delwin.o ../obj_s/lib_echo.o ../obj_s/lib_endwin.o ../obj_s/lib_erase.o ../obj_s/lib_flash.o ../obj_s/lib_gen.o ../obj_s/lib_getch.o ../obj_s/lib_getstr.o ../obj_s/lib_hline.o ../obj_s/lib_immedok.o ../obj_s/lib_inchstr.o ../obj_s/lib_initscr.o ../obj_s/lib_insch.o ../obj_s/lib_insdel.o ../obj_s/lib_insnstr.o ../obj_s/lib_instr.o ../obj_s/lib_isendwin.o ../obj_s/lib_leaveok.o ../obj_s/lib_mouse.o ../obj_s/lib_move.o ../obj_s/lib_mvcur.o ../obj_s/lib_mvwin.o ../obj_s/lib_newterm.o ../obj_s/lib_newwin.o ../obj_s/lib_nl.o ../obj_s/lib_overlay.o ../obj_s/lib_pad.o ../obj_s/lib_printw.o ../obj_s/lib_redrawln.o ../obj_s/lib_refresh.o ../obj_s/lib_restart.o ../obj_s/lib_scanw.o ../obj_s/lib_screen.o ../obj_s/lib_scroll.o ../obj_s/lib_scrollok.o ../obj_s/lib_scrreg.o ../obj_s/lib_set_term.o ../obj_s/lib_slk.o ../obj_s/lib_slkatr_set.o ../obj_s/lib_slkatrof.o ../obj_s/lib_slkatron.o ../obj_s/lib_slkatrset.o ../obj_s/lib_slkattr.o ../obj_s/lib_slkclear.o ../obj_s/lib_slkcolor.o ../obj_s/lib_slkinit.o ../obj_s/lib_slklab.o ../obj_s/lib_slkrefr.o ../obj_s/lib_slkset.o ../obj_s/lib_slktouch.o ../obj_s/lib_touch.o ../obj_s/lib_tstp.o ../obj_s/lib_ungetch.o ../obj_s/lib_vidattr.o ../obj_s/lib_vline.o ../obj_s/lib_wattroff.o ../obj_s/lib_wattron.o ../obj_s/lib_winch.o ../obj_s/lib_window.o ../obj_s/nc_panel.o ../obj_s/safe_sprintf.o ../obj_s/tty_update.o ../obj_s/varargs.o ../obj_s/vsscanf.o ../obj_s/lib_freeall.o ../obj_s/charable.o ../obj_s/lib_add_wch.o ../obj_s/lib_box_set.o ../obj_s/lib_cchar.o ../obj_s/lib_erasewchar.o ../obj_s/lib_get_wch.o ../obj_s/lib_get_wstr.o ../obj_s/lib_hline_set.o ../obj_s/lib_in_wch.o ../obj_s/lib_in_wchnstr.o ../obj_s/lib_ins_wch.o ../obj_s/lib_inwstr.o ../obj_s/lib_key_name.o ../obj_s/lib_pecho_wchar.o ../obj_s/lib_slk_wset.o ../obj_s/lib_unget_wch.o ../obj_s/lib_vid_attr.o ../obj_s/lib_vline_set.o ../obj_s/lib_wacs.o ../obj_s/lib_wunctrl.o ../obj_s/expanded.o ../obj_s/legacy_coding.o ../obj_s/lib_dft_fgbg.o ../obj_s/lib_print.o ../obj_s/new_pair.o ../obj_s/resizeterm.o ../obj_s/use_screen.o ../obj_s/use_window.o ../obj_s/wresize.o ../obj_s/access.o ../obj_s/add_tries.o ../obj_s/alloc_ttype.o ../obj_s/codes.o ../obj_s/comp_captab.o ../obj_s/comp_error.o ../obj_s/comp_hash.o ../obj_s/comp_userdefs.o ../obj_s/db_iterator.o ../obj_s/doalloc.o ../obj_s/entries.o ../obj_s/fallback.o ../obj_s/free_ttype.o ../obj_s/getenv_num.o ../obj_s/home_terminfo.o ../obj_s/init_keytry.o ../obj_s/lib_acs.o ../obj_s/lib_baudrate.o ../obj_s/lib_cur_term.o ../obj_s/lib_data.o ../obj_s/lib_has_cap.o ../obj_s/lib_kernel.o ../obj_s/lib_keyname.o ../obj_s/lib_longname.o ../obj_s/lib_napms.o ../obj_s/lib_options.o ../obj_s/lib_raw.o ../obj_s/lib_setup.o ../obj_s/lib_termcap.o ../obj_s/lib_termname.o ../obj_s/lib_tgoto.o ../obj_s/lib_ti.o ../obj_s/lib_tparm.o ../obj_s/lib_tputs.o ../obj_s/lib_trace.o ../obj_s/lib_ttyflags.o ../obj_s/lib_twait.o ../obj_s/name_match.o ../obj_s/names.o ../obj_s/obsolete.o ../obj_s/read_entry.o ../obj_s/read_termcap.o ../obj_s/strings.o ../obj_s/tries.o ../obj_s/trim_sgr0.o ../obj_s/unctrl.o ../obj_s/visbuf.o ../obj_s/alloc_entry.o ../obj_s/captoinfo.o ../obj_s/comp_expand.o ../obj_s/comp_parse.o ../obj_s/comp_scan.o ../obj_s/parse_entry.o ../obj_s/write_entry.o ../obj_s/define_key.o ../obj_s/hashed_db.o ../obj_s/key_defined.o ../obj_s/keybound.o ../obj_s/keyok.o ../obj_s/version.o -L../lib
/nix/store/6h96vn8vpm01sn0r5shdl48nw94kzls6-x86_64-unknown-netbsd-binutils-2.35.1/bin/x86_64-unknown-netbsd-ld: /nix/store/dy4bg91z7g0p8k3cdq8rbmzj27lsmx5k-libc-netbsd-9.1-x86_64-unknown-netbsd/lib/crt0.o: in function `__start':
(.text+0x31): undefined reference to `__fini_array_start'
/nix/store/6h96vn8vpm01sn0r5shdl48nw94kzls6-x86_64-unknown-netbsd-binutils-2.35.1/bin/x86_64-unknown-netbsd-ld: /nix/store/dy4bg91z7g0p8k3cdq8rbmzj27lsmx5k-libc-netbsd-9.1-x86_64-unknown-netbsd/lib/crt0.o: relocation R_X86_64_PC32 against undefined hidden symbol `__fini_array_start' can not be used when making a shared object
/nix/store/6h96vn8vpm01sn0r5shdl48nw94kzls6-x86_64-unknown-netbsd-binutils-2.35.1/bin/x86_64-unknown-netbsd-ld: final link failed: bad value
collect2: error: ld returned 1 exit status

* ocamlPackages.sha: 1.13 -> 1.14

* llvmPackages_git: 12.0.0 -> 2021-05-17

TODO: Only llvmPackages_git.stdenv builds right now, other packages
still fail. Help is welcome.

* clang-tools: fix clangd

Whatever change has necessitated
https://github.com/NixOS/nixpkgs/pull/122044, it also broke clangd --
<clang-wrapper>/resource-root/include is no longer automagically
searched for includes, which kills pretty much any indexing since that
directory contains vital stuff like stddef.h etc.

Fix by appending the directory to CPATH & CPLUS_INCLUDE_PATH in the
clangd wrapper.

* starspace: build with gzip support

* pferd: 3.0.1 -> 3.1.0

* micropython: 1.13 -> 1.15

* xfce.ristretto: 0.10.0 -> 0.11.0

* python3Packages.black: 21.5b1 -> 21.6b0

* rar2fs: 1.29.4 -> 1.29.5

* imagemagick6: 6.9.12-14 -> 6.9.12-15

* pythonPackages.vincenty: init at 0.1.4

* python3Packages.buienradar: init at 1.0.4

* home-assistant: update component-packages.nix

* home-assistant: test buienradar component

* kube3d: 4.4.4 -> 4.4.5

* xfce.xfce4-screenshooter: 1.9.8 -> 1.9.9

* xfce.mkXfceDerivation: fix homepage

`/about` now redirects to a sign in page, so link to the repo's root instead.

* linuxPackages_5_4.wireguard: 1.0.20210424 -> 1.0.20210606

ChangeLog: https://lists.zx2c4.com/pipermail/wireguard/2021-June/006781.html

* cglm: init at 0.8.3

* gpg-tui: 0.4.1 -> 0.5.0

https://github.com/orhun/gpg-tui/blob/v0.5.0/CHANGELOG.md

* python3Packages.spiderpy: init at 1.5.0

* home-assistant: update component-packages.nix

* home-assistant: test spider component

* imv: install .desktop file

* imv: remove unused fontconfig argument

* imv: clarify license

licenses.gpl2 is deprecated, either gpl2Only or gpl2Plus should be
specified. However, imv is dual-licensed under the GPL and MIT licenses.

MIT is the one in the root LICENSE file, it's the one that Github shows
in  the main repo page and is also the more permissive one, therefore I
changed it to licenses.mit.

* python3Packages.aemet-opendata: init at 0.2.1

* home-assistant: update component-packages.nix

* home-assistant: test aemet component

* newlib: 3.3.0 -> 4.1.0

* python3Packages.aprslib: init at 0.6.47

* home-assistant: update component-packages.nix

* home-assistant: test aprs component

* ocamlPackages.mccs: init 1.1+13

* stylua: init at 0.8.1

* orocos-kdl: 1.4.0 -> 1.5.0

* opencv: update cuda_opt_flow.patch

* nvidia-optical-flow-sdk: 1.0 -> 2.0

* texlive: allow substitutes for texlive packages (#126458)

* gitlab: 13.12.2 -> 13.12.3

* python3Packages.pyatag: init at 0.3.5.3

* home-assistant: update component-packages.nix

* home-assistant: test atag component

* vscode-extensions.coolbear.systemd-unit-file: init at 1.0.6

* vscodium: 1.56.2 -> 1.57.0

* pythonPackages.blurhash: init at 1.1.4

* python3Packages.mastodon-py: init at 1.5.1

* home-assistant: update component-packages.nix

* ocamlPackages.cstruct: remove at 1.9.0 for OCaml < 4.02

This removes unreachable code.

* hunspell-dicts: add Dutch dictionary

* hunspell-dicts: change name to pname

* vscode-extensions.hashicorp.terraform: 2.12.0 -> 2.12.1

* python3Packages.androidtv: 0.0.59 -> 0.0.60

* vector: 0.13.1 -> 0.14.0

* tailscale: add `interfaceName` option

tailscale allows to specify the interface name.
The upstream systemd unit does not expose it directly however, only
via the `FLAGS` environment variable.

I can’t be 100% sure that the escaping is correct, but this is as good
as we can do for now, unless upstream changes their unit file.

* kitty: runHook preBuild and postBuild

* kitty: 0.21.0 -> 0.21.1

https://github.com/kovidgoyal/kitty/releases/tag/v0.21.1

* python3Packages.aio-geojson-client: init at 0.14

* python3Packages.aio-geojson-geonetnz-quakes: init at 0.12

* python3Packages.aio-geojson-geonetnz-volcano: init at 0.5

* python3Packages.aio-geojson-nsw-rfs-incidents: init at 0.3

* home-assistant: update component-packages

* home-assistant: enable geo* tests

* python3Packages.aio-geojson-nsw-rfs-incidents: 0.3 -> 0.4

* litecli: 1.5.0 -> 1.6.0

* google-fonts: unstable-2021-01-19 -> unstable-2021-06-12

Also move to `stdenvNoCC` to reduce rebuilds

* llvmPackages_git: 2021-05-17 -> 2021-06-04

This also fixes the libunwind build (even with GCC 11 it fails with):
/build/source/libunwind/src/libunwind.cpp:19:5: warning: "__has_feature" is not defined, evaluates to 0 [-Wundef]
   19 | #if __has_feature(address_sanitizer)
      |     ^~~~~~~~~~~~~
/build/source/libunwind/src/libunwind.cpp:19:18: error: missing binary operator before token "("
   19 | #if __has_feature(address_sanitizer)
      |                  ^

And the openmp build which failed with this error:
/nix/store/a4yw1svqqk4d8lhwinn9xp847zz9gfma-bash-4.4-p23/bin/bash: CLANG_TOOL-NOTFOUND: command not found
/nix/store/a4yw1svqqk4d8lhwinn9xp847zz9gfma-bash-4.4-p23/bin/bash: CLANG_TOOL-NOTFOUND: command not found
make[2]: *** [libomptarget/deviceRTLs/amdgcn/CMakeFiles/libomptarget-amdgcn-gfx906.dir/build.make:307: libomptarget/deviceRTLs/amdgcn/task.gfx906.bc] Error 127
make[2]: *** [libomptarget/deviceRTLs/amdgcn/CMakeFiles/libomptarget-amdgcn-gfx900.dir/build.make:307: libomptarget/deviceRTLs/amdgcn/task.gfx900.bc] Error 127

* Allow to extend PHP_INI_SCAN_DIR

Fixes #109383

* filezilla: add wrapGAppsHook (#126765)

* Move CompCert into coqPackages. (#126214)

* compcert: preparation to move in coqPackages

* compcert: move into coqPackages

* compcert: remove version 3.7

As a consequence, also remove VST version 2.6

These were broken.

* llvmPackages_git: Fix the libcxx and libcxxabi builds

* ricty: fix source

Moved from http://www.yusa.lab.uec.ac.jp/~yusa/ricty to https://rictyfonts.github.io

* darwin.mas: Fix dontBuild

* maintainers: add deliciouslytyped

* onedrive: 2.4.11 -> 2.4.12

* bootiso: add missing dependencies

* markdown-anki-decks: init at 1.0.0 (#126782)

Co-authored-by: Sandro <sandro.jaeckel@gmail.com>

* reaper: 6.28 -> 6.29 (#126838)

* sentry-cli: init at 1.66.0 (#126228)

* openssl: fix Darwin cross infinite recursion

stdenv depends on openssl, and isGNU depends on stdenv.

Thanks-to: sternenseemann <0rpkxez4ksa01gb3typccl0i@systemli.org>
Fixes: https://github.com/NixOS/nixpkgs/issues/126829

* zig: checks are back!

* hashcat: 6.2.1 -> 6.2.2 (#126820)

Change-Id: I3aa4d98b448b1a046cdcc103011c58a1a67c23de

* nixpkgs-review: 2.6.0 -> 2.6.1 (#126845)

* thefuck: 3.30 -> 3.31

* blueberry: 1.4.2 -> 1.4.3

* python3Packages.wled: 0.4.4 -> 0.5.0 (#126319)

Co-authored-by: Sandro <sandro.jaeckel@gmail.com>

* eksctl: 0.52.0 -> 0.53.0

* python3Packages.async-lru: init at unstable-2020-10-24

* python3Packages.tgcrypto: init at 1.2.2

* python3Packages.pyrogram: init at 1.2.0

* python3Packages.click-threading: 0.4.4 -> 0.5.0

* vdirsyncer: 0.16.8 -> 0.18.0

* python3Packages.ms-cv: init at 0.1.1

* python3Packages.xbox-webapi: init at 2.0.11

* home-assistant: update component-packages.nix

* home-assistant: test xbox component

* codespell: 2.0.0 -> 2.1.0

* alertmanager-irc-relay: 0.4.1 -> 0.4.2

* gnome.aisleriot: 3.22.16 -> 3.22.17

* cheat: 4.2.1 -> 4.2.2

* kora-icon-theme: 1.4.2 -> 1.4.3

* libquotient: 0.6.6 -> 0.6.7

* flyctl: 0.0.222 -> 0.0.223

* armadillo: 10.5.1 -> 10.5.2

* helmfile: 0.139.7 -> 0.139.8

* corosync: 3.1.3 -> 3.1.4

* dnsproxy: 0.37.5 -> 0.37.6

* croc: 9.1.4 -> 9.1.5

* staticjinja: 1.0.1 -> 2.1.0, add version test (#126690)

Co-authored-by: Sandro <sandro.jaeckel@gmail.com>

Co-authored-by: ajs124 <ajs124@users.noreply.github.com>
Co-authored-by: Sandro Jäckel <sandro.jaeckel@gmail.com>
Co-authored-by: Matthieu Coudron <mcoudron@hotmail.com>
Co-authored-by: Fabian Affolter <fabian@affolter-engineering.ch>
Co-authored-by: Jörg Thalheim <Mic92@users.noreply.github.com>
Co-authored-by: Fabian Affolter <mail@fabian-affolter.ch>
Co-authored-by: adisbladis <adisbladis@gmail.com>
Co-authored-by: Zach <zach@hipcreativeinc.com>
Co-authored-by: Naïm Favier <n@monade.li>
Co-authored-by: Ryan Mulligan <ryan@ryantm.com>
Co-authored-by: Maximilian Bosch <maximilian@mbosch.me>
Co-authored-by: Josh Rickmar <jrick@companyzero.com>
Co-authored-by: Anderson Torres <torres.anderson.85@protonmail.com>
Co-authored-by: fortuneteller2k <lythe1107@gmail.com>
Co-authored-by: p3psi <43925055+p3psi-boo@users.noreply.github.com>
Co-authored-by: superherointj <5861043+superherointj@users.noreply.github.com>
Co-authored-by: Yusuf Bera Ertan <y.bera003.06@protonmail.com>
Co-authored-by: rnhmjoj <rnhmjoj@inventati.org>
Co-authored-by: Martin Weinelt <hexa@darmstadt.ccc.de>
Co-authored-by: Elis Hirwing <elis@hirwing.se>
Co-authored-by: marius david <mariusdavid@laposte.net>
Co-authored-by: Thomas Gerbet <thomas@gerbet.me>
Co-authored-by: Martin Weinelt <mweinelt@users.noreply.github.com>
Co-authored-by: Michael Weiss <dev.primeos@gmail.com>
Co-authored-by: George <services+github@figgyc.uk>
Co-authored-by: Samuel Noordhuis <samuel@snoord.com>
Co-authored-by: Bernardo Meurer <bernardo@meurer.org>
Co-authored-by: Vladimir Serov <me@cab404.ru>
Co-authored-by: 06kellyjac <dev@j-k.io>
Co-authored-by: Axel Forsman <axelsfor@gmail.com>
Co-authored-by: Michele Guerini Rocco <rnhmjoj@users.noreply.github.com>
Co-authored-by: Alyssa Ross <hi@alyssa.is>
Co-authored-by: Michael Livshin <repo@cmm.kakpryg.net>
Co-authored-by: John Ericson <git@JohnEricson.me>
Co-authored-by: Mauricio Scheffer <mauricioscheffer@gmail.com>
Co-authored-by: be7a <bela.stoyan@gmail.com>
Co-authored-by: Mustafa Çalışkan <musfay@protonmail.com>
Co-authored-by: Pavol Rusnak <pavol@rusnak.io>
Co-authored-by: Austin Butler <abutler@riotgames.com>
Co-authored-by: Robert Schütz <dev@schuetz-co.de>
Co-authored-by: kraem <ebrin.ronnie@protonmail.com>
Co-authored-by: Robert Hensing <roberth@users.noreply.github.com>
Co-authored-by: IvarWithoutBones <ivar.scholten@protonmail.com>
Co-authored-by: Ricardo M. Correia <rcorreia@wizy.org>
Co-authored-by: figsoda <figsoda@pm.me>
Co-authored-by: Ben Wolsieffer <benwolsieffer@gmail.com>
Co-authored-by: Artturin <Artturin@artturin.com>
Co-authored-by: Vincenzo Mantova <xworld21@gmail.com>
Co-authored-by: Milan Pässler <milan@petabyte.dev>
Co-authored-by: Kevin Amado <kamadorueda@gmail.com>
Co-authored-by: upkeep-bot <foo@bar.com>
Co-authored-by: Vincent Laporte <Vincent.Laporte@gmail.com>
Co-authored-by: Ryan Horiguchi <ryan.horiguchi@gmail.com>
Co-authored-by: Kim Lindberger <kim.lindberger@gmail.com>
Co-authored-by: happysalada <raphael@megzari.com>
Co-authored-by: Profpatsch <mail@profpatsch.de>
Co-authored-by: Luflosi <luflosi@luflosi.de>
Co-authored-by: Serhii Zhuravel <1804871+dxops@users.noreply.github.com>
Co-authored-by: ilmari-lauhakangas <ilmari-lauhakangas@users.noreply.github.com>
Co-authored-by: José Romildo Malaquias <malaquias@gmail.com>
Co-authored-by: Théo Zimmermann <theo.zimmermann@inria.fr>
Co-authored-by: deliciouslytyped <47436522+deliciouslytyped@users.noreply.github.com>
Co-authored-by: Peter Hoeg <peter@hoeg.com>
Co-authored-by: Jan Tojnar <jtojnar@gmail.com>
Co-authored-by: ilian <ilian@tuta.io>
Co-authored-by: Andika Demas Riyandi <andika.riyan@gmail.com>
Co-authored-by: ElXreno <elxreno@gmail.com>
Co-authored-by: Jonathan Ringer <jonringer@users.noreply.github.com>
Co-authored-by: Domen Kožar <domen@dev.si>
Co-authored-by: R. RyanTM <ryantm-bot@ryantm.com>
Co-authored-by: Francesco Gazzetta <fgaz@fgaz.me>