tsm-client: fix absolute symlinks, drop openssl dependency
`tsm-client` is delivered with its
own `lib{crypto,ssl}.so` implementation.
Beginning with version 8.1.9.1, those `.so`-files came with
absolute symlinks to `/opt/...` causing `autoPatchelf`
to abort with error messages of the form

> error: auto-patchelf could not satisfy dependency libssl.so.1.1

I was under the impression that a new dependency
got introduced and added `openssl` to `builtInputs`
in commit 5ad0ecb9019e964d2abfe034e184f8b846e42dfa.
This fixed the build, but `tsm-client` no longer
linked against its own ssl implementation.

The commit at hand corrects that mistake:
It adds a small `preFixup` script that finds
and adapts absolute symlinks to `/opt/`,
so that `autoPatchelfHook` finds those
`so`-files again and sets RPATH properly.
This permits to drop `openssl` from the dependency list again.