Revert "nss: 3.68.4 -> 3.79"
This reverts commit 1c76a270d2d0331aaed02a308acb607e81e5c414.

This breaks the Firefox 91esr build, which is apparently not compatible
with this NSS version.

/build/firefox-91.10.0/security/certverifier/OCSPVerificationTrustDomain.cpp:63:11: error: unknown type name 'SignedDigest'

Will revisit this upgrade, when we drop 91esr in favor of 102esr soon.