nixos/jitsi-meet: fix `cfg.caddy.enable`
This fixes the following error:

```
error: failed processing files:
        FailedJobs(
        "static/404.html": Permission denied (os error 13) at path "/build/static/.tmpRMzDXu"
)
```

(cherry picked from commit 3e5dc7174ede2897c5da25bb7863b2df52400a0c)