nixos/tests/matrix-synapse: fix test
Since matrix-synapse 0.33.0 underscores in server names are rejected
by server name validation, causing the test to fail:
  valueError: Server name 'server_sqlite' contains invalid characters
Relevant upstream change:
https://github.com/matrix-org/synapse/commit/546bc9e28b3d7758c732df8e120639d58d455164