aerospike: drop blanket -Werror
This time -Werror causes build error on gcc-11:

    $ nix build --impure --expr 'with import ./. {}; aerospike.override { stdenv = gcc11Stdenv; }'
    ...
    fabric/clustering.c: In function 'msg_succession_list_field_set.constprop':
    fabric/clustering.c:3750:9: error: '<unknown>' may be used uninitialized [-Werror=maybe-uninitialized]
     3750 |         msg_set_buf(msg, field, (uint8_t*)succession_buffer, buffer_size,
          |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     3751 |                         MSG_SET_COPY);
          |                         ~~~~~~~~~~~~~

Let's drop -Werror and stop adding downstream -Wno-error= workarounds.