django-extensions: 3.1.0 -> 3.1.1
Among other changes, this fixes the following test failure:

    FAILED tests/templatetags/test_syntax_color.py::SyntaxColorTagTests::test_should_colorize_noclasses_with_default_lexer

which was caused by commit 444da66670e ("python3Packages.Pygments: 2.7.2 -> 2.7.4", 2021-02-20).
Upstream fixes it in
https://github.com/django-extensions/django-extensions/commit/2356958fb6e2fee7530eb642f39c326fa2e94f2a.