nixos/wyoming-faster-whisper: fix typo in assertion
Fixes typo in assertion: `initialPromt` -> `initialPrompt`

This typo causes the module to fail with:

```
error: A definition for option `assertions' is not of type `list of unspecified value'. Definition values:
- In `/nix/store/.../nixos/modules/services/home-automation/wyoming/faster-whisper.nix': <function>
```

The typo was introduced in the v2.5.0 update.​​​​​​​​​​​​​​​​