Revert "python3Packages.sqlalchemy: 1.4.45 -> 1.4.46"
This reverts commit 915fd5f93cd3ffbf0eb3f629b3dd2edfed56f5c2.

This fixes the buildbot package from the following error:

    error: builder for '/nix/store/i7chps5jxa0q2ymzjbkgh1rgdzdhzfzq-python3.10-buildbot-3.7.0.drv' failed with exit code 1;
    last 25 log lines:
    > ===============================================================================
    > [SKIPPED]
    > Need to install hvac to test VaultAuthenticatorToken
    >
    > buildbot.test.unit.test_secret_in_hvac.TestSecretInVaultAuthenticatorToken.test_authenticate
    > ===============================================================================
    > [SKIPPED]
    > unidiff is required for GitDiffInfo tests
    >
    > buildbot.test.unit.test_steps_git_diffinfo.TestDiffInfo.test_complex_diff
    > buildbot.test.unit.test_steps_git_diffinfo.TestDiffInfo.test_diff_failure
    > buildbot.test.unit.test_steps_git_diffinfo.TestDiffInfo.test_empty_diff
    > buildbot.test.unit.test_steps_git_diffinfo.TestDiffInfo.test_merge_base_failure
    > ===============================================================================
    > [ERROR]
    > Traceback (most recent call last):
    >   File "/nix/store/2m4mif9lkr2afl829asqq7mi94q0d73z-python3.10-twisted-22.10.0/lib/python3.10/site-packages/twisted/trial/_synctest.py", line 1068, in run
    >     warnings.warn_explicit(**w)
    > sqlalchemy.exc.RemovedIn20Warning: Deprecated API features detected! These feature(s) are not compatible with SQLAlchemy 2.0. To prevent incompatible upgrades prior to updating applications, ensure requirements files are pinned to "sqlalchemy<2.0". Set environment variable SQLALCHEMY_WARN_20=1 to show all deprecation warnings.  Set environment variable SQLALCHEMY_SILENCE_UBER_WARNING=1 to silence this message. (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9) (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)