python3Packages.pdm-pep517: add 'setuptools' test depend
https://github.com/NixOS/nixpkgs/pull/185815 exposed missing
`setuptools` test dependency in `staging`:

    ----------------------------- Captured stderr call -----------------------------
    Traceback (most recent call last):
      File "/build/pdm-pep517-1.0.4/tests/fixtures/projects/demo-cextension-in-src/setup.py", line 3, in <module>
        from setuptools import setup
    ModuleNotFoundError: No module named 'setuptools'
    =========================== short test summary info ============================
    FAILED tests/test_api.py::test_build_with_cextension - pdm.pep517.exceptions....
    FAILED tests/test_api.py::test_build_with_cextension_in_src - pdm.pep517.exce...

The change adds `setuptools` as a check dependency.