python3Packages.cocotb: fix build
I removed the test as it currently fails on master and is removed
upstream in the as-yet-unreleased next version.

The test that fails looks like this:

```
Traceback (most recent call last):
  File "/build/source/tests/test_cases/test_cocotb/test_deprecated.py", line 39, in test_unicode_handle_assignment_deprecated
    dut.stream_in_string.value = "Bad idea"
    ^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/yvcizx3fwkm044jpw9sfpnb0kx0g2bfl-python3.11-cocotb-1.8.1/lib/python3.11/site-packages/cocotb/handle.py", line 370, in __getattr__
    raise AttributeError(f"{self._name} contains no object named {name}")
AttributeError: sample_module contains no object named stream_in_string

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/build/source/tests/test_cases/test_cocotb/test_deprecated.py", line 38, in test_unicode_handle_assignment_deprecated
    with pytest.warns(DeprecationWarning, match=".*bytes.*"):
  File "/nix/store/5ipi1f14ji1nrvqnf8h8fqvr0zny183d-python3.11-pytest-8.0.2/lib/python3.11/site-packages/_pytest/recwarn.py", line 332, in __exit__
    fail(
  File "/nix/store/5ipi1f14ji1nrvqnf8h8fqvr0zny183d-python3.11-pytest-8.0.2/lib/python3.11/site-packages/_pytest/outcomes.py", line 188, in fail
    raise Failed(msg=reason, pytrace=pytrace)
Failed: DID NOT WARN. No warnings of type (<class 'DeprecationWarning'>,) were emitted.
 Emitted warnings: [].
```