python3Packages.jira: fix build
33fb47db6f5d (python3Packages.jira: 3.8.0 -> 3.9.4, 2025-01-19) update
python3Packages.jira to 3.9.4.  After that commit, python-jira fails to build:

    $ nix build -L --impure --expr '(import ./. {}).python3.withPackages(ps: [ ps.jira ])'
    [...]
    error: builder for '/nix/store/bfr24lmgw4izl9ixh2sdm794a9kky7w6-python3.12-jira-3.9.4.drv' failed with exit code 1;
           last 19 log lines:
           > Sourcing python-remove-tests-dir-hook
           > Sourcing python-catch-conflicts-hook.sh
           > Sourcing python-remove-bin-bytecode-hook.sh
           > Sourcing pypa-build-hook
           > Using pypaBuildPhase
           > Sourcing python-runtime-deps-check-hook
           > Using pythonRuntimeDepsCheckHook
           > Sourcing pypa-install-hook
           > Using pypaInstallPhase
           > Sourcing python-imports-check-hook.sh
           > Using pythonImportsCheckPhase
           > Sourcing python-namespaces-hook
           > Sourcing python-catch-conflicts-hook.sh
           > Running phase: unpackPhase
           > unpacking source archive /nix/store/ck51dycsghmkf7449p615crsqdn2xsni-source
           > source root is source
           > setting SOURCE_DATE_EPOCH to timestamp 315619200 of file "source/tox.ini"
           > Running phase: patchPhase
           > substitute(): ERROR: file 'setup.cfg' does not exist
           For full logs, run 'nix log /nix/store/bfr24lmgw4izl9ixh2sdm794a9kky7w6-python3.12-jira-3.9.4.drv'.
    error: 1 dependencies of derivation '/nix/store/i5xib9msa42grs3cwa1ibw0cfdi799f9-python3-3.12.8-env.drv' failed to build

The functionality in setup.cfg was moved to pyproject.toml in
pycontribs/jira@668562a3f8c7 (migrate `setup.cfg` to `pyproject.toml`
(pycontribs/jira#1776), 2024-03-25).

Use pytest-cov-stub instead of the `postPatch` hack.