python37Packages.goobook: Add the missing setuptools dependency
Querying resulted in the following error:

$ goobook query test
Traceback (most recent call last):
  File "/nix/store/y68w4wwx65yfck84vjsdvfwnii5594lc-python3.7-goobook-3.4/bin/.goobook-wrapped", line 7, in <module>
    from goobook.application import main
  File "/nix/store/y68w4wwx65yfck84vjsdvfwnii5594lc-python3.7-goobook-3.4/lib/python3.7/site-packages/goobook/application.py", line 18, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'