geant4: disable OGLX frontend by default on darwin
This requires linking to Gallium, which seems to fail downstream:
```
ERROR: failed to load libFOO.dylib: dlopen(libFOO.dylib, 5): Library not loaded: @rpath/libgallium-24.2.2.dylib
  Referenced from: /nix/store/cnschgva12mp3cklach4c0jcvcghxy1h-mesa-24.2.2/lib/libGL.1.dylib
  Reason: image not found
```

It also appears to break the native OpenGL/Qt backend.