libgdiplus: 5.6.1 -> 6.0.2
Fixes build error: undefined reference to `GifQuantizeBuffer'
that was most likely caused by giflib update in 3605f1285
ABI tracker didn't show removal of this symbol - I don't know,
perhaps we have different build setting, or something.

Here I found no NEWS, ABI tracker seems OK - only minor
incompatibilities in -private headers.  Mono stuff builds now.