liblqr1: fix build on Darwin
Without this patch, we sometimes get the following error when building
this derivation:

```
error: builder for '/nix/store/yhfv2ng67l39z4ycs3ik733ammssm90l-liblqr-1-0.4.2.drv' failed with exit code 2;
       last 10 log lines:
       > libtool: compile:  clang -DHAVE_CONFIG_H -I. -I. -I.. -DDATADIR=\"/nix/store/illjxmhcaslif3j0nxw0mrl6217gmasg-liblqr-1-0.4.2/share/liblqr-1\" -I.. -I/nix/store/076lwg66shi066i6rksnm0y9acq1nsmn-glib-2.72.3-dev/include/glib-2.0 -I/nix/store/2vlnj2x13s88x73i16czxbx43skhi613-glib-2.72.3/lib/glib-2.0/include -I/nix/store/illjxmhcaslif3j0nxw0mrl6217gmasg-liblqr-1-0.4.2/include -fvisibility=hidden -g -O2 -Wall -c lqr_progress.c  -fno-common -DPIC -o .libs/lqr_progress.o
       > /nix/store/zhb1b88lw5qxhk50f75dgfwwh5m0cg7i-bash-5.1-p16/bin/bash ../libtool --tag=CC --mode=link clang  -g -O2 -Wall   -o liblqr-1.la -rpath /nix/store/illjxmhcaslif3j0nxw0mrl6217gmasg-liblqr-1-0.4.2/lib -version-info 3:2:3  lqr_gradient.lo lqr_rwindow.lo lqr_energy.lo lqr_cursor.lo lqr_carver.lo lqr_carver_list.lo lqr_carver_bias.lo lqr_carver_rigmask.lo lqr_vmap.lo lqr_vmap_list.lo lqr_progress.lo -L/nix/store/2vlnj2x13s88x73i16czxbx43skhi613-glib-2.72.3/lib -lglib-2.0 -lm
       > libtool: link: clang -dynamiclib -Wl,-flat_namespace -Wl,-undefined -Wl,suppress -o .libs/liblqr-1.0.dylib  .libs/lqr_gradient.o .libs/lqr_rwindow.o .libs/lqr_energy.o .libs/lqr_cursor.o .libs/lqr_carver.o .libs/lqr_carver_list.o .libs/lqr_carver_bias.o .libs/lqr_carver_rigmask.o .libs/lqr_vmap.o .libs/lqr_vmap_list.o .libs/lqr_progress.o   -L/nix/store/2vlnj2x13s88x73i16czxbx43skhi613-glib-2.72.3/lib -lglib-2.0 -lm  -O2   -install_name  /nix/store/illjxmhcaslif3j0nxw0mrl6217gmasg-liblqr-1-0.4.2/lib/liblqr-1.0.dylib -compatibility_version 4 -current_version 4.2 -Wl,-single_module
       > ld: file not found: /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit for architecture x86_64
       > clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
       > make[2]: *** [Makefile:357: liblqr-1.la] Error 1
       > make[2]: Leaving directory '/private/tmp/nix-build-liblqr-1-0.4.2.drv-0/source/lqr'
       > make[1]: *** [Makefile:332: all-recursive] Error 1
       > make[1]: Leaving directory '/private/tmp/nix-build-liblqr-1-0.4.2.drv-0/source'
       > make: *** [Makefile:242: all] Error 2
```

It is not reproducible under all circumstances, but under the
conditions where it can be reproduced is stable, and adding `AppKit`
as a dependency helps fixing this issue.

This has happened before, but with the Carbon framework back then with
this same derivation: https://github.com/NixOS/nixpkgs/pull/135630

(cherry picked from commit 09a8c1b440a6afc4d7ddbd2d2369436a45d17b9b)