cgt-calc: fix build by backporting uv-build relaxation
On latest unstable:
```
ERROR Missing dependencies:
        uv_build<0.11.0,>=0.8.23
error: Cannot build '/nix/store/w9vn8bl71zib3lgf4dfrdkrfasz9alnx-cgt-calc-2.0.0.drv'.
       Reason: builder failed with exit code 1.
       Output paths:
         /nix/store/kg4zwzbh10vn51h0r6g6jmlhh0wb6k93-cgt-calc-2.0.0-dist
         /nix/store/wnr2qzvnw7l0czbaa0qqm2wdjyfrbnfb-cgt-calc-2.0.0
       Last 25 log lines:
       > Using pypaBuildPhase
       > Sourcing python-runtime-deps-check-hook
       > Using pythonRuntimeDepsCheckHook
       > Sourcing pypa-install-hook
       > Using pypaInstallPhase
       > Sourcing python-imports-check-hook.sh
       > Using pythonImportsCheckPhase
       > Sourcing python-namespaces-hook
       > Sourcing python-catch-conflicts-hook.sh
       > Running phase: unpackPhase
       > unpacking source archive /nix/store/xf1v660b4w4kv0sk1qhwx5lx9gapacgz-source
       > source root is source
       > setting SOURCE_DATE_EPOCH to timestamp 315619200 of file "source/uv.lock"
       > Running phase: patchPhase
       > Running phase: updateAutotoolsGnuConfigScriptsPhase
       > Running phase: configurePhase
       > no configure script, doing nothing
       > Running phase: buildPhase
       > Executing pypaBuildPhase
       > Creating a wheel...
       > pypa build flags: --no-isolation --outdir dist/ --wheel
       > * Getting build dependencies for wheel...
       >
       > ERROR Missing dependencies:
       >     uv_build<0.11.0,>=0.8.23
       For full logs, run:
         nix log /nix/store/w9vn8bl71zib3lgf4dfrdkrfasz9alnx-cgt-calc-2.0.0.drv
```

Fix is upstream but not yet released: https://github.com/KapJI/capital-gains-calculator/pull/781