tdesktop: 1.7.0 -> 1.7.3
GCC 8.x is required to avoid the following error:

cc1plus: error: -Werror=class-memaccess: no option -Wclass-memaccess

If we build without "-Wno-error=class-memaccess" the build should fail
and the upstream requirements were raised from GCC 7 to GCC 8 anyway:
https://github.com/telegramdesktop/tdesktop/commit/b2f821d3deb65ade7416d28a18148176f6c40b34

The two additional patches are required to avoid build errors like this:

/build/source/Telegram/ThirdParty/qtlottie/src/bodymovin/bmbase.cpp:123:12:
error: invalid use of incomplete type 'class QDebug'
   qWarning()
            ^
In file included from
/nix/store/1qk60bhxcf95iicms7mkyjq3h7lz136p-qtbase-5.12.0-dev/include/QtCore/qglobal.h:1200,
                 from
/nix/store/1qk60bhxcf95iicms7mkyjq3h7lz136p-qtbase-5.12.0-dev/include/QtCore/qalgorithms.h:43,
                 from
/nix/store/1qk60bhxcf95iicms7mkyjq3h7lz136p-qtbase-5.12.0-dev/include/QtCore/qlist.h:43,
                 from
/nix/store/1qk60bhxcf95iicms7mkyjq3h7lz136p-qtbase-5.12.0-dev/include/QtCore/QList:1,
                 from
/build/source/Telegram/ThirdParty/qtlottie/src/bodymovin/bmbase.h:31,
                 from
/build/source/Telegram/ThirdParty/qtlottie/src/bodymovin/bmbase.cpp:29:
/nix/store/1qk60bhxcf95iicms7mkyjq3h7lz136p-qtbase-5.12.0-dev/include/QtCore/qlogging.h:57:7:
note: forward declaration of 'class QDebug'
 class QDebug;
       ^~~~~~