gfxstream: fix build with gcc15
- add patch that adds missing `#include <cstdint>`, similar to what fedora does:
https://src.fedoraproject.org/rpms/gfxstream/raw/2c7cbc24596973e2efc8180af81e57ddfa24654b/f/fix_missing_cstdint.patch
(it applies, but somehow we hit more places with missing headers even
with that patch)

Fixes build failure with gcc15:
```
In file included from ../host/compressedTextureFormats/AstcCpuDecompressorNoOp.cpp:15:
../host/compressedTextureFormats/AstcCpuDecompressor.h:48:32:
error: 'uint32_t' has not been declared
   48 |     virtual int32_t decompress(uint32_t imgWidth, uint32_t imgHeight, uint32_t blockWidth,
      |                                ^~~~~~~~
../host/compressedTextureFormats/AstcCpuDecompressor.h:18:1:
note: 'uint32_t' is defined in header '<cstdint>'; this is probably
fixable by adding '#include <cstdint>'
   17 | #include <string>
  +++ |+#include <cstdint>
   18 |
../host/compressedTextureFormats/AstcCpuDecompressorNoOp.cpp:25:43:
error: 'uint32_t' has not been declared
   25 |     int32_t decompress(uint32_t imgWidth, uint32_t imgHeight, uint32_t blockWidth,
      |                                           ^~~~~~~~
../host/compressedTextureFormats/AstcCpuDecompressorNoOp.cpp:25:43:
note: 'uint32_t' is defined in header '<cstdint>'; this is probably
fixable by adding '#include <cstdint>'
```