gclient2nix: update, fix for electron_38
Fixes error:

```
File "/nix/store/x95xf16qsvblyxgcag1fqmrsqm7px6rk-depot_tools-452fe3b/gclient_eval.py", line 643, in _convert
    raise ValueError('invalid "and" operand %r (inside %r)' %
ValueError: invalid "and" operand 'checkout_riscv64' (inside 'checkout_linux and checkout_riscv64 and non_git_source')
```

(cherry picked from commit 62d173f9c81debc92e341da29bf8a29e8b9ec28b)