looking-glass-client: restrict to x86_64-linux
The AArch64 build fails after trying to pull in tmmintrin.h:

```
../common/memcpySSE.h:24:23: fatal error: tmmintrin.h: No such file or directory
 #include <tmmintrin.h>
                       ^
compilation terminated.
make: *** [Makefile:29: .build/renderers/opengl.o] Error 1
```

Which are SSSE3 intrinsics unsupported on ARM. This package also likely would
not be useful on ARM, as it requires KVM and a compatible KVM guest running
the frame relay (usually Windows).