systemd: disable remote support
This disabled systemd-journal-upload and systemd-journal-remote.

We didn't install the unit files anyways, so this was probably not used
at all, and currently fails to build due to libmicrohttpd and systemd
code being incompatible:

```
../src/journal-remote/journal-remote-main.c: In function ‘setup_microhttpd_server’:
../src/journal-remote/journal-remote-main.c:431:38: error: passing argument 5 of ‘MHD_start_daemon’ from incompatible pointer type [-Werror=incompatible-pointer-types]
```