evolution-ews: fix patch compiler errors
/build/evolution-ews-3.56.1/src/common/e-ews-common-utils.c:211:13: error: 'true' undeclared (first use in this function)
  211 |         if (true) {
      |             ^~~~
/build/evolution-ews-3.56.1/src/common/e-ews-common-utils.c:15:1: note: 'true' is defined in header '<stdbool.h>'; this is probably fixable by adding '#include <stdbool.h>'
   14 | #include "e-ews-common-utils.h"
  +++ |+#include <stdbool.h>
   15 |
/build/evolution-ews-3.56.1/src/common/e-ews-common-utils.c:211:13: note: each undeclared identifier is reported only once for each function it appears in
  211 |         if (true) {
      |             ^~~~

(cherry picked from commit 7128c9546c02dbfa25f40a686c4fb489987c4f6a)