nixVersions.git.tests: fix the eval
Without the change the eval fails as:

    $ nix build --no-link -f. nixVersions.git.tests
           error: attribute 'nix_2_23' missing
           at pkgs/tools/package-management/nix/common.nix:252:17:
              251|     tests = {
              252|       nixi686 = pkgsi686Linux.nixVersions.${"nix_${lib.versions.major version}_${lib.versions.minor version}"};
                 |                 ^
              253|     };
           Did you mean one of nix_2_13, nix_2_20, nix_2_21, nix_2_22 or nix_2_3?

The change explicitly passes attribute name around instead of inferring
it from package version.