stone-phaser: Add missing libGL
Cairo will soon no longer propagate libGL. The DPF submodule needs this:

src/pugl/pugl.h:39:14: fatal error: GL/gl.h: No such file or directory
   39 | #    include <GL/gl.h>
      |              ^~~~~~~~~
compilation terminated.

(See also the fix for string-machine, which has the same build issue)