pytest_xdist - make version conditional on python interpreter
Like a number of other modules, the newer version of `pytest_xdist`
simply does not work on a python 2.x interpreter, resulting in
instantiation errors for tools using the 2.x interpreter like:

```
error: pytest-xdist-2.1.0 not supported for interpreter python2.7
(use '--show-trace' to show detailed location information)
```

This change uses the same strategy as those other modules to
conditionalize the version that is selected on the version of the
python interpreter.

I would like to keep this working for a while, at least, since the
DeDRM plugin for Calibre only works under python2 for the moment.