jshon: fix build on aarch64-darwin
```
jshon> clang -std=c99 -Wall -pedantic -Wextra -Werror    -c -o jshon.o jshon.c
jshon> jshon.c:189:25: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
jshon> json_t** stack_safe_peek()
jshon>                         ^
jshon>                          void
jshon> 6 errors generated.
jshon> make: *** [<builtin>: jshon.o] Error 1
```

Signed-off-by: Roman Volosatovs <rvolosatovs@riseup.net>
(cherry picked from commit 73877a6f3459d2ff756074a470dae38a782442d5)