xwax: fix the build (missing alsa-lib input)
Without the change the build fails as
https://hydra.nixos.org/build/294945388:

    alsa.c:24:10: fatal error: alsa/asoundlib.h: No such file or directory
       24 | #include <alsa/asoundlib.h>
          |          ^~~~~~~~~~~~~~~~~~