zerotierone: 1.14.0 -> 1.14.2, migrate to fetchCargoVendor
The version update can't be separated from migration to fetchCargoVendor
because of the rust 1.80 time issue, which was resolved by patching
vendored Cargo.lock.

I'm not entirely sure how the darwin build worked and what could have
changed, but now without `0002-darwin-dont-build-for-both-arches.patch`
Make tries to rebuild libzeroidc.a, by building both aarch64 and x86_64
libs and fails on my x86_64-darwin with the error:

```
error[E0463]: can't find crate for `core`
  |
  = note: the `aarch64-apple-darwin` target may not be installed
  = help: consider downloading the target with `rustup target add aarch64-apple-darwin`
```

This has something to do with the FORCE target and the previous workaround
of `touch FORCE` doesn't seem to work. Patching out the offending
target seems a bit more robust regardless of why the workaround has
stopped working.

Additionally dropped the now obsolete darwin sdk pattern and enabled
__darwinAllowLocalNetworking for `checkPhase`.