zzuf: fix build with gcc14
- add patch from fedora:
https://src.fedoraproject.org/rpms/zzuf/c/998c7e5e632ea4c635a53437a01bfb48cbd744ac
fixing `implicit-function-declaration` error:
```
zzat.c: In function 'run':
zzat.c:482:32: error: implicit declaration of function '_IO_getc'
  482 |             MY_FREAD(ch = (n = _IO_getc(f)), &ch, (n != EOF));
      |                                ^~~~~~~~
```

- add patch from fedora (vendored because patch is in format that does not
apply with `fetchpatch`):
https://src.fedoraproject.org/rpms/zzuf/c/ca7e406989e7ff461600084f2277ad15a8c00058
fixing `implicit-function-declaration` error:
```
zzat.c:565:26: error: implicit declaration of function '__fseeko64'; did you mean 'fseeko64'?
  565 |             MY_FSEEK(l = __fseeko64(f, l1, SEEK_CUR),
      |                          ^~~~~~~~~~
```