pre-commit: Add libiconv for tests on x86_64-darwin
Note: not a checkInput, because we need
this dependency in the role of a _build_
input during tests: library path, etc.

Solves

    E                 = note: ld: library not found for -liconv
    E                         clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
    E
    E
    E               error: failed to compile `rust-hello-world v0.1.0 (/private/tmp/nix-build-python3.9-pre-commit-2.18.1.drv-1/pytest-of-nixbld4/pytest-0/popen-gw3/test_rust_hook0/0/.pre-commit/repomj5itq00)`, intermediate artifacts can be found at `/private/tmp/nix-build-python3.9-pre-commit-2.18.1.drv-1/pytest-of-nixbld4/pytest-0/popen-gw3/test_rust_hook0/0/.pre-commit/repomj5itq00/target`
    E
    E               Caused by:
    E                 could not compile `rust-hello-world` due to previous error

    pre_commit/util.py:146: CalledProcessError

in test case

    FAILED tests/repository_test.py::test_rust_hook