jitsi: fix the run script to work when installed via systemPackages
Otherwise, the wrong directory is changed into, and trying to start Jitsi gives:

$ jitsi
Error: Could not find or load main class net.java.sip.communicator.launcher.SIPCommunicator