flsmg: 4.0.23 -> 4.0.24
Added `versionCheckHook`
Added `patches` to include missing header file `pthread.h`. Without it
the build will fail with:
  > widgets/font_browser.cxx: In function 'void find_fonts()':
       > widgets/font_browser.cxx:391:13: error: 'pthread_create' was not de
       >   391 |         if (pthread_create(&find_font_thread, NULL, find_fi
       >       |             ^~~~~~~~~~~~~~
       >       |             pthread_t
       > make[2]: *** [Makefile:3513: widgets/flmsg-font_browser.o] Error 1