moz-phab: add missing 'pip' runtime dependency
Without the change certificate installation fails as:

    $ moz-phab install-certificate
    ...
    Upgrading to version 1.0.0
    ...-python3.9-setuptools-61.2.0/lib/python3.9/site-packages/setuptools/command/install.py:34:
      SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    ...-python3-3.9.12/bin/python3.9: No module named pip
    CommandError: command '...-python3-3.9.12/bin/python3.9' failed to complete successfully
    Run moz-phab again with '--trace' to show debugging output

Closes: https://github.com/NixOS/nixpkgs/issues/174692