chatterino2: unstable-2019-05-11 -> 2.1.7
Upgrade chatterino2 to the latest release version.

This commit changes the name of the chatterino2 package. Before this
commit, the package is named chatterino2-unstable. After this commit,
the package is named chatterino2. If a user wants to upgrade, they must
first uninstall chatterino2-unstable before installing chatterino2, else
there will be a conflict:

    $ nix-env -iA nixpkgs.chatterino2
    installing 'chatterino2-2.1.7'
    building '/nix/store/hxx0vriblvvlkskcnm4rk32d2ghlvkj5-user-environment.drv'...
    error: packages '/nix/store/icgg81lkh1z17zbzw7ncrfqnkhlb39x9-chatterino2-2.1.7/Applications/chatterino.app/Contents/Info.plist' and '/nix/store/65wapk4pd5gj8dgvd245fzv4z799cnw8-chatterino2-unstable-2019-05-11/Applications/chatterino.app/Contents/Info.plist' have the same priority 5; use 'nix-env --set-flag priority NUMBER INSTALLED_PKGNAME' to change the priority of one of the conflicting packages (0 being the highest priority)
    builder for '/nix/store/hxx0vriblvvlkskcnm4rk32d2ghlvkj5-user-environment.drv' failed with exit code 1
    error: build of '/nix/store/hxx0vriblvvlkskcnm4rk32d2ghlvkj5-user-environment.drv' failed
    $ nix-env -q | grep chatterino2
    chatterino2-unstable-2019-05-11

    $ # chatterino2-unstable conflicts with chatterino2; both can't be
    $ # installed at the same time. Uninstall chatterino2-unstable, then
    $ # try installing chatterino2 again:

    $ nix-env -e chatterino2-unstable
    uninstalling 'chatterino2-unstable-2019-05-11'
    $ nix-env -iA nixpkgs.chatterino2
    installing 'chatterino2-2.1.7'
    $ nix-env -q | grep chatterino2
    chatterino2-2.1.7