rebase generates:
gcc -c extension/clib/msg.c -o extension/clib/msg.o
gcc -c extension/clib/ipc.c -o extension/clib/ipc.o
gcc -c extension/clib/luakit.c -o extension/clib/luakit.o
gcc -o luakit.so extension/luajs.o extension/ipc.o extension/extension.o extension/log.o extension/script_world.o extension/scroll.o extension/clib/page.o extension/clib/dom_document.o extension/clib/soup.o extension/clib/dom_element.o extension/clib/msg.o extension/clib/ipc.o extension/clib/luakit.o common/luajs.o common/luaobject.o common/luayield.o common/util.o common/luautil.o common/luauniq.o common/property.o common/ipc.o common/luah.o common/luaserialize.o common/resource.o common/lualib.o common/luaclass.o common/clib/timer.o common/clib/utf8.o common/clib/ipc.o common/clib/luakit.o common/clib/regex.o common/tokenize.o
rm -rf doc/apidocs
mkdir doc/apidocs
luajit ./build-utils/docgen/makedoc.lua
/nix/store/zrarsvfma3zfc00dg99lfq3s0p163yv9-luajit-2.1.0-beta3/bin/luajit: build-utils/docgen/gen.lua:2: module 'lib.lousy.util' not found:
        no field package.preload['lib.lousy.util']
        no file '/nix/store/xa7a51dw6hvx0r4ka65blxha5660akn9-luajit-2.1.0-beta3-env/lib/lua/5.1/lib/lousy/util.lua'
        no file '/nix/store/xa7a51dw6hvx0r4ka65blxha5660akn9-luajit-2.1.0-beta3-env/share/lua/5.1/lib/lousy/util.lua'
        no file '/nix/store/xa7a51dw6hvx0r4ka65blxha5660akn9-luajit-2.1.0-beta3-env/share/lua/5.1/lib/lousy/util/init.lua'
        no file '/nix/store/xa7a51dw6hvx0r4ka65blxha5660akn9-luajit-2.1.0-beta3-env/lib/lua/5.1/lib/lousy/util/init.lua'
        no file '/nix/store/xa7a51dw6hvx0r4ka65blxha5660akn9-luajit-2.1.0-beta3-env/share/luajit-2.1.0-beta3/lib/lousy/util.lua'
        no file 'build-utils/lib/lousy/util.lua'
        no file '/nix/store/xa7a51dw6hvx0r4ka65blxha5660akn9-luajit-2.1.0-beta3-env/lib/lua/5.1/lib/lousy/util.so'
        no file '/nix/store/xa7a51dw6hvx0r4ka65blxha5660akn9-luajit-2.1.0-beta3-env/share/lua/5.1/lib/lousy/util.so'
        no file '/nix/store/xa7a51dw6hvx0r4ka65blxha5660akn9-luajit-2.1.0-beta3-env/lib/lua/5.1/lib.so'
        no file '/nix/store/xa7a51dw6hvx0r4ka65blxha5660akn9-luajit-2.1.0-beta3-env/share/lua/5.1/lib.so'
stack traceback:
        [C]: in function 'require'
        build-utils/docgen/gen.lua:2: in main chunk
        [C]: in function 'require'
        ./build-utils/docgen/makedoc.lua:9: in main chunk
        [C]: at 0x00406330
make: *** [Makefile:85: doc/apidocs/index.html] Error 1
note: keeping build directory '/tmp/nix-build-luakit-2.1.drv-1'
builder for '/nix/store/dzsw6a59vsz5s2h0zipa1805qk2ny6qi-luakit-2.1.drv' failed with exit code 2
error: build of '/nix/store/dzsw6a59vsz5s2h0zipa1805qk2ny6qi-luakit-2.1.drv' failed