bazel-watcher: use apple sdk11
To fix errors like
```
In file included from __main__/external/com_github_fsnotify_fsevents/go_1_10_after.go:6:
In file included from /nix/store/pn8g2iyc0ynlvrkhi7yzbrdyixx29ay0-apple-framework-CoreServices-11.0.0/Library/Frameworks/CoreServices.framework/Headers/CoreServices.h:39:
In file included from /nix/store/pn8g2iyc0ynlvrkhi7yzbrdyixx29ay0-apple-framework-CoreServices-11.0.0/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Headers/LaunchServices.h:23:
In file included from /nix/store/pn8g2iyc0ynlvrkhi7yzbrdyixx29ay0-apple-framework-CoreServices-11.0.0/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Headers/IconsCore.h:23:
In file included from /nix/store/pn8g2iyc0ynlvrkhi7yzbrdyixx29ay0-apple-framework-CoreServices-11.0.0/Library/Frameworks/CoreServices.framework/Frameworks/OSServices.framework/Headers/OSServices.h:29:
In file included from /nix/store/pn8g2iyc0ynlvrkhi7yzbrdyixx29ay0-apple-framework-CoreServices-11.0.0/Library/Frameworks/CoreServices.framework/Frameworks/OSServices.framework/Headers/CSIdentity.h:43:
In file included from /nix/store/i3wylk33iamimjdsqdhfz4rdc0r5gnyz-apple-framework-Security-11.0.0/Library/Frameworks/Security.framework/Headers/Security.h:87:
/nix/store/i3wylk33iamimjdsqdhfz4rdc0r5gnyz-apple-framework-Security-11.0.0/Library/Frameworks/Security.framework/Headers/SecCode.h:35:10: fatal error: 'xpc/xpc.h' file not found
         ^~~~~~~~~~~
```

`bazel-watcher` is used in `bazel_{3,4,5,6}` tests and some of them fail
on darwin due to sdk version mismatch.

Extracted out from https://github.com/NixOS/nixpkgs/pull/200033
After noticing darwin failues in https://github.com/NixOS/nixpkgs/pull/203465