remove missing attribute 'cabal-helper_0_6_3_1'
$ nix-shell -p haskell.packages.ghc7103.ghc-mod -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/master.tar.gz
error: attribute ‘cabal-helper_0_6_3_1’ missing, at /nix/store/l7kr5m1h1rp16fh7d1m47caj2yj6xz4m-master.tar.gz/pkgs/development/haskell-modules/configuration-ghc-7.10.x.nix:211:53