haskell-digestive-functors-aeson: broken by update of 'text'
Jailbreaking the package makes the build succeeds, but then the test suite fails:

    Running 1 test suites...
    Test suite tests: RUNNING...
    Tests
      Pokemon tests
        Submit pokeForm with valid data:   OK
        Submit pokeForm with invalid data/check error view
          Failed validation:               OK
          jsonErrors shows correct errors: OK
      Pokedex tests
        Valid pokedex with one pokemon:    OK
        Valid pokedex with many pokemon:   OK
        Submit pokedex with a single invalid item
          Failed validation:               OK
          jsonErrors shows correct errors: FAIL
            Exception: HUnitFailure "expected: Object (fromList [(\"pokemon\",Array (fromList [Object (fromList [(\"name\",String \"Name cannot be empty\")])]))])\n but got: Object (fromList [(\"pokemon\",Array (fromList [Object (fromList [(\"name\",String \"Name cannot be empty\"),(\"number\",String \"Could not parse number\")])]))])"
        Submit pokedex with a later invalid item
          Failed validation:               OK
          jsonErrors shows correct errors: FAIL
            Exception: HUnitFailure "expected: Object (fromList [(\"pokemon\",Array (fromList [Null,Object (fromList [(\"name\",String \"Name cannot be empty\")])]))])\n but got: Object (fromList [(\"pokemon\",Array (fromList [Object (fromList [(\"number\",String \"Could not parse number\")]),Object (fromList [(\"name\",String \"Name cannot be empty\"),(\"number\",String \"Could not parse number\")])]))])"
      Top level lists:                     OK
      Booleans work:                       OK