kicad: fix build
Fix configure time error:
  ...
  ImportError: No module named wx
  CMake Error at CMakeModules/FindwxPython.cmake:52 (message):
    wxPython/Phoenix does not appear to be installed on the system

Only build tested.

Fixes: f7e28bf5d818 ("Split buildPythonPackage into setup hooks")
(cherry picked from commit 5af0d0b5da476e37630532f5122cc81e7e40e5f7)