yosys: 0.36 -> 0.37
https://github.com/YosysHQ/yosys/releases/tag/yosys-0.37

The change to the patch is needed to fix this error on macOS:
```
+ clang -std=c++11 -O2 -o cxxrtl-test-value -I../../backends/cxxrtl/runtime test_value.cc -lstdc++
test_value.cc:1:10: fatal error: 'cassert' file not found
         ^~~~~~~~~
1 error generated.
make: *** [Makefile:891: test] Error 1
```