djv: fix build against gcc-11
Without the change build fails on hydra due to `gcc` version mix
between `opencolorio` and `djv`:

    [ 51%] Linking CXX executable ../../build/bin/Render2DStressTest
    ...-binutils-2.39/bin/ld: ...-opencolorio-1.1.1/lib/libOpenColorIO.so:
      undefined reference to `std::__throw_bad_array_new_length()@GLIBCXX_3.4.29'

ZHF: https://github.com/NixOS/nixpkgs/issues/199919