chromiumBeta,chromiumDev: Mark as broken
The builds currently fail with (should work with LLVM 12 [0]):
../../base/check.h:88:3: error: 'nomerge' attribute cannot be applied to a declaration
  NOMERGE ~CheckError();
  ^       ~
../../base/compiler_specific.h:344:19: note: expanded from macro 'NOMERGE'
#define NOMERGE [[clang::nomerge]]
                  ^
1 error generated.

[0]: https://github.com/llvm/llvm-project/commit/fb0f7288051eb2745bb9211306f53ff9aa6f73e2

(cherry picked from commit 5e42fea124a2882cd6ac5e27c9827bdf97c29282)