seq66: fix build against `gcc-13`
Without the chnage build fails on `master` as:

    In file included from os/daemonize.cpp:64:
    ../include/os/daemonize.hpp:58:8: error: 'uint32_t' does not name a type
       58 | extern uint32_t daemonize
          |        ^~~~~~~~
    ../include/os/daemonize.hpp:36:1: note: 'uint32_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?
       35 | #include "seq66_platform_macros.h"      /* for detecting 32-bit builds      */
      +++ |+#include <cstdint>

As upstream changes are quite invasive for backport I am only injecting
missing headers.