haskellPackages.OrderedBits: set platforms=x86
The package doesn't support non-x86 architectures (aarch64)
```
Preprocessing library for OrderedBits-0.0.2.0..
Building library for OrderedBits-0.0.2.0..
[1 of 1] Compiling Data.Bits.Ordered ( lib/Data/Bits/Ordered.hs, dist/build/Data/Bits/Ordered.o, dist/build/Data/Bits/Ordered.dyn_o )

lib/Data/Bits/Ordered.hs:326:14: error:
    The INLINE pragma for ‘lsb’ lacks an accompanying binding
      (The INLINE pragma must be given where ‘lsb’ is declared)
    |
326 |   {-# Inline lsb  #-}
    |              ^^^
```
source code at
https://github.com/choener/OrderedBits/blob/master/lib/Data/Bits/Ordered.hs#L316

Should also avoid trying to build `PrimitiveArray` and other dependent
packages on aarch64.

ZHF: #199919