tests.kernel-config: fix
error: The option `settings.NIXOS_TEST_BOOLEAN.tristate' has conflicting definition values:
- In `structuredExtraConfig': "n"
- In `structuredExtraConfig': "y"

since https://github.com/NixOS/nixpkgs/pull/90065
yes does not silently win over no