picoscope: fix `rules` eval
Without the change `picoscope.rules` failed to evaluate due to wrong
attribute path:

    $ nix build --no-link -f. picoscope.rules
    error: attribute 'writeTextDir' missing
              116|   # users.users.you.extraGroups = [ "pico" ];
              117|   passthru.rules = lib.writeTextDir "lib/udev/rules.d/95-pico.rules" ''
                 |                    ^