Add missing include for libxml2 to gnucobol
Fixes compilation error:

    error: implicit declaration of function 'xmlCleanupParser'

(cherry picked from commit 5f224ecea266a3c04717d512fee2bd851ef69084)