groonga: 12.0.7 -> 12.1.0
Remove autoreconfHook to fix
```
checking whether the compiler supports GNU C++... yes
checking whether g++ accepts -g... yes
checking for g++ option to enable C++11 features... none needed
checking dependency style of g++... none
./configure: line 6599: syntax error near unexpected token `fi'
./configure: line 6599: `fi'
error: builder for '/nix/store/wicc0ap5yiyac5pa4dr7gjcfy7xxmzm2-groonga-12.1.0.drv' failed with exit code 2;
       last 10 log lines:
       > checking for sys/stat.h... yes
       > checking for sys/types.h... yes
       > checking for unistd.h... yes
       > checking whether byte ordering is bigendian... no
       > checking whether the compiler supports GNU C++... yes
       > checking whether g++ accepts -g... yes
       > checking for g++ option to enable C++11 features... none needed
       > checking dependency style of g++... none
       > ./configure: line 6599: syntax error near unexpected token `fi'
       > ./configure: line 6599: `fi'
       For full logs, run 'nix log /nix/store/wicc0ap5yiyac5pa4dr7gjcfy7xxmzm2-groonga-12.1.0.drv'.
```

Remove preConfigure to fix
```
building
build flags: SHELL=/nix/store/jjv9n1pac9mh10digkdkgs3h2l1l9vng-bash-5.1-p16/bin/bash
cd "." && /nix/store/jjv9n1pac9mh10digkdkgs3h2l1l9vng-bash-5.1-p16/bin/bash version-gen.sh
 cd . && /nix/store/jjv9n1pac9mh10digkdkgs3h2l1l9vng-bash-5.1-p16/bin/bash /build/groonga-12.1.0/missing automake-1.16 --foreign Makefile
/build/groonga-12.1.0/missing: line 81: automake-1.16: command not found
WARNING: 'automake-1.16' is missing on your system.
         You should only need it if you modified 'Makefile.am' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'automake' program is part of the GNU Automake package:
         <https://www.gnu.org/software/automake>
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         <https://www.gnu.org/software/autoconf>
         <https://www.gnu.org/software/m4/>
         <https://www.perl.org/>
make: *** [Makefile:553: Makefile.in] Error 127
error: builder for '/nix/store/2w9biv4363f43azz3r4vfxwifwih5giy-groonga-12.1.0.drv' failed with exit code 2;
       last 10 log lines:
       > WARNING: 'automake-1.16' is missing on your system.
       >          You should only need it if you modified 'Makefile.am' or
       >          'configure.ac' or m4 files included by 'configure.ac'.
       >          The 'automake' program is part of the GNU Automake package:
       >          <https://www.gnu.org/software/automake>
       >          It also requires GNU Autoconf, GNU m4 and Perl in order to run:
       >          <https://www.gnu.org/software/autoconf>
       >          <https://www.gnu.org/software/m4/>
       >          <https://www.perl.org/>
       > make: *** [Makefile:553: Makefile.in] Error 127
       For full logs, run 'nix log /nix/store/2w9biv4363f43azz3r4vfxwifwih5giy-groonga-12.1.0.drv'.
```