mupdf: fix build of vendored freeglut with gcc15
- add patch from `freeglut` upstream to vendored fork version:
https://www.github.com/freeglut/freeglut/pull/187

Fixes build failure with gcc15:
```
/build/source/src/x11/fg_init_x11.c:348:6: error: conflicting types for
'fgPlatformDestroyContext'; have 'void(SFG_PlatformDisplay,  struct __GLXcontextRec *)'
{aka 'void(struct tagSFG_PlatformDisplay,  struct __GLXcontextRec *)'}
  348 | void fgPlatformDestroyContext ( SFG_PlatformDisplay pDisplay, SFG_WindowContextType MContext )
      |      ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from /build/source/src/x11/fg_init_x11.c:34:
/build/source/src/egl/fg_init_egl.h:31:13: note: previous declaration of
'fgPlatformDestroyContext' with type 'void(void)'
   31 | extern void fgPlatformDestroyContext();
      |             ^~~~~~~~~~~~~~~~~~~~~~~~
```

(cherry picked from commit d933df8d01ddf3c6fdccd17039ec105fcfbd176d)