atuin: fix build on x86_64-darwin by updating to apple_sdk_11_0
Otherwise, fails to build with:

```
       >   = note: Undefined symbols for architecture x86_64:
       >             "_kCFURLVolumeAvailableCapacityForImportantUsageKey", referenced from:
       >                 sysinfo::unix::apple::disk::get_list::h5f0b9b2218314fb0 in libsysinfo-48f55e52227ea9a5.rlib(sysinfo-48f55e52227ea9a5.sysinfo.81d4345a26454b80-cgu.10.rcgu.o)
       >           ld: symbol(s) not found for architecture x86_64
       >           clang-16: error: linker command failed with exit code 1 (use -v to see invocation)
       >
       >
       > error: could not compile `atuin` (bin "atuin") due to 1 previous error
```

See #234678 for a similar fix on another package.