Revert "system-config-printer: fix python path"
This reverts commit 992dee07c6b71b5fd7bbe83d6c1ebc0ca65277de.

It breaks nixpkgs eval:

$ nix-env -f . -qa '*' --meta --xml --drv-path --show-trace
error: while querying the derivation named ‘system-config-printer-1.5.9’:
...
undefined variable ‘pysmbc’ at .../nixpkgs/pkgs/tools/misc/system-config-printer/default.nix:29:61