nixos/deviceTree: Use ufdt_apply_overlay instead of libfdt
libfdt does not provide helpful error messages when failing to apply a
devicetree overlay; it simply reports:

libfdt.FdtException: pylibfdt error -1: FDT_ERR_NOTFOUND

ufdt_apply_overlay instead provides a bit more helpful message:

ERROR: ufdt_overlay_do_fixups():Couldn't find 'foo' symbol in main dtb
ERROR: ufdt_overlay_apply():failed to perform fixups in overlay

Instead of using pylibfdt's fdt_overlay_apply, shell out to
ufdt_apply_overlay. This is a little less ideal than FFI used today, but
apply_overlays is not performance sensitive and we get much more helpful
output when things go wrong.