inkscape: fix manage extensions
Invoking "manage extensions" results in
```
ValueError: Namespace Gtk not available
```
and this requires gobject-introspection libraries.