tmuxp: 1.12.1 -> 1.23.0
tmuxp 1.12.1 depends on a libtmux where you can import which from the
library. This has been changed in libtmux, and we now need to use
shutil.which to avoid the error:

ImportError: cannot import name 'which' from 'libtmux.common'

Updating the package fixes this issue.