lxd: drop undefined `ui` attribute
From what I can see `lxd-unwrapped-lts` does not define `ui` attribute.
As a result `lxd.ui` fails the eval as:

    $ nix build --no-link -f. lxd.ui
    trace: warning: lxd has been renamed to lxd-lts
    error: attribute 'ui' missing
           at pkgs/by-name/lx/lxd-lts/package.nix:144:39:
              143|   passthru = {
              144|     inherit (lxd-unwrapped-lts) tests ui;
                 |                                       ^
              145|   };
           Did you mean one of go or out?