monitor: Fix build with Vala 0.56.18
error: Compact class `Monitor.HwmonTemperature' cannot inherit from non-compact class `GLib.Object'
(cherry picked from commit 9bb3569e1813eab98c5d36e2ac7842f0e5804689)