stdenv: run toString on lists in env to allow lists in env
will make appending to lists in env in overrideAttrs more ergonomic due
to no longer needing to add spaces manually

```
nix-repl> keepassxc.NIX_CFLAGS_COMPILE
"-Wno-old-style-cast -Wno-error -D__BIG_ENDIAN__=0"

nix-repl> (keepassxc.overrideAttrs(oA: { passthru.oA = oA; })).oA.env.NIX_CFLAGS_COMPILE
[ "-Wno-old-style-cast" "-Wno-error" "-D__BIG_ENDIAN__=0" ]

nix-repl> (keepassxc.overrideAttrs(oA: { passthru.oA = oA; })).oA.NIX_CFLAGS_COMPILE
error:
       … while evaluating the attribute 'oA.NIX_CFLAGS_COMPILE'

         at «string»:1:32:

            1| (keepassxc.overrideAttrs(oA: { passthru.oA = oA; })).oA.NIX_CFLAGS_COMPILE
             |                                ^

       error: attribute 'NIX_CFLAGS_COMPILE' missing

       at «string»:1:1:

            1| (keepassxc.overrideAttrs(oA: { passthru.oA = oA; })).oA.NIX_CFLAGS_COMPILE
             | ^
```