kiwix: mark as broken
Compiling is now emitting:

    ../common/kiwix/kiwix_serve-searcher.o: In function `kiwix::Searcher::getHtml[abi:cxx11]()':
    /tmp/nix-build-kiwix-0.9.drv-0/kiwix-0.9/src/server/../common/kiwix/searcher.cpp:142: undefined reference to `CTPP::CDT::operator[](std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
    ... snip ...
    /tmp/nix-build-kiwix-0.9.drv-0/kiwix-0.9/src/server/../common/kiwix/searcher.cpp:191: undefined reference to `CTPP::CDT::operator=(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
    /tmp/nix-build-kiwix-0.9.drv-0/kiwix-0.9/src/server/../common/kiwix/searcher.cpp:201: undefined reference to `CTPP::SimpleVM::Run(CTPP::CDT&, CTPP::VMLoader const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, CTPP::Logger&)'
    collect2: error: ld returned 1 exit status
    Makefile:506: recipe for target 'kiwix-serve' failed
    make[2]: *** [kiwix-serve] Error 1
    make[2]: Leaving directory '/tmp/nix-build-kiwix-0.9.drv-0/kiwix-0.9/src/server'
    Makefile:396: recipe for target 'all-recursive' failed
    make[1]: *** [all-recursive] Error 1
    make[1]: Leaving directory '/tmp/nix-build-kiwix-0.9.drv-0/kiwix-0.9/src'
    Makefile:456: recipe for target 'all-recursive' failed
    make: *** [all-recursive] Error 1

(cherry picked from commit 2ce26f4f94b6a80efe3a0daf448c76daaeb1b73a)