wezterm: fix `tests` eval
commit 823242c42dd "nixosTests.terminal-emulators.wezterm: drop" removed
`wezterm` test. As a result that started failing `tests` attribute eval
as:

    $ nix build --no-link -f. wezterm.tests
    error:
       error: attribute 'wezterm' missing
          127|       all-terminfo = nixosTests.allTerminfo;
          128|       terminal-emulators = nixosTests.terminal-emulators.wezterm;
             |                            ^