ci/nixpkgs-vet.sh: fix passing arguments
It currently fails with this:

```
error: lib.fileset.toSource: `root`
(/tmp/nix-shell-19054-0/tmp.MB62qzBqsj/base) is a string-like value, but
it should be a path instead.
   Paths in strings are not supported by `lib.fileset`, use
`lib.sources` or derivations instead.
```

Resolves #416175

(cherry picked from commit 36b76b41414c391e78b63cd3f07377984cd437d7)