sc68: unstable-2020-05-18 -> unstable-2021-08-23
Contains a single change to fix build on -fno-common toolchains:

    $ nix-build -E 'with import ./. {}; sc68.override { stdenv = clang12Stdenv; }'
    ...
    ld: as68-opcode.o:/build/code-r693/as68/opcode.c:2418:
      multiple definition of `opcode_table';
        as68-as68.o:/build/code-r693/as68/as68.c:72: first defined here