nixosTests.gnome-xorg: drop
The capability was really dropped in 8fa1c6d44d07.
This fixes eval:
  error: Default graphical session, 'gnome-xorg', not found.
  Valid names for 'services.displayManager.defaultSession' are:
    gnome