nixVersions.nix_2_3: fix build against current gcc
Without the change `nix_2_3` fails the build due to it's dependency
pulling in newer `libstdc++`:

    $ nix build --no-link -f. nix_2_3
    error: builder for '/nix/store/d3vqya9ka7sh4m7q53xkjrv1rzbc0qa1-nix-2.3.17.drv' failed with exit code 2;
           last 10 log lines:
           > Note: Writing nix-instantiate.1
           > Note: Writing nix-prefetch-url.1
           > Note: Writing nix.conf.5
           >   LD     src/libstore/libnixstore.so
           >   LD     src/libmain/libnixmain.so
           >   LD     src/libexpr/libnixexpr.so
           >   LD     src/nix/nix
           > /nix/store/xdqs45iclhp9dz8zz9pvn5zivjbhid1a-binutils-2.40/bin/ld: /nix/store/i3qy2bskybxz53kbi9bbz5a3ysbm8asi-aws-sdk-cpp-1.9.294/lib/libaws-cpp-sdk-transfer.so: undefined reference to `std::ios_base_library_init()@GLIBCXX_3.4.32'
           > collect2: error: ld returned 1 exit status
           > make: *** [mk/lib.mk:122: src/nix/nix] Error 1