waydroid: Add missing ambiant dependencies
Fixes #211741

`waydroid first-launch` would fail due to missing gobject introspection
bindings for Gtk.

```
(      ) [        ] ERROR: Namespace Gtk not available
(      ) [        ] See also: <https://github.com/waydroid>
(      ) [        ] Traceback (most recent call last):
  File "/nix/store/7c0jjr0jid4xhfdsv13jiwp7q4jl9khi-waydroid-1.3.3/lib/waydroid/tools/__init__.py", line 113, in main
    actions.remote_init_client(args)
  File "/nix/store/7c0jjr0jid4xhfdsv13jiwp7q4jl9khi-waydroid-1.3.3/lib/waydroid/tools/actions/initializer.py", line 205, in remote_init_client
    gi.require_version("Gtk", "3.0")
  File "/nix/store/y09awdg92zm58958q6bc6chacw35pfgm-python3.10-pygobject-3.42.2/lib/python3.10/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gtk not available
```

These changes add the necessary environment (the currently idiomatic way
to solve such problems) to the existing wrapper.

The use in `preFixup` is necessary, as the gapps wrapper will not have
ran the required hooks before.

The addition of `gobject-introspection` is necessary for the wrappers
hooks to add GIR repositories to the wrapper args.