evcxr: flip back from `mold` to `mold-unwrapped`
With recent default change of `mold` to wrappper
`evcxr` started failing as:

```
$ echo 42 | nix run -f. evcxr
Welcome to evcxr. For help, type :help
Error: Compilation failed, but no parsable errors were found. STDERR:
mold: fatal: unknown command line option: -run

STDOUT:

```

The change fixes `evcxr` for me:

```
$ echo 42 | nix run -f. evcxr
Welcome to evcxr. For help, type :help
42
```