Revert "trivial: make pkgs.writeText always fixed output"
This reverts commit 9f4b1064c6c9464194eb47cca6f2f42bdbd5c6da.

It caused problems: https://github.com/NixOS/nixpkgs/pull/318872#issuecomment-2196168990

FODs are not allowed to have references, but writeText is often used to create a file with references.

Leading to this error:

error: fixed output derivation 'packages.json' is not allowed to refer to other store paths.