mumble: Fix 32-bit build
32-bit builds fail due to the following error. Apply a patch from master
to fix the issue.

[ 25%] Building CXX object plugins/gtav/CMakeFiles/gtav.dir/gtav.cpp.o
In file included from /build/source/plugins/gtav/Game.h:9,
                 from /build/source/plugins/gtav/gtav.cpp:6:
/build/source/plugins/gtav/structs.h:218:37: error: static assertion failed
  218 | static_assert(sizeof(CCameraAngles) == 0x408, "");
      |               ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
/build/source/plugins/gtav/structs.h:218:37: note: the comparison reduces to '(1028 == 1032)'

Signed-off-by: Felix Singer <felixsinger@posteo.net>