Fix metrics job
It was failing because the pager wasn't set, causing the message

  error: executing '': No such file or directory

to pollute the JSON output.

https://hydra.nixos.org/build/154768851

Issue #76776.