nixos/karakeep: use freeformType for extraEnvironment, refactor
DATA_DIR is protected as it is set to read-only:

error: The option `nodes.karakeep_server.services.karakeep.extraEnvironment.DATA_DIR' is read-only, but it's set multiple times. Definition values:
- In `/nix/store/AAA-source/nixos/modules/services/web-apps/karakeep.nix': "/var/lib/karakeep"
- In `/nix/store/AAA-source/nixos/tests/web-apps/karakeep.nix': "/something/else"

environmentFile is now deprecated properly, it gives a warning but still works (by turning the value into a list and assigning to environmentFiles):

evaluation warning: The option `services.karakeep.environmentFile' defined in `/nix/store/AAA-source/nixos/tests/web-apps/karakeep.nix' has been changed to `services.karakeep.environmentFiles' that has a different type. Please read `services.karakeep.environmentFiles' documentation and update your configuration accordingly.