Revert "release: disallow aliases"
This reverts commit 25c42e7736d0507fd23fb5375a9282f528cc843f.

This commit is still causing evaluation errors (despite passing
OfBorg!)

Here is the current error:

error: undefined variable 'Log4Perl' at
/nix/store/n0gwyv3mcvm3hc9jrmkxjhmsrdjqzcqb-source/maintainers/scripts/nix-generate-from-cpan.nix:7:71

More investigation is needed

/cc @volth