nixpkgs-plugin-update: disable updateScript passthru
Causes error when running maintainer scripts for updating for a specific
maintainer.

"/nix/store/w35a8nwnl6vbrs7xf072iz4h0bzd9lrs-nix-update-1.14.0/lib/python3.13/site-packages/nix_update/update.py",
line 78, in fetch_new_version
    raise UpdateError(msg)
nix_update.errors.UpdateError: Could not find a url in the derivations
src attribute

Signed-off-by: Austin Horstman <khaneliman12@gmail.com>