top-level: Ignore Emacs lock files when looking for overlays
While an Emacs user edits a file foo.nix, Emacs creates a lock file
.#foo.nix as a broken symlink to USER@HOSTNAME.PID:TIMESTAMP.

https://www.gnu.org/software/emacs/manual/html_node/emacs/Interlocking.html

If the file is in the overlays directory, this breaks all nixpkgs
imports with this error, until the user saves the file:

error: getting status of '/home/user/.config/nixpkgs/overlays/user@hostname.683628:1654370645': No such file or directory

Fix this by ignoring filenames beginning with .# in overlay
directories.

Signed-off-by: Anders Kaseorg <andersk@mit.edu>