ofono: fix digest
Without the change build of `ofono` on `staging-next` fails as:

    $ nix build --no-link -f. ofono.src
    error: hash mismatch in fixed-output derivation '/nix/store/yjggdjyrczbm1mc73zd31l0v0nzcmrl9-source.drv':
             specified: sha256-GxQfh/ps5oM9G6B1EVgnjo8LqHD1hMqdnju1PCQq3kA=
                got:    sha256-mnh0qzmgPDfimN/M33HntYj90Xcgc/uF8tKbzeQV1Yg=

I think it started after merge conflict fix.