lib/types.nix: allow CA paths in `pathInStore`
Without the change an attempt to build `nixos` with
`contentAddressedByDefault` fails as:

    $ nix build -f. nixosTests.switchTest
       error: A definition for option `nodes.machine.system.preSwitchChecksScript' is not of type `path in the Nix store'. Definition values:
       - In `/tmp/nixpkgs/nixos/modules/system/activation/pre-switch-check.nix': "/0zp3kfip3vypj8im8wr8w3yay8vid9gsghhnahc539gjj7y7js3s/bin/pre-switch-checks"

This happens because CA paths in `nix` do not have
a `/nix/store` prefix.

The fix accounts for that by leading allowing hash regex.