guile-lib: Disable a test which doesn't work with Guile 2.2
Error is:

    ERROR: In procedure %resolve-variable:
    ERROR: Unbound variable: use-syntax
    FAIL: sxml.ssax.scm

Also add pkg-config so that configure script can find libguile.

Relevant to #28643

(cherry picked from commit 913e770fa819fe8a9395bac30c8c796b944bc2fe)