as31: fix src and meta.homepage
- change `src` to debian mirror (hash did not change), because previous
url requires auth now:
```
nix-build -A as31.src --check
trying http://wiki.erazor-zone.de/_media/wiki:projects:linux:as31:as31-2.3.1.tar.gz
...
curl: (22) The requested URL returned error: 401
error: cannot download as31-2.3.1.tar.gz from any mirror
```

- change `meta.homepage` because previous url requires auth now:
```
curl "http://wiki.erazor-zone.de/wiki:projects:linux:as31" -v
...
< HTTP/1.1 401 Unauthorized
```