arduino-cli: avoid creating temp files for completions
We still need to set HOME or we get

Error: invalid path creating config dir: /homeless-shelter/.arduino15 error: mkdir /homeless-shelter: permission denied