distrobuilder.tests: update `incus.container` reference
Without the change the test build attempt fails the evaluation as:

    $ nix build --no-link -f. distrobuilder.tests.incus

       error: attribute 'container' missing

       at pkgs/tools/virtualization/distrobuilder/default.nix:54:19:

           53|   passthru = {
           54|     tests.incus = nixosTests.incus.container;
             |                   ^

This started happening after `container` test was split in two in
c607e70f7053 "nixosTests.incus: add test with old and new init".