fix(banana-accounting): add missing libgcrypt
without this, i get the following error:

```
error: builder for '/nix/store/a0fl7p3rx5fbmkikl3mjs4680z0r6lc0-banana-accounting-10.0.12.drv' failed with exit code 1;
     last 10 log lines:
     >     libGL.so.1 -> found: /nix/store/rrfg0czyi7c4g3b69xhxxkr1ihprjs1x-libGL-1.6.0/lib
     >     libstdc++.so.6 -> found: /nix/store/wvm2hvqdbbsp1f11463mrw8nyv678ipm-gcc-12.2.0-lib/lib
     > setting RPATH to: /nix/store/fwng8id6j9j0nmwvyj9qgphqkbafm2n5-banana-accounting-10.0.12/usr/lib:/nix/store/rrfg0czyi7c4g3b69xhxxkr1ihprjs1x-libGL-1.6.0/lib:/nix/store/wvm2hvqdbbsp1f11463mrw8nyv678ipm-gcc-12.2.0-lib/lib
     > auto-patchelf: 1 dependencies could not be satisfied
     > error: auto-patchelf could not satisfy dependency libgpg-error.so.0 wanted by /nix/store/fwng8id6j9j0nmwvyj9qgphqkbafm2n5-banana-accounting-10.0.12/usr/lib/libgcrypt.so.20
     > auto-patchelf failed to find all the required dependencies.
     > Add the missing dependencies to --libs or use `--ignore-missing="foo.so.1 bar.so etc.so"`.
     > /nix/store/pw17yc3mwmsci4jygwalj8ppg0drz31v-stdenv-linux/setup: line 79: pop_var_context: head of shell_variables not a function context
     > /nix/store/pw17yc3mwmsci4jygwalj8ppg0drz31v-stdenv-linux/setup: line 1456: pop_var_context: head of shell_variables not a function context
     > /nix/store/pw17yc3mwmsci4jygwalj8ppg0drz31v-stdenv-linux/setup: line 1593: pop_var_context: head of shell_variables not a function context
     For full logs, run 'nix log /nix/store/a0fl7p3rx5fbmkikl3mjs4680z0r6lc0-banana-accounting-10.0.12.drv'.
```