dogtail: remove issue 56943 workaround
and fix double wrapping

it still fails to launch though but its not a regression

$ ./result/bin/dogtail-logout
Traceback (most recent call last):
  File "/nix/store/az8mw2pmhbwlm08176wd62hn0hfzwv8s-python3.10-dogtail-0.9.11/bin/.dogtail-logout-wrapped", line 8, in <module>
    from dogtail.tree import *
  File "/nix/store/az8mw2pmhbwlm08176wd62hn0hfzwv8s-python3.10-dogtail-0.9.11/lib/python3.10/site-packages/dogtail/tree.py", line 5, in <module>
    from dogtail import predicate
  File "/nix/store/az8mw2pmhbwlm08176wd62hn0hfzwv8s-python3.10-dogtail-0.9.11/lib/python3.10/site-packages/dogtail/predicate.py", line 6, in <module>
    from gi.repository import GLib
ModuleNotFoundError: No module named 'gi'