TODO: speech-provider-piper: init at 0.1.0
Does not currently build, will need to study https://github.com/pykeio/ort/blob/main/ort-sys/build.rs:

    error: failed to run custom build command for `ort-sys v2.0.0-rc.2`

    Caused by:
      process didn't exit successfully: `/build/source/build/target/release/build/ort-sys-fcf0b453ef8b63ea/build-script-build` (exit status: 101)
      --- stdout
      cargo:rerun-if-env-changed=ORT_LIB_LOCATION
      cargo:rerun-if-env-changed=ORT_LIB_PROFILE

      --- stderr
      thread 'main' panicked at /build/cargo-vendor-dir/ort-sys-2.0.0-rc.2/build.rs:25:31:
      Failed to GET `https://parcel.pyke.io/v2/delivery/ortrs/packages/msort-binary/1.17.3/ortrs-msort_static-v1.17.3-x86_64-unknown-linux-gnu.tgz`: https://parcel.pyke.io/v2/delivery/ortrs/packages/msort-binary/1.17.3/ortrs-msort_static-v1.17.3-x86_64-unknown-linux-gnu.tgz: Dns Failed: resolve dns name 'parcel.pyke.io:443': failed to lookup address information: Temporary failure in name resolution
      note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
    warning: build failed, waiting for other jobs to finish...
    Traceback (most recent call last):
      File "/build/source/cargo.py", line 21, in <module>
        shutil.copy2(os.path.join(CARGO_TARGET_DIR, 'release', APP_BIN), OUTPUT)
      File "/nix/store/c9m6yd8fg1flz2j5r4bif1ib5j20a0cy-python3-3.12.8/lib/python3.12/shutil.py", line 475, in copy2
        copyfile(src, dst, follow_symlinks=follow_symlinks)
      File "/nix/store/c9m6yd8fg1flz2j5r4bif1ib5j20a0cy-python3-3.12.8/lib/python3.12/shutil.py", line 260, in copyfile
        with open(src, 'rb') as fsrc:
             ^^^^^^^^^^^^^^^
    FileNotFoundError: [Errno 2] No such file or directory: '/build/source/build/target/release/speech-provider-piper'

https://github.com/project-spiel/speech-provider-piper