nodePackages.ijavascript: drop
It fails to build with

    npm error /nix/store/bhc0grw1nwzwgh55qapfqwb3vil5s49y-node-sources/deps/v8/include/v8-local-handle.h: In instantiation of 'v8::Local<T>::Local(v8::Local<S>) [with S = v8::Data; T = v8::Value]':
    npm error ../../nan/nan_callbacks_12_inl.h:175:53:   required from here
    npm error   175 |       cbinfo(info, obj->GetInternalField(kDataIndex));
    npm error       |                                                     ^
    npm error /nix/store/bhc0grw1nwzwgh55qapfqwb3vil5s49y-node-sources/deps/v8/include/v8-local-handle.h:269:42: error: static assertion failed: type check
    npm error   269 |     static_assert(std::is_base_of<T, S>::value, "type check");
    npm error       |                                          ^~~~~
    npm error /nix/store/bhc0grw1nwzwgh55qapfqwb3vil5s49y-node-sources/deps/v8/include/v8-local-handle.h:269:42: note: 'std::integral_constant<bool, false>::value' evaluates to false