edk2: pull upstream brotli fix for gcc-11
Before the patch build on gcc-11 failed as:

    $ nix build --impure --expr 'with import <nixpkgs> {}; edk2.override { stdenv = gcc11Stdenv; }'
    brotli/c/dec/decode.c:2034:14: error:
      argument 4 of type 'uint8_t *' {aka 'unsigned char *'} declared as a pointer [-Werror=vla-parameter]
      2034 |     uint8_t* decoded_buffer) {
           |     ~~~~~~~~~^~~~~~~~~~~~~~

While at it switched to fetchFromGitHub.