python3Packages.influxdb: disable failing test
FAILED influxdb/tests/dataframe_client_test.py::TestDataFrameClient::test_write_points_from_dataframe_with_tag_escaped - FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.