nixUnstable: 2.4pre20200719_a79b6dd -> 2.4pre20200721_ff314f1
Fixes errors like this for me:

```
error: --- Error ------------------------------- nix-build
Nix daemon out of memory
(use '--show-trace' to show detailed location information)
```

(cherry picked from commit 85819d4bbf71c3f067234969e58248687fbfad88)