buildbot: 1.2.0 -> 1.4.0
buildbot was always broken on release-18.09 due to failing tests

One of the failures is:

[ERROR]
Traceback (most recent call last):
  File "/build/buildbot-1.2.0/buildbot/process/properties.py", line 459, in getRenderingFor
    rv = yield build.render(value[index])
  File "/nix/store/sqr3s9cva7r3z12hqb6rxw3w8kiqzmhd-python2.7-Twisted-18.7.0/lib/python2.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/build/buildbot-1.2.0/buildbot/process/properties.py", line 495, in getRenderingFor
    raise KeyError(error_message)
exceptions.KeyError: "secrets service not started, need to configure SecretManager in c['services'] to use 'secrets'in Interpolate"

buildbot.test.unit.test_master.StartupAndReconfig.test_reconfigService_db_url_changed

There is a mention of this at https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=907687
Because buildbot was never working before, we can just bump the version
to the one which passes the test.

(cherry picked from commit 71c42462ab71811bfacb65e89541846fe8c97e0a)