rlaunch: fix build on aarch64-linux
Fixes "error[E0308]: mismatched types; expected `u8`, found `i8`" on aarch64

(cherry picked from commit e48d21ab76b3329dd9ee4e702646c6f941617453)