fix(protonvpn-cli): protonvpn-cli depends on dbus-python
protonvpn-cli does not work without dbus-python. This adds the
dependency. Without this patch:

```
$ protonvpn-cli status
Traceback (most recent call last):
  File "/nix/store/4lyfsgv6ik3i8d861fds7bc5s4hnqyfw-protonvpn-cli-3.11.1/bin/.protonvpn-cli-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/4lyfsgv6ik3i8d861fds7bc5s4hnqyfw-protonvpn-cli-3.11.1/lib/python3.9/site-packages/protonvpn_cli/main.py", line 21, in main
    ProtonVPNCLI()
  File "/nix/store/4lyfsgv6ik3i8d861fds7bc5s4hnqyfw-protonvpn-cli-3.11.1/lib/python3.9/site-packages/protonvpn_cli/cli.py", line 65, in __init__
    res = getattr(self, args.command)()
  File "/nix/store/4lyfsgv6ik3i8d861fds7bc5s4hnqyfw-protonvpn-cli-3.11.1/lib/python3.9/site-packages/protonvpn_cli/cli.py", line 174, in status
    return self.cli_wrapper.status()
  File "/nix/store/4lyfsgv6ik3i8d861fds7bc5s4hnqyfw-protonvpn-cli-3.11.1/lib/python3.9/site-packages/protonvpn_cli/cli_wrapper.py", line 857, in status
    if not self.protonvpn.get_active_protonvpn_connection():
  File "/nix/store/1jhp3mgs9f21nrgb58gy3qg7gjrqq44v-python3.9-protonvpn-nm-lib-3.9.0/lib/python3.9/site-packages/protonvpn_nm_lib/api.py", line 407, in get_active_protonvpn_connection
    return self._env.connection_backend\
  File "/nix/store/1jhp3mgs9f21nrgb58gy3qg7gjrqq44v-python3.9-protonvpn-nm-lib-3.9.0/lib/python3.9/site-packages/protonvpn_nm_lib/core/environment.py", line 43, in connection_backend
    from .connection_backend import ConnectionBackend
  File "/nix/store/1jhp3mgs9f21nrgb58gy3qg7gjrqq44v-python3.9-protonvpn-nm-lib-3.9.0/lib/python3.9/site-packages/protonvpn_nm_lib/core/connection_backend/__init__.py", line 1, in <module>
    from .nm_client import nm_client # noqa
  File "/nix/store/1jhp3mgs9f21nrgb58gy3qg7gjrqq44v-python3.9-protonvpn-nm-lib-3.9.0/lib/python3.9/site-packages/protonvpn_nm_lib/core/connection_backend/nm_client/nm_client.py", line 3, in <module>
    from dbus.mainloop.glib import DBusGMainLoop
ModuleNotFoundError: No module named 'dbus'
```