error message honores nested dots in attribute path elements
while using submodules we encountered that if the value is used but was not assigned
one would see this incorrect error message:

  error: The option `nixcloud.TLS.certs.example.com.mode' is used but not defined.

this patch fixes it to:

  error: The option `nixcloud.TLS.certs."example.com".mode' is used but not defined.

please also backport to 18.03