cvise: fix tarball hash
Without the change the re-fetch of original source fails as:

```
$ nix build --no-link -f. cvise.src --rebuild
error: hash mismatch in fixed-output derivation '/nix/store/rd0vycm33x3hfwsa6iljj1229f9035am-source.drv':
         specified: sha256-UaWOHjgTiSVvpKKw6VFAeRAYkYp4y0Dnamzr7yhH0vQ=
            got:    sha256-ObnhFe7hAKUoUxNJ+9jo0Q4AE6jQqDgI1Ta/jsumqpI=
```

This happens because the `github` tarball generation is dependent on
abbreviated hash length of `cvise` source:

```
$ diffoscope before/ after/
--- before/
+++ after/
│   --- before/CMakeLists.txt
├── +++ after/CMakeLists.txt
│ @@ -84,15 +84,15 @@
│
│  # Determine the short git hash for the source tree.
│  #
│  ## METHOD 1: The source tree is the result of `git archive'.
│  # `git archive' inserts the abbreviated hash of the archive's commit into this
│  # file.  (See the `.gitattributes' file.)
│  #
│ -set(GIT_HASH "2d0889e7")
│ +set(GIT_HASH "2d0889e73")
```

Intially noticed the hash instability when enabled
`config.fetchedSourceNameDefault` locally. Ideally the upstream tarball
should be fixed by https://github.com/marxin/cvise/pull/506.
Meanwhile let's update the hash.