python2Packages.numcodes: disable for python2
setup.py no longer compatible with python2
```
    File "setup.py", line 48
      print('[numcodecs]', *msg, **kwargs)
                           ^
  SyntaxError: invalid syntax
```