ghc: Fix build for mingw cross target
Trying to build `pkgsCross.mingwW64.haskellPackages.hakyll`,
the `terminfo` package within `ghc` would fail to build with:

    fatal error: term.h: No such file or directory
    #include "term.h"

But after making the `--with-curses-libraries` configure flag
conditional on `enableTerminfo`, it would fail with in stage1:

    configure: error: in `/build/ghc-9.2.7/libraries/terminfo/dist-boot/build':
    configure: error: curses library not found, so this package cannot be built

I thought it is because GHC will build `terminfo` for stage0 when host is not windows
https://github.com/ghc/ghc/blob/ghc-9.4.5-release/ghc.mk#L430-L432
and it is actually `linux` here:

    GHC build  : x86_64-unknown-linux
    GHC host   : x86_64-unknown-linux
    GHC target : x86_64-unknown-mingw32
    LLVM target: x86_64-unknown-windows

but it looks like it the condition is on target for stage1
https://github.com/ghc/ghc/blob/ghc-9.4.5-release/ghc.mk#L473-L475
https://github.com/ghc/ghc/blob/ghc-9.4.5-release/mk/config.mk.in#L102-L103