pythonPackages.infoqscraper: drop
It's broken on both master and release-20.09 with
    ImportError: No module named pkg_resources
so it's safe to assume nobody is using it.