srb2: patch missing libGLU dependency
Fixes the following error:

hwOpen of libGLU.so.1: Failed loading libGLU.so.1: libGLU.so.1: cannot
open shared object file: No such file or directory

ERROR: Could not load GLU Library: libGLU.so.1