dozenal: disable parallel build
Parallel build fails for missing dependencies in subdirectories:

    ../doz/doz.c:39:10: fatal error: conv.h: No such file or directory
       39 | #include "conv.h"
          |          ^~~~~~~~

Let's explicitly disable parallelism until upstream fixes it.