whipper: Fix typelib error
`ImportError: cannot import name GLib, introspection typelib not found`

(cherry picked from commit b75575e178906486edb72c05ad0e65c45ca7a215)