gettext: Update to upstream minor ver 0.18.3.2.
This fixes errors in conjunction with gnulib, for example:

error: expected '=', ',', ';', 'asm' or '__attribute__' before
'gl_msvc_invalid_parameter_handler'
gl_msvc_invalid_parameter_handler (const wchar_t *expression,
error: 'gl_msvc_invalid_parameter_handler' undeclared (first use in this
function)

Not sure whether it makes sense to jump to version 0.19.x, but for now
I'm avoiding that to ensure we don't break unrelated stuff.

Signed-off-by: aszlig <aszlig@redmoonstudios.org>