fig2dev: fix build with gcc15
- add patch from merged upstream commit:
https://sourceforge.net/p/mcj/fig2dev/ci/ab4eee3cf0d0c1d861d64b9569a5d1497800cae2
(fetchpatch is from gentoo because of upstream hosting on sourceforge)

Fixes build failure with gcc15:
```
transfig.c:140:26: error: too many arguments to function 'str2lang'; expected 0, have 1
  140 |                 tolang = str2lang(optarg);
      |                          ^~~~~~~~ ~~~~~~
transfig.h:63:22: note: declared here
   63 | extern enum language str2lang();
      |                      ^~~~~~~~
transfig.c:171:13: error: too many arguments to function 'parse_arg'; expected 0, have 6
  171 |         a = parse_arg(tolang, arg_f, arg_s, arg_m, arg_o, argv[optind]);
      |             ^~~~~~~~~ ~~~~~~
transfig.c:36:11: note: declared here
   36 | argument *parse_arg(), *arglist = NULL, *lastarg = NULL;
      |           ^~~~~~~~~
transfig.c:259:7: error: too many arguments to function 'strip'; expected 0, have 2
  259 |   if (strip(arg, ".pic"))
      |       ^~~~~ ~~~
transfig.c:37:7: note: declared here
   37 | char *strip();
      |       ^~~~~
transfig.c:261:19: error: too many arguments to function 'mksuff'; expected 0, have 2
  261 |         a->name = mksuff(arg, "");
      |                   ^~~~~~ ~~~
transfig.h:67:24: note: declared here
   67 | extern char *sysls(), *mksuff();
      |                        ^~~~~~
```