cups-bjnp: ignore unused variable
Without this compiler flag, the build fails with:

> bjnp-utils.c: In function 'get_address_info':
> bjnp-utils.c:90:8: error: unused variable 'tmp_addr'
>    90 |   char tmp_addr[BJNP_HOST_MAX];
>       |        ^~~~~~~~