edmarketconnector: init at 5.13.1
- `EDMarketConnector` repository: https://github.com/EDCD/EDMarketConnector

From project's description:
Downloads commodity market and other station data from the game
Elite: Dangerous for use with all popular online and offline trading tools.

It's a helper tool for the game Elite: Dangerous. Since the in game
tools for trading and searching aren't that good the community has to
make their own. This tool pulls the information from game and uploads it
to various databases for other players to use.

- A test for the watchdog python package had to be disabled

The test basically always resulted in a `Too many open files` error:

```
       > ===End Flaky Test Report===
       > =========================== short test summary info ============================
       > FAILED tests/test_inotify_c.py::test_select_fd - OSError: [Errno 24] Too many open files: '/build/pytest-of-nixbld/pytest-0/test_select_fd0/new_file'
       > =========== 1 failed, 162 passed, 3 skipped, 3 deselected in 54.29s ============
```

See https://github.com/gorakhargosh/watchdog/issues/1095

(cherry picked from commit 9d1654b9816a582b84a4965b962b8091d5c69106)