lean4: 4.30.0 -> 4.31.0
As https://github.com/leanprover/lean4/pull/13196 has landed upstream,
it appears that we no longer need to patch CMakeLists.txt for
mimalloc.

We also patch ProofWidgets to build all submodules. Without this,
building leanPackages.mathlib fails:

```
✖ [280/8555] Building ProofWidgets.Component.RefreshComponent
error: permission denied (error code: 13)
  file: /nix/store/pc6dfbfi22wm8ijv8lnwidwxcwwn56f6-lean4-proofwidgets-0.0.102-unstable-2026-06-15/.lake/build/ir/ProofWidgets/Component/RefreshComponent.setup.json
```

Co-authored-by: Anthony Wang <a@unnamed.website>