onnxruntime: never treat warnings as fatal
onnxruntime is currently failing on staging with:

```
/build/source/onnxruntime/test/ir/graph_test.cc:253:26: error: 'void google::protobuf::RepeatedField< <template-parameter-1-1> >::Resize(int, const Element&) [with Element = long int]' is deprecated [-Werror=deprecated-declarations]
  253 |   m_indicies_data->Resize(static_cast<int>(indices.size()), 0);
      |   ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- snip --
/build/source/onnxruntime/test/ir/graph_test.cc:257:16: error: 'void google::protobuf::RepeatedField< <template-parameter-1-1> >::Resize(int, const Element&) [with Element = long int]' is deprecated [-Werror=deprecated-declarations]
      |   ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

This is one of several cases of onnxruntime having broken on library
updates. This also occured in
https://github.com/NixOS/nixpkgs/commit/d54a79262512ba6e0b163e9a4a3fdd4bfdc7d744,
where we introduced a messy workaround by patching the library. We
believe this was a mistake.

In general, -Werror is highly susceptible to changes in libraries,
compilers, and other components. In Nixpkgs, we often move faster than
upstream, and that is extremely wont to cause breakage. Packages often
use warnings like deprecations to inform packages of changes in a
non-breaking way, but we are not able to meaningfully respond in
Nixpkgs. We can either just ignore the warnings, or patch away the
issues. The latter seems like a great deal of work for a
constantly-moving target (like the commit linked above), and provides
questionable utility.

Thus, we simply promote `--compile-no-warning-as-error` from being
CUDA-only to applying in all cases. This fixes the build failure on
staging as a side-effect of cleaning up this issue.

Alternatively, we could just use `-Wno-error=deprecated-declarations` or
patch, but we believe this is a more correct solution.