ansible-lint: Unset PYTHONPATH in wrapper
There seems to be a weird interaction between PYTHONPATH and the
explicitly set Python search paths with site.addsitedir. Since
ruamel.yaml updated to 0.17.32, ansible-lint errors with the following
error: ModuleNotFoundError: No module named 'ruamel.yaml'

By unsetting the PYTHONPATH, this mitigates the issue, though a more
thorough fix is still needed.