pythonPackages.pylint: add setuptools
Previously it was missing a runtime dependency on setuptools:

    [kier@saelli:~/checkouts/nixpkgs]$ $(nix-build -A python27Packages.pylint --no-out-link)/bin/pylint
    Traceback (most recent call last):
      File "/nix/store/0k8h6n6nxjcs2j5jp54mfppjbx37hrrg-python2.7-pylint-1.9.5/bin/.pylint-wrapped", line 6, in <module>
        from pylint import run_pylint
      File "/nix/store/0k8h6n6nxjcs2j5jp54mfppjbx37hrrg-python2.7-pylint-1.9.5/lib/python2.7/site-packages/pylint/__init__.py", line 11, in <module>
        from .__pkginfo__ import version as __version__
      File "/nix/store/0k8h6n6nxjcs2j5jp54mfppjbx37hrrg-python2.7-pylint-1.9.5/lib/python2.7/site-packages/pylint/__pkginfo__.py", line 25, in <module>
        from pkg_resources import parse_version
    ImportError: No module named pkg_resources

With this change, the same command now correctly prints pylint's help text.

This only applies to Python 2.