callCabal2nix: detect invalid names and print a good error
A friend used an invalid haskell package name, which resulted in a very
bad error message from callCabal2nix, on account of them calling
`cabal init` from their project directory, `bad_name`, which generated a
`bad-name.cabal` file. They didn't notice and did something like
`callCabal2nix "bad_name" ./. {};` in their overlay, generating an
*atrocious* error message on the file not existing:

```
building '/nix/store/00000000000000000000000000000000-cabal2nix-bad_name.drv'...
installing
cabal2nix: nix-prefetch-url: createProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
builder for '/nix/store/00000000000000000000000000000000-cabal2nix-bad_name.drv' failed with exit code 1
error: build of '/nix/store/00000000000000000000000000000000-cabal2nix-bad_name.drv' failed
```

We can and should detect this and throw an assertion explaining what
went wrong on our side.