python3Packages.libpcap: fix build
It previously failed with

    OSError: /nix/store/0vzyp6v62bwlr70xr36iwpsxfsc6jvgq-libpcap-1.10.5/lib/libpcap.so: cannot open shared object file: No such file or directory

because da89a2d075f2279a09585c1b217b8f7382817339 introduced a lib output.