actual-server: use the same version of Node.js everywhere
This fixes nixosTests.actual which is currently failing with

    Error: /nix/store/l632q16pynl84bqqjsmf4mmrp03hhscg-actual-server-25.12.0/lib/actual/node_modules/better-sqlite3/build/Release/better_sqlite3.node: undefined symbol: _ZN2v86String9Utf8ValueC1EPNS_7IsolateENS_5LocalINS_5ValueEEENS0_12WriteOptionsE