smuxi: fix build
This fixes the build error:

    Running aclocal -I m4  ...
    configure.ac:117: warning: macro 'AM_GNU_GETTEXT' not found in library
    configure.ac:118: warning: macro 'AM_GNU_GETTEXT_VERSION' not found in library
    ...
    configure.ac:762: the top level
    configure.ac:117: error: possibly undefined macro: AM_GNU_GETTEXT
    	  If this token and others are legitimate, please use m4_pattern_allow.
    	  See the Autoconf documentation.
    configure.ac:118: error: possibly undefined macro: AM_GNU_GETTEXT_VERSION
    ...
    checking for XML::Parser... ok
    ./configure: line 3892: syntax error near unexpected token `external'
    ./configure: line 3892: `AM_GNU_GETTEXT(external)'
    error: Cannot build '/nix/store/y3jqbgi6415mbkjh0102ip693hhxgy0l-smuxi-unstable-2024-04-14.drv'.
    	   Reason: builder failed with exit code 2.

Which is caused by the gettext package to no longer automatically
include the macro that smuxi requires during aclocal. Thus we simply
pass the gettext macro path to autogen.sh

(cherry picked from commit 861954158bcb2dc9a73ad23b727e10c0ee5c7183)