gnome.gnome-shell: 44.beta → 44.rc
https://gitlab.gnome.org/GNOME/gnome-shell/-/compare/44.beta...44.rc

Since we disabled tests in mutter, we need to do it here as well to avoid:

    ERROR: Dependency "libmutter-test-12" not found, tried pkgconfig

Changelog-Reviewed-By: Jan Tojnar <jtojnar@gmail.com>