nixos-rebuild-ng: do not handle build exceptions in re-exec
Classic `nixos-rebuild` bails-out if re-exec fails, but
`nixos-rebuild-ng` tries to keep going. The problem this is causing is
that failures in re-exec evaluation almost always are errors in the user
configuration, for example:

```diff
diff --git i/modules/nixos/default.nix w/modules/nixos/default.nix
index 1d8ef762..cb7e2c9d 100644
--- i/modules/nixos/default.nix
+++ w/modules/nixos/default.nix
@@ -11,6 +11,6 @@
     ./nix
     ./server
     ./system
-    ./window-manager
+    ./window-manager;
   ];
 }
```

And if you try to run, you get the following output:

```
$ nixos-rebuild switch
warning: Git tree '/etc/nixos' is dirty
error:
       … while calling the 'seq' builtin
         at /nix/store/9v6qa656sq3xc58vkxslqy646p0ajj61-source/lib/modules.nix:361:18:
          360|         options = checked options;
          361|         config = checked (removeAttrs config [ "_module" ]);
             |                  ^
          362|         _module = checked (config._module);

       … while evaluating a branch condition
         at /nix/store/9v6qa656sq3xc58vkxslqy646p0ajj61-source/lib/modules.nix:297:9:
          296|       checkUnmatched =
          297|         if config._module.check && config._module.freeformType == null && merged.unmatchedDefns != [ ] then
             |         ^
          298|           let

       (stack trace truncated; use '--show-trace' to show the full, detailed trace)

       error: syntax error, unexpected ';'
       at /nix/store/c7zc5zg8c2hfnk7ihxaq574c83kjqav3-source/modules/nixos/default.nix:14:21:
           13|     ./system
           14|     ./window-manager;
             |                     ^
           15|   ];
warning: could not build a newer version of nixos-rebuild, using current version
building the system configuration...
warning: Git tree '/etc/nixos' is dirty
error:
       … while calling the 'seq' builtin
         at /nix/store/9v6qa656sq3xc58vkxslqy646p0ajj61-source/lib/modules.nix:361:18:
          360|         options = checked options;
          361|         config = checked (removeAttrs config [ "_module" ]);
             |                  ^
          362|         _module = checked (config._module);

       … while evaluating a branch condition
         at /nix/store/9v6qa656sq3xc58vkxslqy646p0ajj61-source/lib/modules.nix:297:9:
          296|       checkUnmatched =
          297|         if config._module.check && config._module.freeformType == null && merged.unmatchedDefns != [ ] then
             |         ^
          298|           let

       (stack trace truncated; use '--show-trace' to show the full, detailed trace)

       error: syntax error, unexpected ';'
       at /nix/store/c7zc5zg8c2hfnk7ihxaq574c83kjqav3-source/modules/nixos/default.nix:14:21:
           13|     ./system
           14|     ./window-manager;
             |                     ^
           15|   ];
Command 'nix --extra-experimental-features 'nix-command flakes' build --print-out-paths '/etc/nixos#nixosConfigurations."blackrockshooter-nixos".config.system.build.toplevel' --no-link' returned non-zero exit status 1.
```

The error is printed twice because we first try to eval (and fail) for
re-exec and since we keep going the actual build also fails. Since
classic `nixos-rebuild` bails out in the re-exec eval failure, it should
be safe to not handle the exception here.