nixos/readeck: copy config file to mutable place
To prevent this failure:

```
ERROR: open /nix/store/...-readeck.toml: read-only file system
```

(cherry picked from commit af11c3d0c8cf6feca5003a595792163c60fd4446)