haskell-network_2_6_3_1: disable test suite
The package is missing required files for the test suite. This fixes the
following build error:

```
  Building test suite 'regression' for network-2.6.3.1..
  [1 of 1] Compiling Main             ( tests/Regression.hs,
dist/build/regression/regression-tmp/Main.o )

  tests/Regression.hs:12:1: error:
      Could not find module ‘Regression.Issue215’
      Use -v (or `:set -v` in ghci) to see a list of the files searched
for.
     |
  12 | import qualified Regression.Issue215 as Issue215
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```