python3.pkgs.django-haystack: propagate packaging
	  File "/nix/store/155049nzby4i67hh6k8s4m72d3s4zb3j-python3-3.11.9-env/lib/python3.11/site-packages/haystack/__init__.py", line 5, in <module>
	    from packaging.version import Version
	ModuleNotFoundError: No module named 'packaging'

Fixes: 6abc2f4548c0 ("python3Packages.django-haystack: 3.2.1 -> 3.3.0")