wordnet: fix build on `clang-16`
Without the change build fails on `darwin` by default and on `linux`
when `clang` is used explicitly:

    $ nix build --impure --expr 'with import <nixpkgs> {}; wordnet.override { stdenv = clangStdenv; }' -L
    ...
    wordnet> wn.c:132:1: error: type specifier missing, defaults to 'int'; ISO C99 and later do not support implicit int [-Wimplicit-int]
    wordnet> main(int argc,char *argv[])
    wordnet> ^
    wordnet> int

The change disables warnings turned to errors on clang-16+.