flytectl.tests: fix the eval
Without the change the eval fails on` master` as:

    $ nix build --no-link -f. flytectl.tests
    error:
       … while calling the 'derivationStrict' builtin
         at «nix-internal»/derivation-internal.nix:37:12:
           36|
           37|   strict = derivationStrict drvAttrs;
             |            ^
           38|

       … while evaluating derivation 'flytectl-0.9.8-test-version'
         whose name attribute is located at pkgs/stdenv/generic/make-derivation.nix:651:11

       … while evaluating attribute 'buildCommand' of derivation 'flytectl-0.9.8-test-version'
         at pkgs/build-support/trivial-builders/default.nix:81:17:
           80|         enableParallelBuilding = true;
           81|         inherit buildCommand name;
             |                 ^
           82|         passAsFile = [ "buildCommand" ] ++ (derivationArgs.passAsFile or [ ]);

       (stack trace truncated; use '--show-trace' to show the full, detailed trace)

       error: attribute 'version' missing
       at pkgs/by-name/fl/flytectl/package.nix:52:19:
           51|     command = "flytectl version";
           52|     version = "v${finalAttrs.src.version}";
             |                   ^
           53|   };

(cherry picked from commit fd141a2647a7d0e8506c15b45b61a4af6f96a1ec)