rust/hooks: Fix linking for thumb targets
For some reason rustc expect lld linker instead of cc
(https://github.com/rust-lang/rust/blob/4da69dfff1929cc79872b3d05ab7112d84753dba/compiler/rustc_target/src/spec/base/thumb.rs#L35)
for thumbv* targets unlike other targets. Therefore cross compilation
for these targets are broken: gcc do not understand linker args without
-Wl prefix:

    $ nix build
    ...
           > error: linking with `/nix/store/bp791a3wh7b4zqrf4h3vampxpydak7qa-armv7m-unknown-none-eabihf-gcc-wrapper-14.3.0/bin/armv7m-unknown-none-eabihf-cc` failed: exit status: 1
           >   |
           ...
           >   = note: armv7m-unknown-none-eabihf-gcc: error: unrecognized command-line option '-flavor'
           >           armv7m-unknown-none-eabihf-gcc: error: unrecognized command-line option '--as-needed'
           >           armv7m-unknown-none-eabihf-gcc: error: unrecognized command-line option '--eh-frame-hdr'
           >           armv7m-unknown-none-eabihf-gcc: error: unrecognized command-line option '--gc-sections'; did you mean '--data-sections'?

This can be fixed by giving rustc hint that the linker binary is in fact
gcc using linker-flavor codegen CLI argument.