Auto update/python3.8 google resumable media (#28)
* nextcloud22: 22.1.0 -> 22.1.1

Changes: https://github.com/nextcloud/server/compare/v22.1.0...v22.1.1

* nixos/nextcloud: add some notes for `Error: Command "upgrade" is not defined.`

This error occurs if `nextcloud-occ maintenance:install` fails and the
`upgrade` command is attempted to be executed afterwards.

Due to the nature of the installer we can't do much about it, so I guess
it makes sense to add some notes about it. The other notes in the
`Pitfalls`-section are semantically a list of different topics, so I
changed that accordingly now.

Closes #111175

* gopass: 1.12.7 -> 1.12.8

https://github.com/gopasspw/gopass/releases/tag/v1.12.8

* ssldump: 1.1 -> 1.4

* treewide: concatStrings (intersperse ...) -> concatStringsSep ...

Update all usage of lib.concatStrings (lib.intersperse ...) to
lib.concatStringsSep. This produces the same result as per https://github.com/NixOS/nixpkgs/pull/135843,
however it yields a performance benefit on Nix versions that
support the builtins.concatStringsSep primop.

* anki-bin: passthru sources

It wasn't possible to access the actual source on linux or that of the other OS

* anki-bin: 2.1.46 -> 2.1.47

* proxychains: revert commit e6b5d5401e42346a0a2190a

Fixes #136093.

* update-luarocks-packages: support in-repo rockspecs

to handle derivations that are not registered or updated on
luarocks.org, for instance neovim plugins.

* update-luarocks-packages: use the current nixpkgs

restore the behavior of the previous updater that was using the current revision of nixpkgs instead of an outer one

* linuxPackages.tuxedo-keyboard: 3.0.7 -> 3.0.8

* linuxPackages.tuxedo-keyboard: expose all kernel modules

This commit exposes in addition to the tuxedo-keyboard module:

- clevo_acpi
- clevo_wmi
- tuxedo_io

These modules are required to run the Tuxedo Control Center.

* iperf: 3.9 -> 3.10.1 (#136027)

* kakoune: 2020.09.01 -> 2021.08.28

* nixos-install-tools: Add tests.nixos-tests

* silver-searcher: add meta.mainProgram

* vimPlugins: update

* nixos/ipfs: run profile applications offline

* clang_11: Fix RISC-V builds for compiler-rt. (#135718)

Closes: #135628

* vector: 0.15.2 -> 0.16.0

* vector: 0.16.0 -> 0.16.1

* vector: disable flaky tests

* uxn: init at 0.0.0+unstable=2021-08-27

* python38Packages.gensim: 4.0.1 -> 4.1.0

* mcfly: 0.5.8 -> 0.5.9

https://github.com/cantino/mcfly/releases/tag/v0.5.9

* ocaml-ng.ocamlPackages_4_13.ocaml: 4.13.0-α2 → 4.13.0-β1

* libreswan: 4.4 -> 4.5

* msgpack: 3.2.0 -> 3.3.0

* ceph: 16.2.4 -> 16.2.5

* pkgsMusl.libiscsi: fix build

* portaudio: remove Werror (#136060)

* vimPlugins: assign original name to pname

instead of the normalized_name.

there is no need to rename the plugin ?! and it can upset packages for instance packer.nvim generates a config/nvim/plugin/packer_compiled.lua that does vim.api.nvim_command('packadd packer.nvim') which doesnt work on nixpkgs since the "packer.nvim" folder is renamed to "packer-nvim

* mrtg: 2.17.7 -> 2.17.8

* bwm_ng: 0.6.1 -> 0.6.3

* ocamlPackages.ocsigen-toolkit: 2.7.0 → 2.12.2

* rabbitmq: nixpkgs-fmt

* rabbitmq: add option to enable management plugin

* python3Packages.typer: 0.3.2 -> 0.4.0

* terraform-providers.fastly: 0.16.1 -> 0.34.0 (#136158)

* lttng-ust: 2.10.5 -> 2.13.0; clarify license

Also enable parallel building; tested at -j48.

* lttng-tools: 2.11.0 -> 2.13.0; clarify license

Also enable parallel building; tested at -j48.

* linuxPackages.lttng-modules: 2.12.6 -> 2.13.0

Fixes build with linuxPackages_5_14.

* nix-update: 0.4.0 -> 0.5.0

https://github.com/Mic92/nix-update/releases/tag/0.5.0

* slurm: 20.11.8.1 -> 21.08.0.1

* grilo: add patch for CVE-2021-39365

* epmd: add ipv6 assertion

* terraform-providers.aws: 3.43.0 -> 3.56.0 (#136102)

* ocamlPackages.ppx_optcomp: 0.14.1 → 0.14.3

* dbeaver: 21.1.5 -> 21.2.0

* linuxPackages.rtl8188eus-aircrack: parallel build

So much faster.  Tested at -j48.

* linuxPackages.rtl8812au: parallel build

So much faster.  Tested at -j48.

* linuxPackages.rtl8814au: parallel build

So much faster.  Tested at -j48.

* linuxPackages.rtl8821au: parallel build

So much faster.  Tested at -j48.

* linuxPackages.rtl8821ce: parallel build

So much faster.  Tested at -j48.

* linuxPackages.rtl8821cu: parallel build

Tested at -j48.

* linuxPackages.rtl88x2bu: parallel build

So much faster.  Tested at -j48.

* linuxPackages.rtl88xxau-aircrack: parallel build

So much faster.  Tested at -j48.

* python3Packages.pyupgrade: 2.24.0 -> 2.25.0

* android-tools: install missing tools

* rubygems: 3.2.24 -> 3.2.26

* epmd: provide default

* kakoune: simplify derivation

The dependencies and the sed patch appear to be redundant by now.

* nixos/syncthing: fix escapes interpreted in config

Dash `echo` interprets backslash escapes. This causes two consecutive backslashes in JSON to turn into a single one before the string is passed to jq, resulting in a parsing error.

* linuxPackages.vhba: enable PIC

When this was added in 21282246208 ("linuxPackages.vhba: disable PIC hardening"),
it was necessary to prevent a build failure.  Since it now builds fine
with PIC enabled, I think it's safe to enable it.

* linuxPackages.vhba: 20190831 -> 20210418

* libmirage: 3.2.3 -> 3.2.5

* image-analyzer: 3.2.3 -> 3.2.5

* cdemu-client: 3.2.3 -> 3.2.5

* cdemu-daemon: 3.2.3 -> 3.2.5

* gcdemu: 3.2.3 -> 3.2.5

* R: add memory profiling compile option

* python3Packages.scramp: 1.4.0 -> 1.4.1

* python3Packages.pg8000: 1.21.0 -> 1.21.1

* ipcalc: 0.4.1 -> 1.0.1

* vault-bin: 1.8.1 -> 1.8.2

- https://github.com/hashicorp/vault/releases/tag/v1.8.2

* consul: 1.10.1 -> 1.10.2

- https://github.com/hashicorp/consul/releases/tag/v1.10.2

* nomad_1_0: 1.0.9 -> 1.0.10

- https://github.com/hashicorp/nomad/releases/tag/v1.0.10

* nomad_1_1: 1.1.3 -> 1.1.4

- https://github.com/hashicorp/nomad/releases/tag/v1.1.4

* vimPlugins.neon: init at 2021-07-30

* firefox: 91.0.1 -> 91.0.2

* firefox-bin: 91.0.1 -> 91.0.2

* markdown-anki-decks: jailbreak more dependencies

* linuxPackages.akvcam: 1.2.0 -> 1.2.2

The qmake-based build didn't seem to work any more, but there's a
Kbuild-based build system available anyway, so let's just switch to
that and save a dependency.

Also clarify license.

* linuxPackages.isgx: enable parallel building

Tested at -j48.

* tfsec: 0.58.5 -> 0.58.6

* qt5.qt3d: init module

* onlyoffice-bin: 6.2.0 -> 6.3.1

* qt5: Expose internal variables to facilitate out-of-tree building of modules

As it is currently it's almost impossible to accomplish something like:
```nix
...

(qt5.callPackage (
  { qtModule, qtbase, qtdeclarative }:
  qtModule {
    pname = "qt3d";
    qtInputs = [ qtbase qtdeclarative ];
    outputs = [ "out" "dev" "bin" ];
  }
) { })

...
```
because all the required variables such as qtModule are internal-only.

By exposing these it's easier for external projects not to be bound
exactly by the module definitions explicitly listed in nixpkgs.

* nvidia_x11: 470.57.02 → 470.63.01

* linux_latest: 5.13.13 -> 5.14

* linux_latest-libre: 18260 -> 18268

* luaPackages: update

* luaPackages.ltermbox: removed

official repo here https://github.com/LuaDist-testing/ltermbox but nothing is using it and it is outdated/unmaintained (2018)
and poses issue updating

* luaPackages.luadoc: remove since last update in 2013

no update in 7 years, link towards source doesn't work anymore https://luarocks.org/modules/luarocks/luadoc/3.0.1-1

* podman: 3.3.0 -> 3.3.1

https://github.com/containers/podman/releases/tag/v3.3.1

* lua: restore knownRockspec and lgi

- fix std._debug build
- fixed std-normalize
- pinned stdlib since the git version  causes issues with awesome

cleanup

* luaPackages.ansicolors: remove because unmaintained since 2013

luarocks points at https://github.com/kikito/ansicolors.lua with a last
commit in 2013 while its upstream https://github.com/hoelzro/ansicolors
contains a 2017 commit. This last project mentions it's superseeded by
https://github.com/hoelzro/lua-term

* luarocks-nix: bumped luarocks-nix

this new version removes support of src.rock but now supports rockspecs embedded in a repo. The goal is to be able to support neovim plugins that provide a rockspec, even when they are not registered on luarocks.

* linuxPackages.isgx: 2.11 -> 2.14

* lima: 0.6.0 -> 0.6.1

https://github.com/lima-vm/lima/releases/tag/v0.6.1

* dwz: init at 0.14 (#136078)

* houdini: use libudev0-shim

* nixos/nvidia: let user choose whether to install nvidia-settings

* linuxPackages.nvidia_x11: apply kernel module makeFlags

* linuxPackages.nvidia_x11.persistenced: pick up nvidia_x11 makeFlags

* linuxPackages.nvidia_x11.settings: pick up nvidia_x11 makeFlags

* linuxPackages.nvidia_x11.settings: use makeFlags in preBuild's libXNVCtrl build

* linuxPackages.nvidia-x11: use makeFlags in builder.sh

* elasticsearch: nixpkgs-fmt

* kibana: nixpkgs-fmt

* logstash: nixpkgs-fmt

* beats: nixpkgs-fmt

* elk7: 7.5.1 -> 7.10.2

Update pkgs/development/tools/misc/kibana/7.x.nix

Co-authored-by: Mihai Fufezan <36706276+fufexan@users.noreply.github.com>

Update pkgs/servers/search/elasticsearch/7.x.nix

Co-authored-by: Mihai Fufezan <36706276+fufexan@users.noreply.github.com>

Update pkgs/servers/search/elasticsearch/7.x.nix

Co-authored-by: Mihai Fufezan <36706276+fufexan@users.noreply.github.com>

Update pkgs/development/tools/misc/kibana/7.x.nix

Co-authored-by: Mihai Fufezan <36706276+fufexan@users.noreply.github.com>

* logstash: fix download url

Update pkgs/tools/misc/logstash/7.x.nix

Co-authored-by: Mihai Fufezan <36706276+fufexan@users.noreply.github.com>

Update pkgs/tools/misc/logstash/7.x.nix

Co-authored-by: Mihai Fufezan <36706276+fufexan@users.noreply.github.com>

* beats: buildGoPackage -> buildGoModule

* kibana update nodejs 10 -> 14

* linuxPackages.ddcci-driver: use kernel's make flags

* ipfs: nixpkgs-fmt

* ipfs: increase UDP buffer size

* sage: adapt tests for networkx 2.6

* docs: update beam.section

* ipfs: nixpkgs-fmt

* stalonetray: 0.8.3 -> 0.8.4

This update is quite involved for a minor version update.

1. I had to change the source from Sourceforge to Github.

2. I manually specify the autoconf pre-configuration steps. This seems to be
necessary, but is there a better, more canonical way?

3. I had to add the docbook dependency and tinker around with substitutions,
because the original files would pull sources from an online repository. Please
have a look!

Thanks for your comments.

Cheers.

* Fix interaction between appendOverlays and otherPackageSets

The comment

    a dirty hack that should be removed

has led me to believe that nixpkgsFun isn't the right solution,
but bypassing it is worse, because it creates a second, inner
overriding mechanism that doesn't pass its changes to the old,
outer overriding mechanism.

Before this change:

    nix-repl> ((import <nixpkgs> {}).appendOverlays([(f: s: { foobarbaz = "ok"; })])).foobarbaz
    "ok"

    nix-repl> ((import <nixpkgs> {}).appendOverlays([(f: s: { foobarbaz = "ok"; })])).pkgsCross.aarch64-multiplatform.foobarbaz
    error: attribute 'foobarbaz' missing

           at «string»:1:1:

                1| ((import <nixpkgs> {}).appendOverlays([(f: s: { foobarbaz = "ok"; })])).pkgsCross.aarch64-multiplatform.foobarbaz
                 | ^
                2|

After this change:

    nix-repl> ((import ./. {}).appendOverlays([(f: s: { foobarbaz = "ok"; })])).pkgsCross.aarch64-multiplatform.foobarbaz
    "ok"

Thanks to samueldr for discovering this problem.

* kakoune: remove pkg-config, cleanup preConfigure

* flawfinder: 2.0.18 -> 2.0.19

* nixos/roon-server: fix openFirewall

* nixos/roon-bridge: fix openFirewall

* libe57format: 2.1 -> 2.2.0

* logstash: fix passthru.tests

* python3Packages.zeroconf: 0.36.0 -> 0.36.2

* python3Packages.karton-dashboard: 1.2.0 -> 1.2.1

* nixos/syncthing: fix declarative init crash on HTTPS

A previous config may be present that has HTTPS for the REST API enabled.

* nmap: 7.91 -> 7.92

* kops: 1.21.0 -> 1.21.1 (#136057)

* caddy: 2.4.3 -> 2.4.4 (#136252)

* step-cli: 0.16.1 -> 0.17.2

* networkmanagerapplet: 1.22.0 -> 1.24.0

- https://gitlab.gnome.org/GNOME/network-manager-applet/-/blob/1.24.0/NEWS

* tar2ext4: 0.8.20 -> 0.8.21

* linuxPackages.rtw88: mark broken on Linux 5.14

* linuxPackages.xmm7360-pci: mark broken on Linux 5.14

* python3Packages.coqpit: 0.0.10 -> 0.0.13

* tts: relax mecab-python3 constraint

* jenkins: 2.289.3 → 2.303.1

* oh-my-zsh: 2021-08-18 → 2021-08-27

* tts: 0.2.0 -> 0.2.1

* usbredir: fix cross

* hashcat: 6.2.3 -> 6.2.4

* skypeforlinux: 8.69.0.77 -> 8.75.0.140

* offlineimap: 7.3.3 -> 7.3.4 (#136145)

* ipfs: add autoMigrate option

* matrix-synapse: 1.41.0 -> 1.41.1

https://github.com/matrix-org/synapse/releases/tag/v1.41.1

* zfsUnstable: 2.1.0 -> unstable-2021-08-30

* git-branchless: add support for Darwin builds

* maintainers: add msfjarvis

* git-branchless: add msfjarvis as co-maintainer

* nixos/nextcloud: apply doc fixes suggested by fabaff

Co-authored-by: Fabian Affolter <mail@fabian-affolter.ch>

* sequoia: fix license

* element-{web,desktop}: 1.8.1 -> 1.8.2

* ocaml-ng.ocamlPackages_4_08.uunf: mark as broken on aarch64

Fails to build consistently on aarch64 for unknown reasons, probably a
compiler bug as OCaml 4.12 seems to work.

* merkaartor: fix hash

* buildLuarocksPackage: cleanup

* bluespec: unstable-2021.03.29 -> 2021.07

* whitespace

* bluespec: use only 'check-smoke' for now

* whitespace

* bluespec: style changes, checkInputs

* whitespace

* python38Packages.ntc-templates: 2.3.0 -> 2.3.1

* danger-gitlab: init at 8.0.0

* phosh: 0.12.1 -> 0.13.1

* phosh: Remove archseer as maintainer

Per request: https://github.com/NixOS/nixpkgs/pull/133559#issuecomment-897343555

* phoc: Change source URL to GNOME GitLab

* wrangler: 1.19.0 -> 1.19.1

* caddy: build with default go and fix tests

* pick: 2.0.2 -> 4.0.0 (#136348)

* xfig: 3.2.8a -> 3.2.8b (#136366)

https://sourceforge.net/p/mcj/xfig/ci/b6c4fd32a1f3733b84cdbeeb2870b5e9849bc32c/

* python38Packages.google-resumable-media: 2.0.0 -> 2.0.1

Co-authored-by: Maximilian Bosch <maximilian@mbosch.me>
Co-authored-by: Mario Rodas <marsam@users.noreply.github.com>
Co-authored-by: Fabian Affolter <mail@fabian-affolter.ch>
Co-authored-by: polykernel <81340136+polykernel@users.noreply.github.com>
Co-authored-by: Atemu <atemu.main@gmail.com>
Co-authored-by: Chuang Zhu <genelocated@yandex.com>
Co-authored-by: Matthieu Coudron <mcoudron@hotmail.com>
Co-authored-by: Julian Stecklina <julian.stecklina@cyberus-technology.de>
Co-authored-by: Alexander Kiselyov <aleksandr.kiselyov@gmail.com>
Co-authored-by: Joshua Trees <me@jtrees.io>
Co-authored-by: Fabian Affolter <fabian@affolter-engineering.ch>
Co-authored-by: Robert Hensing <robert@roberthensing.nl>
Co-authored-by: Robert Hensing <roberth@users.noreply.github.com>
Co-authored-by: Tom Bereknyei <tomberek@gmail.com>
Co-authored-by: Jörg Thalheim <Mic92@users.noreply.github.com>
Co-authored-by: Max <max@privatevoid.net>
Co-authored-by: Tom Repetti <trepetti@cs.columbia.edu>
Co-authored-by: happysalada <raphael@megzari.com>
Co-authored-by: AndersonTorres <torres.anderson.85@protonmail.com>
Co-authored-by: R. RyanTM <ryantm-bot@ryantm.com>
Co-authored-by: Vincent Laporte <Vincent.Laporte@gmail.com>
Co-authored-by: rnhmjoj <rnhmjoj@inventati.org>
Co-authored-by: Martin Weinelt <hexa@darmstadt.ccc.de>
Co-authored-by: Alyssa Ross <hi@alyssa.is>
Co-authored-by: Michele Guerini Rocco <rnhmjoj@users.noreply.github.com>
Co-authored-by: Matthew Leach <dev@mattleach.net>
Co-authored-by: Matthieu Coudron <teto@users.noreply.github.com>
Co-authored-by: Jonas Chevalier <zimbatm@zimbatm.com>
Co-authored-by: zowoq <59103226+zowoq@users.noreply.github.com>
Co-authored-by: Markus Kowalewski <markus.kowalewski@fysik.su.se>
Co-authored-by: Robert Scott <code@humanleg.org.uk>
Co-authored-by: Johannes Schleifenbaum <johannes@js-webcoding.de>
Co-authored-by: markuskowa <markus.kowalewski@gmail.com>
Co-authored-by: Kevin Cox <kevincox@kevincox.ca>
Co-authored-by: Mustafa Çalışkan <musfay@protonmail.com>
Co-authored-by: Tim Steinbach <tim@nequissimus.com>
Co-authored-by: Robin Stumm <serverkorken@gmail.com>
Co-authored-by: schotts-fired <michael.m.schott@protonmail.com>
Co-authored-by: davidak <davidak@users.noreply.github.com>
Co-authored-by: Maxine Aubrey <maxeaubrey@gmail.com>
Co-authored-by: Sebastian Estrella <2049686+sestrella@users.noreply.github.com>
Co-authored-by: Niklas Hambüchen <mail@nh2.me>
Co-authored-by: Jan Tojnar <jtojnar@gmail.com>
Co-authored-by: Michael Raskin <7c6f434c@mail.ru>
Co-authored-by: adisbladis <adisbladis@gmail.com>
Co-authored-by: GTrunSec <gtrunsec@hardenedlinux.org>
Co-authored-by: Fabián Heredia Montiel <fabianhjr@protonmail.com>
Co-authored-by: Joseph Crail <jbcrail@gmail.com>
Co-authored-by: Bernardo Meurer <bernardo@meurer.org>
Co-authored-by: Mihai Fufezan <36706276+fufexan@users.noreply.github.com>
Co-authored-by: Mauricio Collares <mauricio@collares.org>
Co-authored-by: Dmitry Kalinkin <dmitry.kalinkin@gmail.com>
Co-authored-by: Dominik Schrempf <dominik.schrempf@gmail.com>
Co-authored-by: Jörg Thalheim <joerg@thalheim.io>
Co-authored-by: Pascal Bach <pascal.bach@nextrem.ch>
Co-authored-by: Eric Bailey <yurrriq@users.noreply.github.com>
Co-authored-by: maxine [they] <35892750+maxeaubrey@users.noreply.github.com>
Co-authored-by: Bobby Rong <rjl931189261@126.com>
Co-authored-by: Robin Townsend <robin@robin.town>
Co-authored-by: Harsh Shandilya <me@msfjarvis.dev>
Co-authored-by: Sumner Evans <me@sumnerevans.com>
Co-authored-by: sternenseemann <0rpkxez4ksa01gb3typccl0i@systemli.org>
Co-authored-by: Nikolay Korotkiy <sikmir@gmail.com>
Co-authored-by: Martin Weinelt <mweinelt@users.noreply.github.com>
Co-authored-by: Jack Cummings <jack@mudshark.org>
Co-authored-by: Michael Weiss <dev.primeos@gmail.com>
Co-authored-by: Zhenya Vinogradov <zhenyavinogradov@gmail.com>
Co-authored-by: Vladimír Čunát <v@cunat.cz>
Co-authored-by: Zhaofeng Li <hello@zhaofeng.li>
Co-authored-by: Nick Cao <nickcao@nichi.co>
Co-authored-by: Sandro <sandro.jaeckel@gmail.com>
Co-authored-by: Kranium Mendoza <kranium@gikos.net>
Co-authored-by: LeSuisse <thomas@gerbet.me>