python310Packages.poetry-core: revert update of vendored dependencies
The build of zeroconf fails on x86_64-darwin with

    ERROR: zeroconf-0.47.3-cp310-cp310-macosx_13_0_x86_64.whl is not a
    supported wheel on this platform.

using the newer versions of the vendored dependencies.