xprintidle-ng: fix build
Fixes the config.h include error during build:

```console
In file included from src/xprintidle-ng.c:36:
lib/time.h:28:3: error: #error "Please include config.h first."
    28 |  #error "Please include config.h first."
      |   ^~~~~
```

Introduced since gnulib upgrade:
* https://github.com/coreutils/gnulib/commit/8ad7bc6
* https://lists.gnu.org/archive/html/bug-gnulib/2023-04/msg00088.html
* https://www.gnu.org/software/gnulib/manual/html_node/Source-changes.html

The last version of gnulib now checks that config.h is the first include
in every compilation unit.

This is not the case with the xprintidle-ng source code, so this patch
moves these `config.h` inclusions to be first.