mysql80: 8.0.16 => 8.0.17
Note: "MySQL Router" is a distinct component. Building it fails on macOS 10.12.6 with an error (below); hence, it is skipped.

```
[ 98%] Building CXX object router/src/plugin_info/src/CMakeFiles/mysqlrouter_plugin_info.dir/library_file.cc.o
[ 98%] Building CXX object router/src/plugin_info/src/CMakeFiles/mysqlrouter_plugin_info.dir/main.cc.o
[ 98%] Building CXX object router/src/plugin_info/src/CMakeFiles/mysqlrouter_plugin_info.dir/plugin_info_app.cc.o
[ 98%] Building CXX object router/src/plugin_info/src/CMakeFiles/mysqlrouter_plugin_info.dir/plugin.cc.o
[ 98%] Linking CXX executable ../../../../runtime_output_directory/mysqlrouter_plugin_info
[ 98%] Built target mysqlrouter_plugin_info
Scanning dependencies of target rest_api_lib
[ 98%] Building CXX object router/src/rest_api/src/CMakeFiles/rest_api_lib.dir/rest_api_utils.cc.o
[ 98%] Linking CXX static library librest_api_lib.a
[ 98%] Built target rest_api_lib
Scanning dependencies of target rest_api
[ 98%] Building CXX object router/src/rest_api/src/CMakeFiles/rest_api.dir/rest_api_component.cc.o
In file included from /tmp/nix-build-mysql-8.0.17.drv-0/mysql-8.0.17/router/src/rest_api/src/rest_api_component.cc:30:
/tmp/nix-build-mysql-8.0.17.drv-0/mysql-8.0.17/router/src/rest_api/src/rest_api_plugin.h:90:8: error: 'shared_timed_mutex' is unavailable: introduced in macOS 10.12
  std::shared_timed_mutex rest_api_handler_mutex_;
       ^
/nix/store/3r156gjbpig7xav3crnhffn3msnqmak7-libc++-7.1.0/include/c++/v1/shared_mutex:204:58: note: 'shared_timed_mutex' has been explicitly marked unavailable here
class _LIBCPP_TYPE_VIS _LIBCPP_AVAILABILITY_SHARED_MUTEX shared_timed_mutex
                                                         ^
1 error generated.
make[2]: *** [router/src/rest_api/src/CMakeFiles/rest_api.dir/build.make:63: router/src/rest_api/src/CMakeFiles/rest_api.dir/rest_api_component.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:10908: router/src/rest_api/src/CMakeFiles/rest_api.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
builder for '/nix/store/19c1b8qn0x8fnsa64y4k19r169ifv1b7-mysql-8.0.17.drv' failed with exit code 2
error: build of '/nix/store/19c1b8qn0x8fnsa64y4k19r169ifv1b7-mysql-8.0.17.drv' failed
```

Would skipping it be a regression?  I don't think so: `mysqlrouter` was not
part of `mysql57`, and `mysql80` has not been previously published via
nixpkgs.