python: fix opt-in parallel build_ext builds for setuptools
Commit 52248e44662 ("python: enable opt-in parallel build_ext builds
for setuptools", 2022-04-22), merged in #169761, broke building of
xpra package. The error message is:

    error: option --with-vsock--parallel not recognized

We fix the problem by adding a space.