foundationdb: fix build: use glibc's gettid()
to avoid build error due to conflicting declaration:

    flow/Profiler.actor.cpp: In function 'uint64_t gettid()':
    flow/Profiler.actor.cpp:56:17: error: ambiguating new declaration of 'uint64_t gettid()'
      FILE* f;
                     ^
    In file included from /nix/store/4wy9j24psf9ny4di3anjs7yk2fvfb0gq-glibc-2.31-dev/include/unistd.h:1170:0,
                     from ./flow/Platform.h:49,
                     from ./flow/flow.h:40,
                     from flow/Profiler.actor.cpp:39:
    /nix/store/4wy9j24psf9ny4di3anjs7yk2fvfb0gq-glibc-2.31-dev/include/bits/unistd_ext.h:34:16: note: old declaration '__pid_t gettid()'
     extern __pid_t gettid (void) __THROW;
                    ^~~~~~