ntp: fix build with gcc-14
configure fails with:
> conftest.c: In function 'main':
conftest.c:162:16: error: passing argument 1 of 'pthread_detach' makes integer from pointer without a cast [-Wint-conversion]

pthread_detach expects a pthread_t so provide it one with pthread_self()