brlaser: cleanup and mark linux only (#46622)
The test binaries depend use open_memstream which isn't available on
darwin.

    error: use of undeclared identifier 'open_memstream'

/cc ZHF #45961

(cherry picked from commit 04cba83e7fbbf2f483794618d34b808016d916c4)