tevent: copy cross fix from talloc & add libxcrypt
testing pyembed configuration : Could not build a python embedded interpreter

tevent-aarch64-unknown-linux-gnu> In file included from ../../pytevent.c:26:
tevent-aarch64-unknown-linux-gnu> ../../lib/replace/replace.h:885:10: fatal error: crypt.h: No such file or directory
tevent-aarch64-unknown-linux-gnu>   885 | #include <crypt.h>
tevent-aarch64-unknown-linux-gnu>       |          ^~~~~~~~~
tevent-aarch64-unknown-linux-gnu> compilation terminated.

(cherry picked from commit 30826d6035ffff0ccc16b53f5f42111661214882)