hplip: add missing dependency (#58515)
Graphical programs (e.g. hp-setup) error with:

error: No module named enum

This adds the enum module which fixes the error