python3Packages.pyaxmlparser: fix build
The build is currently broken on master[1] due to a major bump of
`click` in fe0af1ce777abf99a3fd851a86f2000326153207.

Manually patching `setup.py` temporarily fixes the issue. To ensure that
succeeding builds don't deliver packages breaking at runtime due to
dependency issues I switched to the GitHub archive as source since it
contains tests as well.

Additionally, Python 2.7 support has been dropped. It seems as it
was never intended to support Python3 here, I simply forgot to disable
the Python2 build.

```
TypeError: AXMLParser object is not an iterator
```

[1] https://hydra.nixos.org/build/86108813