claws-mail: do not use fetchgit; upstream has force-pushed
Our claws-mail expression no longer builds without substituters; apparently
upstream has force-pushed the 4.1.0 tag to a different commit.  The current
4.1.0 tag is at a commit whose date (Fri May 6 11:01:22 2022 +0100) is almost a
month later than the nixpkgs commit.

Unfortuantely the `fetchgit` expression we're using doesn't have any kind of git
commit hash in it, so I'm unable to rescue it.  Hydra strips out the .git
directory before creating the cache, so I can't get it from there either.

I think we should probably avoid using `fetchgit` here unless we're including
the git commit-hash.  Even better, let's use released tarballs.

```
claws> exporting git://git.claws-mail.org/claws.git (rev 4.1.0) into /nix/store/w616jnh09024djrgx4j3s93dnn6dvwl5-claws
claws> Initialized empty Git repository in /nix/store/w616jnh09024djrgx4j3s93dnn6dvwl5-claws/.git/
claws> remote: Enumerating objects: 1491, done.
claws> remote: Counting objects: 100% (1491/1491), done.
claws> remote: Compressing objects: 100% (1415/1415), done.
claws> remote: Total 1491 (delta 352), reused 505 (delta 67)/s
claws> Receiving objects: 100% (1491/1491), 6.88 MiB | 2.28 MiB/s, done.
claws> Resolving deltas: 100% (352/352), done.
claws> From git://git.claws-mail.org/claws
claws>  * tag               4.1.0      -> FETCH_HEAD
claws> Switched to a new branch 'fetchgit'
claws> removing `.git'...
error: hash mismatch in fixed-output derivation '/nix/store/9rw91mgplypm6yh8bnawr9x7qj5vpik6-claws.drv':
         specified: sha256-II2+dnju6ffznO+klfI8awM4aGUJf3UD1HNofNA/9N0=
            got:    sha256-5S2FuM8sOG8//lrWFUTS/o1eZ/hrKSVgfyKpfaBfO1k=
note: keeping build directory '/tmp/nix-build-claws.drv-0'
```