relic: 8.1.1 -> 8.2.0
Also disable aggressive sandboxing causing some checkPhase failures on
Darwin:

    --- FAIL: TestCompress (0.00s)
    panic: httptest: failed to listen on a port: listen tcp6 [::1]:0: bind: operation not permitted