nixos/zfs: assert that zed.enableMail is only being used when sendmailSetuidWrapper is enabled
Otherwise we crash like:

… while selecting an attribute
  at /nix/store/0b202s06rfm1vlyai37gd0zmzxg59qj0-source/nixos/modules/tasks/filesystems/zfs.nix:827:48:
   826|           lib.mkDefault (
   827|             config.security.wrapperDir + "/" + config.services.mail.sendmailSetuidWrapper.program
      |                                                ^
   828|           )

error: expected a set but found null: null