grafana: fix aarch64-linux build
Build used to fail on aarch64-linux like this:

       > gyp info spawn args   '-Goutput_dir=.'
       > gyp info spawn args ]
       > Traceback (most recent call last):
       >   File "/build/source/node_modules/node-gyp/gyp/gyp_main.py", line 42, in <module>
       >     import gyp  # noqa: E402
       >     ^^^^^^^^^^
       >   File "/build/source/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 9, in <module>
       >     import gyp.input
       >   File "/build/source/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 19, in <module>
       >     from distutils.version import StrictVersion
       > ModuleNotFoundError: No module named 'distutils'
       > gyp ERR! configure error

Looks like `node-gyp` used by Grafana is missing fixes for Python 3.12
(where distutils got dropped).