smpeg: fix build by linking against libX11 explicitly
Error:

/nix/store/anvi6cx0rcj9xn48af849qnr590avyn3-binutils-2.30/bin/ld: gtv.o: undefined reference to symbol 'XMoveWindow'
/nix/store/ps571bzx27x5imzifw4wiah32mpqpgva-libX11-1.6.7/lib/libX11.so.6: error adding symbols: DSO missing from command line