python312Packages.radish-bdd: fix missing yaml dependency
```
Traceback (most recent call last):
  File "/nix/store/m7wyckhw6ll6q2azfpivb0jqk9q9fm8z-python3.12-radish-bdd-0.17.1/bin/.radish-test-wrapped", line 6, in <module>
    from radish.testing.__main__ import main
  File "/nix/store/m7wyckhw6ll6q2azfpivb0jqk9q9fm8z-python3.12-radish-bdd-0.17.1/lib/python3.12/site-packages/radish/testing/__main__.py", line 15, in <module>
    from radish.testing.matches import test_step_matches_configs
  File "/nix/store/m7wyckhw6ll6q2azfpivb0jqk9q9fm8z-python3.12-radish-bdd-0.17.1/lib/python3.12/site-packages/radish/testing/matches.py", line 12, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
```

radish-test requires pyyaml at runtime.