lib.escapeRegex: fix with `boost::regex` implementation
https://github.com/NixOS/nix/pull/7762 switched `nix` to use the
`boost::regex` implementation, which expects that all literal braces are
escaped. That is, the regex `\{crate}` no longer parses. We modify
`lib.escapeRegex` to accommodate this change. Fortunately, the old regex
implementation doesn't mind if closing braces are escaped as well, so
this is backwards compatible and we don't need to worry about
version-gating it.

Without this patch:

Old regex implementation:

    $ nix repl nixpkgs
    Welcome to Nix 2.18.1. Type :? for help.

    Loading installable 'flake:nixpkgs#'...
    Added 5 variables.
    nix-repl> builtins.match (lib.escapeRegex "{}") "{}"
    [ ]

    $ ~/nix/result/bin/nix repl nixpkgs
    Welcome to Nix 2.20.0pre20231130_dirty. Type :? for help.

`boost::regex` implementation:

    $ ~/nix/result/bin/nix repl nixpkgs
    Welcome to Nix 2.20.0pre20231130_dirty. Type :? for help.

    Loading installable 'flake:nixpkgs#'...
    Added 5 variables.
    nix-repl> builtins.match (lib.escapeRegex "{}") "{}"
    error:
           … while calling the 'match' builtin

             at «string»:1:1:

                1| builtins.match (lib.escapeRegex "{}") "{}"
                 | ^

           error: invalid regular expression '\{}'