fix build on darwin platforms
when building on darwin, the build would fail when compiling
`spade-tests` with linker errors like the following:

```
error: linking with `/nix/store/gj5jfkr5y5s95vhgvh5hzq70p8dzhw57-clang-wrapper-16.0.6/bin/cc` failed: exit status: 1

...

  = note: Undefined symbols for architecture arm64:
            "_PyBaseObject_Type", referenced from:
                pyo3::pyclass::create_type_object::create_type_object::h32bb09bb3b93c8f8 (.llvm.6562022786284816598) in spade.spade.ed1a311ee7cc6dbd-cgu.2.rcgu.o
...
```

these missing symbols are all provided by the CPython object files. the
solution is thus to add the folder containing `libpython3.12.a` to the
linker's search paths via `-L` and the `lpython3.12` library to the
linking process via `-l`. these flags are passed to the linker via the
`NIX_CFLAGS_LINK` variable.