xorg: remove xlibsWrapper attribute, use top-level one instead
I noticed this attribute when tried to override `xorg` scope via
overlay:

    final: prev {
      xorg = prev.xorg.overrideScope' (f: p: {
        libXfont2 = p.libXfont2.overrideAttrs (oa: {
          patches = (oa.patches or []) ++ [
            ../libXfont2/nofollow.patch
          ];
        });
      }) // { inherit (prev) xlibsWrapper; };
    }

As a result I got unexpected `pulseaudio` build failures:

    $ nix build --no-link -f. pulseaudio
    error: attribute 'xlibsWrapper' missing

           at pkgs/servers/pulseaudio/default.nix:79:37:

               78|       ++ lib.optional jackaudioSupport libjack2
               79|       ++ lib.optionals x11Support [ xorg.xlibsWrapper xorg.libXtst xorg.libXi ]
                 |                                     ^
               80|       ++ lib.optional useSystemd systemd

Previous changes in this branch remove references to xorg.xlibsWrapper
in favour of xlibsWrapper. Let's remove injection of this attribute into
`xorg.