python: fix buildEnv passthru when using .override
Before this commit, `python3.override { ... }.buildEnv` would take the
un-overriden python interpreter as basis for the buildEnv. With this
commit, we compute self inside the argument passed to callPackage so the
buildEnv will always reference the python interpreter it belongs to.

As an example where this matters, `python3Full` is defined as
`python3.override { x11Support = true; }`. Before this commit,
`python3Full.buildEnv` didn't get that override:

```
nix-shell -p 'with (import ./. {}); python3Full.buildEnv' --command 'python3 -c "import tkinter"'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File
"/nix/store/s7vw8y02cqzx8bnjxl4bkhlnwvz6ws1s-python3-3.7.6/lib/python3.7/tkinter/__init__.py",
line 36, in <module>
    import _tkinter # If this fails your Python may not be configured
for Tk
ModuleNotFoundError: No module named '_tkinter'
```

With this commit, that example now works.