treewide: remove uses of now-removed nixUnstable
nixUnstable was removed in 2b4e18f3d4a7b80af21b640c0970f83b34efceff
but is still referred to from a variety of places, including Hydra's
cross-trunk jobset:

```
in job ‘armv7l-hf.nixUnstable.aarch64-linux’:
error:
       … while evaluating a branch condition
         at /nix/store/m549zq6lcl10d1jqcdgcdaxxj9xdhxfv-source/lib/customisation.nix:479:5:
          478|     in
          479|     if drv == null then null else deepSeq drv' drv';
             |     ^
          480|

       … in the left operand of the update (//) operator
         at /nix/store/m549zq6lcl10d1jqcdgcdaxxj9xdhxfv-source/lib/meta.nix:43:9:
           42|   addMetaAttrs = newAttrs: drv:
           43|     drv // { meta = (drv.meta or {}) // newAttrs; };
             |         ^
           44|

       (stack trace truncated; use '--show-trace' to show the full, detailed trace)

       error: nixUnstable has been removed. For bleeding edge (Nix
       master, roughly weekly updated) use nixVersions.git, otherwise
       use nixVersions.latest.
```