ci/nixpkgs-vet: use temporary Nix store
On Darwin, nixpkgs-vet fails on nix-store --init:

error: creating directory '/nix/store/.links': Operation not permitted

It happens because in contrast to Linux, /nix/store is not a private r/w
directory but the actual host /nix/store (sandboxed r/o, with existing
.links not visible).

Use a temporary writable store for all platforms.