postgresql_14: fix build
Building postgresql_14 currently fails with this on master:

  error: derivation contains an illegal reference specifier 'man'

The reason seems to be a bug in nix, where outputChecks are run
improperly when one of the outputs can already be substituted. Why the
man output can be substituted from hydra is unknown, but adding more
outputChecks for the the man and doc outputs should work around the
problem until nix is fixed.