db4: fix pthread configure detection
add header stdlib.h so pthread detection doesn't fail do to a missing
function prototype for exit.

```
configure:21863: clang -o conftest -O3   -D_GNU_SOURCE -D_REENTRANT
conftest.c  >&5
conftest.c:52:2: error: call to undeclared library function 'exit' with
type 'void (int) __attribute__((noreturn))'; ISO C99 and later do not
support implicit function declarations [-Wimplicit-function-declaration]
   52 |         exit (
      |         ^
conftest.c:52:2: note: include the header <stdlib.h> or explicitly
provide a declaration for 'exit'
```