chromiumBeta: Fix the build
The build was failing with:
[4758/49762] ACTION //third_party/dawn/src/dawn/common:dawn_version_gen__json_tarball(//build/toolchain/linux/unbundle:default)Ke:default)ux/unbundle:default)[Kuide/optimization_guide_internals/resources/optimization_guide_internals.mojom-webui.js
FAILED: gen/third_party/dawn/dawn_version_gen.json_tarball
python3 ../../third_party/dawn/generator/dawn_version_generator.py --dawn-dir ../../third_party/dawn/ --template-dir /build/chromium-102.0.5005.49/third_party/dawn/generator/templates --jinja2-path /build/chromium-102.0.5005.49/third_party/jinja2 --output-json-tarball gen/third_party/dawn/dawn_version_gen.json_tarball --depfile gen/third_party/dawn/dawn_version_gen.json_tarball.d --expected-outputs-file gen/third_party/dawn/dawn_version_gen.expected_outputs --allowed-output-dirs-file gen/third_party/dawn/dawn_version_gen.allowed_output_dirs
Traceback (most recent call last):
[...]
FileNotFoundError: [Errno 2] No such file or directory: 'git'
[4761/49762] ACTION //third_party/blink/renderer/bindings:generate_bindings_all(//build/toolchain/linux/unbundle:default)fault)
ninja: build stopped: subcommand failed.

More details here: https://bugs.chromium.org/p/chromium/issues/detail?id=1321370

The patch doesn't apply to M102 so I had to cherry-pick it manually.

(cherry picked from commit 37a13a3d4d838de3faa2431aab52bf19b5ca4930)