anki: fix build on darwin
Runtime doesn't work:

ModuleNotFoundError: No module named 'PyQt5.QtWebEngineWidgets'

This is probably because qtwebengine is broken on darwin, but doesn't
fail the build (#40149)