mbedtls: fix gcc-11 build by disabling warnings
The build fails on gcc-11. Example reproducer:

    $ nix-build -E 'with import ./. {}; mbedtls.override { stdenv = gcc11Stdenv; }'
    ...
    /build/source/library/ssl_tls.c:3334:5: error:
      'mbedtls_sha512_finish_ret' accessing 64 bytes in a region
        of size 48 [-Werror=stringop-overflow=]
     3334 |     finish( &sha512, padbuf );
          |     ^~~~~~~~~~~~~~~~~~~~~~~~~

Instead of backporting an API change let's disable warnings.