pythonPackages.psycopg2: 2.5.4 -> 2.6.1
The unit tests are disabled because they require a local instance
of PostgreSQL.

All unit tests pass in my local instance for
  - Python 2.7
  - Python 3.4

One test fails for Python 3.5 (not officialy supported anyway):
  - test_copy_from_propagate_error (psycopg2.tests.test_copy.CopyTests)
    ZeroDivisionError: division by zero

This issue is reported upstream:
https://github.com/psycopg/psycopg2/issues/412