pythonPackages.lupa: init at 1.7
Use lua instead of luajit because of problems on Darwin:

  File "/private/var/folders/ym/xnfgyq_n2fzgzzx9gtccxdjm0000gn/T/nix-build-python3.7-lupa-1.7.drv-0/lupa-1.7/lupa/tests/test.py", line 29, in setUp
    self.lua = lupa.LuaRuntime(**self.lua_runtime_kwargs)
  File "lupa/_lupa.pyx", line 208, in lupa._lupa.LuaRuntime.__cinit__
    raise LuaError("Failed to initialise Lua runtime")
lupa._lupa.LuaError: Failed to initialise Lua runtime