Revert "mautrix-telegram: add `prometheus-client` for metrics"
This reverts commit e484541615d76826b2da3240bce5e842d58fbb41.

$ nix-instantiate -A mautrix-telegram
error: undefined variable 'prometheus-client' at /home/src/nixpkgs/pkgs/servers/mautrix-telegram/default.nix:63:5