applyPatches: passthru outputHashAlog
Fixes evaluation of the find-tarballs.nix script used in the tarballs
mirror pipeline.

```
$ nix-instantiate --eval --json --strict maintainers/scripts/find-tarballs.nix --arg expr 'import maintainers/scripts/all-tarballs.nix' --show-trace
[...]
error:
       … while calling anonymous lambda
         at maintainers/scripts/find-tarballs.nix:3:1:
            2|
            3| {
             | ^
            4|   expr,

       … while evaluating uniqueFiles
         at maintainers/scripts/find-tarballs.nix:105:1:
          104| in
          105| uniqueFiles
             | ^
          106|

       … while calling the 'map' builtin
         at maintainers/scripts/find-tarballs.nix:26:17:
           25|
           26|   uniqueFiles = map (x: x.file) (genericClosure {
             |                 ^
           27|     startSet = map (file: {

       … while calling the 'genericClosure' builtin
         at maintainers/scripts/find-tarballs.nix:26:34:
           25|
           26|   uniqueFiles = map (x: x.file) (genericClosure {
             |                                  ^
           27|     startSet = map (file: {

       … while evaluating type
         at maintainers/scripts/find-tarballs.nix:28:28:
           27|     startSet = map (file: {
           28|       key = with file; (if type == null then "" else type + "+") + hash;
             |                            ^
           29|       inherit file;

       error: attribute 'outputHashAlgo' missing
       at maintainers/scripts/find-tarballs.nix:38:16:
           37|     isPatch = (drv ? postFetch && drv.postFetch != "");
           38|     type = drv.outputHashAlgo;
             |                ^
           39|     name = drv.name;
```

(cherry picked from commit f2aff81018ae4ad8a1e244335db7e77f6f7e8997)