tsm-client: use `libxcrypt-legacy` to fix build
Since commit 4e300e071b97e1e3a6ba4d856cc65e5386366f6f
building `tsm-client` fails with error messages

> error: auto-patchelf could not satisfy dependency libcrypt.so.1 wanted by [...]

Luckily, commit 9b766dd41b9b49cb0c1b1f3317fc2273f1f8f3a0
introduces `libxcrypt-legacy` which again provides `libcrypt.so.1`.