fix: remove allowAliases from python interpreter.
When attempting to build the latest unstable I am hitting:
```
 error: attribute 'allowAliases' missing
 at «https://releases.nixos.org/nixos/unstable/nixos-26.11pre1011622.a799d3e3886d/nixexprs.tar.xz?narHash=sha256-G5B1h4sOH4DN/RZ85xYi6zPm2MHdOrNMeUmMslZ28Qs%3D»/pkgs/development/interpreters/python/default.nix:213:24:
```

Reviewing the docs at [https://nixos.org/manual/nixpkgs/stable/#opt-allowAliases](nixpkgs manual), it says:

Nixpkgs should not depend on aliases in its internal code