bat: unvendor zlib; fix darwin
bat fails with
> error: failed to run custom build command for `libz-sys v1.1.8`
due to the vendored libz failing to build with clang-19

the apple-sdk_11 can also be removed as that is now the default for both
darwin x64 and aarch64