mautrix-signal: fix v11 migration for SQLite
When trying to upgrade from v0.3.0 to v0.4.1, the following error
occurs:

    sqlite3.OperationalError: unrecognized token: ":"

This is because the migration script was not written in ANSI SQL and
made use of the double-colon syntax for type casting (supported by
PostgreSQL and CockroachDB, but not SQLite).

This patch comes from the upstream repository and should be included
in the next release of mautrix-signal, so it seems likely that this
can be reverted when the package version is bumped.