flatpak: set sysconfdir
Otherwise, flatpak looks for configuration files inside the Nix store:

	$ flatpak list --installation=test -v
	F: No installations directory in /nix/store/gb76s3h00k2r95snjdxs3840sn3ab22f-flatpak-1.16.1/etc/flatpak/installations.d. Skipping
	error: Could not find installation test

This was previously fixed in 01189fb83231 ("flatpak: fix config
location") but lost in the conversion to Meson in
ae96b319207d ("flatpak: 1.14.10 -> 1.16.0").

(cherry picked from commit 8d747abaec96d58c3bdbaef4c6be69c445dd2efa)