shutter: fix runtime error (missing imagemagick)
Fixes this:

  $ shutter
  ERROR: imagemagick is missing --> aborting!

Due to 73f1f5eb3969743fe459e7cc36cfb766c7f5318a
("imagemagick: split dev output to fix #9604") which was committed in
the same period as shutter was added to nixpkgs.