python313Packages.smolagents: disable test requiring network access
It fails with

    AssertionError: assert 'Missing API Key' in '<ExceptionInfo litellm.APIError: APIError: GroqException - [Errno -3] Temporary failure in name resolution tblen=7>'