ueransim: backport `gcc-15` fix
Without the change the build fails on `master` as
https://hydra.nixos.org/build/320137255:

    /build/source/src/ext/yaml-cpp/emitterutils.cpp:221:11: error: 'uint16_t' was not declared in this scope
      221 | std::pair<uint16_t, uint16_t> EncodeUTF16SurrogatePair(int codePoint) {
          |           ^~~~~~~~

(cherry picked from commit 0eadfd334f4f6b3f540db3db17e260644fd5ac9c)