yubikey-manager4: drop
yubikey-manager-qt no longer uses this and it is broken, so remove it.

____________________ TestUtilityFunctions.test_parse_pkcs12 ____________________

self = <tests.test_util.TestUtilityFunctions testMethod=test_parse_pkcs12>

    def test_parse_pkcs12(self):
        with open_file("rsa_2048_key_cert.pfx") as rsa_2048_key_cert_pfx:
            data = rsa_2048_key_cert_pfx.read()

        key1, certs1 = _parse_pkcs12_cryptography(pkcs12, data, None)
>       key2, certs2 = _parse_pkcs12_pyopenssl(crypto, data, None)

tests/test_util.py:122:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
ykman/util.py:61: in _parse_pkcs12_pyopenssl
    p12 = crypto.load_pkcs12(data, password)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <module 'OpenSSL.crypto' from '/nix/store/si21r6n8pv695zp8jxx9x49rjaldvin9-python3.11-pyopenssl-23.3.0/lib/python3.11/site-packages/OpenSSL/crypto.py'>
attr = 'load_pkcs12'

    def __getattr__(self, attr: str) -> object:
>       obj = getattr(self._module, attr)
E       AttributeError: module 'OpenSSL.crypto' has no attribute 'load_pkcs12'