datamodel-code-generator: fix `mainProgram`
Currently running `nix run nixpkgs#datamodel-code-generator -- --help`
produces an error:

```
error: unable to execute '/nix/store/v99ll0sn384sv52fy4mhxdyqic6438hk-python3.13-datamodel-code-generator-0.71.0/bin/datamodel-code-generator': No such file or directory
```

because of:

```bash
$ nix build nixpkgs#datamodel-code-generator
$ ls -la result/bin/
.r-xr-xr-x 2.9k root  1 Jan  1970 .datamodel-codegen-wrapped
.r-xr-xr-x 1.8k root  1 Jan  1970 datamodel-codegen
```

(cherry picked from commit f35afa3df0d71ad8ea929a338138b12bb11f9859)