python3Packages.jsonrpclib-pelix: fix build with hatchling
Since the update in 64d32cc2aa01d8f3d8dbfceeb768b2b02e84a5aa ,
the build fails with

> setuptools.errors.InvalidConfigError: License classifiers have been superseded by license expressions (see https://peps.python.org/pep-0639/).

This is likely caused by the addition of `pyproject.toml` in
https://github.com/tcalmant/jsonrpclib/commit/987cbfff76500054e77d30b50cd38b781646f5c8

The new `pyproject.toml` mandates hatchling as build system.
Since non-pyproject.toml-build are deprecated,
we use the opportunity to migration the
build to pyproject.toml and hatchling.