cinnamon.cinnamon-common: use correct python for scrollbar-test-widget.py
Loading Themes module
Traceback (most recent call last):
  File "/xxxxxx/share/cinnamon/cinnamon-settings/bin/scrollbar-test-widget.py", line 6, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'

This file is being called as
Gio.Subprocess.new(['python3', '/xxxxxx/scrollbar-test-widget.py', str(self.content_widget.get_id())], Gio.SubprocessFlags.NONE)