guacamole-client: fix `tests` attribute eval
Without the change `tests` eval fails as:

    $ nix build --no-link -f. guacamole-client.tests
    error: attribute 'guacamole-client' missing

`guacamole-client` test was removed in a4e7f5011d86f966d
"nixos/tests: remove reference to non-existent test"