warpinator: fix "Connect manually" not working
When you clicked on "Connect manually" in the menu, nothing will happen
and in the console you see

```
  File "/nix/store/764ilfz0lhln19gx470fas661l9g7324-warpinator-1.8.10/libexec/warpinator/warpinator.py", line 839, in manual_connect
    self.connect_dialog = ManualConnectDialog(self)
                          ~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/nix/store/764ilfz0lhln19gx470fas661l9g7324-warpinator-1.8.10/libexec/warpinator/warpinator.py", line 1215, in __init__
    img = qr.make_image()
  File "/nix/store/8akrxjps12p9jgj3j26dd0av7iz04q3h-python3-3.13.7-env/lib/python3.13/site-packages/qrcode/main.py", line 364, in make_image
    from qrcode.image.pil import Image, PilImage
  File "/nix/store/8akrxjps12p9jgj3j26dd0av7iz04q3h-python3-3.13.7-env/lib/python3.13/site-packages/qrcode/image/pil.py", line 2, in <module>
    from PIL import Image, ImageDraw
ModuleNotFoundError: No module named 'PIL'

```

(cherry picked from commit 1cfea9657a3101a8ee7e794e268b3c52d11c1020)