chromiumBeta: Add curl as dependency to fix the build
This fixes the following build error:
[14969/46739] CXX obj/third_party/crashpad/crashpad/util/util/http_transport_libcurl.o[KK[K.o[KKy_reader.or.od.ooor_linux.mojom-shared.o
FAILED: obj/third_party/crashpad/crashpad/util/util/http_transport_libcurl.o
clang++ [...]
../../third_party/crashpad/crashpad/util/net/http_transport_libcurl.cc:17:10: fatal error: 'curl/curl.h' file not found
#include <curl/curl.h>
         ^~~~~~~~~~~~~
1 error generated.

(cherry picked from commit c0ead3d0c4ae8762be2fdbb0e191c285876dd904)