kakasi: avoid an implicit declaration of `exit`.
This caused the following false alarm:

```
error: can not use EUC-JP or UTF-8 encoding on iconv
```

See https://git.launchpad.net/ubuntu/+source/kakasi/commit/?h=applied/ubuntu/plucky&id=08f53a5.