python2Packages.hickle: disable
```
  Processing ./hickle-4.0.1-py2-none-any.whl
  ERROR: Package 'hickle' requires a different Python: 2.7.18 not in '>=3.5'
```

(cherry picked from commit f1325cdfe7da80f809c4c6f6d22a4d1a22c7422e)