fwbuilder: disable blanket `-Werror`
`-Werror` flag usually causes build failures due to minor changes in
compiler versions. They might be useful for developers themselves but
are rarely useful for distributions.

last time `fwbuilder` failed the build against newer `libxml2`:

    libfwbuilder/src/fwbuilder/XMLTools.cpp: In static member function 'static void libfwbuilder::XMLTools::initXMLTools()':
    libfwbuilder/src/fwbuilder/XMLTools.cpp:222:18: error: 'int xmlInitMemory()' is deprecated [-Werror=deprecated-declarations]
      222 |     xmlInitMemory();
          |     ~~~~~~~~~~~~~^~