jnetmap: 0.5.4 -> 0.5.5
This fixes a startup crash:

  $ jnetmap
  Exception in thread "main" java.lang.NoClassDefFoundError: edu/uci/ics/jung/graph/MultiGraph
  ...
  (exit code 1)

(cherry picked from commit c0c9af0824d2efc1771214a9586885068ed05a23)