ninja: refactor version,src
This patch fixes a problem with nix-prefetch (and thus a number of update
scripts) where it would throw the following error when run in nixpkgs:

```
error: attribute 'rev' missing
at pkgs/by-name/ni/ninja/package.nix:19:34:
   18|   pname = "ninja";
   19|   version = lib.removePrefix "v" finalAttrs.src.rev;
     |                                  ^
```

This seems to be caused by an oversight where nix-prefetch overrides
fetchFromGitHub in a weird way, where rev is not returned, but so far this
is the only package that is triggering this bug. The related issue in
nix-prefetch is still unhandled, hence this change.

See: msteen/nix-prefetch#54 #403032