Fix lnav-0.8.0 compilation.
nix-env -i lnav currently result of a failure:

    command_executor.cc:34:21: fatal error: pcrecpp.h: No such file or
    directory

This fixes by using pcre-cpp instead of pcre.

Signed-off-by: Vincent Demeester <vincent@sbr.pm>