llvm: Backport a patch that is required for llvmPackages_16
This comes from eb2eafd2af7d (or rather [0]). I only backported the
patch instead of the whole commit to avoid mass rebuilds for
llvmPackages 13 and 14 (there is a small diff in the patches due to the
headers ("index" and the line numbers)).

This fixes:
```
error (ignored): error: end of string reached
error: getting status of 'pkgs/development/compilers/llvm/common/clang/add-nostdlibinc-flag.patch': No such file or directory
```

[0]: pkgs/development/compilers/llvm/git/clang/add-nostdlibinc-flag.patch