yabai: fix hash
error: invalid SRI hash '1szyjcwkhn2wbrcfhh9lh5bnfm1cavxrx6xj4q7521z3zj29a9kf'
(cherry picked from commit 685f290786f872dc11336abe8624368b7ae3f264)