backintime-common: add missing dependency 'packaging'
Fixes this fatal startup error:

  $ nix-build -A backintime-common && ./result/bin/backintime
  [...]
  ModuleNotFoundError: No module named 'packaging'

Fixes https://github.com/NixOS/nixpkgs/issues/241966.