python3Packages.pydantic Disable docs build for python<3.10
It fails, because the examples require python3.10 to be executed.

```
WARNING: examples for 3.10+ requires python 3.10. They won't be executed
Traceback (most recent call last):
  File "/build/source/docs/build/main.py", line 31, in <module>
    sys.exit(main())
  File "/build/source/docs/build/main.py", line 27, in main
    return exec_examples()
  File "/build/source/docs/build/exec_examples.py", line 354, in exec_examples
    versions.extend(populate_upgraded_versions(file, file_text, lowest_version))
  File "/build/source/docs/build/exec_examples.py", line 294, in populate_upgraded_versions
    new_file.write_text(upgraded_file_text)
  File "/nix/store/9pilxd2znfsj64ybyg8lmgql9vy3fq4g-python3-3.9.16/lib/python3.9/pathlib.py", line 1285, in write_text
    with self.open(mode='w', encoding=encoding, errors=errors) as f:
  File "/nix/store/9pilxd2znfsj64ybyg8lmgql9vy3fq4g-python3-3.9.16/lib/python3.9/pathlib.py", line 1252, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/nix/store/9pilxd2znfsj64ybyg8lmgql9vy3fq4g-python3-3.9.16/lib/python3.9/pathlib.py", line 1120, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/build/source/docs/.tmp_examples/upgraded/dataclasses_default_schema_3_9.py'
make: *** [Makefile:118: docs] Error 1
```