Disable Rust doctests on Darwin.
Since Rust 1.30 (?) some Rust crates do not build, see e.g. #49693 and #49708
and fail with:

dyld: Symbol not found: __ZTIN4llvm2cl18GenericOptionValueE

So far, the common pattern seems to be that the linking fails in doctests. This
change is a temporary workaround that disables doctests for Rust crates on
Darwin. This avoids the need to patch individual derivations and still runs
library tests.