gnucash: fix missing gobject-introspection
 ➜ ./result/bin/gnucash
Traceback (most recent call last):
  File "/nix/store/1rm7rm8izpdyy8v53ybcr244hm010m07-gnucash-5.11/share/gnucash/python/init.py", line 6, in <module>
    from gi import require_version
ModuleNotFoundError: No module named 'gi'