python312Packages.openusd: fix build on darwin
Due to an update to Clang 19 the compiler got stricter
and will fail with

```
error: no member named '_Set' in 'SdfChildrenProxy<_View>'
```

Upstream has merged an fix, which this commit will pull

Signed-off-by: Florian Brandes <florian.brandes@posteo.de>