When packaging rubygems, prune git repos from the bundler cache:
There's a comment not far above this indicating that it's important to
*not* purge the cache, but consider this case:

    gem 'rails', git: 'https://github.com/rails/rails.git'

Since rails depends on several other gems from its own repository, this
results in the Gemfile.lock stanza:

    GIT
      remote: https://github.com/rails/rails.git
      revision: c2093cdf8e48ccc4211195c3523319a1767a205a
      specs:
        actioncable (6.0.0.beta3)
          ...(some dependents)...
        actionmailbox (6.0.0.beta3)
          ...(some dependents)...
        actionmailer (6.0.0.beta3)
          ...(some dependents)...
        ...(and 10 more)...

Rails is a 200MB+ repo, so when building this, it results in 2.6GB+ of
space usage. But even more importantly, nixpkgs will link everything
under `lib/` currently, which includes, in this case, the redundant
copies of `$out/${ruby.gemPath}/cache/bundler/git/rails-<sha>`:

    these derivations will be built:
      /nix/store/rxsi3i9bkmyw93h5xn99mhw5il59w7sx-your-package.drv
    building '/nix/store/rxsi3i9bkmyw93h5xn99mhw5il59w7sx-your-package.drv'...
    collision between `/nix/store/5qvwx0qyhx19vswg0cv3zdzn18qc8fn7-ruby2.5.5-actiontext-6.0.0.beta3/lib/ruby/gems/2.5.0/cache/bundler/git/rails-fcf0202857b07db1a0f6220dae5ca99319ca0f32/objects/info/packs' and `/nix/store/hybin7vdghvb81sb3j9g4yyym6j2wkh3-ruby2.5.5-actioncable-6.0.0.beta3/lib/ruby/gems/2.5.0/cache/bundler/git/rails-fcf0202857b07db1a0f6220dae5ca99319ca0f32/objects/info/packs'
    builder for '/nix/store/rxsi3i9bkmyw93h5xn99mhw5il59w7sx-your-package.drv' failed with exit code 255
    error: build of '/nix/store/rxsi3i9bkmyw93h5xn99mhw5il59w7sx-your-package.drv' failed

Long story short, keeping the whole git repo around feels pathological
from the get-go, but I'm not sure how to resolve this conflict at all
without pruning it. This is distinctly different from a gem cache where
a `*.gem` can only ever correspond to one installed gem.