foundationdb: fix "was not declared" build errors
Since glibc 2.28, `<sys/types.h>` no longer includes
`<sys/sysmacros.h>`, which provides these macros,
so we have to explicitly import the latter, too, to fix the following
build problems:

    flow/Platform.cpp: In function 'void getDiskStatistics(const string&, uint64_t&, uint64_t&, uint64_t&, uint64_t&, uint64_t&, uint64_t&)':
    flow/Platform.cpp:626:56: error: 'gnu_dev_major' was not declared in this scope
       if(majorId == (unsigned int) gnu_dev_major(buf.st_dev) && minorId == (unsigned int) gnu_dev_minor(buf.st_dev)) {
                                                            ^
    flow/Platform.cpp:626:111: error: 'gnu_dev_minor' was not declared in this scope
       if(majorId == (unsigned int) gnu_dev_major(buf.st_dev) && minorId == (unsigned int) gnu_dev_minor(buf.st_dev)) {
                                                                                                                   ^

(cherry picked from commit 4406883af179fc5962302b07ee6ce511f6f81d94)