vcstools: fix dependencies
missing setuptools

```
$ ./results/vcstool/bin/vcs --help
Traceback (most recent call last):
  File "/nix/store/m9w0gapwnwffhnvyv3ds14mgbx2p5y93-vcstool-0.2.7/bin/.vcs-wrapped", line 6, in <module>
    from vcstool.commands.vcs import main
  File "/nix/store/m9w0gapwnwffhnvyv3ds14mgbx2p5y93-vcstool-0.2.7/lib/python3.7/site-packages/vcstool/commands/vcs.py", line 5, in <module>
    from vcstool.commands.help import get_entrypoint
  File "/nix/store/m9w0gapwnwffhnvyv3ds14mgbx2p5y93-vcstool-0.2.7/lib/python3.7/site-packages/vcstool/commands/help.py", line 6, in <module>
    from pkg_resources import load_entry_point
ModuleNotFoundError: No module named 'pkg_resources'
```