libbacktrace: Enable tests
Only on Linux since they will fail on Darwin:

    dsymutil btest
    error: cannot parse the debug map for 'btest': The file was not recognized as a valid object file
    make[1]: *** [Makefile:2584: btest.dSYM] Error 1