screen: disable parallel build
Parallel build fails for missing generated header dependencies:

    screen.h:48:10: fatal error: comm.h: No such file or directory
        48 | #include "comm.h"
           |          ^~~~~~~~

Upstream fixes are intermingled with added features and are not
straightforward to backport. Let's disable parallelism until next
release.