qt5.qtwebengine: use the 13.3 SDK because the 14.4 SDK does not work
While the 14.4 SDK works to build the rest of Qt 5, building Qt
WebEngine fails with errors like the following:

    In file included from gen/base/base_jumbo_37.cc:14:
    In file included from ./../../3rdparty/chromium/base/mac/mach_port_rendezvous.cc:16:
    In file included from ../../3rdparty/chromium/base/mac/foundation_util.h:34:
    In file included from /nix/store/sfdyfscmykycv7nfscn551lyl3gf4n27-apple-sdk-14.4/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/ApplicationServices.framework/Headers/ApplicationServices.h:39:
    In file included from /nix/store/sfdyfscmykycv7nfscn551lyl3gf4n27-apple-sdk-14.4/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreText.framework/Headers/CoreText.h:26:
    In file included from /nix/store/sfdyfscmykycv7nfscn551lyl3gf4n27-apple-sdk-14.4/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreText.framework/Headers/CTFramesetter.h:21:
    In file included from /nix/store/sfdyfscmykycv7nfscn551lyl3gf4n27-apple-sdk-14.4/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreText.framework/Headers/CTTypesetter.h:20:
    /nix/store/sfdyfscmykycv7nfscn551lyl3gf4n27-apple-sdk-14.4/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreText.framework/Headers/CTLine.h:138:5: error: unknown type name 'CFAttributedStringRef'; did you mean 'CFMutableStringRef'?
        CFAttributedStringRef attrString ) CT_AVAILABLE(macos(10.5), ios(3.2), watchos(2.0), tvos(9.0));
        ^
    /nix/store/sfdyfscmykycv7nfscn551lyl3gf4n27-apple-sdk-14.4/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFBase.h:500:70: note: 'CFMutableStringRef' declared here
    typedef struct CF_BRIDGED_MUTABLE_TYPE(NSMutableString) __CFString * CFMutableStringRef;
                                                                     ^