zoom-us: 6.7.5.6891 -> 7.0.0.1666
This update brings some changes in dependencies.
Major change is apparently migration from qt5 to qt6.

I added some new dependencies, based on

* `.PKGINFO` in the "source" archive
* report by `autoPatchelf`
* error messages when invoking zoom

Caution: One dependency is missing, as `autoPatchelf` complains:

> error: auto-patchelf could not satisfy dependency libQt6Bodymovin.so.6 wanted by /nix/store/................................-zoom-7.0.0.1666/opt/zoom/Qt/qml/Qt/labs/lottieqt/liblottieqtplugin.so

I failed to locate a package within
nixpkgs which contains that library.
The internet suggests `qtlottie`, but our
`qt6.qtlottie` doesn't contain the required library file.

I also used the oppurtunity to drop some dependencies
where I couldn't determine how/why they might be needed.
Some of them might still be needed,
but I want to avoid infinite accumulation of dependencies,
and removing them is the only way to find out.
Also, a major update seems to be the best
opportunity to perform such a cleanup.

Co-authored-by: R. RyanTM <ryantm-bot@ryantm.com>