lxcfs.tests: update `incus.container` reference
Without the change the test build attempt fails the evaluation as:

    $nix build --no-link -f. lxcfs.tests
       error: attribute 'container' missing

       at pkgs/os-specific/linux/lxcfs/default.nix:64:23:

           63|   passthru.tests = {
           64|     incus-container = nixosTests.incus.container;
             |                       ^

This started happening after `container` test was split in two in
c607e70f7053 "nixosTests.incus: add test with old and new init".