postgresqlPackages.plv8: install all files
Previously, the update complained due to missing migration files:

	db=# alter extension plv8 update to '2.3.15';
	ERROR:  extension "plv8" has no update path from version "2.3.13" to version "2.3.15"

Now it fails for a different reason:

	db=# alter extension plv8 update to '2.3.15';
	ERROR:  could not access file "$libdir/plv8-2.3.13": No such file or directory

Changing installation directory using DESTDIR is an ugly hack that might backfire
but PGXS does not currently seem to allow overriding the installation directory.