pythonPackages.Babel: Fix use of glibcLocales, skip musl tests. Fixes #74904.
The test failure:

    File "/build/Babel-2.7.0/babel/messages/pofile.py", line 325, in _invalid_pofile
      print(u"WARNING: Problem on line {0}: {1}".format(lineno + 1, line))
    UnicodeEncodeError: 'ascii' codec can't encode character u'\xe0' in position 84: ordinal not in range(128)

occurs in either of these cases:

* glibc is used and `glibcLocales` is not a `buildInput`
* musl is used and tests are run

`python3Packages.Babel` does not have this problem, on either glibc
or musl.

I also found that the `preCheck` `export LC_ALL="en_US.UTF-8"` is not
necessary in any case.

With this commit,

    python27Packages.Babel
    python3Packages.Babel
    pkgsMusl.python27Packages.Babel
    pkgsMusl.python3Packages.Babel

all build.