libsForQt5.mapbox-gl-native: mark broken (`gcc-13` build failure)
The build fails against `gcc-13` on `master` as
https://hydra.nixos.org/build/247923347:

    /build/source/include/mbgl/util/geometry.hpp:9:6: error: elaborated-type-specifier for a scoped enum must not use the 'class' keyword [-Werror]
        9 | enum class FeatureType : uint8_t {
          | ~~~~ ^~~~~

Following suggestion of package removal by marking it broken first:
https://github.com/NixOS/nixpkgs/pull/284574#issuecomment-1913688797