fetchurl: Improve error messages
I recently saw this error message, which required I use the `--debugger`
to locate:

```
error:
       … while evaluating an expression to select 'drvPath' on it
         at «internal»:1:552:
       … while calling the 'derivationStrict' builtin
         at «internal»:1:208:
       (stack trace truncated; use '--show-trace' to show the full trace)

       error: multiple hashes passed to fetchurl
```

This patch improves the error message, and other error messages from
`fetchurl`:

```
error:
       … while evaluating an expression to select 'drvPath' on it
         at «internal»:1:552:
       … while calling the 'derivationStrict' builtin
         at «internal»:1:208:
       (stack trace truncated; use '--show-trace' to show the full trace)

       error: multiple hashes passed to fetchurl: [
         "https://github.com/reorg/pg_repack/archive/refs/tags/ver_1.5.0.tar.gz"
       ]
```