ldb: fix cross & add libxcrypt
ERROR: Python module pytdb of version 1.4.7 not found, and bundling disabled
(cherry picked from commit 0d4a49af8670cf2adf2e23a65830ca4e0bdbe4b2)