dataexplorer: pin jdk17
Since the default jdk changed to jdk19, DataExplorer fails at startup:

```console
$ ./result/bin/DataExplorer
java.lang.NullPointerException: Cannot read field "width" because the return value of "gde.config.Settings.getWindow()" is null
	at gde.ui.DataExplorer.execute(DataExplorer.java:406)
	at gde.GDE.main(GDE.java:544)
```

Therefore, pin to jdk17, which is also the latest recommended version by
upstream:

> The only requirement is the installation of a Java run-time of version
> 8 to Java 17 for the 32 bit versions and Java 11 to 17 for the 64 bit
> versions, such as IcedTea or open JDK.

https://www.nongnu.org/dataexplorer/index.html#Introduction