stdenvBootstrapTools: revert "inherit {cross,local}System"
This reverts commit 5643714dea562f0161529ab23058562afeff46d0.

The change was based on e663518d ("all-packages.nix: add bootstrapTools
to top-level.nix"). Unfortunately that change had intended side-effect
in releases.nix that turned stdenvBootstrapTools into a no-op.

As a result 5643714dea562 "stdenvBootstrapTools: inherit {cross,local}System"
change dropped the locaSystem argument without evaluation failure.

Once the accidental change was fixed unexpected `localSystem` parameter
started failing evals:

    $ nix build -f pkgs/top-level/release.nix stdenvBootstrapTools.x86_64-linux.dist
    error: anonymous function at pkgs/stdenv/linux/make-bootstrap-tools.nix:1:1 called with unexpected argument 'localSystem'

       at /home/slyfox/dev/git/nixpkgs-master/pkgs/top-level/release.nix:169:16:

          168|             inherit
          169|               (import ../stdenv/linux/make-bootstrap-tools.nix {
             |                ^
          170|                 localSystem = { inherit system; };

Let's roll it back cleanly to restore stdenvBootstrapTools builds on hydra.