nixos/sshd: Allow UsePAM being null
This commit allows setting the `UsePAM` setting to null. Without it, nix
fails to evaluate with:
```
error: ‘mkIf’ called with a non-Boolean condition
```

Setting it to null means no line for `UsePAM` is written into the
resulting sshd config file. This is needed if openssh is compiled
without PAM support. Otherwise the following log message is produced:
```
rexec line 15: Unsupported option UsePAM
```

This also adds the nixos test openssh-null-pam to set `UsePAM` to null.
This also tests that the above log line is not produced in that case.