actual-server.webUi: remove non-existent attribute
Before ther change `actual-server` exported unevaluatable `webUi`
attribute:

    $ nix eval --impure --expr 'with import ./. {}; actual-server.webUi'
    error:
       … while evaluating the attribute 'webUi'
         at pkgs/by-name/ac/actual-server/package.nix:111:39:
          110|   passthru = {
          111|     inherit (finalAttrs) offlineCache webUi;
             |                                       ^
          112|     tests = nixosTests.actual;

       error: attribute 'webUi' missing
       at pkgs/by-name/ac/actual-server/package.nix:111:39:
          110|   passthru = {
          111|     inherit (finalAttrs) offlineCache webUi;
             |                                       ^
          112|     tests = nixosTests.actual;

(cherry picked from commit 74d37cf3481117423817fa0d605f4945a6417030)