vimix-icon-theme: lowercase `colorVariants` when passed to install.sh
When attempting to overlay this package and customize the `colorVariants`, the build fails. For example, this overlay:


```nix
vimix-icon = variant: prev.vimix-icon-theme.override { colorVariants = [variant]; };

```

Results in:

```
error: builder for '/nix/store/6kvvwn2yhmbqgvm66jgr684sc34jbf7q-vimix-icon-theme-2025.02.10.drv' failed with exit code 1;
       last 15 log lines:
       > Running phase: unpackPhase
       > unpacking source archive /nix/store/fj2xx34nlbq6g5sbnbxvkjiajp78aa30-source
       > source root is source
       > Running phase: patchPhase
       > patching script interpreter paths in install.sh
       > install.sh: interpreter directive changed from "#!/bin/bash" to "/nix/store/11ciq72n4fdv8rw6wgjgasfv4mjs1jrw-bash-5.2p37/bin/bash"
       > Running phase: updateAutotoolsGnuConfigScriptsPhase
       > Running phase: configurePhase
       > no configure script, doing nothing
       > Running phase: buildPhase
       > no Makefile or custom buildPhase, doing nothing
       > Running phase: glibPreInstallPhase
       > Running phase: installPhase
       > ERROR: Unrecognized installation option 'Beryl'.
       > Try './install.sh -h' for more information.
```


This seems to be due to https://github.com/vinceliuice/Vimix-icon-theme/commit/4dae8dfe14b41a1313a9fdc4c72c3a2b4950e173