mars: fix build on gcc-10
Without the change build fails due to gcc-11/gcc-10 libstdc++ mix:

    [100%] Linking CXX executable ../../marsshooter
    ld: .../libsfml-graphics.so.2.5.1: undefined reference to `std::__throw_bad_array_new_length()@GLIBCXX_3.4.29'
    collect2: error: ld returned 1 exit status