pantalaimon: fix startup
Fixes: ImportError: cannot import name GLib, introspection typelib not found
(cherry picked from commit 750a94a55122cb65426d067c13f93c388de18702)