phash: compilation fixes
This includes a patch already sent upstream that fixes compilation with Werror due to a lacking return, as well as adding a linker flag to include a threaded version of a library.
The fftw3_threads part stems from cimg requiring this apparently when linking the examples:

> test_texthash.cpp:(.text.startup+0x1c1): undefined reference to `fftw_init_threads'

I wouldn't know how to patch this upstream, however other packages in nixpkgs seem to provide the LDFLAGS too.

Signed-off-by: benaryorg <binary@benary.org>