nickel: nixVersions.nix_2_24 -> nixVersions.nix_2_28
1.12.2 doesn't build with nix 2.24 (with enableNixImport) because of the import
reorganization in 2.28:

> cpp/nix.hh:3:10: fatal error: nix/expr/primops.hh: No such file or directory

This is the case starting from 1.12.0 [1]:

[1]: https://github.com/tweag/nickel/commit/f58ca43228eca4fee2e554503cc4194c3d6c3f06