nixos/resolved: Disable resolvconf when enabled
Fixes #353225
Possibly fixes #445496

When a reference is made between users.groups and environment.etc,
the entire NixOS system configuration will fail to evaluate due to
an infinte recursion between the resolved and resolvconf modules.
Example (from building .#nixosTests.containers-hosts):

```
       … while evaluating definitions from `/nix/store/5djjm1dipmdh82issrmpfjdplp7hk0pp-source/nixos/modules/services/logging/logrotate.nix':

       … while evaluating the option `containers.netmask.services.logrotate.enable':

       … while evaluating the option `containers.netmask.users.groups':

       … while evaluating definitions from `/nix/store/5djjm1dipmdh82issrmpfjdplp7hk0pp-source/nixos/modules/config/resolvconf.nix':

       … while evaluating the option `containers.netmask.networking.resolvconf.enable':

       … while evaluating the option `containers.netmask.environment.etc':

       … while evaluating definitions from `/nix/store/5djjm1dipmdh82issrmpfjdplp7hk0pp-source/nixos/modules/services/logging/logrotate.nix':

       (stack trace truncated; use '--show-trace' to show the full, detailed trace)

       error: infinite recursion encountered
       at /nix/store/5djjm1dipmdh82issrmpfjdplp7hk0pp-source/lib/modules.nix:1512:13:
         1511|     _type = "if";
         1512|     inherit condition content;
             |             ^
         1513|   };
```