tint2: fix build
Apparently this subproject was missing an explicit dependency on libm

Fixes

```
> /nix/store/9g4gsby96w4cx1i338kplaap0x37apdf-binutils-2.43.1/bin/ld: CMakeFiles/tint2conf.dir/__/util/common.c.o: undefined reference to symbol 'log10@@GLIBC_2.2.5'
> /nix/store/9g4gsby96w4cx1i338kplaap0x37apdf-binutils-2.43.1/bin/ld: /nix/store/6q2mknq81cyscjmkv72fpcsvan56qhmg-glibc-2.40-66/lib/libm.so.6: error adding symbols: DSO missing from command line
> collect2: error: ld returned 1 exit status
```