opencascade-occt: fix compilation on darwin (#365409)
```
FAILED: src/TKV3d/CMakeFiles/TKV3d.dir/__/StdPrs/StdPrs_BRepFont.cxx.o
/nix/store/raqax5qp65an4jcwj1bzd5lq589ywpg0-clang-wrapper-16.0.6/bin/clang++ -DHAVE_FREETYPE -DHAVE_OPENGL -DHAVE_OPENGL_EXT -DHAVE_TK -DOCC_CO>
/tmp/nix-build-opencascade-occt-7.8.1.drv-0/occt-V7_8_1-bd2a789/src/StdPrs/StdPrs_BRepFont.cxx:460:17: error: cannot initialize a variable of t>
    const char* aTags      = &anOutline->tags[aStartIndex];
                ^            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

(cherry picked from commit 159385c1aec83734ea490c762925647846f749b6)