gnu-efi: fix musl build
gnu-efi> /build/gnu-efi-3.0.17//lib/console.c:84:68: error: passing argument 2 of ‘ConOut->OutputString’ from incompatible pointer type [8;;h
ttps://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wincompatible-pointer-types-Werror=incompatible-pointer-types8;;]
gnu-efi>    84 |                 uefi_call_wrapper(ConOut->OutputString, 2, ConOut, L"\b \b");
gnu-efi>       |                                                                    ^~~~~~~~
gnu-efi>       |                                                                    |
gnu-efi>       |                                                                    short unsigned int *

(cherry picked from commit d5fa9726414a185463203d2c7af211cca6a89e40)