elfutils: Fix header compatibility with glibc 2.21
Regression introduced by df2b9b48cbf8eb765760c699843e43457d844bee.

This breaks the build for ltrace and other programs using libelf,
because the header file relies on features from glibc >= 2.22.

Here is an excerpt from the log output of the configure script from
ltrace:

In file included from ...elfutils-0.165/include/gelf.h:32:0,
                 from conftest.c:57:
...elfutils-0.165/include/libelf.h:280:8: error: unknown type name 'Elf32_Chdr'
 extern Elf32_Chdr *elf32_getchdr (Elf_Scn *__scn);
        ^
...elfutils-0.165/include/libelf.h:281:8: error: unknown type name 'Elf64_Chdr'
 extern Elf64_Chdr *elf64_getchdr (Elf_Scn *__scn);
        ^
In file included from conftest.c:57:0:
...elfutils-0.165/include/gelf.h:89:9: error: unknown type name 'Elf64_Chdr'
 typedef Elf64_Chdr GElf_Chdr;
         ^

The issue has been reported in the Debian bug tracker at
https://bugs.debian.org/810885 and I'm using the patch from Mark
Wielaard that has been posted there which adds compatibility for older
glibc versions.

Signed-off-by: aszlig <aszlig@redmoonstudios.org>