timedoctor: remove broken uninstallable package
The package fails t install as it requires x86_64-linux, but it's
dependency requires i686 linux:

    $ nix build --no-link -f. timedoctor --show-trace
    error: unsupported CPU i686

       … while evaluating the attribute 'version'

       at pkgs/development/compilers/adoptopenjdk-bin/jdk-linux-base.nix:40:3:

           39|
           40|   version = sourcePerArch.${cpuName}.version or (throw "unsupported CPU ${cpuName}");
             |   ^

I only onticed it because it uses `xorg.libXaw3d` while nothing else does.

Let's remove it.