pitivi: unbreak build
[Breakage introduced in commit 5c4e00b6b797c444c0a0ca434c3b6f
("gst_all_1: 1.6.1 -> 1.8.0 (#14628)").]

The build is failing due to a Wayland test/example program
(<gst-plugins-bad>/tests/examples/waylandsink) being built with a gtk3
input without Wayland support (or detection is failing):

  main.c:28:2: error: #error "Wayland is not supported in GTK+"

Fix it by explicitly disabling wayland; pass --enable-wayland=no to
configure.