pax-utils: enable seccomp and fuzzong only on `linux`
On `darwin` the build fails on missing `memfd_create()` symbols as
https://hydra.nixos.org/build/314413362:

    ../fuzz-ar.c:18:7: error: call to undeclared function 'memfd_create'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
       18 |         fd = memfd_create("fuzz-input.a", MFD_CLOEXEC);
          |              ^