uhexen2: fix the build against SDL_compat
Without the change build fails due to missing libraries as
https://hydra.nixos.org/build/294936344:

    ../h2shared/glheader.h:40:10: fatal error: GL/gl.h: No such file or directory
       40 | #include <GL/gl.h>
          |          ^~~~~~~~~