mariadb: Fix build on darwin
TokuDB is not supported and does not compile on darwin.

https://mariadb.com/kb/en/mariadb/enabling-tokudb/
https://github.com/Homebrew/homebrew/commit/a14984cd174fb01221a3cb3058732b4f4855e428

Setting '-Wno-error=cpp' causes errors:

    error: unknown warning option '-Werror=cpp' [-Werror,-Wunknown-warning-option]