lib.makeOverridable: Propagate function arguments
Previously when using `.override` of overridable derivations, it was
impossible to know which arguments it accepts, because the function
argument aren't propagated:

  > lib.functionArgs pkgs.hello.override
  { }
  > pkgs.hello.override { foo = 0; }
  error: anonymous function at /nixpkgs/pkgs/applications/misc/hello/default.nix:1:1 called with unexpected argument 'foo', at /nixpkgs/lib/customisation.nix:69:12
  > pkgs.hello.override { stdenv = pkgs.gccStdenv; }
  { name = "hello-2.10"; ... }

With this change, lib.functionArgs works according to intuition:

  > lib.functionArgs pkgs.hello.override
  { fetchurl = false; stdenv = false; }

Note that builtins.functionArgs does not work with this:

  > builtins.functionArgs pkgs.hello.override
  error: 'functionArgs' requires a function, at (string):1:21

This is due to how lib.setFunctionArgs is implemented: It actually
creates an attribute set with an attribute __functor for the function
and __functionArgs for the arguments. Nix can pretend such attributes to
be functions when they have __functor, but builtins.functionArgs doesn't
automatically use __functionArgs. That's why lib.functionArgs needs to
be used, which checks for the __functionArgs attribute.