hugin: use glew-egl to fix startup crash
Currently, hugin crashes on startup with an unhelpful

ERROR: 21:14:22.923574 (/build/hugin-2021.0.0/src/hugin1/hugin/GLViewer.cpp:133) SetUpContext(): Error initialising GLEW: Unknown error.

As outlined in [1], this is caused by glew being compiled without egl
support. As such, switching to glew-egl fixes the problem and hugin
starts up fine.

[1]: https://bbs.archlinux.org/viewtopic.php?id=278127