sqlar: fix build error
Disable warnings to be treated as errors, since otherwise the build
would fail with this message:

```
sqlite3.c: In function 'sqlite3SelectNew':
sqlite3.c:116663:10: error: function may return address of local variable [8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wreturn-local-addr-Werror=return-local-addr8;;]
116663 |   return pNew;
```