wasmtime: fix build on aarch64-darwin
The check phase fails on aarch64-darwin because of:

```
$ nix-build -A wasmtime
...
buildPhase completed in 1 minutes 41 seconds
Running phase: checkPhase
Executing cargoCheckHook
++ cargo test -j 10 --profile release --target aarch64-apple-darwin --frozen -- --test-threads=10
...
       >   error: linker `rust-lld` not found
       >     |
       >     = note: No such file or directory (os error 2)
       >
       >   error: could not compile `wasi-preview1-component-adapter` (lib) due to 1 previous error
```

I tried to bring `lld` into scope and set `RUSTFLAGS = "-C linker=lld`
but I couldn't get the tests to build. So I just disabled them on aarch64-darwin.

(cherry picked from commit cca07f139dc2b01fee4f241d43b450a8df4b2e89)