cdk: enable and fix parallel build
Without the change parallel build occasionally fails due to missing
dependency on generated headers:

Fixes the follow build failure on make -j16:

    build flags: -j16 -l16 SHELL=/bin/bash
    bash ./gen-scale.sh DSCALE DScale Double double ./include/gen-scale.h>include/dscale.h
    bash ./gen-scale.sh FSCALE FScale Float float ./include/gen-scale.h>include/fscale.h
    bash ./gen-scale.sh FSLIDER FSlider Float float ./include/gen-slider.h>include/fslider.h
    bash ./gen-scale.sh SCALE Scale Int int ./include/gen-scale.h>include/scale.h
    gcc -g -O2  -DHAVE_CONFIG_H -I./include -I./include -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=500 -D_XOPEN_SOURCE_EXTENDED -c cdkscreen.c
    gcc -g -O2  -DHAVE_CONFIG_H -I./include -I./include -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=500 -D_XOPEN_SOURCE_EXTENDED -c debug.c
    In file included from ./include/cdk_int.h:13,
                     from cdkscreen.c:1:
    ./include/cdk.h:321:10: fatal error: uscale.h: No such file or directory
      321 | #include <uscale.h>
          |          ^~~~~~~~~~