haxor-news: unstable-2020-10-20 -> unstable-2022-04-22
Package was not building with error, I removed the manual package
overrides and it built fine.

Also updated to the most recent unstable commit afterwards.

From what I tested it seems to work fine.

```
error: builder for '/nix/store/15l75w52cxc77zwdqv2w41cz0sylky0q-python3.13-prompt-toolkit-1.0.18.drv' failed with exit code 1;
       last 21 log lines:
       > Sourcing python-remove-tests-dir-hook
       > Sourcing python-catch-conflicts-hook.sh
       > Sourcing python-remove-bin-bytecode-hook.sh
       > Sourcing pypa-build-hook
       > Using pypaBuildPhase
       > Sourcing python-runtime-deps-check-hook
       > Using pythonRuntimeDepsCheckHook
       > Sourcing pypa-install-hook
       > Using pypaInstallPhase
       > Sourcing python-imports-check-hook.sh
       > Using pythonImportsCheckPhase
       > Sourcing python-namespaces-hook
       > Sourcing python-catch-conflicts-hook.sh
       > Sourcing pytest-check-hook
       > Using pytestCheckPhase
       > Running phase: unpackPhase
       > unpacking source archive /nix/store/hxiafm537za17sivpcljvqr6qlsclc8n-prompt_toolkit-1.0.18.tar.gz
       > source root is prompt_toolkit-1.0.18
       > setting SOURCE_DATE_EPOCH to timestamp 1570133629 of file "prompt_toolkit-1.0.18/setup.cfg"
       > Running phase: patchPhase
       > substitute(): ERROR: file 'src/prompt_toolkit/__init__.py' does not exist
       For full logs, run:
         nix log /nix/store/15l75w52cxc77zwdqv2w41cz0sylky0q-python3.13-prompt-toolkit-1.0.18.drv
```

(cherry picked from commit d6966c3ef22eb2bfbb4c72600fc85ad74deb7a9a)
Signed-off-by: Matthias Beyer <mail@beyermatthias.de>