firefox-esr-128-unwrapped: fix build on darwin
The patch fixes the following failure:

Perma error[E0412]: cannot find type `_Allocator` in this scope

Signed-off-by: Ihar Hrachyshka <ihar.hrachyshka@gmail.com>
(cherry picked from commit e2908c536e25c722d2984ef4a3fd08bbb2c71df6)