Revert "pkgs/top-level/release.nix.nix: Use fetchGit if possible"
This reverts commit 67d0a57ef9eedde69192e08db77751c1c1062e0e.

which caused evaluation errors in restricted eval mode, producing:

error: access to URI
'/var/lib/ofborg/checkout/repo/38dca4e3aa6bca43ea96d2fcc04e8229/mr-est/eval-1-lassulus.ewr1.nix.ci' is
forbidden in restricted mode