python2Packages.cytoolz: disable
no longer compatibled with python2

```
    File "cytoolz/itertoolz.pyx", line 15, in init cytoolz.itertoolz
      from itertools import chain, islice, zip_longest
  ImportError: cannot import name zip_longest
```