nix-required-mounts: Gracefully exit when derivation is absent
When derivation is absent, current code would prevent the build and
produce an unexpected error like this:

  ERROR:root:/nix/store/qs3g6m1yyms1l9qhqwkvwh5jb7a6n9as-pre-eval.drv doesn't exist. Cf. https://github.com/NixOS/nix/issues/9272 Exiting the hook
  ERROR:root:Couldn't parse the output of`nix show-derivation`. Expected JSON, observed:
  ERROR:root:
  Traceback (most recent call last):
    File "/nix/store/kw6y875jj193lzzzisqj1vjib8jrhfa0-nix-required-mounts-0.0.1/bin/.nix-required-mounts-wrapped", line 9, in <module>
      sys.exit(entrypoint())
               ~~~~~~~~~~^^
    File "/nix/store/kw6y875jj193lzzzisqj1vjib8jrhfa0-nix-required-mounts-0.0.1/lib/python3.13/site-packages/nix_required_mounts.py", line 294, in entrypoint
      parsed_drv: dict = parse_derivation(args.derivation_path, args.nix_exe)
                         ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/nix/store/kw6y875jj193lzzzisqj1vjib8jrhfa0-nix-required-mounts-0.0.1/lib/python3.13/site-packages/nix_required_mounts.py", line 91, in parse_derivation
      [canon_drv_path] = parsed_drv.keys()
                         ^^^^^^^^^^
  UnboundLocalError: cannot access local variable 'parsed_drv' where it is not associated with a value

Fix this by actually exiting as the log suggests instead of letting
Python eat its tail.

This lets us use builders with nix-required-mounts for regular remote
builds without pushing derivations to them.

(cherry picked from commit de49de0a75f67628ad0edfc18c77c2600be4931e)