poke: mark aarch64-darwin as a bad platform
Jitter fails to compile on aarch64-darwin:

Undefined symbols for architecture arm64:
  "_jitter_print_context_kind_destroy", referenced from:
      _jitter_print_libtextstyle_finalize in libjitter-libtextstyle.a(jitter-print-libtextstyle.o)
  "_jitter_print_context_kind_make_trivial", referenced from:
      _jitter_print_libtextstyle_initialize in libjitter-libtextstyle.a(jitter-print-libtextstyle.o)
  "_jitter_print_context_make", referenced from:
      _jitter_print_context_make_libtextstyle in libjitter-libtextstyle.a(jitter-print-libtextstyle.o)
     (maybe you meant: _jitter_print_context_make_libtextstyle)
  "_ostream_flush", referenced from:
      _jitter_print_context_libtextstyle_flush in libjitter-libtextstyle.a(jitter-print-libtextstyle.o)
  "_ostream_write_mem", referenced from:
      _jitter_print_context_libtextstyle_print_chars in libjitter-libtextstyle.a(jitter-print-libtextstyle.o)
  "_styled_ostream_begin_use_class", referenced from:
      _jitter_print_context_libtextstyle_begin_decoration in libjitter-libtextstyle.a(jitter-print-libtextstyle.o)
  "_styled_ostream_end_use_class", referenced from:
      _jitter_print_context_libtextstyle_end_decoration in libjitter-libtextstyle.a(jitter-print-libtextstyle.o)
  "_styled_ostream_set_hyperlink", referenced from:
      _jitter_print_context_libtextstyle_begin_decoration in libjitter-libtextstyle.a(jitter-print-libtextstyle.o)
      _jitter_print_context_libtextstyle_end_decoration in libjitter-libtextstyle.a(jitter-print-libtextstyle.o)
ld: symbol(s) not found for architecture arm64

(cherry picked from commit 9f5b96a9e13b6e934448c576a7a525be70e0ad69)