netperf: fix Darwin build
This fixes the following build error on Darwin:
```
In file included from ./src/libsmbios_c/common/libsmbios_c_source.h:37:
./src/libsmbios_c/common/select_platform_config.h:16:7: error: "Unknown platform - please report to libsmbios maintainer."
#     error "Unknown platform - please report to libsmbios maintainer."
      ^
1 error generated.
make[1]: *** [Makefile:1728: src/libsmbios_c/common/out_libsmbios_c_la-common.lo] Error 1
```

Per the netperf doc, `libsmbios` is only used on Linux.