jfsrec: build with boost 1.44.0
Compilation with the latest version, boost 1.47.0, fails as follows:

  g++ -DHAVE_CONFIG_H -I. -I. -I..     -g -O2 -c -o inode.o inode.cpp
  inode.cpp: In member function 'virtual boost::filesystem3::path jfsrec::Inode::get_full_path()':
  inode.cpp:70:54: error: invalid conversion from 'bool (*)(const std::string&)' to 'boost::enable_if_c<true, void>::type*'
  inode.cpp:70:54: error:   initializing argument 2 of 'boost::filesystem3::path::path(const Source&, typename boost::enable_if<boost::filesystem3::path_traits::is_pathable<typename boost::decay<Source>::type> >::type*) [with Source = std::basic_string<char>, typename boost::enable_if<boost::filesystem3::path_traits::is_pathable<typename boost::decay<Source>::type> >::type = void]'
  inode.cpp:72:54: error: invalid conversion from 'bool (*)(const std::string&)' to 'boost::enable_if_c<true, void>::type*'
  inode.cpp:72:54: error:   initializing argument 2 of 'boost::filesystem3::path::path(const Source&, typename boost::enable_if<boost::filesystem3::path_traits::is_pathable<typename boost::decay<Source>::type> >::type*) [with Source = std::basic_string<char>, typename boost::enable_if<boost::filesystem3::path_traits::is_pathable<typename boost::decay<Source>::type> >::type = void]'
  make[2]: *** [inode.o] Error 1

It appears that jfsrec assumes that fs::path is a string, which isn't
true anymore in Boost.FS v3.

svn path=/nixpkgs/trunk/; revision=27750