pypy27Packages.pyreqwest-impersonate: fix the eval
Without the change the eval fails as:

    $ nix build --no-link -f. pypy27Packages.pyreqwest-impersonate
    error:
       error: cannot coerce a set to a string: { dev = «thunk»; }

(cherry picked from commit d8b2244fdbde06cae253e6d086e947a91b73312f)