Revert "Add taskjuggler ruby gem"
This reverts commit 67a46ce928c9190c9b11982120000df711ef1945.

It seems this commit is the reason for this hydra breakage:

  [pbuilding /nix/store/hwdyx4mf5638mxkka64cxjcj75vw3hmz-nixpkgs-tarball-1.0pre28245_67a46ce
  [punpacking sources
  [...snip lots of stuff...]
  'manual.pdf' successfully built
  [qmake: Leaving directory `/tmp/nix-build-nixpkgs-tarball-1.0pre28245_67a46ce.drv-0/git-export/doc'
  [q[q[prunning tests
  [pchecking pkgs/top-level/all-packages.nix on i686-linux
  error: while evaluating the attribute `drvPath' at `/nix/store/l7ny7f17aii5qfgmadr2wcp3wan54wlp-nix-1.5.3/share/nix/corepkgs/derivation.nix:19:9':
  while evaluating the builtin function `derivationStrict':
  while instantiating the derivation named `ruby-actionmailer-4.0.0' at `/tmp/nix-build-nixpkgs-tarball-1.0pre28245_67a46ce.drv-0/git-export/pkgs/development/interpreters/ruby/gem.nix:16:5':
  while evaluating the derivation attribute `propagatedNativeBuildInputs' at `/tmp/nix-build-nixpkgs-tarball-1.0pre28245_67a46ce.drv-0/git-export/pkgs/stdenv/generic/default.nix:78:17':
  while evaluating the attribute `outPath' at `/nix/store/l7ny7f17aii5qfgmadr2wcp3wan54wlp-nix-1.5.3/share/nix/corepkgs/derivation.nix:18:9':
  while evaluating the builtin function `getAttr':
  while evaluating the builtin function `derivationStrict':
  while instantiating the derivation named `ruby-actionpack-4.0.0' at `/tmp/nix-build-nixpkgs-tarball-1.0pre28245_67a46ce.drv-0/git-export/pkgs/development/interpreters/ruby/gem.nix:16:5':
  while evaluating the derivation attribute `propagatedNativeBuildInputs' at `/tmp/nix-build-nixpkgs-tarball-1.0pre28245_67a46ce.drv-0/git-export/pkgs/stdenv/generic/default.nix:78:17':
  while evaluating the attribute `outPath' at `/nix/store/l7ny7f17aii5qfgmadr2wcp3wan54wlp-nix-1.5.3/share/nix/corepkgs/derivation.nix:18:9':
  while evaluating the builtin function `getAttr':
  while evaluating the builtin function `derivationStrict':
  while instantiating the derivation named `ruby-activesupport-4.0.0' at `/tmp/nix-build-nixpkgs-tarball-1.0pre28245_67a46ce.drv-0/git-export/pkgs/development/interpreters/ruby/gem.nix:16:5':
  while evaluating the derivation attribute `propagatedNativeBuildInputs' at `/tmp/nix-build-nixpkgs-tarball-1.0pre28245_67a46ce.drv-0/git-export/pkgs/stdenv/generic/default.nix:78:17':
  while evaluating the attribute `outPath' at `/nix/store/l7ny7f17aii5qfgmadr2wcp3wan54wlp-nix-1.5.3/share/nix/corepkgs/derivation.nix:18:9':
  while evaluating the builtin function `getAttr':
  while evaluating the builtin function `derivationStrict':
  while instantiating the derivation named `ruby-multi_json-1.7.8' at `/tmp/nix-build-nixpkgs-tarball-1.0pre28245_67a46ce.drv-0/git-export/pkgs/development/interpreters/ruby/gem.nix:16:5':
  while evaluating the derivation attribute `src' at `/tmp/nix-build-nixpkgs-tarball-1.0pre28245_67a46ce.drv-0/git-export/pkgs/development/interpreters/ruby/gem.nix:11:5':
  while evaluating the attribute `outPath' at `/nix/store/l7ny7f17aii5qfgmadr2wcp3wan54wlp-nix-1.5.3/share/nix/corepkgs/derivation.nix:18:9':
  while evaluating the builtin function `getAttr':
  while evaluating the builtin function `derivationStrict':
  hash `no hash' has wrong length for hash type `sha256'
  [q[q[qbuild time elapsed:  0m0.038s 0m0.023s 0m20.586s 0m2.004s
  builder for `/nix/store/lxmyqg7z1l71ji5vdar2m5w66dx45v20-nixpkgs-tarball-1.0pre28245_67a46ce.drv' failed with exit code 1
  error: build of `/nix/store/lxmyqg7z1l71ji5vdar2m5w66dx45v20-nixpkgs-tarball-1.0pre28245_67a46ce.drv' failed