nix-info: fix nixpkgs tarball evaluation
error: while evaluating the attribute ‘darwin-tested’ at /build/git-export/lib/attrsets.nix:199:44:
[..]
while evaluating the attribute ‘nix-info.x86_64-darwin’ at /build/git-export/lib/attrsets.nix:199:44:
attribute ‘x86_64-darwin’ missing, at /build/git-export/pkgs/top-level/release.nix:50:15

(cherry picked from commit 9805818d2443ea663408561a82defb195b073dca)