neovimUtils.buildNeovimPlugin: use version from derivation if missing
Trying to use:
`plugin = pkgs.neovimUtils.buildNeovimPlugin { luaAttr = "rocks-nvim"; };`

fails with:

```
error: attribute 'version' missing

at /nix/store/0ww4wsg5q5hmnzv06a0k1q32jc49y7gi-source/pkgs/applications/editors/neovim/build-neovim-plugin.nix:28:19:

    27|         })).overrideAttrs (drv: {
    28|         version = attrs.version;
	|                   ^
    29|         rockspecVersion = drv.rockspecVersion;
```

This PR fixes it.