ipmitool: fix build on -fno-common toolchains
Without the change build fails on toolchains like clang-13 which
switch to -fno-common by default:

    $ nix build --impure --expr 'with import ./. {}; ipmitool.override { stdenv = clang13Stdenv; }'
    ...
    ld: ../lib/.libs/libipmitool.a(ipmi_hpmfwupg.o):/build/ipmitool-1.8.18/lib/../include/ipmitool/ipmi_hpmfwupg.h:803:
      multiple definition of `gVersionInfo'; ipmitool.o:/build/ipmitool-1.8.18/src/../include/ipmitool/ipmi_hpmfwupg.h:803: first defined here

Pull upstream fix to move definition to .c file.