qt514.qtbase: add fix build for gcc-11 (upstream backports)
Without the change build on `gcc-11` fails as:

    $ nix build --impure --expr 'with import ./. {}; qt514.qtbase.override { stdenv = gcc11Stdenv; }'
    ...
    src/corelib/global/qendian.h:333:54: error: incomplete type 'std::numeric_limits' used in nested name specifier
      333 |     { return QSpecialInteger(std::numeric_limits<T>::min()); }
          |                                                      ^~~

Not applying patches as is as they have minor whitespace conflicts.