pyjwkest: remove 'future' dependency to fix build
This dependency is unused in pyjwkest, but disabled in nixpkgs.
There is an upstream pull request pending to remove the dependency:
https://github.com/IdentityPython/pyjwkest/pull/107

Before this change, these 2 Python packages failed to build:

nix build .#python313Packages.pyjwkest
nix build .#python313Packages.oic

With the following message:

error:
       … while evaluating the attribute 'drvPath'
         at /nix/store/65sypvf1f26fyi1vq6h25wg9z5gipgy8-source/lib/customisation.nix:429:7:
          428|     // {
          429|       drvPath =
             |       ^
          430|         assert condition;

       … while evaluating the attribute 'drvPath'
         at /nix/store/65sypvf1f26fyi1vq6h25wg9z5gipgy8-source/lib/customisation.nix:429:7:
          428|     // {
          429|       drvPath =
             |       ^
          430|         assert condition;

       … while calling the 'derivationStrict' builtin
         at <nix/derivation-internal.nix>:37:12:
           36|
           37|   strict = derivationStrict drvAttrs;
             |            ^
           38|

       (stack trace truncated; use '--show-trace' to show the full, detailed trace)

       error: future-1.0.0 not supported for interpreter python3.13

(I am using the oic package via the pretix-oidc plugin.)

(cherry picked from commit dbefe89d9e3c8cad3d417754bbb819963f97be99)