lldb: Fix dependency cycle between `out` and `lib` outputs
Remove the `lib` output, so that `/lib` goes to the `out` output
instead. This fixes the following error:

ERROR: noBrokenSymlinks: the symlink .../lib/python3.12/site-packages/lldb/lldb-argdumper points to a missing target .../bin/lldb-argdumper

Fixes #380196