backintime: add missing dependency 'packaging'
Fixes this error:

  $ ./result/bin/backintime-qt
  /nix/store/fpr65b2gwpa4q9w3k6z8kjcd9yprmg6s-backintime-qt-1.3.3
  Traceback (most recent call last):
    File "/nix/store/fpr65b2gwpa4q9w3k6z8kjcd9yprmg6s-backintime-qt-1.3.3/share/backintime/qt/app.py", line 35, in <module>
      import qttools
    File "/nix/store/fpr65b2gwpa4q9w3k6z8kjcd9yprmg6s-backintime-qt-1.3.3/share/backintime/qt/qttools.py", line 32, in <module>
      from packaging.version import Version
  ModuleNotFoundError: No module named 'packaging'

Fixes https://github.com/NixOS/nixpkgs/issues/241966.