python3Packages.python-dbusmock: Add missing gobject-introspection
This is needed to find GLib typelib:
ImportError: cannot import name GLib, introspection typelib not found