python3Packages.speedtest-cli: 2.1.2 -> 2.1.3
(cherry picked from commit 67b7e63d41f683cf7fcb87cdff6fc93886680c29)

Rationale for backport: release 2.1.3 fixes the following runtime
error[1]:

    $ speedtest-cli
    Retrieving speedtest.net configuration...
    Traceback (most recent call last):
      File "/nix/store/ykdf27yk3pc62719c60mb7a8akg84jma-python3.8-speedtest-cli-2.1.2/bin/.speedtest-cli-wrapped", line 9, in <module>
        sys.exit(main())
      File "/nix/store/ykdf27yk3pc62719c60mb7a8akg84jma-python3.8-speedtest-cli-2.1.2/lib/python3.8/site-packages/speedtest.py", line 1986, in main
        shell()
      File "/nix/store/ykdf27yk3pc62719c60mb7a8akg84jma-python3.8-speedtest-cli-2.1.2/lib/python3.8/site-packages/speedtest.py", line 1872, in shell
        speedtest = Speedtest(
      File "/nix/store/ykdf27yk3pc62719c60mb7a8akg84jma-python3.8-speedtest-cli-2.1.2/lib/python3.8/site-packages/speedtest.py", line 1091, in __init__
        self.get_config()
      File "/nix/store/ykdf27yk3pc62719c60mb7a8akg84jma-python3.8-speedtest-cli-2.1.2/lib/python3.8/site-packages/speedtest.py", line 1173, in get_config
        ignore_servers = list(
    ValueError: invalid literal for int() with base 10: ''

[1] https://github.com/sivel/speedtest-cli/releases/tag/v2.1.3