directfb: explicitly disable parallel building
Disable parallel building as parallel builds fail due to incomplete
depends between autogenerated CoreSlave.h and it's include sites:

```
   CC       prealloc_surface_pool_bridge.lo
   prealloc_surface_pool_bridge.c:41:10:
       fatal error: core/CoreSlave.h: No such file or directory
```

Dependencies are specified manually in src/core/Makefile.am. Instead
of fixing them one by one locally let's disable parallel builds until
upstream fixes them.