ucx: fix FOD hash
- fix FOD hash for `src` with tag `v1.19.1`

Upstream seems to have moved `v1.19.1` tag:
https://github.com/openucx/ucx/commits/v1.19.1/
and "rereleased"
https://github.com/openucx/ucx/releases/tag/v1.19.1
because of:
https://www.github.com/openucx/ucx/pull/11039
after update PR was merged in nixpkgs.

Now `v1.19.1` tag points to commit: 
https://github.com/openucx/ucx/commit/7009d7a19b1c2464224a3fe117a4155fb29298f5
instead of commit it pointed to before:
https://github.com/openucx/ucx/commit/a702467fd479dde8699f1f3d329733f51d0a9ab9
(confirmed by changing `rev`, it produces previous hash)

Fixes build failure:
```
error: hash mismatch in fixed-output derivation '/nix/store/wyy75b1nangzbxsfv80rflv34dvr4irv-source.drv':
         specified: sha256-goANgYuMO1yColKOrqoBOj+yh68OSW7O8Ppng/pd4b0=
            got:    sha256-54yLejOFdCa2KYstZuo+hZ5lSQR8WTZMa7lS0prc5NY=
```