Revert "pdftk: use minimal jre"
This reverts commit d8e439a9b9b6e06587a0e9a1f1c7596ef4574878.

Using the minimal jre results in classes needed for some operations no
longer being available, e.g. when attempting to fill a form:

Error: could not load a required library for this operation.
java.lang.NoClassDefFoundError: java/awt/Color
Make sure that bcprov and commons-lang3 are installed and included in the
classpath. See also https://gitlab.com/pdftk-java/pdftk/issues/2.
   No output created.