alock: mark linux only
The darwin build fails and it's probably not particularly useful there.

    utils.c:33:19: error: use of undeclared identifier 'CLOCK_MONOTONIC'
        clock_gettime(CLOCK_MONOTONIC, &t);

/cc ZHF #45961

(cherry picked from commit 139eb11a6d471bb78aed90d6da827f66f727c429)