nodePackages.parcel: drop
Running parcel fails with

    Error: No prebuild or local build of @parcel/watcher found. Tried @parcel/watcher-linux-x64-glibc. Please ensure it is installed (don't use --no-optional when installing with npm). Otherwise it is possible we don't support your platform yet. If this is the case, please report an issue to https://github.com/parcel-bundler/watcher.
        at Object.<anonymous> (/nix/store/04mykikjc5bldvx76pank0yz5c68s7l4-parcel-2.13.3/lib/node_modules/parcel/node_modules/@parcel/watcher/index.js:26:13)
        at Module._compile (node:internal/modules/cjs/loader:1554:14)
        at Object..js (node:internal/modules/cjs/loader:1706:10)
        at Module.load (node:internal/modules/cjs/loader:1289:32)
        at Function._load (node:internal/modules/cjs/loader:1108:12)
        at TracingChannel.traceSync (node:diagnostics_channel:322:14)
        at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
        at Module.require (node:internal/modules/cjs/loader:1311:12)
        at require (node:internal/modules/helpers:136:16)
        at Object.<anonymous> (/nix/store/04mykikjc5bldvx76pank0yz5c68s7l4-parcel-2.13.3/lib/node_modules/parcel/node_modules/@parcel/fs/lib/index.js:9:28)