lib: CA fixes
```nix
nix-repl> pkgs = import ./. { config = { contentAddressedByDefault = true; }; }

nix-repl> toString pkgs.busybox
"/083nm0nmzng04dzx05w8zbc4ha70674wc1slfbk09ng69a28fgg2"
```

`iso.nix`

```
{ config, pkgs, ... }:
{
  imports = [
    <nixpkgs/nixos/modules/installer/cd-dvd/installation-cd-minimal.nix>
  ];
  # This breaks the build:
  nixpkgs.config.contentAddressedByDefault = true;
}
```

```
nix repl -I nixos-config=iso.nix --file ./nixos/.
nix-repl> config.system.extraDependencies
  error: A definition for option `system.extraDependencies."[definition 1-entry 1]"' is not of type `path in the Nix store'. Definition values:
       - In `/nix/store/m90lvfa50gc7s1ysa9zzx2drdm10pmyc-source/nixos/modules/profiles/installation-device.nix': <derivation stdenv-linux>
```