conan: pin distro==1.5.0 to fix build
Or else the build fails with

  ERROR: No matching distribution found for distro<=1.6.0,>=1.0.2

since distro==1.7.0 in nixpkgs now.