nixos/virtualisation/podman: fix broken evaluation
- The following error occurs when building:

error: A definition for option `environment.systemPackages."[definition 8-entry 2]"' is not of type `package'. Definition values:
  - In `/nix/store/dgp9wmspgm6zhl66f0c81rvg3v7wwbsb-source/nixos/modules/virtualisation/podman/default.nix':
    ''
      /nix/store/yyspp8pf5fhpx17wb2ndrhdd7y5kqb4g-podman-docker-compat-5.7.0export HOME=$(mktemp -d) # work around `docker <cmd>`
        installShellCompletion --cmd docker \
          --bash <($out/bin/docker completion bash) \
          --zsh <($out/bin/docker completion zsh) \

- This error occurs because the string is being concatenated to the output
  of the function evaluation of `pkgs.runCommand` instead of being
  concatenated to the string input of the function.

- Tested locally and the build works again.