deadbeef: fix build against clang-16
Without the change build fails as https://cache.nixos.org/log/848ky6rxa8v0wzy72gyrv15v7my7f22c-deadbeef-1.9.5.drv

    libbinio/binio.cpp:498:3: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
      register long bits;

The change allies the fix similar to upstream fix from https://github.com/DeaDBeeF-Player/deadbeef/issues/3012
but without the patch conflict.