ffmpeg: don't use gcc on darwin
This isn't necessary and causes build failures for certain versions.

    CC      libavfilter/libmpcodecs/vf_eq2.o
    CC      libavfilter/libmpcodecs/vf_fil.o
    CC      libavfilter/libmpcodecs/vf_fspp.o
    libavfilter/libmpcodecs/vf_fspp.c:939:18: error: unknown token in expression
            movq %mm2, 0*8+(%rsp)

/cc ZHF #45961