nixos/mautrix-facebook: set verification levels
These are now required otherwise startup fails with:

> TypeError: 'NoneType' object is not subscriptable

The chosen levels are stricter than default but don't require unsupported signing or DB editing so seem like a reasonable high bar for now. It is easy for users to lower the levels so it is better to be stricter by default.

Default levels: https://github.com/mautrix/facebook/blob/0ce0588725f86719b3c83cd6f08dc18d06276938/mautrix_facebook/example-config.yaml#L247-L263