zynaddsubfx: pull upstream fix for -fno-common (mruby-zest)
Without the change internal dependency mruby-zest fails to build on
-fno-common toolchain as:

    ld: libmruby.a(nvg_context.o):mruby-nanovg/src/nvg_context.c:217: multiple definition of
      `mrb_nvg_context_type'; libmruby.a(gem.o):mruby-widget-lib/src/gem.c:293: first defined here

(cherry picked from commit 338484a75e756e7430d3edec20dcf8c3fff13992)