haskell.packages.ghc865Binary.exceptions: fix eval
Without the change the eval fails as:

    $ nix build --no-link -f. haskell.packages.ghc865Binary.exceptions
    error: attribute 'exceptions_0_10_7' missing
           at pkgs/development/haskell-modules/configuration-ghc-8.6.x.nix:98:16:
               97|   # This became a core library in ghc 8.10., so we don’t have an "exception" attribute anymore.
               98|   exceptions = self.exceptions_0_10_7;
                 |                ^
               99|
           Did you mean exceptions_0_10_8?

(cherry picked from commit 8b65aca289e03baf613e1160726b9f1a4a3d0079)