tradcpp: fix build with gcc15
- add "-std=gnu17" to `env.NIX_CFLAGS_COMPILE`

Last update from upstream was in 2019.

Fixes build failure with gcc15:
```
In file included from main.c:36:
bool.h:36:13: error: 'bool' cannot be defined via 'typedef'
   36 | typedef int bool;
      |             ^~~~
bool.h:36:13: note: 'bool' is a keyword with '-std=c23' onwards
bool.h:36:1: warning: useless type name in empty declaration
   36 | typedef int bool;
      | ^~~~~~~
```