vapoursynth: require macOS 13.3
Otherwise the build fails with:

    src/vspipe/vspipe.cpp:285:21: error: 'to_chars' is unavailable: introduced in macOS 13.3
      285 |     auto res = std::to_chars(buffer, buffer + sizeof(buffer), v, std::chars_format::fixed);
          |                     ^
    /nix/store/zzn2cvbh4gs4zvyv9p52kclqqvqrfb5x-libcxx-19.1.2+apple-sdk-15.5/include/c++/v1/__charconv/to_chars_floating_point.h:38:1: note: 'to_chars' has been explicitly marked unavailable here
       38 | to_chars(char* __first, char* __last, double __value, chars_format __fmt);
          | ^
    1 error generated.