feat: make npm dep fetch consistency error more helpful
Previously, this would simply error with
```
thread 'main' (8933822) panicked at src/main.rs:79:34:
dependency should have a hash
```
which isn't _super_ helpful.

With this change it will at least print out the package that is missing a cache hash.