chromium: move gnChromium to nativeBuildInputs,
because electron 35+ needs gn in PATH at build time

[41984/43140] ACTION //third_party/electron_node:generate_config_gypi(//build/toolchain/linux/unbundle:default)
FAILED: gen/third_party/electron_node/config.gypi
python3 ../../third_party/electron_node/tools/generate_config_gypi.py gen/third_party/electron_node/config.gypi --out-dir . --dep-file gen/third_party/electron_node/generate_config_gypi.d --node-gn-path //third_party/electron_node
Traceback (most recent call last):
  File "/build/src/out/Release/../../third_party/electron_node/tools/generate_config_gypi.py", line 113, in <module>
    main()
  File "/build/src/out/Release/../../third_party/electron_node/tools/generate_config_gypi.py", line 100, in main
    config = get_gn_config(args.out_dir)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/src/out/Release/../../third_party/electron_node/tools/generate_config_gypi.py", line 32, in get_gn_config
    gn_args = subprocess.check_output(
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/26yi95240650jxp5dj78xzch70i1kzlz-python3-3.12.9/lib/python3.12/subprocess.py", line 468, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/26yi95240650jxp5dj78xzch70i1kzlz-python3-3.12.9/lib/python3.12/subprocess.py", line 550, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/26yi95240650jxp5dj78xzch70i1kzlz-python3-3.12.9/lib/python3.12/subprocess.py", line 1028, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/nix/store/26yi95240650jxp5dj78xzch70i1kzlz-python3-3.12.9/lib/python3.12/subprocess.py", line 1963, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'gn'