gitmoji-cli: install package.json
Otherwise it fails to run with

    (node:36784) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
    (Use `node --trace-warnings ...` to show where the warning was created)
    /nix/store/g06q0h9a9hb5zgm1vnpddi062hpy3hpa-gitmoji-cli-9.0.0/lib/node_modules/gitmoji-cli/lib/cli.js:2
    import meow from 'meow';
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module
        at internalCompileFunction (node:internal/vm:73:18)
        at wrapSafe (node:internal/modules/cjs/loader:1178:20)
        at Module._compile (node:internal/modules/cjs/loader:1220:27)
        at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
        at Module.load (node:internal/modules/cjs/loader:1119:32)
        at Module._load (node:internal/modules/cjs/loader:960:12)
        at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:86:12)
        at node:internal/main/run_main_module:23:47

    Node.js v18.18.2

(cherry picked from commit 57358cd35aa9ac9c94040ad09c4f04a246a24e70)