autofs: fix build w/glibc-2.34
This build was also broken by a libc const that isn't a number anymore
and thus can't be used at places where a constant value is needed:

    automount.c:86:37: error: initializer element is not constant

Failing Hydra build: https://hydra.nixos.org/build/153253104