hplip: add missing dependency
Graphical programs (e.g. hp-setup) error with:

error: No module named enum

This adds the enum module which fixes the error

(cherry picked from commit 8308e4148abcf2d02b2b31afb920a5b8a0a57f72)