systemd.disallowedReferences: avoid `null` values
hydra-queue-runner complains like this:
  loading build 302783324 (nixpkgs:cross-trunk:rpi-musl.mpg123.x86_64-linux)
  queue monitor: error:
         … while loading build 302783324:
         … while parsing derivation '/nix/store/8r46dmzzchv9jhb09y8dlih4h5k6smkm-systemd-minimal-armv6l-unknown-linux-musleabihf-257.6.drv'
         error: attribute 'disallowedReferences' must be a list of strings
  checking the queue for builds...
  loading build 302783295 (nixpkgs:cross-trunk:rpi-musl.mpg123.aarch64-darwin)

(cherry picked from commit 40df6d5813ed6ebb809a77416bbb1ddfbeedd846)