graphite2: fix build with gcc15
- add patch from fedora, that adds missing `#include <stdint.h>`

Fixes build failure with gcc15:
```
/build/graphite2-1.3.14/tests/featuremap/featuremaptest.cpp: In function 'void testFeatTable(const T&, const std::string&)':
/build/graphite2-1.3.14/tests/featuremap/featuremaptest.cpp:310:14: error: 'uint16_t' was not declared in this scope [-Wtemplate-body]
  310 |         for (uint16_t j = 0; j < table.m_defs[i].m_numFeatSettings; j++)
      |              ^~~~~~~~
/build/graphite2-1.3.14/tests/featuremap/featuremaptest.cpp:310:14: note: 'uint16_t' is defined in header '<cstdint>'; this is probably fixable by adding '#include <cstdint>'
/build/graphite2-1.3.14/tests/featuremap/featuremaptest.cpp:310:30: error: 'j' was not declared in this scope [-Wtemplate-body]
  310 |         for (uint16_t j = 0; j < table.m_defs[i].m_numFeatSettings; j++)
      |                              ^
```