libgnomeprint: updated to version 2.18.8
I made this update hoping that it would fix the build errors with CUPS 1.5.x,
but unfortunately the new version still fails to compile:

  gnome-print-cups-transport.c:59:2: error: expected specifier-qualifier-list before 'FILE'
  gnome-print-cups-transport.c: In function 'gp_transport_cups_init':
  gnome-print-cups-transport.c:128:11: error: 'GPTransportCups' has no member named 'file'
  gnome-print-cups-transport.c: In function 'gp_transport_cups_finalize':
  gnome-print-cups-transport.c:140:15: error: 'GPTransportCups' has no member named 'file'
  gnome-print-cups-transport.c: In function 'gp_transport_cups_open':
  gnome-print-cups-transport.c:194:11: error: 'GPTransportCups' has no member named 'file'
  gnome-print-cups-transport.c:196:15: error: 'GPTransportCups' has no member named 'file'
  gnome-print-cups-transport.c: In function 'gp_transport_cups_close':
  gnome-print-cups-transport.c:238:2: error: 'GPTransportCups' has no member named 'file'
  gnome-print-cups-transport.c:241:23: error: 'GPTransportCups' has no member named 'file'
  gnome-print-cups-transport.c:245:11: error: 'GPTransportCups' has no member named 'file'
  gnome-print-cups-transport.c: In function 'gp_transport_cups_write':
  gnome-print-cups-transport.c:270:2: error: 'GPTransportCups' has no member named 'file'
  gnome-print-cups-transport.c:276:13: warning: incompatible implicit declaration of built-in function 'fwrite'
  gnome-print-cups-transport.c:276:57: error: 'GPTransportCups' has no member named 'file'
  make[4]: *** [gnome-print-cups-transport.lo] Error 1

I commit the update anyway, because (a) I feel that having the latest version
probably can't hurt and (b) the old expression had an incorrect name attribute,
which is now fixed.

svn path=/nixpkgs/trunk/; revision=29281