dolphinEmuMaster: mark broken on darwin
The default version isn't enabled on darwin either, however it did work
at some point.

    /tmp/nix-build-dolphin-emu-2018-08-17.drv-0/source/Source/Core/Core/NetPlayServer.cpp:1180:26: error: unknown type name 'lzo_uint32_t'; did you mean 'lzo_uint32'?
      std::vector<u8> wrkmem(LZO1X_1_MEM_COMPRESS);

/cc ZHF #45961

(cherry picked from commit f6bc086b212b5aa11c47d5bb57082aa89baeb15e)