cxxtest: fix python3Packages eval failure
Without this, one gets the following error:

    error: do not use python3Packages when building Python packages,
    specify each used package as a separate argument

which was introduced by #394838.