open-policy-agent: fix broken tests due to file removals
this package has been broken on darwin since 2025-09 (v1.9.0):
https://hydra.nixos.org/build/329365116

with the error:
```
v1/server/compile_handler_test.go:43:50: undefined: fixture
v1/server/compile_handler_test.go:58:9: undefined: newFixtureWithStore
FAIL    github.com/open-policy-agent/opa/v1/server [build failed]
FAIL
```

When I tested removing these preCheck lines locally on my darwin machine, it was able to build
the originally removed tests/checks and the broken ones sucessfully.