otto-matic: 4.0.1 -> 4.0.1-unstable-2023-11-13
Fixes build failure on `master` due to `gcc-13` update a https://hydra.nixos.org/build/247574057:

    In file included from /build/source/extern/Pomme/src/PommeDebug.cpp:1:
    /build/source/extern/Pomme/src/PommeDebug.h:21:34: error: 'uint32_t' was not declared in this scope
       21 |         std::string FourCCString(uint32_t t, char filler = '?');
          |                                  ^~~~~~~~