moonlight-qt: fix build on x86_64-darwin
error: no member named 'aligned_alloc' in the global namespace
(cherry picked from commit e4c8127a4f91407dcdd89ffc6f59925441b5e8ce)