gpaste: Fix GNOME Shell extension not finding typelib
The extension started failing with:

    Error: Requiring GPaste, version 2: Typelib file for namespace 'GPaste', version '2' not found

Turns out I broke the name of the placeholder variable in e75decf46b045e79e80eed06301fa74ac15c583c.

Not sure how this had been working for me until now.