tests.haskell.setBuildTarget: demonstrate configure bug
Adding a seemingly harmless and unused library component to the test for
setBuildTarget makes the test fail in the installPhase (`./Setup
register ..`) with:

  Error: Setup: '/nix/store/ah2iqzixws3fkhvlml0859hqzjjrvgsz-ghc-9.8.4/bin/ghc'
  exited with an error:
  <command line>: Could not find module ‘SomeModule’.
  Use -v to see a list of the files searched for.