pkgsi686Linux.python3Packages.rdflib: disable test failing on 32-bit systems
Without the change test fails due to too short hash length as:

    =========================== short test summary info ============================
    FAILED test/test_extras/test_infixowl/test_restriction.py::test_restriction_str_and_hash - AssertionError: assert 9 > 17
    = 1 failed, 6343 passed, 72 skipped, 304 deselected, 373 xfailed, 2 xpassed, 130 warnings in 54.86s =