nixos/doc: add missing `name` parameter to `runNixOSTest`
Without this, evaluation crashes:

```
error:
       … while evaluating the 'name' attribute of a derivation

        ...

       … while evaluating the option `name':

       (stack trace truncated; use '--show-trace' to show the full, detailed trace)

       error: The option `name' was accessed but has no value defined. Try setting the option.
```