openrazer-daemon: Fix typelib error
`ImportError: cannot import name GLib, introspection typelib not found`

(cherry picked from commit 43cdb75ca3f0bac2ce1485c9936cb13e193efd01)