lsb-release: Fix the output when /etc/os-release is missing
This also fixes the short output.

The previous behaviour broke e.g. the build of radiotray-ng:
Error: /etc/os-release is not present, aborting.
Error: /etc/os-release is not present, aborting.
Error: /etc/os-release is not present, aborting.
CMake Error at package/CMakeLists.txt:10 (string):
  string no output variable specified

Building version: 0.2.6 for   -- DEB packaging...
CMake Error at package/CMakeLists.txt:56 (if):
  if given arguments:

    "STREQUAL" "16.04" "OR" "STREQUAL" "stretch"

  Unknown arguments specified

-- Configuring incomplete, errors occurred!