pass-import: use magic instead of filemagic
pass import needs magic to determine file types
the current python dependency used is
https://github.com/aliles/filemagic. This is very outdated and when
running the import plugin we get an error "AttributeError: module
'magic' has no attribute 'from_buffer'"
Pass import actually specifies this: https://github.com/file/file as the
required dependency. Using these python bindings fixes the error