test-driver: Run ptpython REPL at global scope
This is a workaround for
https://github.com/prompt-toolkit/ptpython/issues/279, which was making
it impossible to run the installer test interactively:

>>> start_all()
…
>>> test_script()
…
machine # [  382.137683] reboot: Power down
(7.06 seconds)
(8.23 seconds)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nix/store/lbn2xnibdcvpgkpbrkdh2vlf1ap6930v-nixos-test-driver/bin/.nixos-test-driver-wrapped", line 888, in test_script
    exec(os.environ["testScript"])
  File "<string>", line 69, in <module>
  File "<string>", line 18, in create_machine_named
NameError: name 'default_flags' is not defined

name 'default_flags' is not defined

There’s no reason to expose the local variables of the run_tests
function, anyway.

Signed-off-by: Anders Kaseorg <andersk@mit.edu>