flex: use fetchuril instead of fetchpatch to avoid extra depends
Weekly `gcc` snapshots don't come with pre-generated `flex` lexers
and thus require `flex` dependency. Attempt to use them as is fails as:

    error: anonymous function at pkgs/build-support/fetchurl/boot.nix:5:1 called with unexpected argument 'meta'
       at pkgs/build-support/fetchpatch/default.nix:18:1:
           17| in
           18| fetchurl ({
             | ^
           19|   postFetch = ''
    (use '--show-trace' to show detailed location information)

This happens due to a circulare dependency between fetchpatch dependencies
and flex.

The change uses simpler `fetchurl` to ease use of `flex` in `gcc`.

This allows me to use existing `gcc` `.nix` files for weekly `gcc`
snapshots by only adding extra `flex` dependency.