bant: 0.1.7 fix changed hash of fixed derivation.
The hash of the fixed derivation changed

If the old derivation with the hash was cached on the system, the
build failed with:

```
ERROR: /build/output/external/googletest~1.14.0.bcr.1/BUILD.bazel:80:11: Compiling googletest/src/gtest.cc failed: The include path '/nix/store/p5w6cmwqfvhyaf4vjr7jb18a90icrrr2-openjdk-21.0.3+9/include' references a path outside of the execution root.
ERROR: /build/output/external/abseil-cpp~20240116.2/absl/base/BUILD.bazel:755:11: Compiling absl/base/internal/strerror.cc failed: The include path '/nix/store/p5w6cmwqfvhyaf4vjr7jb18a90icrrr2-openjdk-21.0.3+9/include' references a path outside of the execution root.
```

This indicates that the derivation also bakes in the path of the used
JDK, which apparently changed since last time. Quick fix for now:
adapt hash, but hopefully there could be a more long-term solution.