tabula: mark as broken
The resulting executable fails with, among others, the following error:

```
org.jruby.rack.RackInitializationException: load error: /tmp/jetty-0.0.0.0-8080-tabula.jar-_-any-3187750518228613870.dir/webapp/WEB-INF/webapp/tabula_web -- java.lang.reflect.InaccessibleObjectException: Unable to make field public static final int java.util.zip.ZipConstants.ENDSIZ accessible: module java.base does not "opens java.util.zip" to unnamed module @4985cbcb
```

Working it around with `--add-opens` causes it to start, but to fail on any HTTP requests received without producing a useful error message in response or on std{out,err}.