python3Packages.sentry-sdk: add missing test dep
The tests will fail with

    ModuleNotFoundError: No module named 'sqlalchemy'

when sqlalchemy is not part of the test inputs, which prevents building
the package. Therefore, add it as a checkInput.