gitAndTools.stgit: Fix broken package. (#84198)
The stgit package is installing using make, which leaves the application in a state where it can not properly find the installed package stgit.

---
File "/run/current-system/sw/bin/stg", line 35, in <module>
    from stgit.main import main
ImportError: No module named stgit.main
---

This is fixed by using buildPythonApplication instead of stdenv.mkDerivation.