naev: fix the build after luajit update
On `staging-next` `naev` fails the build as:

    ../src/lutf8lib.c: In function 'Lutf8_codepoint':
    ../src/lutf8lib.c:421:22: error: 'INT_MAX' undeclared (first use in this function)
      421 |   if (pose - posi >= INT_MAX)  /* (lua_Integer -> int) overflow? */
          |                      ^~~~~~~

It started after commit a69699eff "luajit_2_1: 2.1.1713773202 -> 2.1.1741730670"
which exposed missing include. It's already fixed upstream, but the change is
a bit invasive. Let's settle on header injection.