ghc863: add haskellCompilerName to prevent errors
such as:
error: while evaluating anonymous function at /home/teto/mptcpnetlink/hs/default.nix:1:1, called from /home/teto/mptcpnetlink/hs/shell-test.nix:65:6:
while evaluating 'doHaddock' at /home/teto/nixpkgs/pkgs/development/haskell-modules/lib.nix:71:15, called from /home/teto/mptcpnetlink/hs/default.nix:5:1:
while evaluating 'overrideCabal' at /home/teto/nixpkgs/pkgs/development/haskell-modules/lib.nix:37:24, called from /home/teto/nixpkgs/pkgs/development/haskell-modules/lib.nix:71:20:
while evaluating 'callCabal2nix' at /home/teto/nixpkgs/pkgs/development/haskell-modules/make-package-set.nix:206:32, called from /home/teto/mptcpnetlink/hs/default.nix:5:24:
while evaluating 'callCabal2nixWithOptions' at /home/teto/nixpkgs/pkgs/development/haskell-modules/make-package-set.nix:191:66, called from /home/teto/nixpkgs/pkgs/development/haskell-modules/make-package-set.nix:206:38:
while evaluating 'overrideCabal' at /home/teto/nixpkgs/pkgs/development/haskell-modules/lib.nix:37:24, called from /home/teto/nixpkgs/pkgs/development/haskell-modules/make-package-set.nix:202:10:
while evaluating 'callPackageKeepDeriver' at /home/teto/nixpkgs/pkgs/development/haskell-modules/make-package-set.nix:156:33, called from /home/teto/nixpkgs/pkgs/development/haskell-modules/make-package-set.nix:202:25:
while evaluating 'overrideCabal' at /home/teto/nixpkgs/pkgs/development/haskell-modules/lib.nix:37:24, called from /home/teto/nixpkgs/pkgs/development/haskell-modules/make-package-set.nix:157:5:
while evaluating 'callPackage' at /home/teto/nixpkgs/pkgs/development/haskell-modules/make-package-set.nix:114:22, called from /home/teto/nixpkgs/pkgs/development/haskell-modules/make-package-set.nix:157:20:
while evaluating 'callPackageWithScope' at /home/teto/nixpkgs/pkgs/development/haskell-modules/make-package-set.nix:74:37, called from /home/teto/nixpkgs/pkgs/development/haskell-modules/make-package-set.nix:114:28:
while evaluating 'makeOverridable' at /home/teto/nixpkgs/lib/customisation.nix:67:24, called from /home/teto/nixpkgs/pkgs/development/haskell-modules/make-package-set.nix:97:8:
while evaluating 'drvScope' at /home/teto/nixpkgs/pkgs/development/haskell-modules/make-package-set.nix:87:18, called from /home/teto/nixpkgs/lib/customisation.nix:69:12:
while evaluating the attribute 'installPhase' of the derivation 'cabal2nix-netlink-pm' at /home/teto/nixpkgs/pkgs/development/haskell-modules/make-package-set.nix:125:7:
while evaluating the attribute 'ghc.haskellCompilerName' at /home/teto/nixpkgs/pkgs/development/haskell-modules/make-package-set.nix:318:5:
attribute 'haskellCompilerName' missing, at /home/teto/nixpkgs/pkgs/development/haskell-modules/make-package-set.nix:135:32