lib.modules: Use user option prefix instead of optionMeta declaration prefix
This feels like cheating, but it works out much better for the
error messages:

    nix-repl> :p (evalModules { modules = [ {
        options.foo = mkOption { };
        options._module.optionMeta.wonk = mkOption { };
      } ]; }).options.foo.meta
    error: The option `options.foo.meta.wonk' was accessed but has no value defined. Try setting the option.