pkgsStatic.dbus: fix
Plausibly broken by 4db1e1cf1356bf7569db932fb339efa83657ee5d:

```
/nix/store/6iy5zryd4b8hmwpj9mky2by0ajardffk-x86_64-unknown-linux-musl-binutils-2.44/bin/x86_64-unknown-linux-musl-ld: /nix/store/jp3n4kccjv0zbz50kw3qbrlnfb0mp43d-audit-static-x86_64-unknown-linux-musl-4.1.2-unstable-2025-09-06-lib/lib/libaudit.a(libaudit.o): in function `audit_can_control':
(.text+0x36a8): undefined reference to `capng_save_state'
/nix/store/6iy5zryd4b8hmwpj9mky2by0ajardffk-x86_64-unknown-linux-musl-binutils-2.44/bin/x86_64-unknown-linux-musl-ld: (.text+0x36bb): undefined reference to `capng_have_capability'
/nix/store/6iy5zryd4b8hmwpj9mky2by0ajardffk-x86_64-unknown-linux-musl-binutils-2.44/bin/x86_64-unknown-linux-musl-ld: (.text+0x36c7): undefined reference to `capng_restore_state'
/nix/store/6iy5zryd4b8hmwpj9mky2by0ajardffk-x86_64-unknown-linux-musl-binutils-2.44/bin/x86_64-unknown-linux-musl-ld: /nix/store/jp3n4kccjv0zbz50kw3qbrlnfb0mp43d-audit-static-x86_64-unknown-linux-musl-4.1.2-unstable-2025-09-06-lib/lib/libaudit.a(libaudit.o): in function `audit_can_write':
(.text+0x3838): undefined reference to `capng_save_state'
/nix/store/6iy5zryd4b8hmwpj9mky2by0ajardffk-x86_64-unknown-linux-musl-binutils-2.44/bin/x86_64-unknown-linux-musl-ld: (.text+0x384b): undefined reference to `capng_have_capability'
/nix/store/6iy5zryd4b8hmwpj9mky2by0ajardffk-x86_64-unknown-linux-musl-binutils-2.44/bin/x86_64-unknown-linux-musl-ld: (.text+0x3857): undefined reference to `capng_restore_state'
/nix/store/6iy5zryd4b8hmwpj9mky2by0ajardffk-x86_64-unknown-linux-musl-binutils-2.44/bin/x86_64-unknown-linux-musl-ld: /nix/store/jp3n4kccjv0zbz50kw3qbrlnfb0mp43d-audit-static-x86_64-unknown-linux-musl-4.1.2-unstable-2025-09-06-lib/lib/libaudit.a(libaudit.o): in function `audit_can_read':
(.text+0x3898): undefined reference to `capng_save_state'
/nix/store/6iy5zryd4b8hmwpj9mky2by0ajardffk-x86_64-unknown-linux-musl-binutils-2.44/bin/x86_64-unknown-linux-musl-ld: (.text+0x38ab): undefined reference to `capng_have_capability'
/nix/store/6iy5zryd4b8hmwpj9mky2by0ajardffk-x86_64-unknown-linux-musl-binutils-2.44/bin/x86_64-unknown-linux-musl-ld: (.text+0x38b7): undefined reference to `capng_restore_state'
collect2: error: ld returned 1 exit status
```