hunspellDicts.fr-moderne: remove the alias
The alias is causing rstudio to fail:

    $ nix-build -A nixosTests.rstudio-server
    ...
    error: 'fr-moderne' was removed because it doesn't exist upstream
    anymore

This is because the package iterates through all of the entries of the
attrset.