kitty: fix build on aarch64-darwin
Fixing the following issue:

```
kitty/cocoa_window.m:179:37: error: 'NSUserNotificationCenter' is deprecated:
  first deprecated in macOS 11.0 - All NSUserNotifications API should be replaced
  with UserNotifications.frameworks API [-Werror,-Wdeprecated-declarations]
```