libgnt: 2.14.3 -> 2.14.4-dev
Without the update build will fail on `ncurses-6.5` update as:

    ../gntwm.c:183:52: error: invalid use of incomplete typedef 'PANEL' {aka 'struct panel'}
      183 |                                 if (mvwin_wch(below->win, y - getbegy(below->win), sx - 1 - getbegx(below->win), &ch) != OK)
          |                                                    ^~

This is caused by `ncurses` hiding opaque fields by default in a new
release.