video-trimmer: add missing codecs
Otherwise it will complain when trying to trim screencasts produced by GNOME Shell:

	(video-trimmer:3229521): GStreamer-Play-WARNING **: 22:37:13.327: GstPlay: scaletempo element not available. Audio pitch will not be preserved during trick modes

	(video-trimmer:3229521): VideoTrimmer-WARNING **: 22:37:13.357: src/video_preview.rs:142: Error in MediaFile: Error from element /GstPlayBin:playbin/GstURIDecodeBin:uridecodebin0: Your GStreamer installation is missing a plug-in.
	Your GStreamer installation is missing a plug-in.
	../gst/playback/gsturidecodebin.c(1027): no_more_pads_full (): /GstPlayBin:playbin/GstURIDecodeBin:uridecodebin0:
	no suitable plugins found:
	../gst/playback/gstdecodebin2.c(4701): gst_decode_bin_expose (): /GstPlayBin:playbin/GstURIDecodeBin:uridecodebin0/GstDecodeBin:decodebin0:
	no suitable plugins found:
	Missing decoder: WebM (video/webm)