gmic-qt: build from Git source to avoid mutable tarball
The previous tarball src sometimes gets mutated (see e.g. [this
comment][1]). This was changed from the Git src in
fd3e2b49f4a3138a1c3e2dd854578f64b9c772cd (see also [upstream
discussion][2]). However the delta seems simple; it had error:

```
In file included from /build/source/src/GmicProcessor.cpp:48:
/nix/store/jk1dp7v01pisw0flybqwyjg63in6r9fp-gmic-3.3.5-dev/include/gmic.h:191:21: fatal error: gmic.cpp: No such file or directory
  191 | #define cimg_plugin "gmic.cpp"
```

workaround this by linking `gmic.cpp` into the expected location as it
appears in the tarball.

cimg is now needed in buildInputs as it is bundled in the tarball, but
not the Git src.

Change the updateScript to simpler one that can use the Git tags.

This may appear to be downgrading, but this is only because the previous
drv used the gmic version, not the gmic-qt version.

[1]: https://github.com/NixOS/nixpkgs/pull/311734#issuecomment-2118663822
[2]: https://github.com/c-koi/gmic-qt/pull/175