python2Packages.unittest-sml-reporting: disable py2
```
builder for '/nix/store/5hqb6vylvzjj92db46wrzd3mp56vv1ms-python2.7-unittest-xml-reporting-3.0.2.drv' failed with exit code 1; last 10 log lines:
  no configure script, doing nothing
  building
  Executing setuptoolsBuildPhase
  Traceback (most recent call last):
    File "nix_run_setup", line 8, in <module>
      exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\\r\\n', '\\n'), __file__, 'exec'))
    File "setup.py", line 21, in <module>
      raise RuntimeError('This version requires Python 3.5+')  # pragma: no cover
  RuntimeError: This version requires Python 3.5+
  builder for '/nix/store/5hqb6vylvzjj92db46wrzd3mp56vv1ms-python2.7-unittest-xml-reporting-3.0.2.drv' failed with exi
```