linux: only configure IDE to "no" pre-5.14
When trying to build a 5.14 (rc-*), this fails to build otherwise:

> error: unused option: IDE

(cherry picked from commit ced7721191dbc31b29f467a432a590e9df8385be)