gpm-ncurses: enable `ncurses` depend
commit 4d47a0e "gpm: remove ncurses null override "
broke `w3m` in `staging` as:

    $ nix build -f. w3m -L
    ...
    ld: terms.o: in function `do_getch':
    /build/source/terms.c:2174: undefined reference to `Gpm_Wgetch'

It happens because `w3m` uses `gpm-ncurses` which change
did not update to use `withNcurses = true;`. Updating it now.