zug: add a patch to include algorithm
Fix `error: 'sort' is not a member of 'std'; did you mean 'qsort'?`

(cherry picked from commit 70515a57c4ca8d7aa3622f721f97877f41d3ca95)