lib.doRename: add test for nested option priorities
This test demonstrates a bug where lib.doRename leads to a crash when a nested old option is defined with priority:

```
 error: A definition for option `new.foo' is not of type `signed integer'. Definition values:
       - In [...]:
           {
             _type = "override";
             content = 1234;
             priority = 1000;
           }
```