patchance: Fix startup failure
`cgitb` was removed since Python 3.13. Patchance was broken in
`nixos-25.05` and also broken in `nixos-26.11`. It fails to start with

> ModuleNotFoundError: No module named 'cgitb'

That `cgitb` import is unused anyway. Just adding a patch removing it.