nixos/test-driver: read test script from store instead of env var
The env var approach caps out at 128K which makes large test scripts fail checks with:
```
error: executing '.../bin/bash': Argument list too long
```

The script already exists in the store, let's use that.