pypy27Packages.incremental: fix the eval
Without the change the eval fails as:

    $ nix-instantiate -A pypy27Packages.incremental
    error:
       … while evaluating the attribute 'drvPath'
         at lib/customisation.nix:365:7:
          364|     in commonAttrs // {
          365|       drvPath = assert condition; drv.drvPath;
             |       ^
          366|       outPath = assert condition; drv.outPath;

       … while evaluating the attribute 'drvPath'
         at lib/customisation.nix:365:7:
          364|     in commonAttrs // {
          365|       drvPath = assert condition; drv.drvPath;
             |       ^
          366|       outPath = assert condition; drv.outPath;

       … while calling the 'derivationStrict' builtin
         at <nix/derivation-internal.nix>:34:12:
           33|
           34|   strict = derivationStrict drvAttrs;
             |            ^
           35|

       (stack trace truncated; use '--show-trace' to show the full, detailed trace)

       error: cannot coerce a set to a string: { scripts = «thunk»; }

https://github.com/NixOS/nixpkgs/pull/335112#issuecomment-2322364846
suggests that "The Python 2 version of buildPythonPackage doesn't support
optional-dependencies outside of passthru."

Added `passthru` explicitly.