gcc: fix missing atomic ops errors on risc-v
Fixes errors like:

    ld: [...]: undefined reference to `__atomic_exchange_1'

* Backport patch from gcc 13 that uses libatomic for missing ops:
  https://gcc.gnu.org/git?p=gcc.git;a=commit;h=f797260adaf52bee0ec0e16190bbefbe1bfc3692
  A few conflicts were resolved, so the patch is included as a file.
* Remove workarounds from
  * aws-sdk-cpp
  * libjxl
  * numactl
  * mariadb
  * zstd