bip: drop blanket -Werror
Without the change the build fails on `master` as
https://hydra.nixos.org/build/249146359:

    In function 'array_count',
        inlined from 'irc_line_free' at line.c:220:18:
    util.h:206:17: error: null pointer dereference [-Werror=null-dereference]
      206 |         return a->elemc;
          |                ~^~~~~~~

Instead of disabling another warning let's drop blanket `-Werror`.
While at it enabled parallel builds by default.