nixosTests.nixops: Revert "tests.nixops: fix broken eval" to fix eval
This reverts commit c946245c7a595c0834d3787ce4215419fc3df73b.

Without the change test eval fail at top level of `nixpkgs` as:

    $ nix build --no-link -f. nixosTests.nixops
       error: function 'anonymous lambda' called without required argument 'testers'