python3Packages.pyarrow: fix darwin build for when a build flag is false
nix-repl> with import <nixpkgs> {}; stdenv.mkDerivation { name="test"; true = true; false = false; }
«derivation /nix/store/2xk4hhfnaqymwq0iw9hxi5a34a8dbywz-test.drv»

nix show-derivation /nix/store/2xk4hhfnaqymwq0iw9hxi5a34a8dbywz-test.drv | grep -E '(true|false)'
      "false": "",
      "true": "1"

  File "setup.py", line 77, in strtobool
    raise ValueError("invalid truth value %r" % (val,))
ValueError: invalid truth value ''

(cherry picked from commit e5690827b5b6fc5aef4c8e135653ff507412b2d8)