aws-azure-login: Link Puppeteer to Chromium
Closes #272544.

The test verifies that the command fails for the *right* reason, rather
than the original issue:

> Error: Could not find expected browser (chrome) locally. Run `npm
> install` to download the correct Chromium revision (982053).

(cherry picked from commit 44896b15cb8c355c701681c67ae7701648500a82)