Revert "btrfs-progs: 4.8.2 -> 4.8.3"
This reverts commit e82c325bff0295ed4bbbd308fd4f99cdfd9ab515.

This package update breaks the `update-grub.pl` script:

    updating GRUB 2 menu...
    Btrfs did not return a path for the subvolume at /
    error: unable to activate new configuration

This backwards-incompatible change is the culprit:

    $ /nix/store/np25r3yzv2r41ji7v73j110inpj8lhn2-btrfs-progs-4.8.2/bin/btrfs subvol show /
    / is toplevel subvolume

vs.

    $ /nix/store/h53vs13nqvjwahpl26a4s7ygqk9xw1mw-btrfs-progs-4.8.3/bin/btrfs subvol show /
    /
    	Name: 			<FS_TREE>
    	UUID: 			-
    	Parent UUID: 		-
    	Received UUID: 		-
    	Creation time: 		-
    	Subvolume ID: 		5
    	Generation: 		6004631
    	Gen at creation: 	0
    	Parent ID: 		0
    	Top level ID: 		0
    	Flags: 			-
    	Snapshot(s):