gss: fix Darwin build by pinning autoconf269
The autoconf 2.73 update on staging-next broke gnulib's stdint.h
generation: the `GNULIBHEADERS_OVERRIDE_WINT_T` AC_SUBST variable ends
up empty in the generated Makefile, so sed substitutes it as the empty
string in `stdint.h` line 89 (from `stdint.in.h` line 88, plus the one
`DO NOT EDIT` header line the generator prepends), producing a bare
`#if` that fails to parse:

    In file included from strverscmp.c:25:
    ./stdint.h:89:5: error: expected value in expression
       89 | #if
          |     ^

Template line:
https://github.com/coreutils/gnulib/blob/0a01f6737dc5666c730bdfe6a038da53a4156cc2/lib/stdint.in.h#L88

A `CFLAGS=-std=gnu17` pin does not help: autoconf still reports C11
features as "none needed" (same as the previously-succeeding autoconf
2.72 build), yet the substitution is still empty

The nixpkgs gnulib pin (2024-10-01) is too old for this autoconf

Refs: https://github.com/NixOS/nixpkgs/issues/511329