gcc: keep using gcc8 to work-around failing rpi build
https://hydra.nixos.org/build/109284638

```
In file included from <command-line>:
./../include/libc-symbols.h:471:26: error: '__EI___errno_location'
specifies less restrictive attributes than its target
'__errno_location': 'const', 'nothrow' [-Werror=missing-attributes]
  471 |   extern __typeof (name) __EI_##name \
      |                          ^~~~~
./../include/libc-symbols.h:475:29: note: in expansion of macro
'__hidden_ver1'
475 | #  define hidden_def(name)  __hidden_ver1(__GI_##name, name,
name);
      |                             ^~~~~~~~~~~~~
./../include/libc-symbols.h:539:32: note: in expansion of macro
'hidden_def'
  539 | # define libc_hidden_def(name) hidden_def (name)
      |                                ^~~~~~~~~~
errno-loc.c:28:1: note: in expansion of macro 'libc_hidden_def'
   28 | libc_hidden_def (__errno_location)
      | ^~~~~~~~~~~~~~~
errno-loc.c:24:1: note: '__EI___errno_location' target declared here
   24 | __errno_location (void)
      | ^~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[2]: *** [../o-iterator.mk:9: /build/build/csu/errno-loc.os] Error 1
```