pdf2htmlEX: mark as broken
See https://hydra.nixos.org/build/81003667

The build is currently broken on Hydra due to the following error:

```
CairoFontEngine.cc:681:17: error: 'void Object::free()' is private within this context
```

This issue is was also reported in AUR (https://aur.archlinux.org/packages/pdf2htmlex/)
and in the upstream issue tracker (https://github.com/coolwanglu/pdf2htmlEX/issues/753) with
no answer until now.

The current README.md states that the project is no longer under active
development and it seems as there are currently no active maintainers
who could fix this:

* https://github.com/coolwanglu/pdf2htmlEX/commit/5d0a2239fcf6ef60a1140edb917fad69d751d6e3
* https://github.com/coolwanglu/pdf2htmlEX/issues/772

(cherry picked from commit de6544b50e53e0e843f95d876f4cca743fed00e0)