octoprint: remove vendored dep class-doc from propagatedBuildInputs
The class-doc is not compatible with python 3.14:

/nix/store/6339q18g3hcpy4rva7imigshkjz80ljn-python3.14-class-doc-0.2.6
/nix/store/lq7p5r0sxa80x2qlhksy03df5fz184h9-python3.14-class-doc-0.2.6-dist
Last 25 log lines:
 >       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 > class_doc.py:227: in extract_all_attr_docstrings
 >     for node, comments in (
 > _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ __ _ _ _ _ _ _ _
 >
 > .0 = <generator object windowed at 0x7ffff57db940>
 >
 >         for node, comments in (
 >             (node, inspect.cleandoc(next_node.value.s).split('\n'))
 >             for node, next_node in mitertools.windowed(cls_def.body, 2)
 >             if isinstance(node, (ast.Assign, ast.AnnAssign))
 > >           if isinstance(next_node, ast.Expr) and isinstance(next_node.value, ast.Str)
 >                                                                                ^^^^^^^
 >             if _ast_tools.count_neighbor_newlines(lines, node, next_node) == 0
 >         )
 >         for target in _get_assign_targets(node)
 >     }
 > E   AttributeError: module 'ast' has no attribute 'Str'
 >
 > class_doc.py:231: AttributeError
 > =========================== short test summary info ============================
 > FAILED test_class_doc.py::test_attr_docstring_extraction - AttributeError: module 'ast' has no attribute 'Str'
 > FAILED test_class_doc.py::test_docs_extracting_for_nested_cls[Inner2-result0] - AttributeError: module 'ast' has no attribute 'Str'
 > FAILED test_class_doc.py::test_docs_extracting_for_nested_cls[Inner-result1] - AttributeError: module 'ast' has no attribute 'Str'
 > =================== 3 failed, 14 passed, 2 xpassed in 0.09s ====================

The class-doc dependency was copied into the upstream octoprint repository,
so it was removed from propagatedBuildInputs.
Its dependency more-itertools is added instead:
https://github.com/OctoPrint/OctoPrint/blob/4bef84e2966fc2eee8c8e7eed2c4f21be6a9c159/setup.py#L105