tpm2-tools: remove nested wrappers
symlinks like `tpm2_createprimary -> tpm2` were wrapped, causing argv0
issues due to double wrapping:

   $ tpm2_ptool init
   [..]
   RuntimeError: Could not execute tpm2_createprimary: b'ERROR:
   /nix/store/[..]/bin/.tpm2_createprimary-wrapped: unknown tool.

This patch only wraps the `tpm2` and `tss2` executables, and not the
symlinks to them `tpm2_*` and `tss2_*`