syncthing-gtk: add missing runtime dependencies
This commit adds various dependencies to nativeBuildInputs to
address various errors of the following form:

ImportError: Typelib file for namespace 'xxx', version 'x.y.z' not found