ns-3: 39 -> 44, fix build with gcc14
- update to latest release tag (ns-3.44), that contains commit:
https://gitlab.com/nsnam/ns-3-dev/-/commit/5b130ba365831cf54674828e46cfa6b7b69c9f77
it fixes build with gcc14.
Without it build fails with this and similar errors:
```
/build/source/src/core/model/val-array.h:83:16: error: template-id not
allowed for constructor in C++20 []
   83 |     ValArray<T>() = default;
      |                ^
```

Diff: https://gitlab.com/nsnam/ns-3-dev/-/compare/ns-3.39...ns-3.44

Changelog: https://gitlab.com/nsnam/ns-3-dev/-/blob/ns-3.44/CHANGES.md