python.withPackages: ignore collisions
Some Python packages have paths that will otherwise collide. As an
example:

```
nix-build --no-out-link --expr '(import ./. {}).python.withPackages (ps: with ps; [pylint pytest])'
these derivations will be built:
  /nix/store/p45ffzp7h06vsp76lss76mvrz0xc10z2-python-2.7.13-env.drv
building path(s) ‘/nix/store/j1dvlk4207vi7szx41jjipbafyxyi6h7-python-2.7.13-env’
collision between `/nix/store/r8vhvakvxac14rggwfxddyqhhpwsn5pf-python2.7-logilab-common-0.63.2/bin/.pytest-wrapped' and `/nix/store/8mv8wrrmnads4lqmh0nic1xfdgwdvdxx-python2.7-pytest-3.0.7/bin/.pytest-wrapped'
builder for ‘/nix/store/p45ffzp7h06vsp76lss76mvrz0xc10z2-python-2.7.13-env.drv’ failed with exit code 25
error: build of ‘/nix/store/p45ffzp7h06vsp76lss76mvrz0xc10z2-python-2.7.13-env.drv’ failed
```