nixos/init-script: fix missing nixos config
The d3528cdc3dbe82a0551707fe869aec02bba72956 introduced error:
  error: attribute 'nixos' missing

The correct config is clearly system.nixos thus just a simple swap and
just missed in testing.