bpftools: add missing `openssl` depend
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=40863f4d6ef2c34bb00dd1070dfaf9d5f27a497e
added `BPF` program signing support. This bork `bpftools` build as:

    sign.c:16:10: fatal error: openssl/opensslv.h: No such file or directory
       16 | #include <openssl/opensslv.h>
          |          ^~~~~~~~~~~~~~~~~~~~