libcpucycles: hacky build fix
The `env` gets inherited from a derivation using structured attrs, i.e.
it also contains `NIX_HARDENING_ENABLE`. If this is not set,
`stdenv.mkDerivation` will set `NIX_HARDENING_ENABLE` right into the
derivation causing the evaluation to fail since there's now an overlap
between with `env`:

    error: The `env` attribute set cannot contain any attributes passed to derivation. The following attributes are overlapping:
     - NIX_HARDENING_ENABLE: in `env`: "bindnow format pic relro stackprotector strictoverflow zerocallusedregs"; in derivation arguments: [
     "bindnow"
     "format"
     "pic"
     "relro"
     "stackprotector"
     "strictoverflow"
     "zerocallusedregs"
    ]