libwacom: Fix libwacom-show-stylus
It would fail like this:

```
> libwacom-show-stylus
Error: No module named 'libevdev'
One or more python modules are missing. Please install those modules and re-run this tool.
```

Or even earlier if the system does not have any python3:

```
> sudo libwacom-show-stylus
/usr/bin/env: ‘python3’: No such file or directory
```

With this change it can work:

```
> sudo ./result/bin/libwacom-show-stylus
Using "ILIT2901:00 222A:0001 Stylus": /dev/input/event7
Using stylus file(s): /nix/store/995gjgcafxbssn50k3bhksws7jnb28cx-libwacom-2.14.0/share/libwacom/lenovo.stylus, /nix/store/995gjgcafxbssn50k3bhksws7jnb28cx-libwacom-2.14.0/share/libwacom/wacom.stylus
Tool id 0x0 serial 0xff in-proximity: False
```

Signed-off-by: Daniel Schaefer <git@danielschaefer.me>