pyside2: fixup build after qt5 update
in commit 202fff431f9.  I blame upstream:
https://invent.kde.org/qt/qt/qtdeclarative/-/commit/7f067fa8a52e677e29eb5606125aa31bf442f495
(but I don't know these project, so can't know who's at fault)

Build error:
  qtdeclarative-5.15.7-dev/include/QtQuickWidgets/qaccessiblequickwidget.h:46:10:
    fatal error: 'private/qaccessiblequickview_p.h' file not found