openssh_gssapi: fix build
Hydra build is failing[1] because of a hash-mismatch of the gss-api
patch from debian.

I updated the patch, and activated the `autoreconfHook` when building
gss support as well, otherwise the build would fail with the following
error:

```
ERROR: configure is out of date; please run autoreconf (and configure)
```

[1] https://hydra.nixos.org/build/109409845