mididings: drop
Doesn't support recent python3 versions that use `async` as a keyword.

```
  File "/build/source/mididings/units/call.py", line 36
    def __init__(self, function, async, cont):
                                 ^
SyntaxError: invalid syntax
```