cvs: fix build with gcc15
- add "-std=gnu17" to `env.NIX_CFLAGS_COMPILE`

Upstream had no updates since 2019

Fedora used 13k LOC patch instead and submitted it upstream:
https://src.fedoraproject.org/rpms/cvs/c/43fad212ad729bdeabfe93b1f12007a75fc2862d
https://savannah.nongnu.org/bugs/index.php?66726

Fixes build failure with gcc15:
```
sighandle.c: In function 'SIG_handle':
sighandle.c:207:18: error: too many arguments to function
'this->handler'; expected 0, have 1
  207 |                 (*this->handler)(sig);
      |                 ~^~~~~~~~~~~~~~~ ~~~
sighandle.c:59:35: note: declared here
   59 |         RETSIGTYPE              (*handler)();
      |                                   ^~~~~~~
```