aseprite: fix build with glibc 2.30
Otherwise it fails with:

In file included from /build/source/src/allegro/include/allegro/base.h:41,
                 from /build/source/src/allegro/include/allegro.h:25,
                 from /build/source/src/./she/alleg4/alleg_surface.h:11,
                 from /build/source/src/she/alleg4/alleg_surface.cpp:11:
/build/source/src/allegro/include/allegro/alcompat.h:44:22: error: conflicting declaration of C function 'fixed fadd(fixed, fixed)'
   44 |       AL_ALIAS(fixed fadd(fixed x, fixed y), fixadd(x, y))
      |                      ^~~~
/build/source/src/allegro/include/allegro/internal/alconfig.h:164:49: note: in definition of macro 'AL_ALIAS'
  164 |       static __attribute__((unused)) __inline__ DECL    \
      |                                                 ^~~~
In file included from /nix/store/y57skwl8a5vbkrjrc30ygdw9vr1p6n19-gcc-9.2.0/include/c++/9.2.0/cmath:45,
                 from /nix/store/y57skwl8a5vbkrjrc30ygdw9vr1p6n19-gcc-9.2.0/include/c++/9.2.0/math.h:36,
                 from /build/source/src/./base/base.h:13,
                 from /build/source/src/./config.h:40,
                 from /build/source/src/she/alleg4/alleg_surface.cpp:8:
/nix/store/2v6pi2wj3lcsc3j48n7flx9mgqyii1lv-glibc-2.30-dev/include/bits/mathcalls-narrow.h:24:20: note: previous declaration 'float fadd(double, double)'
   24 | __MATHCALL_NARROW (__MATHCALL_NAME (add), __MATHCALL_REDIR_NAME (add), 2);
      |                    ^~~~~~~~~~~~~~~

(cherry picked from commit 0ded378b10a17d2e7525bcd2002e89e10ecd7967)