python3Packages.labgrid: add packaging module
Add missing packaging module, fixes the following backtrace while trying
to use labgrid-client:

  Traceback (most recent call last):
    File "/nix/store/izj1dw63bqh47bq10v1b2d7qqg9al7f7-python3.9-labgrid-0.4.1/bin/.labgrid-client-wrapped", line 6, in <module>
      from labgrid.remote.client import main
    File "/nix/store/izj1dw63bqh47bq10v1b2d7qqg9al7f7-python3.9-labgrid-0.4.1/lib/python3.9/site-packages/labgrid/__init__.py", line 1, in <module>
      from .target import Target
    File "/nix/store/izj1dw63bqh47bq10v1b2d7qqg9al7f7-python3.9-labgrid-0.4.1/lib/python3.9/site-packages/labgrid/target.py", line 9, in <module>
      from .driver import Driver
    File "/nix/store/izj1dw63bqh47bq10v1b2d7qqg9al7f7-python3.9-labgrid-0.4.1/lib/python3.9/site-packages/labgrid/driver/__init__.py", line 4, in <module>
      from .serialdriver import SerialDriver
    File "/nix/store/izj1dw63bqh47bq10v1b2d7qqg9al7f7-python3.9-labgrid-0.4.1/lib/python3.9/site-packages/labgrid/driver/serialdriver.py", line 5, in <module>
      from packaging import version
  ModuleNotFoundError: No module named 'packaging'