stdenv: Fix inputDerivation for __structuredAttrs (again?)
Supposedly https://github.com/NixOS/nixpkgs/pull/368226 fixed it, but
either nobody actually tested it or older Nix versions were fine, but
all currently available Nix versions, including 2.24 and 2.32 complain
about it:

    building '/nix/store/9n4hwzk8s74n6cq8dlxa4qas9jchsbgc-inputDerivation.drv'...
    error: output '/nix/store/l3gmc01pwa42rzq9riv8wm3skzkm144r-inputDerivation' is not allowed to refer to the following paths:
             /nix/store/k5z8rkvj1fn1nrf05l5a86aflc5s1p6m-stdenv-linux
             /nix/store/l3gmc01pwa42rzq9riv8wm3skzkm144r-inputDerivation
             /nix/store/l622p70vy8k5sh7y5wizi5f2mic6ynpg-source-stdenv.sh
             /nix/store/qsydfxm1vq6q9jac2kq3r8kn0xdmsldf-bash-5.3p3
             /nix/store/shkw4qm9qcw5sc5n1k5jznc83ny02r39-default-builder.sh

This commit fixes it (again?) and adds a regression test