minizip: install missing `ints.h` header
Without the change the `gtwebengine` fails to buil as:

    /nix/store/...-minizip-1.3.2/include/minizip/ioapi.h:74:10: fatal error: ints.h: No such file or directory
       74 | #include "ints.h"
          |          ^~~~~~~~

(cherry picked from commit 373ddfd70dcd2933ba3385c3a173f228381ee5f5)
We're affected also here:
https://hydra.nixos.org/build/322951570/nixlog/1