treewide: bash -> bashNoninteractive & bashInteractive -> bash
stdenv changed due to
error: output '/nix/store/...-stdenv-linux' is not allowed to refer to the following paths:
         /nix/store/...-ncurses-6.2
         /nix/store/...-readline-8.1p0
         /nix/store/...-bash-interactive-5.1-p12