rmapi: 0.25 -> 0.0.27.1 and switching to a maintained fork (#355090)
Current version is outdated and falls behind server API:
```console
$ rmapi
ERROR: 2024/11/10 23:41:20 main.go:77: failed to build documents tree, last error: request failed with status 410
```

https://github.com/juruen/rmapi repo is archived
https://github.com/ddvk/rmapi looks like a viable fork

This fork and version bump is suggested in
https://www.reddit.com/r/RemarkableTablet/comments/1flzmqq/rmapi_error/
https://github.com/ddvk/rmapi/issues/5

(cherry picked from commit 837ed96b9748a8576ea99c3845cc00947ec075fa)