nixos/pantheon fix GNOME_SESSION_DEBUG conflict
When session debugging was enabled in GNOME but not in Pantheon

	{
	  services.xserver = {
	    desktopManager.pantheon = {
	      enable = true;
	    };
	    desktopManager.gnome3 = {
	      enable = true;
	      debug = true;
	    };
	  };
	}

it caused a conflict:

	error: The option `environment.sessionVariables.GNOME_SESSION_DEBUG' has conflicting definitions, in `<nixpkgs/nixos/modules/services/x11/desktop-managers/pantheon.nix>' and `<nixpkgs/nixos/modules/services/x11/desktop-managers/gnome3.nix>'.