ubports-click: Propagate required pkg-config packages properly
In file included from /build/source/src/usermetricsservice/TranslationLocatorImpl.cpp:28:
/nix/store/b78cqp0g2xf8p6gl11pxsdi2dih9v0fa-click-unstable-2023-02-22/include/click-0.4/click.h:10:10: fatal error: json-glib/json-glib.h: No such file or directory

The Requires.private (only apply to static compilation & linking) should be Requires (always apply), that way reverse
dependencies always get the required flags for json-glib etc.