systemtap-unwrapped: fix 32bit build
- add patch from merged upstream commit:
https://sourceware.org/git/?p=systemtap.git;a=commit;h=94efb7c4eb02de0e3565cb165b53963602d3dcb6

Does not apply with `fetchpatch` because of some problem with diff
encoding on gitweb side for `po/cs.po` file.

Proper diff as shown on html page of gitweb and from local git repo:
```
--- a/po/cs.po
+++ b/po/cs.po
@@ -2039,7 +2039,7 @@ msgstr "Zahazuji kontrolu '@defined' bez vedlejších účinků "
 
 #: elaborate.cxx:5119
 #, fuzzy, c-format
-msgid "Collapsing unresolved @define to %ld [stapprobes]"
+msgid "Collapsing unresolved @define to %lld [stapprobes]"
 msgstr "Zahazuji kontrolu '@defined' bez vedlejších účinků "
 
 #: elaborate.cxx:5127
```

Diff with `patch` or `commitdiff_plain` from gitweb:
https://sourceware.org/git/?p=systemtap.git;a=patch;h=94efb7c4eb02de0e3565cb165b53963602d3dcb6
https://sourceware.org/git/?p=systemtap.git;a=commitdiff_plain;h=94efb7c4eb02de0e3565cb165b53963602d3dcb6
```
--- a/po/cs.po
+++ b/po/cs.po
@@ -2039,7 +2039,7 @@ msgstr "Zahazuji kontrolu '@defined' bez vedlejÅ¡Ã­ch ÃºÄinkÅ¯ "
 
 #: elaborate.cxx:5119
 #, fuzzy, c-format
-msgid "Collapsing unresolved @define to %ld [stapprobes]"
+msgid "Collapsing unresolved @define to %lld [stapprobes]"
 msgstr "Zahazuji kontrolu '@defined' bez vedlejÅ¡Ã­ch ÃºÄinkÅ¯ "
 
 #: elaborate.cxx:5127
```

Fixes build failure on 32bit platforms:
```
elaborate.cxx: In member function 'virtual void const_folder::visit_defined_op(defined_op*)':
elaborate.cxx:5119:33: error: format '%ld' expects argument of type
'long int', but argument 2 has type 'int64_t' {aka 'long long int'}
[-Werror=format=]
 5119 |       session.print_warning (_F("Collapsing unresolved @define to %ld [stapprobes]", value), e->tok);
      |                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
staputil.h:54:27: note: in definition of macro '_'
   54 | #define _(string) gettext(string)
      |                           ^~~~~~
elaborate.cxx:5119:30: note: in expansion of macro '_F'
 5119 |       session.print_warning (_F("Collapsing unresolved @define to %ld [stapprobes]", value), e->tok);
      |                              ^~
elaborate.cxx:5119:69: note: format string is defined here
 5119 |       session.print_warning (_F("Collapsing unresolved @define to %ld [stapprobes]", value), e->tok);
      |                                                                   ~~^
      |                                                                     |
      |                                                                     long int
      |                                                                   %lld
```