octavePackages: use alternative fetchers for moved projects
Many projects moved from SourceForge to other hosting sites. Use an
appropriate fetcher for each of the packages that have moved to the
new sites.

octavePackages.bim: fetchurl -> fetchFromGitHub

There was a migration from SourceForge to GitHub by the authors.

octavePackages.msh: fetchurl -> fetchFromGitHub

There was a migration from SourceForge to GitHub by the authors.

octavePackages.statistics: fetchurl -> fetchFromGitHub

There was a migration from SourceForge to GitHub by the authors.

octavePackages.octclip: fetchurl -> fetchFromBitbucket

There was a migration from SourceForge to Bitbucket by the authors.

octavePackages.geometry: fetchurl -> fetchhg

Release 4.0.0 is broken. Revision
04965cda30b5f9e51774194c67879e7336df1710 was made shortly thereafter,
fixing a compilation bug.

The bug in question:
polygon.cpp:208:22:
error: static assertion failed: comparison object must be invocable as const
is_invocable_v<const _Compare&, const _Key&, const _Key&>,

octavePackages.octproj: fetchurl -> fetchFromBitbucket

There was a migration from SourceForge to Bitbucket by the authors.