linux_xanmod: change URL prefetching in update script
Recently, there has been an issue with `nix-prefetch` that broke the
update script:

```
--- SHOWING ERROR LOG FOR linux-xanmod-6.12.62 ----------------------

this path will be fetched (0.02 MiB download, 0.07 MiB unpacked):
  /nix/store/6xiirw87j5l8n6da4ijibw90r8v1b7zh-nix-prefetch-0.4.1
copying path '/nix/store/6xiirw87j5l8n6da4ijibw90r8v1b7zh-nix-prefetch-0.4.1' from 'https://cache.nixos.org'...
Updating Xanmod "lts" from 6.12.62 to 6.12.63 (xanmod1)
error:
       … while calling the 'zipAttrsWith' builtin
         at /nix/store/wdqrnd6fkxdsf4xn2kkfa8f42shfw0i3-source/lib/attrsets.nix:1701:5:
         1700|     in
         1701|     f [ ] [ rhs lhs ];
             |     ^
         1702|

       … while evaluating a branch condition
         at /nix/store/wdqrnd6fkxdsf4xn2kkfa8f42shfw0i3-source/lib/attrsets.nix:1478:29:
         1477|   */
         1478|   optionalAttrs = cond: as: if cond then as else { };
             |                             ^
         1479|

       (stack trace truncated; use '--show-trace' to show the full, detailed trace)

       error: expected a set but found a function: «lambda extendsWithExclusion @ /nix/store/wdqrnd6fkxdsf4xn2kkfa8f42shfw0i3-source/lib/customisation.nix:846:30»
```

It's possible that this is caused by something else, but we should keep
the update script working until we find out what exactly and fix it.

Note: This first started happening to me on `nixos-25.11`, and is
[reproducible by other people](https://github.com/NixOS/nixpkgs/pull/468873#issuecomment-3624990626)