cvise: fix `unifdef.patch` (crashes otherwise)
Without the change `cvise` does not even parse:

    $ cvise --help |& unnix
      File "/<<NIX>>/cvise-2.12.0/bin/.cvise-wrapped", line 96
        programs['unifdef'] = '/<<NIX>>/unifdef-2.12/bin/unifdef'
        ^^^^^^^^
    SyntaxError: expected 'except' or 'finally' block

Happens because the patch applies to the unrelated bit of the source.

While at it added minimal `cvise --help` test.