udiskie: 1.7.4 -> 1.7.5
`udiskie` breaks for me with the following error when using 1.7.4:

```
Traceback (most recent call last):
  File "/nix/store/cqa72mqgm5gi0xpqp5r8csdizv3p3ajr-udiskie-1.7.4/lib/python3.6/site-packages/udiskie/cli.py", line 307, in _start_async_tasks
    results = yield self._init()
  File "/nix/store/cqa72mqgm5gi0xpqp5r8csdizv3p3ajr-udiskie-1.7.4/lib/python3.6/site-packages/udiskie/cli.py", line 495, in _init
    tasks.append(Async())
NameError: name 'Async' is not defined
```

The error has been confirmed by the Debian issue tracker, so it's
obviously not related to NixOS.

See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=899419 for further
reference.