getmail: drop
Stuck on python2 and there is a fork that isn't. Recommend getmail6
instead.

```
Traceback (most recent call last):
  File "/build/getmail-5.14/nix_run_setup", line 8, in <module>
    exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\\r\\n', '\\n'), __file__, 'exec'))
  File "setup.py", line 51
    print 'Default installation directories:'
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('Default installation directories:')?
```