hyprpaper: Add missing libGL
Cairo will soon no longer propagate libGL.

/build/source/src/events/../includes.hpp:31:10: fatal error: GLES3/gl32.h: No such file or directory
   31 | #include <GLES3/gl32.h>
      |          ^~~~~~~~~~~~~~
compilation terminated.