scipp: fix source hash for 25.08.0
The hash from #438905 appears to have been incorrect or changed, now
causing build failures with a hash mismatch error. This updates it to
the correct sha256 hash.

```
HEAD is now at acba0d29e python3Packages.scipp: 25.05.1 -> 25.08.0
(#438905)
these 6 derivations will be built:
  /nix/store/plv0464mjm3v1fnqcvzbb7f89b7cg7r9-source.drv

/nix/store/z2vpvci0xia1ca10znjpqk07k81hiz9l-python3.12-scipp-25.08.0.drv

/nix/store/fpmnsl861dv8n5bqzfpyyw8p1zg7q7yv-python3.12-plopp-25.07.1.drv

/nix/store/nz7c239ig48pc1v03sm6dcpmh37x3l9x-python3.13-scipp-25.08.0.drv

/nix/store/ih7xvk2972mx9wla0cpwlh6w76i5wf9h-python3.13-plopp-25.07.1.drv
  /nix/store/ma22wk6jjqd9m6gxq2770wg5yr59p1fw-review-shell.drv
...
error: hash mismatch in fixed-output derivation
'/nix/store/plv0464mjm3v1fnqcvzbb7f89b7cg7r9-source.drv':
         specified: sha256-s3whsNYqS7hsqvWX73E8KbDMUZTGWLgeqmN08tXPkwE=
            got:    sha256-nLccJlFnnVTpamph2oIaMxRD5ljrw6GlCnnTx7LfrO0=
```