vte: don't use Clang when cross-compiling
Cross is broken when building with Clang:

	powerpc64le-unknown-linux-gnu-clang++ -Isrc/test-pastify.p -Isrc -I../src -I. -I.. -I/nix/store/1lkclcimgy0yyx7c1acq49g11jb14sz4-glib-powerpc64le-unknown-linux-gnu-2.72.3-dev/include/glib-2.0 -I/nix/store/7b3s5g8b52ng1zyy427n8vq4a70mm5c9-glib-powerpc64le-unknown-linux-gnu-2.72.3/lib/glib-2.0/include -fcolor-diagnostics -D_FILE_OFFSET_BITS=64 -O0 -std=gnu++20 -Wall -Wextra -Wcast-align -Wempty-body -Wendif-labels -Werror=init-self -Werror=missing-include-dirs -Werror=pointer-arith -Wfloat-equal -Wignored-qualifiers -Winvalid-pch -Wmisleading-indentation -Wmissing-declarations -Wmissing-field-initializers -Wmissing-format-attribute -Wmissing-include-dirs -Wmissing-noreturn -Wno-address-of-packed-member -Wno-c99-designator -Wno-missing-field-initializers -Wno-packed -Wno-switch-enum -Wno-unused-parameter -Wshadow -Wshift-negative-value -Wsign-compare -Wstrict-aliasing=2 -Wtype-limits -Wundef -Wuninitialized -Wuninitialized -Wunused -Wunused-function -Wunused-label -Wunused-local-typedefs -Wunused-value -Wunused-variable -Wvla -Wwrite-strings -fdiagnostics-show-option -fno-common -fno-semantic-interposition -fno-strict-aliasing -Wnon-virtual-dtor -Wno-unknown-attributes -fvisibility-inlines-hidden -fvisibility=hidden -Werror=format=2 -Werror=format-nonliteral -Werror=format-security -MD -MQ src/test-pastify.p/pastify.cc.o -MF src/test-pastify.p/pastify.cc.o.d -o src/test-pastify.p/pastify.cc.o -c ../src/pastify.cc
	In file included from ../src/pastify.cc:21:
	../src/pastify.hh:21:10: fatal error: 'string' file not found
	#include <string>
	         ^~~~~~~~
	1 error generated.
	[109/210] Compiling C++ object src/test-utf8.p/utf8.cc.o
	FAILED: src/test-utf8.p/utf8.cc.o
	powerpc64le-unknown-linux-gnu-clang++ -Isrc/test-utf8.p -Isrc -I../src -I. -I.. -I/nix/store/1lkclcimgy0yyx7c1acq49g11jb14sz4-glib-powerpc64le-unknown-linux-gnu-2.72.3-dev/include/glib-2.0 -I/nix/store/7b3s5g8b52ng1zyy427n8vq4a70mm5c9-glib-powerpc64le-unknown-linux-gnu-2.72.3/lib/glib-2.0/include -fcolor-diagnostics -D_FILE_OFFSET_BITS=64 -O0 -std=gnu++20 -Wall -Wextra -Wcast-align -Wempty-body -Wendif-labels -Werror=init-self -Werror=missing-include-dirs -Werror=pointer-arith -Wfloat-equal -Wignored-qualifiers -Winvalid-pch -Wmisleading-indentation -Wmissing-declarations -Wmissing-field-initializers -Wmissing-format-attribute -Wmissing-include-dirs -Wmissing-noreturn -Wno-address-of-packed-member -Wno-c99-designator -Wno-missing-field-initializers -Wno-packed -Wno-switch-enum -Wno-unused-parameter -Wshadow -Wshift-negative-value -Wsign-compare -Wstrict-aliasing=2 -Wtype-limits -Wundef -Wuninitialized -Wuninitialized -Wunused -Wunused-function -Wunused-label -Wunused-local-typedefs -Wunused-value -Wunused-variable -Wvla -Wwrite-strings -fdiagnostics-show-option -fno-common -fno-semantic-interposition -fno-strict-aliasing -Wnon-virtual-dtor -Wno-unknown-attributes -fvisibility-inlines-hidden -fvisibility=hidden -Werror=format=2 -Werror=format-nonliteral -Werror=format-security -MD -MQ src/test-utf8.p/utf8.cc.o -MF src/test-utf8.p/utf8.cc.o.d -o src/test-utf8.p/utf8.cc.o -c ../src/utf8.cc
	In file included from ../src/utf8.cc:26:
	../src/utf8.hh:28:10: fatal error: 'cstdint' file not found
	#include <cstdint>
	         ^~~~~~~~~
	1 error generated.

Using GCC when cross-compiling to aarch64, I don't encounter the
linker errors that occur when building natively.  Since we're forced
to use GCC sometimes anyway, I've also changed to use GCC on systems
where GCC is new enough, so Clang only affects the platforms that
really need it.