mongodb: fix double link of isNamedError on darwin.
duplicate symbol 'mongo::error_details::isNamedCode<100>' in:
    build/nixos/mongo/libmongodmain.a(db.o)
    build/nixos/third_party/murmurhash3/libmurmurhash3.a(MurmurHash3.o)
duplicate symbol 'mongo::error_details::isNamedCode<11000>' in:
    build/nixos/mongo/libmongodmain.a(db.o)
    build/nixos/third_party/murmurhash3/libmurmurhash3.a(MurmurHash3.o)
ld: 380094 duplicate symbols for architecture x86_64
clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
scons: *** [build/nixos/mongo/mongod] Error 1
scons: building terminated because of errors.
build/nixos/mongo/mongo failed: Error 1
build/nixos/mongo/mongos failed: Error 1
build/nixos/mongo/mongod failed: Error 1