python3Packages.paho-mqtt: regenerate certificates for tests
The certificate tests/ssl/server.crt expired on July 6, 2026, leading to

    ssl.SSLError: [SSL: SSLV3_ALERT_CERTIFICATE_EXPIRED] ssl/tls alert certificate expired (_ssl.c:1032)

in the tests.

(cherry picked from commit 78e3a0877691fac433ce626641597f14de0d06af)