beets.plugins.{alternative,copyartifacts}: fix evaluation
Commit 8c5d37129fc5097d9fb52e95fb07de75392d1c3c apparently did not
confirm that all its alterations resulted in evaluatable expressions,
meaning that these files became unevaluatable:

    error: undefined variable 'lib' at
    /var/nixup/nixpkgs/pkgs/tools/audio/beets/plugins/alternatives.nix:22:21

The fix is simply to make sure the required value is available as a
function argument.

Verified through evaluation.