guix: fix build user takeover patch
The preceding fix only applies one of two patches, which breaks builds:

   error: getting attributes of path `/gnu/store/<item>': No such file
   or directory

The Debian package maintainer, Vagrant Cascadian, is a frequent Guix
committer, so the Debian package is a suitable upstream patch source
when Guix commits require backporting to the current release tarball.

Fixes: 633a3b8f1913 ("guix: build user takeover patch")
(cherry picked from commit e3c99d6c50dda8856745d163eb2d531718ff8820)