matrix-synapse.tools: fix the eval (delete)
Without the change the eval fails as:

    $ nix build --no-link -f. matrix-synapse.tools
    error: attribute 'tools' missing
       at pkgs/by-name/ma/matrix-synapse/package.nix:47:54:
           46|     # for backward compatibility
           47|     inherit (matrix-synapse-unwrapped) plugins tests tools;
             |                                                      ^
           48|   };

(cherry picked from commit 7d1ed12e3745c5207ee0f85e797682e2d35e5379)