driftnet: fix build
It used to fail with

    error: initialization of 'unsigned char' from 'void *' makes integer from pointer without a cast

(cherry picked from commit bb058ee8ec1935059a8d5d502725f34105e9350f)