rspamd: disable blas by default
We run integration tests in the nixos-mailserver project and identified
the commit enabling blas support in rspamd to be breaking for rspamc
learn_ham/spam calls from within dovecot sieve scripts using the pipe
command.

https://gitlab.com/simple-nixos-mailserver/nixos-mailserver/-/issues/321

```
Debug: sieve: action pipe: running program: sa-learn-spam.sh
Debug: program exec:/nix/store/3yv9zxi9ls8w4vmp4sxmil30jj8n08kk-sieve-pipe-bins/sa-learn-spam.sh: Created
Debug: program exec:/nix/store/3yv9zxi9ls8w4vmp4sxmil30jj8n08kk-sieve-pipe-bins/sa-learn-spam.sh: Pass environment: USER=user1@example.com
Debug: program exec:/nix/store/3yv9zxi9ls8w4vmp4sxmil30jj8n08kk-sieve-pipe-bins/sa-learn-spam.sh: Pass environment: HOME=/var/vmail
Debug: program exec:/nix/store/3yv9zxi9ls8w4vmp4sxmil30jj8n08kk-sieve-pipe-bins/sa-learn-spam.sh: Pass environment: HOST=server
Debug: program exec:/nix/store/3yv9zxi9ls8w4vmp4sxmil30jj8n08kk-sieve-pipe-bins/sa-learn-spam.sh: Establishing connection
Debug: program exec:/nix/store/3yv9zxi9ls8w4vmp4sxmil30jj8n08kk-sieve-pipe-bins/sa-learn-spam.sh: Forked child process
Debug: program exec:/nix/store/3yv9zxi9ls8w4vmp4sxmil30jj8n08kk-sieve-pipe-bins/sa-learn-spam.sh (1945): Connected to program
Debug: program exec:/nix/store/3yv9zxi9ls8w4vmp4sxmil30jj8n08kk-sieve-pipe-bins/sa-learn-spam.sh (1945): Finished streaming payload to program
Debug: program exec:/nix/store/3yv9zxi9ls8w4vmp4sxmil30jj8n08kk-sieve-pipe-bins/sa-learn-spam.sh (1945): Finished input to program
Debug: program exec:/nix/store/3yv9zxi9ls8w4vmp4sxmil30jj8n08kk-sieve-pipe-bins/sa-learn-spam.sh (1945): Disconnected
Debug: program exec:/nix/store/3yv9zxi9ls8w4vmp4sxmil30jj8n08kk-sieve-pipe-bins/sa-learn-spam.sh (1945): Waiting for program to finish after 8 msecs (timeout = 9992 msecs)
Debug: program exec:/nix/store/3yv9zxi9ls8w4vmp4sxmil30jj8n08kk-sieve-pipe-bins/sa-learn-spam.sh (1945): Execution timed out after 10000 milliseconds: Sending TERM signal
Debug: program exec:/nix/store/3yv9zxi9ls8w4vmp4sxmil30jj8n08kk-sieve-pipe-bins/sa-learn-spam.sh (1945): Child process ended
Error: program exec:/nix/store/3yv9zxi9ls8w4vmp4sxmil30jj8n08kk-sieve-pipe-bins/sa-learn-spam.sh (1945): Forcibly terminated with signal 15
Debug: program exec:/nix/store/3yv9zxi9ls8w4vmp4sxmil30jj8n08kk-sieve-pipe-bins/sa-learn-spam.sh (1945): Destroy
Error: sieve: failed to pipe message to program `sa-learn-spam.sh': refer to server log for more information. [2025-05-09 23:31:40]
```

(cherry picked from commit 5530777c3c19ee226ede37ec0b70f658d2890e60)