nixosTests.tomcat: add `lib` to imports to fix eval
Without the change eval fails as:

    $ nix build --no-link -f. nixosTests.tomcat

        error: undefined variable 'lib'

(cherry picked from commit 15a672bf1f329115270ba2e63b0d4f0e49e58098)