nixos/malloc: revert "add back maybe unnecessary line"
This reverts commit ed55524.

error: The option `boot.kernel.sysctl."vm.max_map_count"' is defined multiple times while it's expected to be unique.

Definition values:
- In `nix/var/nix/profiles/per-user/root/channels/nixos/nixos/modules/config/malloc.nix': 1048576
- In `nix/var/nix/profiles/per-user/root/channels/nixos/nixos/modules/config/sysctl.nix': 1048576
Use `lib.mkForce value` or `lib.mkDefault value` to change the priority on any of these definitions.