nixos/oci-containers: stricter dependencies for rootless containers with sdnotify=healthy
After running this configuration for a while, we
noticed that the containers didn't get back up once and the services
failed with the following error:

    Error: current system boot ID differs from cached boot ID; an unhandled reboot has occurred.

This is hard to reproduce and seems to be a timing issue. However,
the logs indicated two issues that this patch now solves:

* Things in `/tmp` were preserved that weren't supposed to be. This is
  now solved by using `PrivateTmp=yes` which makes systemd clear the
  `/tmp` the service sees whenever it stops. From `systemd.exec(5)`:

  > If true, all temporary files created by a service
  > in these directories will be removed after the service is stopped.

* The ExecStartPost= indicated that the user session got stopped before
  which is required or sdnotify=healthy. Add explicit ordering for
  user@. This unfortunately requires a statically declared uid.