gnutls: Disable parallel building
This can fail randomly with

    CC       systemkey.o
  In file included from systemkey.c:47:0:
  systemkey-args.h:1:1: error: unterminated comment
   /*   -*- buffer-read-only: t -*- vi: set ro:

which is presumably caused by a race with the generation step above:

  autogen systemkey-args.def

http://hydra.nixos.org/build/37878764#tabs-buildsteps