electron_31: fix build after llvm bump
This fixes the following build errors:

~~~
[2607/50420] CXX obj/third_party/perfetto/src/tracing/client_api_without_backends/track_event_legacy.o
FAILED: obj/third_party/perfetto/src/tracing/client_api_without_backends/track_event_legacy.o
clang++ -MD -MF [...]
In file included from ../../third_party/perfetto/src/tracing/track_event_legacy.cc:17:
In file included from ../../third_party/perfetto/include/perfetto/tracing/track_event_legacy.h:26:
In file included from ../../third_party/perfetto/include/perfetto/tracing/track_event.h:20:
../../third_party/perfetto/include/perfetto/tracing/internal/track_event_data_source.h:331:20: error: a template argument list is expected after a name prefixed by the template keyword [-Wmissing-template-arg-list-after-template-kw]
  331 |     Base::template Trace([](typename Base::TraceContext ctx) { ctx.Flush(); });
      |                    ^
[...]
6 errors generated.
~~~

and

~~~
FAILED: obj/electron/electron_lib/keyboard_util.o
clang++ -MD -MF [...]
../../electron/shell/common/keyboard_util.cc:19:30: error: constexpr function never produces a constant expression [-Winvalid-constexpr]
   19 | constexpr CodeAndShiftedChar KeyboardCodeFromKeyIdentifier(
      |                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../electron/shell/common/keyboard_util.cc:111:33: note: non-constexpr function 'find' cannot be used in a constant expression
  111 |   if (auto* const iter = Lookup.find(str); iter != Lookup.end())
      |                                 ^
../../base/containers/flat_tree.h:310:18: note: declared here
  310 |   const_iterator find(const Key& key) const;
      |                  ^
1 error generated.
~~~

This is happening since staging has been merged into master, which
included both a rustc and llvm bump.

Note that we inherit the llvm that rustc exposes.

Co-Authored-By: K900 <me@0upti.me>