nixos/node-red: fix `cfg.package` default value
This fixes the following eval error:

```
error: nodePackages.node-red cannot be found in pkgs
```

when having `services.node-red.enable = true;` without specifying
`services.node-red.package`, just like the nixos VM test.

Follow-up of f509382c11ed445b52f249efa6e2fe66d1b56fa7, which attempted
to fix this as well.

Breakage introduced in 0a37316d6cfea44280f4470b6867a711a24606bd.