qt4: fix parallel building of moc_qtgradientviewdialog.o
Previously the last of these commands:

```
make -j sub-tools-bootstrap
make -j sub-uic sub-moc sub-rcc
make -C tools/designer/src/lib .obj/release-shared/moc_qtgradientviewdialog.o
```

failed with this error:

```
In file included from .uic/release-shared/ui_qtgradientviewdialog.h:63:0,
                 from .moc/release-shared/../../../../../shared/qtgradienteditor/qtgradientviewdialog.h:47,
                 from .moc/release-shared/moc_qtgradientviewdialog.cpp:9:
../../../shared/qtgradienteditor/qtgradientview.h:47:31: fatal error: ui_qtgradientview.h: No such file or directory
```

because uic did not ensure that the build of moc_qtgradientviewdialog.o happens
after the build of moc_qtgradientview.o.