displaycal: drop
Last release from 2019, hasn't migrated to python3.

```
Traceback (most recent call last):
  File "/build/DisplayCAL-3.8.9.3/nix_run_setup", line 8, in <module>
    exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\\r\\n', '\\n'), __file__, 'exec'))
  File "setup.py", line 258
    print "Bumping version number %s ->" % \
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Bumping version number %s ->" % \)?
```