postgresql11Packages.plv8: Fix build on crypt
Likely a downfall from https://github.com/NixOS/nixpkgs/pull/181764, the package would no longer build for Postgres < 14:

    In file included from /nix/store/ybkyabc23chdfy48n3h1zqwa57vp38wd-glibc-2.35-163-dev/include/bits/sigstksz.h:24,
                     from /nix/store/ybkyabc23chdfy48n3h1zqwa57vp38wd-glibc-2.35-163-dev/include/signal.h:328,
                     from /nix/store/cm4akn9l84yqfcmz0hhn8jkm59s7sdjz-postgresql-11.17/include/server/storage/sinval.h:17,
                     from /nix/store/cm4akn9l84yqfcmz0hhn8jkm59s7sdjz-postgresql-11.17/include/server/access/xact.h:21,
                     from plv8.cc:23:
    /nix/store/ybkyabc23chdfy48n3h1zqwa57vp38wd-glibc-2.35-163-dev/include/unistd.h:1159:14: error: declaration of 'char* crypt(const char*, const char*) noexcept' has a different exception specifier
     1159 | extern char *crypt (const char *__key, const char *__salt)
          |              ^~~~~
    In file included from /nix/store/cm4akn9l84yqfcmz0hhn8jkm59s7sdjz-postgresql-11.17/include/server/c.h:1248,
                     from /nix/store/cm4akn9l84yqfcmz0hhn8jkm59s7sdjz-postgresql-11.17/include/server/postgres.h:46,
                     from plv8.h:20,
                     from plv8.cc:8:
    /nix/store/cm4akn9l84yqfcmz0hhn8jkm59s7sdjz-postgresql-11.17/include/server/port.h:317:14: note: from previous declaration 'char* crypt(const char*, const char*)'
      317 | extern char *crypt(const char *key, const char *setting);
          |              ^~~~~
    plv8.cc: In function 'v8::Local<v8::Value> DoCall(v8::Local<v8::Context>, v8::Handle<v8::Function>, v8::Handle<v8::Object>, int, v8::Handle<v8::Value>*, bool)':
    plv8.cc:863:1: warning: control reaches end of non-void function [8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wreturn-type-Wreturn-type8;;]
      863 | }
          | ^

Not sure why it works without this on newer versions.