chromium: remove broken `pulseSupport = false;` override
As far as I can tell, this override broke almost 10 years ago in
8391241e0c90c8e5ee90d86d6cc1c9146e575768.

When trying to build the fixup commit that followed immediately after
that (5f53fddf1ef784e2279bd4236c9f7566a038e89c) the build fails with the
following error:

~~~
[11704/21910] CXX obj/media/media/vp9_compressed_header_parser.o
[11705/>
FAILED: obj/media/audio/audio/audio_manager_alsa.o
g++ -MMD -MF obj/media/audio/audio/audio_manager_alsa.o.d [...]
In file included from ../../media/audio/alsa/audio_manager_alsa.cc:28:0:
../../media/audio/pulse/audio_manager_pulse.h:8:30: fatal error: pulse/pulseaudio.h: No such file or directory
compilation terminated.
ninja: build stopped: subcommand failed.
~~~

And the same happens when trying to build chromium with
`pulseSupport = false;` and picking random releases between 17.03 and
now.

I don't think there is a good reason to keep this, especially since no
one bothered to test this in almost a decade. The chromium derivation is
a mess, so let's run with this rather small win and remove this broken,
mostly useless, obscure and untested permutation.