OVMF: fix buils against `openssl-3.0.13`
Without the change the build fails on `staging-next` as
https://hydra.nixos.org/build/248863953/nixlog/2/tail:

    /build/edk2-unvendored-src/CryptoPkg/Library/OpensslLib/openssl/crypto/property/property_parse.c:107:19: error: ‘INT64_MAX’ undeclared (first use in this function)
      107 |         if (v > ((INT64_MAX - (*s - '0')) / 10)) {
          |                   ^~~~~~~~~

The unbundled version of `openssl` `nixpkgs` injects into `edk2` started
using `INT64_MAX` that `edk2`'s `<stdint.h>` does not provide and relies
on `openssl` to define as a fallback.

Let's pull in `openssl`'s own definition of those.