librdf_raptor2: backport fix for `libxml2-2.11`
`libxml2-2.11` removed `checked` bit of private API and broke
`librdf_raptor2` build as:

       src/raptor_libxml.c:256:12: error: 'xmlEntity' {aka 'struct _xmlEntity'} has no member named 'checked'
         256 |     if(!ret->checked)
             |            ^~

The change pull upstream fix.