gns3-gui: Add the missing setuptools dependency
Fixes #81048.
Note: This commit is not cherry-picked, but required to fix:
ImportError: No module named pkg_resources