ffmpeg-headless: backport binutils-2.41 fix
Without the change build fails against `binutils-2.41` as:

    ./libavcodec/x86/mathops.h: Assembler messages:
    ./libavcodec/x86/mathops.h:125: Error: operand type mismatch for `shr'
    CC     libavformat/framehash.o
    make: *** [ffbuild/common.mak:81: libavformat/rtpdec_h261.o] Error 1 shuffle=3456075312

This happens because `binutils` was made stricter not to accept negative
immediate values to `shl`: https://sourceware.org/PR30578

`ffmpeg` had to adapt and we are pulling upstream fix.