psysh: mark as broken, remove teams.php
I'm strongly against the PHP team maintaining packages just because they
happen to be written in PHP.

Also,

    $ nix-build -A psysh.composerVendor --check
    checking outputs of '/nix/store/1mpgxnyzw18bv824drzi05k6mxb9znss-psysh-composer-vendor-0.12.7.drv'...
    /nix/store/nxza0ss75gbgwycsld0gyw1m729271j9-composer-vendor-hook.sh/nix-support/setup-hook: line 13: composerNoDev: unbound variable
    error: builder for '/nix/store/1mpgxnyzw18bv824drzi05k6mxb9znss-psysh-composer-vendor-0.12.7.drv' failed with exit code 1

Marking as broken until somebody picks it up and performs a proper fix.