cinnamon.cinnamon-common: unbreak looking-glass
Reported in issue 213728.
ModuleNotFoundError: No module named 'pyinotify'

(cherry picked from commit 7f5ad3e298a3e83e01f76619d7b65c91182e9922)