Revert "python3Packages.pathspec: 0.12.1 -> 1.0.3"
This reverts commit df82b1df7659da269f3ff14e93abbc0fd43a75d4.

Confuses mypy.

mypy/modulefinder.py:20: error: Module "pathspec.patterns.gitwildmatch" does not explicitly export attribute "GitWildMatchPatternError"  [attr-defined]