bobcat: Fix build on aarch64-linux
The code base requires a C++20 capable compiler toolchain.

Also, we need to link with the gcc library explicitly to avoid running
into undefined reference to `__aarch64_ldadd4_acq_rel' errors.