pypy3Packages.home-assistant-chip-clusters: fix the eval
Without the change the eval fails as:

    nix build --no-link -f. pypy3Packages.home-assistant-chip-clusters
    error:
       … while evaluating the attribute 'drvPath'
         at lib/customisation.nix:365:7:
          364|     in commonAttrs // {
          365|       drvPath = assert condition; drv.drvPath;
             |       ^
          366|       outPath = assert condition; drv.outPath;

       … while evaluating the attribute 'drvPath'
         at lib/customisation.nix:365:7:
          364|     in commonAttrs // {
          365|       drvPath = assert condition; drv.drvPath;
             |       ^
          366|       outPath = assert condition; drv.outPath;

       … while calling the 'derivationStrict' builtin
         at <nix/derivation-internal.nix>:34:12:
           33|
           34|   strict = derivationStrict drvAttrs;
             |            ^
           35|

       (stack trace truncated; use '--show-trace' to show the full, detailed trace)

       error: expected a set but found null: null

It happens because one of the dependencies is `null`:

    nix-repl> pypy310Packages.brotlicffi.propagatedBuildInputs
    [
    null
      «derivation /nix/store/1jdx98sk2ii89m6ksbfg7rv8ryp9wdgi-pypy3.10-7.3.12.drv»
    ]

Let's filter those out.