nixos/lxd-container: add /run to squashfs
Without /run the system won't boot with the following error:

```
To detach from the console, press: <ctrl>+a q
setting up /etc...
ln: failed to create symbolic link '/run/current-system': No such file or directory
ln: failed to create symbolic link '/run/booted-system': No such file or directory
error: getting status of '/run/current-system': No such file or directory
starting systemd...
/sbin/init: line 146: /run/current-system/systemd/lib/systemd/systemd: No such file or directory
Error: write /dev/pts/ptmx: file already closed
```

Creating it fixes the error

I'm not entierly sure if this is an lxd error or if nix is actually supposed to create /run if it doesn't exist