nixos/resolvconf: Enable by default
Fixes #353225

The value of `networking.resolvconf.enable` was previously
predicated on the existence `environment.etc."resolv.conf"`.
This could lead to infinite recursion when an attribute defined
within the resolvconf module was also required to define
`environment.etc` (see example below).

Instead, set the default to an explicit true and set the value to
false where required in-tree. This turns out to only be two places:
systemd-resolved and tetrd.

Example infrec (from building .#nixosTests.containers-hosts):

```
       … while evaluating definitions from `/nix/store/5djjm1dipmdh82issrmpfjdplp7hk0pp-source/nixos/modules/services/logging/logrotate.nix':

       … while evaluating the option `containers.netmask.services.logrotate.enable':

       … while evaluating the option `containers.netmask.users.groups':

       … while evaluating definitions from `/nix/store/5djjm1dipmdh82issrmpfjdplp7hk0pp-source/nixos/modules/config/resolvconf.nix':

       … while evaluating the option `containers.netmask.networking.resolvconf.enable':

       … while evaluating the option `containers.netmask.environment.etc':

       … while evaluating definitions from `/nix/store/5djjm1dipmdh82issrmpfjdplp7hk0pp-source/nixos/modules/services/logging/logrotate.nix':

       (stack trace truncated; use '--show-trace' to show the full, detailed trace)

       error: infinite recursion encountered
       at /nix/store/5djjm1dipmdh82issrmpfjdplp7hk0pp-source/lib/modules.nix:1512:13:
         1511|     _type = "if";
         1512|     inherit condition content;
             |             ^
         1513|   };
```