lxc: Fix build error with glibc 2.26
This issue doesn't necessarily have to do with glibc 2.26 and it could
have been fixed if we'd replace -Werror with -Wall.

The error in question was:

storage/overlay.c:808:13: error: 'dirlen' may be used uninitialized in
this function [-Werror=maybe-uninitialized]

After looking at the code in overlay.c it indeed might use dirlen
unitialized.

Unrelated to the glibc upgrade which brought the problem to the surface,
this also has been fixed upstream at lxc/lxc@180c477a326ce85632249ff169.

The reason however, that led to the upstream fix was a segfault which
has been reported at lxc/lxc#1802.

Signed-off-by: aszlig <aszlig@nix.build>
Cc: @wkennington, @globin, @fpletz