libf2c: explicitly disable parallel builds
Attempt to enable build parallelism exposes missing dependency:

  libf2c> main.c:4:10: fatal error: signal1.h: No such file or directory
  libf2c>     4 | #include "signal1.h"
  libf2c>       |          ^~~~~~~~~~~