deadpixi-sam: remove duplicate alias
It is already listed in aliases.nix, and I managed to get this from Nix:

  error: Alias deadpixi-sam is still in all-packages.nix

Fixes: 218d81bc9db4 ("all-packages: move aliases to aliases.nix")