ucblogo: avoid use of a `wrapGAppsHook` alias
Without the change the eval fails with aliases disabled as:

    nix build --no-link -f. ucblogo --arg config '{allowAliases = false;}'
    error:
       … while calling the 'abort' builtin
         at lib/customisation.nix:269:13:
          268|        # which is especially relevant with allowAliases = false
          269|        else abort "lib.customisation.callPackageWith: ${error}";
             |             ^
          270|

       error: evaluation aborted with the following error message:
         'lib.customisation.callPackageWith: Function called without
           required argument "wrapGAppsHook" at pkgs/by-name/uc/ucblogo/package.nix:7,
           did you mean "wrapGAppsHook3" or "wrapGAppsHook4"?'