spyder: add patch fix startup error
Upstream clears out all sys.path entries that come from PYTHONPATH,
which completely breaks Nixpkgs packaging. Patch out that code to fix
running spyder.

Before:

  $ spyder
  Traceback (most recent call last):
    File "/nix/store/icbklw22yrzy7s8k2ai8chkhrvna8pxr-python3.10-spyder-5.4.0/bin/..spyder-wrapped-wrapped", line 6, in <module>
      from spyder.app.start import main
    File "/nix/store/icbklw22yrzy7s8k2ai8chkhrvna8pxr-python3.10-spyder-5.4.0/lib/python3.10/site-packages/spyder/app/start.py", line 42, in <module>
      import zmq
  ModuleNotFoundError: No module named 'zmq'
  (exit with error code 1)

After:

  $ spyder
  (succeeds startup)

Note that once the GUI is up, it complains (inside GUI) that we've got
wrong version of 2 deps and
"ModuleNotFoundError: No module named 'spyder_kernels'".

Fixes https://github.com/NixOS/nixpkgs/issues/208567