modules/xmr-stak: drop broken cudaSupport option
Tanvir Ahmed T. reports that `services.xmr-stak.enable = true;` shows
that `23.05` ships broken `xmr-stak` module:

    error: function 'anonymous lambda' called with unexpected argument 'cudaSupport'

I broke it when I removed `cudaSupport` flag in
    https://github.com/NixOS/nixpkgs/commit/a5ce71d4e8cbe1d3311aeddc86a8d847989d6099

I'm just removing the option without an attempt to supply the stub as
module was already broken on `23.05` release. There are probably no
users of `xmr-stak` module by now.

Closes: https://github.com/NixOS/nixpkgs/issues/256703