gnutar: pull missing `libintl` dependency on Darwin
Without the change `gnutar` fails the build as:

      "_libintl_setlocale", referenced from:
          _main in tar.o
      "_libintl_textdomain", referenced from:
          _main in tar.o
    ld: symbol(s) not found for architecture x86_64

https://hydra.nixos.org/build/228724258/nixlog/2/tail
https://hydra.nixos.org/build/228711328/nixlog/2/tail

Picked from PR #244996