openocd: fix build with new glibc
Fixes this build error:

  In file included from src/helper/options.c:38:
  /nix/store/dl4h1p847f2rsrsfvlmm6cxxx7q21kxj-glibc-2.30-dev/include/sys/sysctl.h:21:2: error: #warning "The <sys/sysctl.h> header is deprecated and will be removed." [-Werror=cpp]
     21 | #warning "The <sys/sysctl.h> header is deprecated and will be removed."
        |  ^~~~~~~
  cc1: all warnings being treated as errors

Fixes: 48a997cd ("Merge #66528: glibc: 2.27 -> 2.30 (into staging)")