m2crypto: Use SWIG 2
Fixes "AttributeError: 'module' object has no attribute 'PKCS5_SALT_LEN'".

Fixes #9457.

(cherry picked from commit 6d42b79b29d7ecd98a942d46bcf362692d1e43c6)