gkraken: Fix wrapping
Fixes the following error when trying to run the final script:

Traceback (most recent call last):
  File "/nix/store/z1klbgg6p9v3vszjyvsjix9s4blsl7mv-gkraken-1.2.0/bin/.gkraken-wrapped", line 45, in <module>
    gi.require_version('Gtk', '3.0')
  File "/nix/store/k46f21qglnnl2grkx6gq6j6jlawfkgpw-python3.10-pygobject-3.42.2/lib/python3.10/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gtk not available

See https://github.com/NixOS/nixpkgs/issues/56943

(cherry picked from commit 901a78b6ad93472619d8079f7ab5ce827c5c5baf)