mesa: fix build with gcc15
- remove `rustPlatform.bindgenHook` from `buildInputs`,
`rustPlatform.bindgenHook` adds gcc headers to `BINDGEN_EXTRA_CLANG_ARGS`
which somehow conflict more with gcc15 than gcc14.
Removing hook should let meson use bindgen from cli with clang libraries.

Fixes bindgen error building `mesa` with gcc15:
```
FAILED: [code=1] src/nouveau/compiler/nak_bindings.rs
/nix/store/rm899xgm82kanr814dk8siwyghyxwphg-rust-bindgen-0.72.0/bin/bindgen
../src/nouveau/compiler/nak_bindings.h ...
/build/source/src/nouveau/winsys/./nouveau_bo.h:41:4: error: unknown
type name 'atomic_uint_fast32_t'
Unable to generate bindings: clang diagnosed error:
/build/source/src/nouveau/winsys/./nouveau_bo.h:41:4: error: unknown
type name 'atomic_uint_fast32_t'
```