solanum: mark broken on darwin
> Solanum is developed on Linux with glibc, but is currently portable
> to most POSIX-compatible operating systems. However, this portability
> is likely to be removed unless someone is willing to maintain it. If
> you'd like to be that person, please let us know on IRC.

But darwin apparently broke:

In file included from librb/version.c:23:
librb/../include/serno.h:1:10: fatal error: 'datecode.h' file not found
    1 | #include "datecode.h"
      |          ^~~~~~~~~~~~