minimal-bootstrap.musl11: add stdio_flush_on_exit.patch, drop always-flush.patch
The upstream version of this patch has been commented out
since 913e70d77b67722a5b3bd42f21b9ea4cc02046e9, due to
error: implicit declaration of function '__stdio_exit'

Revived this approach by updating the patch to forward declare.