llama-cpp: require newer apple sdk for Metal
Latest update [1] pulled code that relies on MTLBuffer `gpuaddress`
property that was added in macOS 13.0+ [2]. Build failed with:

error: property 'gpuAddress' not found on object of type 'id<MTLBuffer>'

[1] https://github.com/NixOS/nixpkgs/pull/438529
[2] https://developer.apple.com/documentation/metal/mtlbuffer/gpuaddress