octopus-caller: fix `gcc-13` build failure (drop `-Werror`)
Without the change the build on `master` fails as
https://hydra.nixos.org/build/249090788:

    /build/source/src/config/option_collation.cpp: In function 'auto octopus::options::make_variant_generator_builder(const OptionMap&, boost::optional<const octopus::ReadSetProfile&>)':
    /build/source/src/config/option_collation.cpp:1298: error: redundant move in initialization [-Werror=redundant-move]
     1298 |                 throw ConflictingSourceVariantFile {std::move(source_path), *output_path};
          |

Blanket `-Werror` frequently causes build failures unless upstream is
quick at addressing build failures.