zig: fix compilation on Darwin AArch64
On macOS AArch64, Zig's zig0 build is failing with the following error:

    Undefined symbols for architecture arm64:
      "operator delete[](void*)", referenced from:
          lld::elf::Configuration::~Configuration() in liblldELF.a(Driver.cpp.o)
          ...
      "operator delete(void*)", referenced from:
          _ZigLLVMGetNativeFeatures in libzigcpp.a(zig_llvm.cpp.o)
          ...
      "operator new[](unsigned long)", referenced from:
          bigint_unsigned_division(BigInt const*, BigInt const*, BigInt*, BigInt*) in libzigstage1.a(bigint.cpp.o)
          ...
      "operator new(unsigned long)", referenced from:
          _ZigLLVMTargetMachineEmitToFile in libzigcpp.a(zig_llvm.cpp.o)
          ...
      "operator new(unsigned long, std::nothrow_t const&)", referenced from:
          _ZigLLVMTargetMachineEmitToFile in libzigcpp.a(zig_llvm.cpp.o)
          ...
    ld: symbol(s) not found for architecture arm64
    clang-13: error: linker command failed with exit code 1 (use -v to see invocation)

This is because libc++ is selected during linking, but the libc++abi
isn't linked. Link libc++abi to fix the errors.

I think macOS x86_64 is still failing for a different reason.