ghc863: similarly to solve ghcWithHoogle problem
error: while evaluating the attribute 'NIX_GHC' of the derivation 'ghc-shell-for-netlink-pm-1.0.0' at /home/teto/nixpkgs/pkgs/development/haskell-modules/make-package-set.nix:301:9:
while evaluating 'ghcWithHoogle' at /home/teto/nixpkgs/pkgs/development/haskell-modules/make-package-set.nix:238:21, called from /home/teto/nixpkgs/pkgs/development/haskell-modules/make-package-set.nix:292:18:
while evaluating 'withPackages' at /home/teto/nixpkgs/pkgs/development/haskell-modules/make-package-set.nix:116:18, called from /home/teto/nixpkgs/pkgs/development/haskell-modules/make-package-set.nix:244:10:
while evaluating 'callPackageWith' at /home/teto/nixpkgs/lib/customisation.nix:108:35, called from /home/teto/nixpkgs/pkgs/development/haskell-modules/make-package-set.nix:116:28:
while evaluating 'makeOverridable' at /home/teto/nixpkgs/lib/customisation.nix:67:24, called from /home/teto/nixpkgs/lib/customisation.nix:112:8:
while evaluating anonymous function at /home/teto/nixpkgs/pkgs/development/haskell-modules/with-packages-wrapper.nix:1:1, called from /home/teto/nixpkgs/lib/customisation.nix:69:12:
while evaluating 'closePropagation' at /home/teto/nixpkgs/lib/deprecated.nix:160:22, called from /home/teto/nixpkgs/pkgs/development/haskell-modules/with-packages-wrapper.nix:45:57:
while evaluating 'uniqList' at /home/teto/nixpkgs/lib/deprecated.nix:91:14, called from /home/teto/nixpkgs/lib/deprecated.nix:160:29:
while evaluating 'go' at /home/teto/nixpkgs/lib/deprecated.nix:92:18, called from /home/teto/nixpkgs/lib/deprecated.nix:98:8:
while evaluating 'innerClosePropagation' at /home/teto/nixpkgs/lib/deprecated.nix:143:32, called from /home/teto/nixpkgs/lib/deprecated.nix:160:52:
while evaluating 'innerClosePropagation' at /home/teto/nixpkgs/lib/deprecated.nix:143:32, called from /home/teto/nixpkgs/lib/deprecated.nix:151:21:
while evaluating 'uniqList' at /home/teto/nixpkgs/lib/deprecated.nix:91:14, called from /home/teto/nixpkgs/lib/deprecated.nix:153:24:
while evaluating 'go' at /home/teto/nixpkgs/lib/deprecated.nix:92:18, called from /home/teto/nixpkgs/lib/deprecated.nix:98:8:
while evaluating 'go' at /home/teto/nixpkgs/lib/deprecated.nix:92:18, called from /home/teto/nixpkgs/lib/deprecated.nix:97:27:
while evaluating 'go' at /home/teto/nixpkgs/lib/deprecated.nix:92:18, called from /home/teto/nixpkgs/lib/deprecated.nix:97:27:
while evaluating 'go' at /home/teto/nixpkgs/lib/deprecated.nix:92:18, called from /home/teto/nixpkgs/lib/deprecated.nix:97:27:
while evaluating 'go' at /home/teto/nixpkgs/lib/deprecated.nix:92:18, called from /home/teto/nixpkgs/lib/deprecated.nix:97:27:
while evaluating 'go' at /home/teto/nixpkgs/lib/deprecated.nix:92:18, called from /home/teto/nixpkgs/lib/deprecated.nix:97:27:
while evaluating 'go' at /home/teto/nixpkgs/lib/deprecated.nix:92:18, called from /home/teto/nixpkgs/lib/deprecated.nix:97:27:
while evaluating 'go' at /home/teto/nixpkgs/lib/deprecated.nix:92:18, called from /home/teto/nixpkgs/lib/deprecated.nix:97:27:
while evaluating 'go' at /home/teto/nixpkgs/lib/deprecated.nix:92:18, called from /home/teto/nixpkgs/lib/deprecated.nix:97:27:
while evaluating 'go' at /home/teto/nixpkgs/lib/deprecated.nix:92:18, called from /home/teto/nixpkgs/lib/deprecated.nix:97:27:
while evaluating the attribute 'buildPhase' of the derivation 'hoogle-local-0.1' at /home/teto/nixpkgs/pkgs/development/haskell-modules/hoogle.nix:57:3:
attribute 'doc' missing, at /home/teto/nixpkgs/pkgs/development/haskell-modules/hoogle.nix:40:10