gnome.atomix: pull upstream fix for -fno-common toolchains
Without the change build on -fno-common toolchains fails as:

    $ nix build --impure --expr 'with import ~/nm {}; gnome.atomix.override { stdenv = clang13Stdenv; }'
    ld: src/libatomix.a.p/canvas_helper.c.o: undefined reference to symbol 'ceil@@GLIBC_2.2.5'
    ld: /nix/store/m4g6lswi75b739cpdx8wfxlfmcazyks9-glibc-2.34-115/lib/libm.so.6: error adding symbols: DSO missing from command line