ntfy: Switch to python3. Also fixes test failure.
Fixes test error:

    AttributeError: 'module' object has no attribute 'test_prowl'

(cherry picked from commit 35593698d5dd49117d9d082174add68389f96e08)