stunnel: fix compilation on darwin
stunnel 5.65 has a build error on darwin: `client.c:1514:11: error: use
of undeclared identifier 'environ'`. I think darwin is unique in that it
has unistd but doesn't define `environ`. I tested the resulting binary
for my stunnel use-case and it works on x86-darwin.

Introduced in:
https://github.com/NixOS/nixpkgs/commit/f6d7bf0315b59728ea4c6329287a2c2a5cd71223

Failing build: https://hydra.nixos.org/build/187400018