electron: node_module_version should be int
FAILED: gen/third_party/electron_node/config.gypi
python3 ../../third_party/electron_node/tools/generate_config_gypi.py gen/third_party/electron_node/config.gypi --out-dir . --dep-file gen/third_party/electron_node/generate_config_gypi.d --node-gn-path //third_party/electron_node
Traceback (most recent call last):
  File "/build/src/out/Release/../../third_party/electron_node/tools/generate_config_gypi.py", line 113, in <module>
    main()
  File "/build/src/out/Release/../../third_party/electron_node/tools/generate_config_gypi.py", line 105, in main
    f.write(repr(translate_config(args.out_dir, config, v8_config)))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/src/out/Release/../../third_party/electron_node/tools/generate_config_gypi.py", line 62, in translate_config
    'node_module_version': int(config['node_module_version']),
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '"133"'

Co-authored-by: Ljuzig <diamond.bertelli@gmail.com>
(cherry picked from commit 5213e7eef40ae3d1c058e7be377ce9e30c46c713)