python312Packages.pymupdf: fix "mupdf not found" import error
Fixes the following error:

```
Traceback (most recent call last):
  File "/nix/store/73znvwd538dglfsk2wdixj106i5infjn-python3-3.11.9-env/lib/python3.11/site-packages/fitz/__init__.py", line 140, in <module>
    from . import mupdf
ImportError: cannot import name 'mupdf' from partially initialized module 'fitz' (most likely due to a circular import) (/nix/store/73znvwd538dglfsk2wdixj106i5infjn-python3-3.11.9-env/lib/python3.11/site-packages/fitz/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/nix/store/73znvwd538dglfsk2wdixj106i5infjn-python3-3.11.9-env/lib/python3.11/site-packages/fitz/__init__.py", line 142, in <module>
    import mupdf
```