home-assistant: rerun tests failing with RuntimeError
The flakyness in home-assistant stems from premature event loop closing,
due to race conditions throughout the test suite.

> RuntimeError: Event loop is closed

They also happen during upstreams testsuite runs, but they silently
ignore them, so I don't expect a fix for them in the near future.

Alleviate our pains by rerunning tests that fail in this particular way.