rust-script: add missing dependency
`rust-script` calls `Command::new("cargo")`.

Previously, the following command would fail:

```shell
$ nix-shell -p rust-script --run "rust-script -fe '1+2'"
error: No such file or directory (os error 2)
```

Add cargo to PATH so that this functions as expected.

Fixes: fornwall/rust-script#151
Related-to: fornwall/rust-script#55