auto-patchelf: fix crash when multiple candidates missing
Fixes a crash in auto-patchelf, encountered when a dependency
that had multiple candidates didn't resolve.

>     any(libopenxr_loader.so.1, libopenxr_loader.so) -> not found!
[...]
> auto-patchelf: 6 dependencies could not be satisfied
> Traceback (most recent call last):
>   File "/nix/store/rax3bhibi4667jvxv7j22kalzsi9p8xs-auto-patchelf-0-unstable-2024-08-14/bin/auto-patchelf", line 608, in <module>
>     main()
>     ~~~~^^
>   File "/nix/store/rax3bhibi4667jvxv7j22kalzsi9p8xs-auto-patchelf-0-unstable-2024-08-14/bin/auto-patchelf", line 579, in main
>     auto_patchelf(
>     ~~~~~~~~~~~~~^
>         logger,
>         ^^^^^^^
>     ...<8 lines>...
>         add_existing=args.add_existing,
>         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>         extra_args=args.extra_args)
>         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/nix/store/rax3bhibi4667jvxv7j22kalzsi9p8xs-auto-patchelf-0-unstable-2024-08-14/bin/auto-patchelf", line 475, in auto_patchelf
>     if fnmatch(dep.name.name, pattern):
>                ^^^^^^^^^^^^^
> AttributeError: 'str' object has no attribute 'name'