libsForQt5.applet-window-buttons: 0.9.0 -> 0.10.1
This fixes the build, which was previously failing with:

	In file included from /build/source/build/libappletdecoration/appletdecorationplugin_autogen/EWIEGA46WW/moc_previewbridge.cpp:10,
	                 from /build/source/build/libappletdecoration/appletdecorationplugin_autogen/mocs_compilation.cpp:9:
	/build/source/build/libappletdecoration/appletdecorationplugin_autogen/EWIEGA46WW/../../../../libappletdecoration/previewbridge.h:53:10: error: 'void Decoration::Applet::PreviewBridge::update(KDecoration2::Decoration*, const QRect&)' marked 'override', but does not override
	   53 |     void update(KDecoration2::Decoration *decoration, const QRect &geometry) override;
	      |          ^~~~~~