gdal: wrap executables in environment containing numpy
Since gdal 3.8.1 there is a numpy dependency on the python library it
seems. This resulted in broken python scrips such as gdal2tiles.py

```
[nix-shell:~/map-scraper/shake-rg]$ gdal2tiles.py --help
ModuleNotFoundError: No module named 'numpy'
```

Therefore it's important to wrap the executables in an environment which
contains numpy.