global-platform-pro: 20.01.23 -> 24.10.15
* Update jdk from v8 to v11 to keep it building.
* There are no jreMAJOR_headless versions above MAJOR=8 and jre_minimal
  doesn't work[1], so switch to jre_headless (currently v21 on
  nixpkgs-unstable) to keep it running. The newer jre causes a big
  package closure size difference: 153 MiB -> 627 MiB.
* Upstream changed the way `git describe` info gets built into the
  artifacts, so add a postPatch snippet to handle that.
  (Fixes `Error: inStream parameter is null` issue that happens
  otherwise.)
  Upstream asked for a suffix to the version string to differentiate
  from official builds; use "-nixpkgs" for that.

[1] $ gp -i
    Error: Unable to initialize main class pro.javacard.gptool.GPTool
    Caused by: java.lang.NoClassDefFoundError: javax/smartcardio/CardException