feh: fix cross
Required to avoid:

   > aarch64-unknown-linux-gnu-gcc -g -O2 -Wall -Wextra -pedantic -std=c11 -D_POSIX_C_SOURCE=200809L -D_XOPEN_SOURCE=700 -D_DARWIN_C_SOURCE -DHAVE_LIBCURL -DHAVE_MKSTEMPS -DHAVE_STRVERSCMP -DHAVE_LIBXINERAMA -DHAVE_LIBEXIF -DHAVE_INOTIFY -DPREFIX=\"/nix/store/8w2gzmyvg703wa9fj3vdpi87rcskan1f-feh-aarch64-unknown-linux-gnu-3.9\" -DPACKAGE=\"feh\" -DVERSION=\"\"   -c -o main.o main.c
   > In file included from main.c:34:
   > wallpaper.h:31:10: fatal error: X11/Intrinsic.h: No such file or directory
   >    31 | #include <X11/Intrinsic.h>      /* Xlib, Xutil, Xresource, Xfuncproto */
   >       |          ^~~~~~~~~~~~~~~~~
   > compilation terminated.
   > make[1]: *** [<builtin>: main.o] Error 1
   > make[1]: Leaving directory '/build/source/src'
   > make: *** [Makefile:6: build-src] Error 2