chromedriver: Disable on aarch64-darwin
chromedriver_mac64_m1.zip is currently not available anymore and I do not have time to look into it:
path is '/nix/store/zhz7hrk94dc0dn7a42czhd1nz9142826-chromedriver_mac64.zip'
nix-prefetch-url https://chromedriver.storage.googleapis.com/106.0.5249.61/chromedriver_mac64_m1.zip
error: unable to download 'https://chromedriver.storage.googleapis.com/106.0.5249.61/chromedriver_mac64_m1.zip': HTTP error 404

       response body:

       <?xml version='1.0' encoding='UTF-8'?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Details>No such object: chromedriver/106.0.5249.61/chromedriver_mac64_m1.zip</Details></Error>

(cherry picked from commit 3d50284bb23e2a7e5031206e03cabd9e10b8907d)