llvmPackages.clang-tools: ensure wrapper uses bash
The wrapper script relies on features only available with bash, namely
arithmetic evaluation as in `while (( $# )); do`. So let's ensure that
the shebang is patched to use bash. (bash's POSIX `sh` evaluates this as
intended.)

A minimal reproducer with a project that generally ought to pass
clang-tidy checking may look like so:

```nix
{
  pkgs ? import <nixpkgs> { },
}:
pkgs.fwupd.overrideAttrs (
  final: prev: {
    nativeBuildInputs = prev.nativeBuildInputs ++ [ pkgs.clang-tools ];
    preCheck = ''
      ninja clang-tidy
    '';
  }
)
```

Before, you may see many errors about missing headers and some lines
that suspiciously look like bash errors.

```
fwupd> >>> /nix/store/gf6qdh329rc8lbby710r9rzhwqkkgv3h-clang-tools-21.1.8/bin/clang-tidy --use-color -quiet -p /build/source/build /build/source/plugins/uf2/fu-self-test.c
fwupd> /nix/store/gf6qdh329rc8lbby710r9rzhwqkkgv3h-clang-tools-21.1.8/bin/clang-tidy: line 5: 129: not found
fwupd> /nix/store/gf6qdh329rc8lbby710r9rzhwqkkgv3h-clang-tools-21.1.8/bin/clang-tidy: line 23: 129: not found
fwupd> 276 warnings and 1 error generated.
fwupd> Error while processing /build/source/plugins/uf2/fu-self-test.c.
fwupd> /nix/store/dm7fg33sqnjxkwdpirnnbnx7wyi89m82-glib-2.88.3-dev/include/glib-2.0/glib/gtypes.h:41:10: error: 'time.h' file not found [clang-diagnostic-error]
fwupd>    41 | #include <time.h>
fwupd>       |          ^~~~~~~~
```

With this change, these clang-tidy errors no longer appear.