Kaldi: fix build
Resolve build issues with Kaldi due to OpenFST dependency on GCC14

When compiling OpenFST (a Kaldi dependency) with GCC13,
numerous warnings occur, such as:
`warning: expected 'template' keyword before dependent template name`.

However, with GCC14, these warnings escalate to errors, causing the
build to fail. Consequently, the Kaldi package is no longer building
with versions >25.05, as the standard environment (stdenv) now relies on
GCC14.

Building with gcc13Stdenv however still fails with:
```
> ERROR: noBrokenSymlinks: found 40 dangling symlinks, 0 reflexive symlinks and 0 unreadable symlinks
```

Looks like this is related to https://github.com/NixOS/nixpkgs/pull/370750/

Setting `dontCheckForBrokenSymlinks = true;` can prevent it from
happening.